use crate::ir::*;
use crate::util::{escape_string, to_pascal_case, to_snake_case};
use super::{EmitOptions, Emitter, needs_python_quoting};

pub struct PydanticEmitter;

/// Tracks which Python imports/features the generated module needs.
#[derive(Default)]
struct ModuleFeatures {
    needs_before_validator: bool,
    needs_type_adapter: bool,
    needs_json: bool,
    needs_re: bool,
    needs_model_validator: bool,
    needs_type_helpers: bool,
    needs_deep_equal: bool,
    needs_interpreter: bool,
}

impl Emitter for PydanticEmitter {
    fn extension(&self) -> &str {
        "py"
    }

    fn emit_with_options(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> String {
        let pascal = to_pascal_case(name);
        let mut features = ModuleFeatures::default();

        // Scan all IR nodes to determine needed features
        scan_features(&converted.root, &mut features);
        for def in &converted.defs {
            scan_features(&def.schema, &mut features);
        }

        let mut counter = 0usize;

        // Build definitions and root
        let mut def_blocks = Vec::new();
        for def in &converted.defs {
            def_blocks.push(emit_definition(
                &def.name,
                &def.schema,
                &converted.defs,
                &mut counter,
            ));
        }
        let root_block = emit_definition(
            &pascal,
            &converted.root,
            &converted.defs,
            &mut counter,
        );

        // Assemble the body (definitions + root) first so that in shared-helpers
        // mode we can strip the static utility defs and detect which shared
        // helper names the module actually references.
        let mut body = String::new();
        for block in &def_blocks {
            body.push_str(block);
            body.push_str("\n\n");
        }
        body.push_str(&root_block);
        body.push('\n');

        if options.helpers_file.is_some() {
            // The _try_validate/_try_validate_g defs are static — in shared mode
            // they live in the helpers module instead of being emitted inline.
            body = body
                .replace(&format!("\n{TRY_VALIDATE_HELPER}\n"), "\n")
                .replace(&format!("\n{TRY_VALIDATE_G_HELPER}\n"), "\n");
        }

        let mut out = String::new();

        // Header
        out.push_str(&format!(
            "# Generated by json-schema-transformer\n# {name}\n# DO NOT EDIT — changes will be overwritten on regeneration\n\n"
        ));

        // Imports
        out.push_str("from __future__ import annotations\n\n");
        out.push_str("from dataclasses import dataclass\n");
        out.push_str("from enum import Enum\n");
        out.push_str("from typing import Annotated, Any, Literal, Optional, Union\n\n");

        let mut pydantic_imports = vec!["Field"];
        if features.needs_before_validator {
            pydantic_imports.push("BeforeValidator");
        }
        if features.needs_type_adapter {
            pydantic_imports.push("TypeAdapter");
            pydantic_imports.push("ValidationError");
        }
        if features.needs_model_validator {
            pydantic_imports.push("model_validator");
        }
        out.push_str(&format!(
            "from pydantic import {}\n",
            pydantic_imports.join(", ")
        ));
        out.push_str("from pydantic.dataclasses import dataclass as pydantic_dataclass\n");

        if features.needs_json {
            out.push_str("import json\n");
        }
        if features.needs_re {
            out.push_str("try:\n    import regex as re\nexcept ImportError:\n    import re\n");
        }

        if let Some(helpers_file) = &options.helpers_file {
            // Shared-helpers mode: import the utilities from the companion
            // module instead of inlining them.
            let helper_module = helpers_file.trim_end_matches(".py");
            let mut names: Vec<&str> = Vec::new();
            for n in ["_check_str", "_check_int", "_check_number", "_check_bool", "_check_unique_items", "_deep_equal"] {
                if body.contains(n) {
                    names.push(n);
                }
            }
            if body.contains("_try_validate(") {
                names.push("_try_validate");
            }
            if body.contains("_try_validate_g(") {
                names.push("_try_validate_g");
            }
            if body.contains("_jsi_validate(") {
                names.push("_jsi_validate");
            }
            if !names.is_empty() {
                out.push_str(&format!(
                    "\n# Shared runtime helpers live in {helpers_file} next to this file. Generated\n\
                     # modules are commonly loaded by file path, so make sure this directory is\n\
                     # on sys.path before importing them.\n\
                     import os as _os, sys as _sys\n\
                     _jst_dir = _os.path.dirname(_os.path.abspath(__file__))\n\
                     if _jst_dir not in _sys.path:\n    \
                         _sys.path.insert(0, _jst_dir)\n\
                     from {helper_module} import {}\n",
                    names.join(", ")
                ));
            }
            out.push_str("\n");
        } else {
            out.push_str("\n");

            // Type strictness helpers
            if features.needs_type_helpers {
                out.push_str(TYPE_CHECK_HELPERS);
                out.push('\n');
            }

            // Deep equality helper (type-aware, so false != 0 and true != 1)
            if features.needs_deep_equal {
                out.push_str(DEEP_EQUAL_HELPER);
                out.push('\n');
            }

            // Embedded draft 2020-12 interpreter (for SchemaIr::Interpreted roots)
            if features.needs_interpreter {
                out.push_str(JSI_PY_HELPER);
                out.push('\n');
            }
        }

        // Definitions + root
        out.push_str(&body);

        out
    }

    fn helpers_content(&self) -> Option<String> {
        let mut s = String::from(
            "# Generated by json-schema-transformer — shared runtime helpers\n\
             # DO NOT EDIT — changes will be overwritten on regeneration\n\n\
             from pydantic import ValidationError\n\n\
             try:\n    import regex as re\nexcept ImportError:\n    import re\n",
        );
        s.push_str(TYPE_CHECK_HELPERS);
        s.push_str(DEEP_EQUAL_HELPER);
        s.push('\n');
        s.push_str(TRY_VALIDATE_HELPER);
        s.push('\n');
        s.push_str(TRY_VALIDATE_G_HELPER);
        s.push_str(JSI_PY_HELPER);
        Some(s)
    }

    fn default_helpers_file(&self) -> Option<&'static str> {
        Some("jst_helpers.py")
    }
}

// ── Feature scanning ────────────────────────────────────────────────────────

fn scan_features(ir: &SchemaIr, f: &mut ModuleFeatures) {
    match ir {
        SchemaIr::Interpreted { .. } => {
            f.needs_before_validator = true;
            f.needs_json = true;
            f.needs_re = true;
            f.needs_interpreter = true;
        }
        SchemaIr::String(_) | SchemaIr::Number(_) | SchemaIr::Integer(_)
        | SchemaIr::Boolean | SchemaIr::Literal(_) => {
            f.needs_before_validator = true;
            f.needs_type_helpers = true;
        }
        SchemaIr::TypeGuarded(guards) => {
            f.needs_before_validator = true;
            for (guard, schema) in guards {
                match (guard, schema.as_ref()) {
                    (TypeGuard::String, SchemaIr::String(c)) => {
                        if c.pattern.is_some() {
                            f.needs_re = true;
                        }
                    }
                    (TypeGuard::Object, SchemaIr::Record(_)) => {
                        f.needs_type_adapter = true;
                    }
                    (TypeGuard::Object, SchemaIr::Object(obj)) => {
                        if obj.fields.values().any(|field| !matches!(&field.schema, SchemaIr::Any | SchemaIr::Unknown)) {
                            f.needs_type_adapter = true;
                        }
                        if !obj.pattern_properties.is_empty() {
                            f.needs_re = true;
                            f.needs_type_adapter = true;
                        }
                        if !obj.dependent_schemas.is_empty() {
                            f.needs_type_adapter = true;
                        }
                        if matches!(obj.additional_properties, AdditionalProperties::Schema(_)) {
                            f.needs_type_adapter = true;
                        }
                        if obj.property_names.is_some() {
                            f.needs_type_adapter = true;
                        }
                    }
                    (TypeGuard::Array, SchemaIr::Array(arr)) => {
                        if !matches!(arr.items.as_ref(), SchemaIr::Any) || arr.contains.is_some() {
                            f.needs_type_adapter = true;
                        }
                        if arr.unique_items {
                            f.needs_json = true;
                        }
                    }
                    (TypeGuard::Array, SchemaIr::Tuple(t)) => {
                        f.needs_type_adapter = true;
                        if t.unique_items {
                            f.needs_json = true;
                        }
                    }
                    _ => {}
                }
            }
        }
        SchemaIr::Not { .. } => {
            f.needs_before_validator = true;
            f.needs_type_adapter = true;
        }
        SchemaIr::Conditional { .. } => {
            f.needs_before_validator = true;
            f.needs_type_adapter = true;
        }
        SchemaIr::ConstEqual(_) => {
            f.needs_before_validator = true;
            f.needs_deep_equal = true;
            f.needs_json = true;
        }
        SchemaIr::ComplexEnum(_) => {
            f.needs_before_validator = true;
            f.needs_deep_equal = true;
            f.needs_json = true;
        }
        SchemaIr::MixedEnum(_) => {
            f.needs_before_validator = true;
            f.needs_deep_equal = true;
        }
        SchemaIr::Union(members) if members.len() > 1 => {
            f.needs_before_validator = true;
            f.needs_type_adapter = true;
        }
        SchemaIr::ExclusiveUnion(_) => {
            f.needs_before_validator = true;
            f.needs_type_adapter = true;
        }
        SchemaIr::Intersection(members) if members.len() > 1 => {
            f.needs_before_validator = true;
            f.needs_type_adapter = true;
        }
        SchemaIr::Never => {
            f.needs_before_validator = true;
        }
        SchemaIr::Enum(cases) if cases.is_empty() => {
            f.needs_before_validator = true;
        }
        SchemaIr::Array(a) => {
            if a.unique_items {
                f.needs_before_validator = true;
                f.needs_json = true;
                // Field-level uniqueItems uses the _check_unique_items helper
                f.needs_type_helpers = true;
            }
            if a.contains.is_some() {
                f.needs_before_validator = true;
                f.needs_type_adapter = true;
            }
        }
        SchemaIr::Tuple(_) => {
            f.needs_before_validator = true;
            f.needs_type_adapter = true;
        }
        SchemaIr::Object(o) => {
            if !o.pattern_properties.is_empty() {
                f.needs_re = true;
                f.needs_model_validator = true;
                f.needs_type_adapter = true;
            }
            if o.property_names.is_some() {
                f.needs_model_validator = true;
            }
            if o.min_properties.is_some() || o.max_properties.is_some() {
                f.needs_model_validator = true;
            }
            if !o.dependent_required.is_empty() {
                f.needs_model_validator = true;
            }
            if !o.dependent_schemas.is_empty() {
                f.needs_model_validator = true;
                f.needs_type_adapter = true;
            }
        }
        _ => {}
    }

    // Recurse into children
    visit_children(ir, |child| scan_features(child, f));
}

fn visit_children(ir: &SchemaIr, mut visitor: impl FnMut(&SchemaIr)) {
    match ir {
        SchemaIr::Array(a) => {
            visitor(&a.items);
            if let Some(c) = &a.contains {
                visitor(&c.schema);
            }
        }
        SchemaIr::Tuple(t) => {
            for item in &t.items {
                visitor(item);
            }
            if let Some(rest) = &t.rest {
                visitor(rest);
            }
            if let Some(c) = &t.contains {
                visitor(&c.schema);
            }
        }
        SchemaIr::Object(o) => {
            for f in o.fields.values() {
                visitor(&f.schema);
            }
            for (_, s) in &o.pattern_properties {
                visitor(s);
            }
            if let Some(pn) = &o.property_names {
                visitor(pn);
            }
            for (_, s) in &o.dependent_schemas {
                visitor(s);
            }
            if let AdditionalProperties::Schema(s) = &o.additional_properties {
                visitor(s);
            }
        }
        SchemaIr::Record(r) => {
            visitor(&r.key);
            visitor(&r.value);
        }
        SchemaIr::Union(ms) | SchemaIr::ExclusiveUnion(ms) | SchemaIr::Intersection(ms) => {
            for m in ms {
                visitor(m);
            }
        }
        SchemaIr::Nullable(inner)
        | SchemaIr::Optional(inner)
        | SchemaIr::Default(inner, _)
        | SchemaIr::Describe(inner, _) => visitor(inner),
        SchemaIr::Not { base, not_schema } => {
            visitor(base);
            visitor(not_schema);
        }
        SchemaIr::Conditional {
            base,
            if_schema,
            then_schema,
            else_schema,
        } => {
            visitor(base);
            visitor(if_schema);
            if let Some(s) = then_schema {
                visitor(s);
            }
            if let Some(s) = else_schema {
                visitor(s);
            }
        }
        SchemaIr::TypeGuarded(guards) => {
            for (_, s) in guards {
                visitor(s);
            }
        }
        _ => {}
    }
}

// ── Definition dispatch ─────────────────────────────────────────────────────

fn emit_definition(
    name: &str,
    ir: &SchemaIr,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    match ir {
        SchemaIr::Interpreted { schema, remotes } => {
            emit_interpreted(name, schema, remotes, counter)
        }
        SchemaIr::Object(obj) => emit_object_class(name, obj, defs, counter),
        SchemaIr::TypeGuarded(guards) => emit_type_guarded(name, guards, defs, counter),
        SchemaIr::Not { base, not_schema } => emit_not(name, base, not_schema, defs, counter),
        SchemaIr::Conditional {
            base,
            if_schema,
            then_schema,
            else_schema,
        } => emit_conditional(
            name,
            base,
            if_schema,
            then_schema.as_deref(),
            else_schema.as_deref(),
            defs,
            counter,
        ),
        SchemaIr::Enum(cases) if cases.is_empty() => emit_never(name, counter),
        SchemaIr::Literal(lit) => emit_literal(name, lit, counter),
        SchemaIr::ConstEqual(val) => emit_const_equal(name, val, counter),
        SchemaIr::ComplexEnum(values) => emit_complex_enum(name, values, counter),
        SchemaIr::MixedEnum(lits) => emit_mixed_enum(name, lits, counter),
        SchemaIr::Union(members) if members.len() > 1 => {
            emit_union(name, members, defs, counter)
        }
        SchemaIr::ExclusiveUnion(members) => {
            emit_exclusive_union(name, members, defs, counter)
        }
        SchemaIr::Intersection(members) if members.len() == 1 => {
            emit_definition(name, &members[0], defs, counter)
        }
        SchemaIr::Intersection(members) if members.len() > 1 => {
            emit_intersection(name, members, defs, counter)
        }
        SchemaIr::Array(arr) if arr.unique_items || arr.contains.is_some() => {
            emit_constrained_array(name, arr, defs, counter)
        }
        SchemaIr::Tuple(tuple) => emit_constrained_tuple(name, tuple, defs, counter),
        SchemaIr::Never => emit_never(name, counter),
        SchemaIr::Ref(ref_name) => {
            // Direct reference to a named def — use the actual type, not a string
            format!("{name} = {ref_name}")
        }
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => {
            emit_definition(name, inner, defs, counter)
        }
        SchemaIr::Nullable(inner) => {
            if matches!(inner.as_ref(), SchemaIr::Object(_)) {
                *counter += 1;
                let inner_name = format!("_Inner{}", *counter);
                let inner_def = emit_definition(&inner_name, inner, defs, counter);
                format!("{inner_def}\n\n{name} = Optional[{inner_name}]")
            } else {
                format!("{name} = Optional[{}]", annotated_type(inner, defs))
            }
        }
        _ => {
            // Simple type alias with optional Field constraints
            format!("{name} = {}", annotated_type(ir, defs))
        }
    }
}

// ── Annotated type (Phase 1: root types with constraints) ───────────────────

/// True when a field's schema is (possibly wrapped) an array with uniqueItems,
/// which Field() constraints cannot express.
fn field_array_has_unique_items(ir: &SchemaIr) -> bool {
    match ir {
        SchemaIr::Array(arr) => arr.unique_items,
        SchemaIr::Describe(inner, _)
        | SchemaIr::Default(inner, _)
        | SchemaIr::Nullable(inner)
        | SchemaIr::Optional(inner) => field_array_has_unique_items(inner),
        _ => false,
    }
}

fn annotated_type(ir: &SchemaIr, defs: &[DefEntry]) -> String {
    match ir {
        SchemaIr::String(_) => {
            let constraints = field_constraints(ir);
            if constraints.is_empty() {
                "Annotated[str, BeforeValidator(_check_str)]".to_string()
            } else {
                format!("Annotated[str, Field({constraints}), BeforeValidator(_check_str)]")
            }
        }
        SchemaIr::Integer(_) => {
            let constraints = field_constraints(ir);
            if constraints.is_empty() {
                "Annotated[int, BeforeValidator(_check_int)]".to_string()
            } else {
                format!("Annotated[int, Field({constraints}), BeforeValidator(_check_int)]")
            }
        }
        SchemaIr::Number(_) => {
            let constraints = field_constraints(ir);
            if constraints.is_empty() {
                "Annotated[float, BeforeValidator(_check_number)]".to_string()
            } else {
                format!("Annotated[float, Field({constraints}), BeforeValidator(_check_number)]")
            }
        }
        SchemaIr::Boolean => {
            "Annotated[bool, BeforeValidator(_check_bool)]".to_string()
        }
        SchemaIr::Array(arr) => {
            let item_type = py_type(&arr.items, defs);
            let base = format!("list[{item_type}]");
            let constraints = field_constraints(ir);
            let mut extras = Vec::new();
            if !constraints.is_empty() {
                extras.push(format!("Field({constraints})"));
            }
            if arr.unique_items {
                extras.push("BeforeValidator(_check_unique_items)".to_string());
            }
            if extras.is_empty() {
                base
            } else {
                format!("Annotated[{base}, {}]", extras.join(", "))
            }
        }
        SchemaIr::Nullable(inner) | SchemaIr::Optional(inner) => {
            format!("Optional[{}]", annotated_type(inner, defs))
        }
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => {
            annotated_type(inner, defs)
        }
        SchemaIr::Ref(name) => name.clone(),
        SchemaIr::Lazy(name) => format!("\"{name}\""),
        _ => py_type(ir, defs),
    }
}

// ── Object class emission (enhanced with model_validator) ───────────────────

fn emit_object_class(
    name: &str,
    obj: &ObjectSchema,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    let mut preamble = String::new();

    let has_aliases = obj.fields.iter().any(|(k, _)| {
        let py_name = to_snake_case(k);
        py_name != *k || needs_python_quoting(k)
    });
    let forbid_extra = matches!(obj.additional_properties, AdditionalProperties::Forbidden);
    let has_pattern_props = !obj.pattern_properties.is_empty();
    let has_advanced_constraints = has_pattern_props
        || obj.property_names.is_some()
        || obj.min_properties.is_some()
        || obj.max_properties.is_some()
        || !obj.dependent_required.is_empty()
        || !obj.dependent_schemas.is_empty();

    // With patternProperties, we need to allow extra keys and validate manually
    let effective_forbid = forbid_extra && !has_pattern_props;

    let config = if has_aliases || effective_forbid {
        let mut config_parts = Vec::new();
        if has_aliases {
            config_parts.push("\"populate_by_name\": True");
        }
        if effective_forbid {
            config_parts.push("\"extra\": \"forbid\"");
        }
        format!(
            "@pydantic_dataclass(config={{{}}})",
            config_parts.join(", ")
        )
    } else {
        "@pydantic_dataclass".to_string()
    };

    let mut lines = vec![config, format!("class {name}:")];

    if obj.fields.is_empty() && !has_advanced_constraints {
        lines.push("    pass".to_string());
    } else {
        // Required fields must come before optional (Python dataclass rule)
        let mut sorted_fields: Vec<_> = obj.fields.iter().collect();
        sorted_fields.sort_by_key(|(_, f)| if f.required { 0 } else { 1 });

        if sorted_fields.is_empty() {
            lines.push("    pass".to_string());
        }

        for (k, f) in &sorted_fields {
            let py_name = to_snake_case(k);
            let mut py_type = py_type(&f.schema, defs);
            if field_array_has_unique_items(&f.schema) {
                py_type = format!("Annotated[{py_type}, BeforeValidator(_check_unique_items)]");
            }
            let field_args = field_constraints(&f.schema);

            let type_str = if f.required {
                py_type
            } else {
                format!("Optional[{py_type}]")
            };

            let needs_alias = py_name != **k || needs_python_quoting(k);
            let has_field = !field_args.is_empty() || needs_alias;

            if !has_field && !f.required {
                lines.push(format!("    {py_name}: {type_str} = None"));
            } else if !has_field {
                lines.push(format!("    {py_name}: {type_str}"));
            } else {
                let mut field_parts = Vec::new();
                if !field_args.is_empty() {
                    field_parts.push(field_args);
                }
                if needs_alias {
                    field_parts.push(format!("alias=\"{}\"", escape_string(k)));
                }
                let field_expr = format!("Field({})", field_parts.join(", "));

                if f.required {
                    lines.push(format!(
                        "    {py_name}: Annotated[{type_str}, {field_expr}]"
                    ));
                } else {
                    field_parts.push("default=None".to_string());
                    let field_expr_with_default =
                        format!("Field({})", field_parts.join(", "));
                    lines.push(format!(
                        "    {py_name}: {type_str} = {field_expr_with_default}",
                    ));
                }
            }
        }

        // model_validator for advanced constraints
        if has_advanced_constraints {
            let mut checks = Vec::new();

            // patternProperties
            for (pattern, schema) in &obj.pattern_properties {
                let (sub_preamble, sub_type) =
                    emit_sub_schema("pp", schema, defs, counter);
                if !sub_preamble.is_empty() {
                    preamble.push_str(&sub_preamble);
                    preamble.push('\n');
                }
                *counter += 1;
                let ta_name = format!("_pp_ta_{}", *counter);
                preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
                checks.push(format!(
                    "            for k, val in data.items():\n                if re.search(r\"{}\", k):\n                    {ta_name}.validate_python(val)",
                    pattern.replace('"', "\\\"")
                ));
            }

            // additionalProperties: false with patternProperties
            if forbid_extra && has_pattern_props {
                let named_keys: Vec<String> = obj
                    .fields
                    .keys()
                    .map(|k| format!("\"{}\"", escape_string(k)))
                    .collect();
                let patterns: Vec<String> = obj
                    .pattern_properties
                    .iter()
                    .map(|(p, _)| format!("r\"{}\"", p.replace('"', "\\\"")))
                    .collect();
                checks.push(format!(
                    "            _named = {{{}}}\n            _patterns = [{}]\n            for k in data:\n                if k not in _named and not any(re.search(p, k) for p in _patterns):\n                    raise ValueError(f'unexpected property: {{k}}')",
                    named_keys.join(", "),
                    patterns.join(", ")
                ));
            }

            // propertyNames
            if let Some(pn) = &obj.property_names {
                let pn_checks = emit_property_names_checks(pn);
                if !pn_checks.is_empty() {
                    checks.push(format!(
                        "            for k in data:\n{}",
                        pn_checks
                            .iter()
                            .map(|c| format!("                {c}"))
                            .collect::<Vec<_>>()
                            .join("\n")
                    ));
                }
            }

            // minProperties / maxProperties
            if let Some(min) = obj.min_properties {
                checks.push(format!(
                    "            if len(data) < {min}:\n                raise ValueError('object must have at least {min} properties')"
                ));
            }
            if let Some(max) = obj.max_properties {
                checks.push(format!(
                    "            if len(data) > {max}:\n                raise ValueError('object must have at most {max} properties')"
                ));
            }

            // dependentRequired
            for (prop, required) in &obj.dependent_required {
                let req_checks: Vec<String> = required
                    .iter()
                    .map(|r| {
                        format!(
                            "                    if \"{}\" not in data:\n                        raise ValueError('\"{}\" is required when \"{}\" is present')",
                            escape_string(r),
                            escape_string(r),
                            escape_string(prop)
                        )
                    })
                    .collect();
                checks.push(format!(
                    "            if \"{}\" in data:\n{}",
                    escape_string(prop),
                    req_checks.join("\n")
                ));
            }

            // dependentSchemas
            for (prop, schema) in &obj.dependent_schemas {
                let (sub_preamble, sub_type) =
                    emit_sub_schema("ds", schema, defs, counter);
                if !sub_preamble.is_empty() {
                    preamble.push_str(&sub_preamble);
                    preamble.push('\n');
                }
                *counter += 1;
                let ta_name = format!("_ds_ta_{}", *counter);
                preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
                checks.push(format!(
                    "            if \"{}\" in data:\n                {ta_name}.validate_python(data)",
                    escape_string(prop)
                ));
            }

            if !checks.is_empty() {
                lines.push(String::new());
                lines.push("    @model_validator(mode='before')".to_string());
                lines.push("    @classmethod".to_string());
                lines.push("    def _validate_constraints(cls, data):".to_string());
                lines.push("        if isinstance(data, dict):".to_string());
                for check in &checks {
                    lines.push(check.clone());
                }
                lines.push("        return data".to_string());
            }
        }
    }

    let class_def = lines.join("\n");
    if preamble.is_empty() {
        class_def
    } else {
        format!("{preamble}\n{class_def}")
    }
}

// ── TypeGuarded emission (Phase 2) ──────────────────────────────────────────

fn emit_type_guarded(
    name: &str,
    guards: &[(TypeGuard, Box<SchemaIr>)],
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    *counter += 1;
    let fn_name = format!("_validate_{}", counter);
    let mut lines = Vec::new();
    let mut preamble = String::new();

    lines.push(format!("def {fn_name}(v):"));

    for (guard, schema) in guards {
        let (type_check, checks) = match guard {
            TypeGuard::String => {
                ("isinstance(v, str)", emit_string_guard_checks(schema))
            }
            TypeGuard::Number => (
                "isinstance(v, (int, float)) and not isinstance(v, bool)",
                emit_number_guard_checks(schema),
            ),
            TypeGuard::Object => {
                let checks = emit_object_guard_checks(schema, defs, counter, &mut preamble);
                ("isinstance(v, dict)", checks)
            }
            TypeGuard::Array => {
                let checks = emit_array_guard_checks(schema, defs, counter, &mut preamble);
                ("isinstance(v, (list, tuple))", checks)
            }
        };

        if checks.is_empty() {
            continue;
        }

        lines.push(format!("    if {type_check}:"));
        for check in &checks {
            lines.push(format!("        {check}"));
        }
    }

    lines.push("    return v".to_string());
    lines.push(String::new());
    lines.push(format!(
        "{name} = Annotated[Any, BeforeValidator({fn_name})]"
    ));

    if preamble.is_empty() {
        lines.join("\n")
    } else {
        format!("{preamble}\n{}", lines.join("\n"))
    }
}

fn emit_string_guard_checks(ir: &SchemaIr) -> Vec<String> {
    let mut checks = Vec::new();
    if let SchemaIr::String(c) = ir {
        if let Some(min) = c.min_length {
            checks.push(format!(
                "if len(v) < {min}: raise ValueError('minLength')"
            ));
        }
        if let Some(max) = c.max_length {
            checks.push(format!(
                "if len(v) > {max}: raise ValueError('maxLength')"
            ));
        }
        if let Some(pat) = &c.pattern {
            checks.push(format!(
                "if not re.search(r\"{}\", v): raise ValueError('pattern')",
                pat.replace('"', "\\\"")
            ));
        }
    }
    checks
}

fn emit_number_guard_checks(ir: &SchemaIr) -> Vec<String> {
    let mut checks = Vec::new();
    let c = match ir {
        SchemaIr::Number(c) | SchemaIr::Integer(c) => c,
        _ => return checks,
    };
    if let Some(min) = c.minimum {
        checks.push(format!(
            "if v < {}: raise ValueError('minimum')",
            format_py_number(min)
        ));
    }
    if let Some(max) = c.maximum {
        checks.push(format!(
            "if v > {}: raise ValueError('maximum')",
            format_py_number(max)
        ));
    }
    if let Some(emin) = c.exclusive_minimum {
        checks.push(format!(
            "if v <= {}: raise ValueError('exclusiveMinimum')",
            format_py_number(emin)
        ));
    }
    if let Some(emax) = c.exclusive_maximum {
        checks.push(format!(
            "if v >= {}: raise ValueError('exclusiveMaximum')",
            format_py_number(emax)
        ));
    }
    if let Some(mul) = c.multiple_of {
        let n = format_py_number(mul);
        checks.push(format!(
            "if not __import__('math').isfinite(v / {n}) or abs(__import__('math').remainder(v, {n})) > 1e-10: raise ValueError('multipleOf')"
        ));
    }
    checks
}

fn emit_object_guard_checks(
    ir: &SchemaIr,
    defs: &[DefEntry],
    counter: &mut usize,
    preamble: &mut String,
) -> Vec<String> {
    // Handle Record type (additionalProperties as schema, no named properties)
    if let SchemaIr::Record(rec) = ir {
        let mut checks = Vec::new();
        if !matches!(rec.value.as_ref(), SchemaIr::Any | SchemaIr::Unknown) {
            let (sub_preamble, sub_type) = emit_sub_schema("rv", &rec.value, defs, counter);
            if !sub_preamble.is_empty() {
                preamble.push_str(&sub_preamble);
                preamble.push('\n');
            }
            *counter += 1;
            let ta_name = format!("_rv_ta_{}", *counter);
            preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
            checks.push(format!(
                "for _k, _val in v.items(): {ta_name}.validate_python(_val)"
            ));
        }
        return checks;
    }

    let obj = match ir {
        SchemaIr::Object(obj) => obj,
        _ => return vec![],
    };
    let mut checks = Vec::new();

    // Required fields
    for (k, f) in &obj.fields {
        if f.required {
            checks.push(format!(
                "if \"{}\" not in v: raise ValueError('required: {}')",
                escape_string(k),
                escape_string(k)
            ));
        }
    }

    // minProperties / maxProperties
    if let Some(min) = obj.min_properties {
        checks.push(format!(
            "if len(v) < {min}: raise ValueError('minProperties')"
        ));
    }
    if let Some(max) = obj.max_properties {
        checks.push(format!(
            "if len(v) > {max}: raise ValueError('maxProperties')"
        ));
    }

    // additionalProperties: false (only when no patternProperties — otherwise handled below)
    if matches!(obj.additional_properties, AdditionalProperties::Forbidden)
        && obj.pattern_properties.is_empty()
    {
        let known: Vec<String> = obj
            .fields
            .keys()
            .map(|k| format!("\"{}\"", escape_string(k)))
            .collect();
        if known.is_empty() {
            checks.push(
                "if len(v) > 0: raise ValueError('additionalProperties')".to_string(),
            );
        } else {
            checks.push(format!(
                "if any(k not in {{{}}} for k in v): raise ValueError('additionalProperties')",
                known.join(", ")
            ));
        }
    }

    // Field type validation
    for (k, f) in &obj.fields {
        let key_str = escape_string(k);
        // Skip Any-typed fields — no validation needed
        if matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) {
            continue;
        }
        let (sub_preamble, sub_type) = emit_sub_schema("fg", &f.schema, defs, counter);
        if !sub_preamble.is_empty() {
            preamble.push_str(&sub_preamble);
            preamble.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_fg_ta_{}", *counter);
        preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        checks.push(format!(
            "if \"{key_str}\" in v:\n            {ta_name}.validate_python(v[\"{key_str}\"])"
        ));
    }

    // patternProperties
    if !obj.pattern_properties.is_empty() {
        let named_keys: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
        let mut pp_lines = Vec::new();
        for (pattern, schema) in &obj.pattern_properties {
            let (sub_preamble, sub_type) = emit_sub_schema("pp", schema, defs, counter);
            if !sub_preamble.is_empty() {
                preamble.push_str(&sub_preamble);
                preamble.push('\n');
            }
            *counter += 1;
            let ta_name = format!("_pp_ta_{}", *counter);
            preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
            pp_lines.push(format!(
                "if re.search(r\"{}\", k): _matched = True; {ta_name}.validate_python(val)",
                pattern.replace('"', "\\\"")
            ));
        }
        // additionalProperties in combination with patternProperties
        let ap_line = match &obj.additional_properties {
            AdditionalProperties::Forbidden => {
                format!(
                    "if not _matched and k not in {{{}}}: raise ValueError(f'unexpected property: {{k}}')",
                    named_keys.join(", ")
                )
            }
            AdditionalProperties::Schema(ap_schema) => {
                let (sub_preamble, sub_type) = emit_sub_schema("ap", ap_schema, defs, counter);
                if !sub_preamble.is_empty() {
                    preamble.push_str(&sub_preamble);
                    preamble.push('\n');
                }
                *counter += 1;
                let ta_name = format!("_ap_ta_{}", *counter);
                preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
                format!(
                    "if not _matched and k not in {{{}}}: {ta_name}.validate_python(val)",
                    named_keys.join(", ")
                )
            }
            _ => String::new(),
        };
        let mut body = String::from("for k, val in v.items():\n            _matched = False\n");
        for pl in &pp_lines {
            body.push_str(&format!("            {pl}\n"));
        }
        if !ap_line.is_empty() {
            body.push_str(&format!("            {ap_line}"));
        }
        checks.push(body.trim_end().to_string());
    } else if let AdditionalProperties::Schema(ap_schema) = &obj.additional_properties {
        // additionalProperties with schema (no patternProperties)
        let named_keys: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
        let (sub_preamble, sub_type) = emit_sub_schema("ap", ap_schema, defs, counter);
        if !sub_preamble.is_empty() {
            preamble.push_str(&sub_preamble);
            preamble.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_ap_ta_{}", *counter);
        preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        let named_set = if named_keys.is_empty() {
            "set()".to_string()
        } else {
            format!("{{{}}}", named_keys.join(", "))
        };
        checks.push(format!(
            "for k, val in v.items():\n            if k not in {named_set}: {ta_name}.validate_python(val)"
        ));
    }

    // propertyNames — use TypeAdapter for complex constraints
    if let Some(pn) = &obj.property_names {
        let (sub_preamble, sub_type) = emit_sub_schema("pn", pn, defs, counter);
        if !sub_preamble.is_empty() {
            preamble.push_str(&sub_preamble);
            preamble.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_pn_ta_{}", *counter);
        preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        checks.push(format!(
            "for k in v: {ta_name}.validate_python(k)"
        ));
    }

    // dependentRequired
    for (prop, required) in &obj.dependent_required {
        for r in required {
            checks.push(format!(
                "if \"{}\" in v and \"{}\" not in v: raise ValueError('dependentRequired')",
                escape_string(prop),
                escape_string(r)
            ));
        }
    }

    // dependentSchemas
    for (prop, schema) in &obj.dependent_schemas {
        let (sub_preamble, sub_type) = emit_sub_schema("dsg", schema, defs, counter);
        if !sub_preamble.is_empty() {
            preamble.push_str(&sub_preamble);
            preamble.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_dsg_ta_{}", *counter);
        preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        checks.push(format!(
            "if \"{}\" in v: {ta_name}.validate_python(v)",
            escape_string(prop)
        ));
    }

    checks
}

fn emit_array_guard_checks(
    ir: &SchemaIr,
    defs: &[DefEntry],
    counter: &mut usize,
    preamble: &mut String,
) -> Vec<String> {
    let mut checks = Vec::new();

    // Handle Tuple IR (prefixItems) inside an Array TypeGuard
    if let SchemaIr::Tuple(tuple) = ir {
        for (i, item) in tuple.items.iter().enumerate() {
            if matches!(item, SchemaIr::Any) {
                continue;
            }
            let (sub_preamble, sub_type) = emit_sub_schema("tg", item, defs, counter);
            if !sub_preamble.is_empty() {
                preamble.push_str(&sub_preamble);
                preamble.push('\n');
            }
            *counter += 1;
            let ta_name = format!("_tg_ta_{}", *counter);
            preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
            checks.push(format!(
                "if len(v) > {i}: {ta_name}.validate_python(v[{i}])"
            ));
        }
        let prefix_count = tuple.items.len();
        if tuple.rest.is_none() {
            checks.push(format!(
                "if len(v) > {prefix_count}: raise ValueError('too many items')"
            ));
        } else if let Some(rest) = &tuple.rest {
            if !matches!(rest.as_ref(), SchemaIr::Any) {
                let (sub_preamble, sub_type) = emit_sub_schema("tgr", rest, defs, counter);
                if !sub_preamble.is_empty() {
                    preamble.push_str(&sub_preamble);
                    preamble.push('\n');
                }
                *counter += 1;
                let ta_name = format!("_tgr_ta_{}", *counter);
                preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
                checks.push(format!(
                    "for _i in range({prefix_count}, len(v)): {ta_name}.validate_python(v[_i])"
                ));
            }
        }
        if let Some(min) = tuple.min_items {
            checks.push(format!("if len(v) < {min}: raise ValueError('minItems')"));
        }
        if let Some(max) = tuple.max_items {
            checks.push(format!("if len(v) > {max}: raise ValueError('maxItems')"));
        }
        if tuple.unique_items {
            checks.push(
                "if len(set(json.dumps(x, sort_keys=True, default=str) for x in v)) != len(v): raise ValueError('uniqueItems')"
                    .to_string(),
            );
        }
        return checks;
    }

    if let SchemaIr::Array(arr) = ir {
        if let Some(min) = arr.min_items {
            checks.push(format!(
                "if len(v) < {min}: raise ValueError('minItems')"
            ));
        }
        if let Some(max) = arr.max_items {
            checks.push(format!(
                "if len(v) > {max}: raise ValueError('maxItems')"
            ));
        }
        if arr.unique_items {
            checks.push(
                "if len(set(json.dumps(x, sort_keys=True, default=str) for x in v)) != len(v): raise ValueError('uniqueItems')"
                    .to_string(),
            );
        }
        if let Some(contains) = &arr.contains {
            let (sub_preamble, sub_type) =
                emit_sub_schema("cg", &contains.schema, defs, counter);
            if !sub_preamble.is_empty() {
                preamble.push_str(&sub_preamble);
                preamble.push('\n');
            }
            *counter += 1;
            let ta_name = format!("_cg_ta_{}", *counter);
            preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));

            let min = contains.min_contains.unwrap_or(1);
            checks.push(format!(
                "_mc = sum(1 for x in v if _try_validate_g({ta_name}, x))"
            ));
            checks.push(format!(
                "if _mc < {min}: raise ValueError('must contain at least {min} matching items')"
            ));
            if let Some(max) = contains.max_contains {
                checks.push(format!(
                    "if _mc > {max}: raise ValueError('must contain at most {max} matching items')"
                ));
            }

            // Ensure the _try_validate_g helper is defined
            preamble.push_str(&format!("\n{TRY_VALIDATE_G_HELPER}\n"));
        }

        // Items type validation
        if !matches!(arr.items.as_ref(), SchemaIr::Any) {
            let (sub_preamble, sub_type) = emit_sub_schema("ig", &arr.items, defs, counter);
            if !sub_preamble.is_empty() {
                preamble.push_str(&sub_preamble);
                preamble.push('\n');
            }
            *counter += 1;
            let ta_name = format!("_ig_ta_{}", *counter);
            preamble.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
            checks.push(format!(
                "for _item in v: {ta_name}.validate_python(_item)"
            ));
        }

        // Items = false (Never) — reject all items
        if matches!(arr.items.as_ref(), SchemaIr::Never) {
            checks.push("if len(v) > 0: raise ValueError('no items allowed')".to_string());
        }
    }
    checks
}

fn emit_property_names_checks(pn: &SchemaIr) -> Vec<String> {
    let mut checks = Vec::new();
    if let SchemaIr::String(c) = pn {
        if let Some(max) = c.max_length {
            checks.push(format!(
                "if len(k) > {max}: raise ValueError('propertyNames: maxLength')"
            ));
        }
        if let Some(min) = c.min_length {
            checks.push(format!(
                "if len(k) < {min}: raise ValueError('propertyNames: minLength')"
            ));
        }
        if let Some(pat) = &c.pattern {
            checks.push(format!(
                "if not re.search(r\"{}\", k): raise ValueError('propertyNames: pattern')",
                pat.replace('"', "\\\"")
            ));
        }
    }
    checks
}

// ── Not emission (Phase 3) ──────────────────────────────────────────────────

fn emit_not(
    name: &str,
    base: &SchemaIr,
    not_schema: &SchemaIr,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    let base_type = annotated_type(base, defs);
    let (sub_preamble, sub_type) = emit_sub_schema("not", not_schema, defs, counter);

    *counter += 1;
    let ta_name = format!("_not_ta_{}", *counter);
    let fn_name = format!("_validate_not_{}", *counter);

    let mut out = String::new();
    if !sub_preamble.is_empty() {
        out.push_str(&sub_preamble);
        out.push('\n');
    }
    out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n\n"));
    out.push_str(&format!("def {fn_name}(v):\n"));
    out.push_str(&format!("    try:\n"));
    out.push_str(&format!("        {ta_name}.validate_python(v)\n"));
    out.push_str(&format!("    except (ValidationError, ValueError, TypeError):\n"));
    out.push_str(&format!("        return v\n"));
    out.push_str(&format!(
        "    raise ValueError('must not match excluded schema')\n\n"
    ));
    out.push_str(&format!(
        "{name} = Annotated[{base_type}, BeforeValidator({fn_name})]"
    ));

    out
}

// ── Conditional emission (Phase 3) ──────────────────────────────────────────

fn emit_conditional(
    name: &str,
    base: &SchemaIr,
    if_schema: &SchemaIr,
    then_schema: Option<&SchemaIr>,
    else_schema: Option<&SchemaIr>,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    let base_type = annotated_type(base, defs);

    let (if_preamble, if_type) = emit_sub_schema("if", if_schema, defs, counter);
    *counter += 1;
    let if_ta = format!("_if_ta_{}", *counter);

    let then_ta = then_schema.map(|ts| {
        let (p, t) = emit_sub_schema("then", ts, defs, counter);
        *counter += 1;
        let name = format!("_then_ta_{}", *counter);
        (p, t, name)
    });

    let else_ta = else_schema.map(|es| {
        let (p, t) = emit_sub_schema("else", es, defs, counter);
        *counter += 1;
        let name = format!("_else_ta_{}", *counter);
        (p, t, name)
    });

    *counter += 1;
    let fn_name = format!("_validate_cond_{}", *counter);

    let mut out = String::new();

    // Preamble: sub-schema definitions and TypeAdapters
    if !if_preamble.is_empty() {
        out.push_str(&if_preamble);
        out.push('\n');
    }
    out.push_str(&format!("{if_ta} = TypeAdapter({if_type})\n"));

    if let Some((ref p, ref t, ref n)) = then_ta {
        if !p.is_empty() {
            out.push_str(p);
            out.push('\n');
        }
        out.push_str(&format!("{n} = TypeAdapter({t})\n"));
    }
    if let Some((ref p, ref t, ref n)) = else_ta {
        if !p.is_empty() {
            out.push_str(p);
            out.push('\n');
        }
        out.push_str(&format!("{n} = TypeAdapter({t})\n"));
    }

    // Validator function
    out.push_str(&format!("\ndef {fn_name}(v):\n"));
    out.push_str(&format!("    _if_matched = True\n"));
    out.push_str(&format!("    try:\n"));
    out.push_str(&format!("        {if_ta}.validate_python(v)\n"));
    out.push_str(&format!(
        "    except (ValidationError, ValueError, TypeError):\n"
    ));
    out.push_str(&format!("        _if_matched = False\n"));

    if let Some((_, _, ref n)) = then_ta {
        out.push_str(&format!("    if _if_matched:\n"));
        out.push_str(&format!("        {n}.validate_python(v)\n"));
    }
    if let Some((_, _, ref n)) = else_ta {
        out.push_str(&format!("    if not _if_matched:\n"));
        out.push_str(&format!("        {n}.validate_python(v)\n"));
    }

    out.push_str(&format!("    return v\n\n"));
    out.push_str(&format!(
        "{name} = Annotated[{base_type}, BeforeValidator({fn_name})]"
    ));

    out
}

// ── Literal emission ────────────────────────────────────────────────────────

fn emit_literal(name: &str, lit: &LiteralValue, counter: &mut usize) -> String {
    // Use identity/type-aware checks to avoid Python's bool/int confusion
    *counter += 1;
    let fn_name = format!("_validate_literal_{}", *counter);

    match lit {
        LiteralValue::Bool(b) => {
            let py_val = if *b { "True" } else { "False" };
            format!(
                "def {fn_name}(v):\n    if v is not {py_val}:\n        raise ValueError('must be {py_val}')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
            )
        }
        LiteralValue::Integer(i) => {
            format!(
                "def {fn_name}(v):\n    if isinstance(v, bool) or not isinstance(v, (int, float)) or v != {i}:\n        raise ValueError('must be {i}')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
            )
        }
        LiteralValue::Number(n) => {
            let py_n = format_py_number(*n);
            format!(
                "def {fn_name}(v):\n    if isinstance(v, bool) or not isinstance(v, (int, float)) or v != {py_n}:\n        raise ValueError('must be {py_n}')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
            )
        }
        LiteralValue::Null => {
            format!(
                "def {fn_name}(v):\n    if v is not None:\n        raise ValueError('must be null')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
            )
        }
        LiteralValue::String(s) => {
            let escaped = escape_string(s);
            format!(
                "def {fn_name}(v):\n    if not isinstance(v, str) or v != \"{}\":\n        raise ValueError('must be \"{}\"')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]",
                escaped, escaped
            )
        }
    }
}

// ── ConstEqual emission (Phase 5) ───────────────────────────────────────────

fn emit_const_equal(name: &str, val: &serde_json::Value, counter: &mut usize) -> String {
    let json_str = serde_json::to_string(val).unwrap_or_else(|_| "null".to_string());
    // Escape single quotes in JSON string for Python
    let json_str_escaped = json_str.replace('\'', "\\'");
    *counter += 1;
    let fn_name = format!("_validate_const_{}", *counter);

    format!(
        "def {fn_name}(v):\n    _expected = json.loads('{json_str_escaped}')\n    if not _deep_equal(v, _expected):\n        raise ValueError('must equal const value')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
    )
}

// ── ComplexEnum emission (Phase 5) ──────────────────────────────────────────

fn emit_complex_enum(
    name: &str,
    values: &[serde_json::Value],
    counter: &mut usize,
) -> String {
    let json_str =
        serde_json::to_string(values).unwrap_or_else(|_| "[]".to_string());
    let json_str_escaped = json_str.replace('\'', "\\'");
    *counter += 1;
    let fn_name = format!("_validate_enum_{}", *counter);

    format!(
        "def {fn_name}(v):\n    _allowed = json.loads('{json_str_escaped}')\n    if not any(_deep_equal(v, a) for a in _allowed):\n        raise ValueError('must be one of the allowed values')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
    )
}

// ── MixedEnum emission ──────────────────────────────────────────────────────

fn emit_mixed_enum(
    name: &str,
    lits: &[LiteralValue],
    counter: &mut usize,
) -> String {
    // Build a list of Python literal values with type awareness
    let py_values: Vec<String> = lits.iter().map(|l| match l {
        LiteralValue::String(s) => format!("\"{}\"", escape_string(s)),
        LiteralValue::Number(n) => format_py_number(*n),
        LiteralValue::Integer(i) => format!("{i}"),
        LiteralValue::Bool(b) => if *b { "True" } else { "False" }.to_string(),
        LiteralValue::Null => "None".to_string(),
    }).collect();

    *counter += 1;
    let fn_name = format!("_validate_mixed_enum_{}", *counter);

    let allowed_list = py_values.join(", ");
    format!(
        "def {fn_name}(v):\n    _allowed = [{allowed_list}]\n    if not any(_deep_equal(v, a) for a in _allowed):\n        raise ValueError('must be one of the allowed values')\n    return v\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
    )
}

// ── Union emission (anyOf) ──────────────────────────────────────────────────

fn emit_union(
    name: &str,
    members: &[SchemaIr],
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    if members.len() == 1 {
        return emit_definition(name, &members[0], defs, counter);
    }

    let mut out = String::new();
    let mut ta_names = Vec::new();

    for member in members {
        let (sub_preamble, sub_type) = emit_sub_schema("anyof", member, defs, counter);
        if !sub_preamble.is_empty() {
            out.push_str(&sub_preamble);
            out.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_anyof_ta_{}", *counter);
        out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        ta_names.push(ta_name);
    }

    *counter += 1;
    let fn_name = format!("_validate_anyof_{}", *counter);

    out.push_str(&format!("\ndef {fn_name}(v):\n"));
    for ta in &ta_names {
        out.push_str(&format!("    try:\n"));
        out.push_str(&format!("        {ta}.validate_python(v)\n"));
        out.push_str(&format!("        return v\n"));
        out.push_str(&format!(
            "    except (ValidationError, ValueError, TypeError):\n"
        ));
        out.push_str(&format!("        pass\n"));
    }
    out.push_str(
        "    raise ValueError('must match at least one schema')\n\n",
    );
    out.push_str(&format!(
        "{name} = Annotated[Any, BeforeValidator({fn_name})]"
    ));

    out
}

// ── ExclusiveUnion emission ─────────────────────────────────────────────────

fn emit_exclusive_union(
    name: &str,
    members: &[SchemaIr],
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    if members.len() == 1 {
        return emit_definition(name, &members[0], defs, counter);
    }

    let mut out = String::new();
    let mut ta_names = Vec::new();

    for member in members {
        let (sub_preamble, sub_type) = emit_sub_schema("oneof", member, defs, counter);
        if !sub_preamble.is_empty() {
            out.push_str(&sub_preamble);
            out.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_oneof_ta_{}", *counter);
        out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        ta_names.push(ta_name);
    }

    *counter += 1;
    let fn_name = format!("_validate_oneof_{}", *counter);

    out.push_str(&format!("\ndef {fn_name}(v):\n"));
    out.push_str("    _matches = 0\n");
    for ta in &ta_names {
        out.push_str(&format!("    try:\n"));
        out.push_str(&format!("        {ta}.validate_python(v)\n"));
        out.push_str(&format!("        _matches += 1\n"));
        out.push_str(&format!(
            "    except (ValidationError, ValueError, TypeError):\n"
        ));
        out.push_str(&format!("        pass\n"));
    }
    out.push_str(
        "    if _matches != 1:\n        raise ValueError(f'must match exactly one schema, matched {{_matches}}')\n",
    );
    out.push_str("    return v\n\n");
    out.push_str(&format!(
        "{name} = Annotated[Any, BeforeValidator({fn_name})]"
    ));

    out
}

// ── Intersection emission ───────────────────────────────────────────────────

fn emit_intersection(
    name: &str,
    members: &[SchemaIr],
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    if members.len() == 1 {
        return emit_definition(name, &members[0], defs, counter);
    }

    let mut out = String::new();
    let mut ta_names = Vec::new();

    for member in members {
        let (sub_preamble, sub_type) = emit_sub_schema("inter", member, defs, counter);
        if !sub_preamble.is_empty() {
            out.push_str(&sub_preamble);
            out.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_inter_ta_{}", *counter);
        out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        ta_names.push(ta_name);
    }

    *counter += 1;
    let fn_name = format!("_validate_inter_{}", *counter);

    out.push_str(&format!("\ndef {fn_name}(v):\n"));
    for ta in &ta_names {
        out.push_str(&format!("    {ta}.validate_python(v)\n"));
    }
    out.push_str("    return v\n\n");
    out.push_str(&format!(
        "{name} = Annotated[Any, BeforeValidator({fn_name})]"
    ));

    out
}

// ── Constrained array emission ──────────────────────────────────────────────

fn emit_constrained_array(
    name: &str,
    arr: &ArraySchema,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    let item_type = py_type(&arr.items, defs);
    let base_type = format!("list[{item_type}]");
    let constraints = field_constraints(&SchemaIr::Array(arr.clone()));

    let mut out = String::new();
    let mut validator_checks = Vec::new();

    // uniqueItems
    if arr.unique_items {
        validator_checks.push(
            "    if len(set(json.dumps(x, sort_keys=True, default=str) for x in v)) != len(v):\n        raise ValueError('uniqueItems')"
                .to_string(),
        );
    }

    // contains
    if let Some(contains) = &arr.contains {
        let (sub_preamble, sub_type) =
            emit_sub_schema("contains", &contains.schema, defs, counter);
        if !sub_preamble.is_empty() {
            out.push_str(&sub_preamble);
            out.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_contains_ta_{}", *counter);
        out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));

        let min = contains.min_contains.unwrap_or(1);
        validator_checks.push(format!(
            "    _match_count = sum(1 for x in v if _try_validate({ta_name}, x))"
        ));
        validator_checks.push(format!(
            "    if _match_count < {min}:\n        raise ValueError('must contain at least {min} matching items')"
        ));
        if let Some(max) = contains.max_contains {
            validator_checks.push(format!(
                "    if _match_count > {max}:\n        raise ValueError('must contain at most {max} matching items')"
            ));
        }

        // Add the _try_validate helper if not already present
        out.push_str(&format!("\n{TRY_VALIDATE_HELPER}\n"));
    }

    if validator_checks.is_empty() {
        // Just use annotated type
        if constraints.is_empty() {
            out.push_str(&format!("{name} = {base_type}"));
        } else {
            out.push_str(&format!(
                "{name} = Annotated[{base_type}, Field({constraints})]"
            ));
        }
    } else {
        *counter += 1;
        let fn_name = format!("_validate_arr_{}", *counter);

        out.push_str(&format!("def {fn_name}(v):\n"));
        out.push_str("    if not isinstance(v, (list, tuple)):\n        return v\n");
        for check in &validator_checks {
            out.push_str(check);
            out.push('\n');
        }
        out.push_str("    return v\n\n");

        if constraints.is_empty() {
            out.push_str(&format!(
                "{name} = Annotated[{base_type}, BeforeValidator({fn_name})]"
            ));
        } else {
            out.push_str(&format!(
                "{name} = Annotated[{base_type}, Field({constraints}), BeforeValidator({fn_name})]"
            ));
        }
    }

    out
}

// ── Tuple emission ──────────────────────────────────────────────────────────

fn emit_constrained_tuple(
    name: &str,
    tuple: &TupleSchema,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    let mut out = String::new();
    let mut checks = Vec::new();

    // Item type adapters for each prefix item
    let mut item_tas = Vec::new();
    for (i, item) in tuple.items.iter().enumerate() {
        let (sub_preamble, sub_type) = emit_sub_schema("ti", item, defs, counter);
        if !sub_preamble.is_empty() {
            out.push_str(&sub_preamble);
            out.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_ti_ta_{}", *counter);
        out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
        item_tas.push((i, ta_name));
    }

    // Rest type adapter
    let rest_ta = match &tuple.rest {
        None => None,
        Some(rest) if matches!(rest.as_ref(), SchemaIr::Any) => None,
        Some(rest) => {
            let (sub_preamble, sub_type) = emit_sub_schema("tr", rest, defs, counter);
            if !sub_preamble.is_empty() {
                out.push_str(&sub_preamble);
                out.push('\n');
            }
            *counter += 1;
            let ta_name = format!("_tr_ta_{}", *counter);
            out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));
            Some(ta_name)
        }
    };

    // Validate prefix items
    for (i, ta) in &item_tas {
        checks.push(format!(
            "    if len(v) > {i}:\n        {ta}.validate_python(v[{i}])"
        ));
    }

    // Validate rest items
    let prefix_count = tuple.items.len();
    if let Some(ref rest_ta) = rest_ta {
        checks.push(format!(
            "    for _i in range({prefix_count}, len(v)):\n        {rest_ta}.validate_python(v[_i])"
        ));
    } else if tuple.rest.is_none() {
        // items: false — no additional items beyond prefix
        checks.push(format!(
            "    if len(v) > {prefix_count}:\n        raise ValueError('too many items')"
        ));
    }

    // minItems / maxItems
    if let Some(min) = tuple.min_items {
        checks.push(format!(
            "    if len(v) < {min}:\n        raise ValueError('minItems')"
        ));
    }
    if let Some(max) = tuple.max_items {
        checks.push(format!(
            "    if len(v) > {max}:\n        raise ValueError('maxItems')"
        ));
    }

    // uniqueItems
    if tuple.unique_items {
        checks.push(
            "    if len(set(json.dumps(x, sort_keys=True, default=str) for x in v)) != len(v):\n        raise ValueError('uniqueItems')"
                .to_string(),
        );
    }

    // contains
    if let Some(contains) = &tuple.contains {
        let (sub_preamble, sub_type) =
            emit_sub_schema("tc", &contains.schema, defs, counter);
        if !sub_preamble.is_empty() {
            out.push_str(&sub_preamble);
            out.push('\n');
        }
        *counter += 1;
        let ta_name = format!("_tc_ta_{}", *counter);
        out.push_str(&format!("{ta_name} = TypeAdapter({sub_type})\n"));

        let min = contains.min_contains.unwrap_or(1);
        checks.push(format!(
            "    _match_count = sum(1 for x in v if _try_validate({ta_name}, x))"
        ));
        checks.push(format!(
            "    if _match_count < {min}:\n        raise ValueError('must contain at least {min} matching items')"
        ));
        if let Some(max) = contains.max_contains {
            checks.push(format!(
                "    if _match_count > {max}:\n        raise ValueError('must contain at most {max} matching items')"
            ));
        }
    }

    *counter += 1;
    let fn_name = format!("_validate_tuple_{}", *counter);

    out.push_str(&format!("\ndef {fn_name}(v):\n"));
    out.push_str("    if not isinstance(v, (list, tuple)):\n        return v\n");
    for check in &checks {
        out.push_str(check);
        out.push('\n');
    }
    out.push_str("    return v\n\n");
    out.push_str(&format!(
        "{name} = Annotated[list, BeforeValidator({fn_name})]"
    ));

    out
}

// ── Never emission ──────────────────────────────────────────────────────────

fn emit_never(name: &str, counter: &mut usize) -> String {
    *counter += 1;
    let fn_name = format!("_validate_never_{}", *counter);
    format!(
        "def {fn_name}(v):\n    raise ValueError('schema rejects all values')\n\n{name} = Annotated[Any, BeforeValidator({fn_name})]"
    )
}

// ── Interpreted emission ────────────────────────────────────────────────────

/// Embed the raw schema + remote documents as JSON and validate with the
/// emitted `_jsi_validate` interpreter (see JSI_PY_HELPER).
fn emit_interpreted(
    name: &str,
    schema: &serde_json::Value,
    remotes: &[(String, serde_json::Value)],
    counter: &mut usize,
) -> String {
    *counter += 1;
    let n = *counter;

    // Double-encode: json.loads of a JSON string literal. serde_json only emits
    // \", \\ and \uXXXX escapes, all of which mean the same thing in a Python
    // double-quoted string literal.
    let schema_json = serde_json::to_string(schema).unwrap_or_else(|_| "true".to_string());
    let schema_literal =
        serde_json::to_string(&serde_json::Value::String(schema_json)).unwrap();
    let remotes_json = {
        let map: serde_json::Map<String, serde_json::Value> = remotes
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        serde_json::to_string(&serde_json::Value::Object(map))
            .unwrap_or_else(|_| "{}".to_string())
    };
    let remotes_literal =
        serde_json::to_string(&serde_json::Value::String(remotes_json)).unwrap();

    format!(
        "_jsi_schema_{n} = json.loads({schema_literal})\n\
         _jsi_remotes_{n} = json.loads({remotes_literal})\n\
         \n\
         def _jsi_check_{n}(v):\n    \
             if not _jsi_validate(_jsi_schema_{n}, _jsi_remotes_{n}, v):\n        \
                 raise ValueError('does not match schema')\n    \
             return v\n\
         \n\
         {name} = Annotated[Any, BeforeValidator(_jsi_check_{n})]"
    )
}

// ── Sub-schema emission ─────────────────────────────────────────────────────

fn emit_sub_schema(
    prefix: &str,
    ir: &SchemaIr,
    defs: &[DefEntry],
    counter: &mut usize,
) -> (String, String) {
    match ir {
        SchemaIr::Object(_)
        | SchemaIr::TypeGuarded(_)
        | SchemaIr::Not { .. }
        | SchemaIr::Conditional { .. }
        | SchemaIr::ConstEqual(_)
        | SchemaIr::ComplexEnum(_)
        | SchemaIr::MixedEnum(_)
        | SchemaIr::Literal(_)
        | SchemaIr::ExclusiveUnion(_)
        | SchemaIr::Never
        | SchemaIr::Tuple(_)
        | SchemaIr::Enum(_) => {
            *counter += 1;
            let sub_name = format!("_{prefix}_{}", *counter);
            let def = emit_definition(&sub_name, ir, defs, counter);
            (format!("{def}\n"), sub_name)
        }
        SchemaIr::Intersection(members) if members.len() == 1 => {
            emit_sub_schema(prefix, &members[0], defs, counter)
        }
        SchemaIr::Intersection(members) if members.len() > 1 => {
            *counter += 1;
            let sub_name = format!("_{prefix}_{}", *counter);
            let def = emit_definition(&sub_name, ir, defs, counter);
            (format!("{def}\n"), sub_name)
        }
        SchemaIr::Union(members) if members.len() > 1 => {
            *counter += 1;
            let sub_name = format!("_{prefix}_{}", *counter);
            let def = emit_definition(&sub_name, ir, defs, counter);
            (format!("{def}\n"), sub_name)
        }
        SchemaIr::Array(arr) if arr.unique_items || arr.contains.is_some() => {
            *counter += 1;
            let sub_name = format!("_{prefix}_{}", *counter);
            let def = emit_definition(&sub_name, ir, defs, counter);
            (format!("{def}\n"), sub_name)
        }
        _ => (String::new(), annotated_type(ir, defs)),
    }
}

// ── Type mapping ────────────────────────────────────────────────────────────

fn py_type(ir: &SchemaIr, defs: &[DefEntry]) -> String {
    match ir {
        // Strict scalars: JSON Schema forbids pydantic's lax coercions
        // ("1" -> 1.0, True -> 1, 1 -> "1"), so every scalar annotation
        // carries its type-check BeforeValidator even when nested.
        SchemaIr::String(_) => "Annotated[str, BeforeValidator(_check_str)]".to_string(),
        SchemaIr::Number(_) => "Annotated[float, BeforeValidator(_check_number)]".to_string(),
        SchemaIr::Integer(_) => "Annotated[int, BeforeValidator(_check_int)]".to_string(),
        SchemaIr::Boolean => "Annotated[bool, BeforeValidator(_check_bool)]".to_string(),
        SchemaIr::Null => "None".to_string(),
        // Interpreted is handled in emit_definition (root-level only); as a bare
        // type annotation it degrades to Any.
        SchemaIr::Any | SchemaIr::Unknown | SchemaIr::Interpreted { .. } => "Any".to_string(),
        SchemaIr::Never => "Any".to_string(),

        SchemaIr::Literal(lit) => match lit {
            LiteralValue::String(s) => format!("Literal[\"{}\"]", escape_string(s)),
            LiteralValue::Number(n) => format!("Literal[{n}]"),
            LiteralValue::Integer(i) => format!("Literal[{i}]"),
            LiteralValue::Bool(b) => {
                format!("Literal[{}]", if *b { "True" } else { "False" })
            }
            LiteralValue::Null => "None".to_string(),
        },

        SchemaIr::ConstEqual(_) => "Any".to_string(),

        SchemaIr::Enum(cases) => {
            let parts: Vec<String> = cases
                .iter()
                .map(|c| format!("\"{}\"", escape_string(c)))
                .collect();
            format!("Literal[{}]", parts.join(", "))
        }

        SchemaIr::MixedEnum(lits) => {
            let parts: Vec<String> = lits.iter().map(|l| py_literal_value(l)).collect();
            format!("Literal[{}]", parts.join(", "))
        }

        SchemaIr::ComplexEnum(_) => "Any".to_string(),

        SchemaIr::Array(arr) => {
            format!("list[{}]", py_type(&arr.items, defs))
        }

        SchemaIr::Tuple(tuple) => {
            let parts: Vec<String> =
                tuple.items.iter().map(|i| py_type(i, defs)).collect();
            if let Some(rest) = &tuple.rest {
                let rest_type = py_type(rest, defs);
                format!("tuple[{}, *tuple[{rest_type}, ...]]", parts.join(", "))
            } else {
                format!("tuple[{}]", parts.join(", "))
            }
        }

        SchemaIr::Object(_) => "dict[str, Any]".to_string(),

        SchemaIr::Record(rec) => {
            format!("dict[str, {}]", py_type(&rec.value, defs))
        }

        SchemaIr::Union(members) | SchemaIr::ExclusiveUnion(members) => {
            let parts: Vec<String> =
                members.iter().map(|m| py_type(m, defs)).collect();
            format!("Union[{}]", parts.join(", "))
        }

        SchemaIr::Intersection(_) => "Any".to_string(),

        SchemaIr::Nullable(inner) => format!("Optional[{}]", py_type(inner, defs)),
        SchemaIr::Optional(inner) => format!("Optional[{}]", py_type(inner, defs)),
        SchemaIr::Default(inner, _) => py_type(inner, defs),
        SchemaIr::Describe(inner, _) => py_type(inner, defs),
        SchemaIr::Not { base, .. } => py_type(base, defs),
        SchemaIr::Conditional { base, .. } => py_type(base, defs),
        SchemaIr::TypeGuarded(_) => "Any".to_string(),

        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => format!("\"{name}\""),
    }
}

fn py_literal_value(lit: &LiteralValue) -> String {
    match lit {
        LiteralValue::String(s) => format!("\"{}\"", escape_string(s)),
        LiteralValue::Number(n) => format!("{n}"),
        LiteralValue::Integer(i) => format!("{i}"),
        LiteralValue::Bool(b) => {
            if *b { "True" } else { "False" }.to_string()
        }
        LiteralValue::Null => "None".to_string(),
    }
}

fn field_constraints(ir: &SchemaIr) -> String {
    let mut parts = Vec::new();

    match ir {
        SchemaIr::String(c) => {
            if let Some(min) = c.min_length {
                parts.push(format!("min_length={min}"));
            }
            if let Some(max) = c.max_length {
                parts.push(format!("max_length={max}"));
            }
            if let Some(pat) = &c.pattern {
                parts.push(format!("pattern=r\"{}\"", pat));
            }
        }
        SchemaIr::Number(c) | SchemaIr::Integer(c) => {
            let is_integer = matches!(ir, SchemaIr::Integer(_));
            if let Some(v) = c.minimum {
                parts.push(format!("ge={}", format_py_number(v)));
            }
            if let Some(v) = c.maximum {
                parts.push(format!("le={}", format_py_number(v)));
            }
            if let Some(v) = c.exclusive_minimum {
                parts.push(format!("gt={}", format_py_number(v)));
            }
            if let Some(v) = c.exclusive_maximum {
                parts.push(format!("lt={}", format_py_number(v)));
            }
            if let Some(v) = c.multiple_of {
                // Pydantic requires multiple_of on int fields to be integer-coercible
                if !is_integer || v == v.trunc() {
                    parts.push(format!("multiple_of={}", format_py_number(v)));
                }
            }
        }
        SchemaIr::Array(a) => {
            if let Some(min) = a.min_items {
                parts.push(format!("min_length={min}"));
            }
            if let Some(max) = a.max_items {
                parts.push(format!("max_length={max}"));
            }
        }
        SchemaIr::Describe(inner, desc) => {
            parts.push(format!("description=\"{}\"", escape_string(desc)));
            let inner_constraints = field_constraints(inner);
            if !inner_constraints.is_empty() {
                parts.push(inner_constraints);
            }
        }
        SchemaIr::Default(inner, _) => {
            let inner_constraints = field_constraints(inner);
            if !inner_constraints.is_empty() {
                parts.push(inner_constraints);
            }
        }
        _ => {}
    }

    parts.join(", ")
}

fn format_py_number(n: f64) -> String {
    if n == n.trunc() && n.abs() < 1e15 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

// ── Python helper constants ─────────────────────────────────────────────────

/// Type strictness helpers — JSON Schema requires bool != int, string != number, etc.
const TYPE_CHECK_HELPERS: &str = include_str!("type_checks.py");

/// Self-contained draft 2020-12 validator with annotation tracking, used for
/// schemas routed to SchemaIr::Interpreted (unevaluatedProperties/Items,
/// $dynamicRef/$dynamicAnchor, $anchor, nested $id scopes, remote $refs).
/// Python port of the JSI_HELPER TypeScript interpreter in zod.rs.
const JSI_PY_HELPER: &str = include_str!("jsi_validator.py");

/// Deep equality that distinguishes types (false != 0, true != 1, 1 != 1.0 for containers)
const DEEP_EQUAL_HELPER: &str = include_str!("deep_equal.py");

/// Static "does this value validate?" probe used by `contains` checks on
/// constrained arrays/tuples. Schema-independent, so it moves to the shared
/// helpers file in shared-helpers mode.
const TRY_VALIDATE_HELPER: &str = "def _try_validate(ta, v):\n    try:\n        ta.validate_python(v)\n        return True\n    except (ValidationError, ValueError, TypeError):\n        return False\n";

/// Variant used inside type-guard validators (broader exception net).
const TRY_VALIDATE_G_HELPER: &str = "def _try_validate_g(ta, v):\n    try:\n        ta.validate_python(v)\n        return True\n    except Exception:\n        return False\n";
