use crate::ir::*;
use crate::util::to_pascal_case;
use super::{EmitOptions, Emitter, HelperSet};

pub struct KotlinEmitter;

impl Emitter for KotlinEmitter {
    fn extension(&self) -> &str {
        "kt"
    }

    fn emit_with_options(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> String {
        self.emit_module(converted, name, options).0
    }

    fn emit_collecting(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> (String, HelperSet) {
        self.emit_module(converted, name, options)
    }

    fn helpers_content_for(&self, needs: &HelperSet) -> Option<String> {
        if needs.is_empty() {
            return None;
        }
        let mut s = String::from(concat!(
            "// Generated by json-schema-transformer — shared runtime helpers\n",
            "// DO NOT EDIT — changes will be overwritten on regeneration\n\n",
            "package jst.helpers\n\n",
            "import kotlinx.serialization.json.*\n\n",
        ));
        if needs.contains("validatable") {
            // Deliberately public: generated (public) classes implement it,
            // and a public class may not expose an internal supertype.
            s.push_str(VALIDATABLE_KT);
            s.push('\n');
        }
        if needs.contains("error") {
            // JstIssue/JstValidationException stay public on purpose: user
            // code catches the exception type and inspects `issues`. Only the
            // pointer-escape helper is internalized.
            s.push_str(&internalize(ERROR_KT));
            s.push('\n');
        }
        if needs.contains("canonicalize") {
            s.push_str(&internalize(CANONICALIZE_KT));
            s.push('\n');
        }
        if needs.contains("lenient_json") {
            s.push_str(&internalize(LENIENT_JSON_KT));
            s.push('\n');
        }
        // The interpreter calls _jsiEq internally, so it drags the equality
        // helper into the shared file even when no module imports it directly.
        if needs.contains("jsi_eq") || needs.contains("jsi") {
            s.push_str(&internalize(EQ_HELPER_KT));
            s.push_str("\n\n");
        }
        if needs.contains("jsi") {
            s.push_str(&internalize(JSI_HELPER_KT));
            s.push('\n');
        }
        Some(s)
    }

    fn helpers_content(&self) -> Option<String> {
        let mut all = HelperSet::default();
        for n in ["validatable", "error", "canonicalize", "lenient_json", "jsi_eq", "jsi"] {
            all.insert(n);
        }
        self.helpers_content_for(&all)
    }

    fn default_helpers_file(&self) -> Option<&'static str> {
        Some("JstHelpers.kt")
    }
}

impl KotlinEmitter {
    fn emit_module(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> (String, HelperSet) {
        let pascal = to_pascal_case(name);
        let mut out = String::new();

        out.push_str(&format!(
            "// Generated by json-schema-transformer\n// {name}\n// DO NOT EDIT — changes will be overwritten on regeneration\n\n"
        ));

        // Collection mode: utilities live in the fixed `jst.helpers`
        // package (see helpers_content_for) instead of being inlined per file.
        let shared = options.helpers.is_some();

        // The validation interface generated classes conform to. Shared mode
        // uses the canonical name from `jst.helpers`; inline mode mangles it
        // with the file's root type name (like the JSI classes) because
        // top-level declarations are package-scoped on the JVM and many
        // generated files may be compiled as one module.
        let iface = if shared {
            "_JstValidatable".to_string()
        } else {
            format!("_{pascal}JstValidatable")
        };
        // Names of the issue/exception classes as visible from this file.
        // Top-level classes are package-scoped on the JVM, so inline mode
        // mangles them per file (like the JSI classes); shared mode uses the
        // canonical names from `jst.helpers`.
        let (issue, exc) = if shared {
            ("JstIssue".to_string(), "JstValidationException".to_string())
        } else {
            (
                format!("_{pascal}JstIssue"),
                format!("_{pascal}JstValidationException"),
            )
        };
        let gopts = GenOptions {
            iface: &iface,
            issue: &issue,
            exc: &exc,
            mutable: options.mutable,
        };

        // Emit body first so we can scan for needed imports.
        // All $defs type names are prefixed with the root pascal name so that
        // hundreds of generated files can be compiled into a single Kotlin
        // module without top-level name collisions (e.g. `Foo` in many files).
        let mut counter = 0usize;
        let mut body = String::new();
        for def in &converted.defs {
            let safe_name = sanitize_kotlin_name(&def.name, &pascal);
            body.push_str(&emit_definition(&safe_name, &def.schema, &converted.defs, &pascal, &mut counter, &gopts));
            body.push_str("\n\n");
        }
        body.push_str(&emit_definition(
            &pascal,
            &converted.root,
            &converted.defs,
            &pascal,
            &mut counter,
            &gopts,
        ));
        body.push('\n');

        // Determine which imports are actually needed
        let needs_interpreter = body.contains("_jsiValidate(");
        let needs_eq = body.contains("_jsiEq(") || needs_interpreter;
        let needs_lenient = body.contains("_lenientJson");
        let needs_canonicalize = body.contains("_canonicalize(");
        // Helpers inlined into this file (never in shared mode) pull in
        // kotlinx.serialization.json types beyond what the body itself uses.
        let inline_eq = needs_eq && !shared;
        let inline_canonicalize = needs_canonicalize && !shared;
        let needs_serial_name = body.contains("@SerialName(");
        let needs_json_element = body.contains("JsonElement") || inline_eq;
        let needs_json_object = body.contains("JsonObject") || inline_canonicalize || inline_eq;
        let needs_json_primitive = body.contains("JsonPrimitive")
            || body.contains("jsonPrimitive")
            || body.contains("JsonNull")
            || inline_eq;
        let needs_json_array = body.contains("JsonArray") || body.contains("jsonArray") || inline_eq;
        let needs_kserializer = body.contains("KSerializer");
        let needs_json_content = body.contains("JsonContentPolymorphicSerializer")
            || body.contains("jsonObject");
        let needs_decode_from_element = body.contains("decodeFromJsonElement<");
        // validate()/toValidatedJson() round-trip through the type's own
        // serializer via the reified StringFormat extensions.
        let needs_validatable = body.contains("JstValidatable");
        let needs_encode_to_element = body.contains(".encodeToJsonElement(");
        // Zod-style issue collection: any wrapper serializer that validates
        // references the issue/exception classes (mangled names still contain
        // the canonical substrings).
        let needs_error = body.contains("JstIssue") || body.contains("JstValidationException");
        let needs_ptr = body.contains("_jstPtr(");

        if needs_serial_name {
            out.push_str("import kotlinx.serialization.SerialName\n");
        }
        out.push_str("import kotlinx.serialization.Serializable\n");
        if needs_validatable {
            out.push_str("import kotlinx.serialization.decodeFromString\n");
            out.push_str("import kotlinx.serialization.encodeToString\n");
        }
        if needs_kserializer {
            out.push_str("import kotlinx.serialization.KSerializer\n");
            out.push_str("import kotlinx.serialization.descriptors.SerialDescriptor\n");
            out.push_str("import kotlinx.serialization.encoding.Decoder\n");
            out.push_str("import kotlinx.serialization.encoding.Encoder\n");
        }
        if needs_json_element {
            out.push_str("import kotlinx.serialization.json.JsonElement\n");
        }
        if needs_json_object || needs_json_content {
            out.push_str("import kotlinx.serialization.json.JsonObject\n");
            out.push_str("import kotlinx.serialization.json.jsonObject\n");
        }
        if needs_json_primitive {
            out.push_str("import kotlinx.serialization.json.JsonPrimitive\n");
            out.push_str("import kotlinx.serialization.json.JsonNull\n");
            out.push_str("import kotlinx.serialization.json.jsonPrimitive\n");
            out.push_str("import kotlinx.serialization.json.intOrNull\n");
            out.push_str("import kotlinx.serialization.json.longOrNull\n");
            out.push_str("import kotlinx.serialization.json.doubleOrNull\n");
            out.push_str("import kotlinx.serialization.json.booleanOrNull\n");
            out.push_str("import kotlinx.serialization.json.contentOrNull\n");
        }
        if needs_json_array {
            out.push_str("import kotlinx.serialization.json.JsonArray\n");
            out.push_str("import kotlinx.serialization.json.jsonArray\n");
        }
        if needs_decode_from_element {
            out.push_str("import kotlinx.serialization.json.decodeFromJsonElement\n");
        }
        if needs_encode_to_element {
            out.push_str("import kotlinx.serialization.json.encodeToJsonElement\n");
        }
        let mut needs = HelperSet::default();
        if shared {
            if needs_validatable {
                needs.insert("validatable");
                out.push_str("import jst.helpers._JstValidatable\n");
            }
            if needs_error {
                needs.insert("error");
                out.push_str("import jst.helpers.JstIssue\n");
                out.push_str("import jst.helpers.JstValidationException\n");
                if needs_ptr {
                    out.push_str("import jst.helpers._jstPtr\n");
                }
            }
            // Reference helpers declared once in the companion file's fixed
            // `jst.helpers` package (canonical names — no per-file mangling).
            if needs_canonicalize {
                needs.insert("canonicalize");
                out.push_str("import jst.helpers._canonicalize\n");
            }
            if body.contains("_jsiEq(") {
                needs.insert("jsi_eq");
                out.push_str("import jst.helpers._jsiEq\n");
            }
            if needs_interpreter {
                needs.insert("jsi");
                out.push_str("import jst.helpers._jsiValidate\n");
            }
            if needs_lenient {
                needs.insert("lenient_json");
                out.push_str("import jst.helpers._lenientJson\n");
            }
        }
        out.push('\n');

        // Emit helper functions (inline mode only)
        if !shared {
            if needs_validatable {
                out.push_str(&VALIDATABLE_KT.replace("_JstValidatable", &iface));
                out.push('\n');
            }
            if needs_error {
                // Class names are mangled per file (JVM package scoping);
                // `_jstPtr` stays `private`, which is file-scoped for
                // top-level functions, so it never collides across files.
                let err = ERROR_KT
                    .replace("JstValidationException", &exc)
                    .replace("JstIssue", &issue);
                out.push_str(&err);
                out.push('\n');
            }
            if needs_canonicalize {
                out.push_str(CANONICALIZE_KT);
                out.push('\n');
            }
            if needs_lenient {
                out.push_str(LENIENT_JSON_KT);
                out.push('\n');
            }
            if needs_eq {
                out.push_str(EQ_HELPER_KT);
                out.push_str("\n\n");
            }
            if needs_interpreter {
                // Top-level classes are package-scoped on the JVM even when
                // `private`, so mangle the helper class names with the file's
                // root type name to keep the single-module batch compile happy.
                let helper = JSI_HELPER_KT
                    .replace("_JsiAnn", &format!("_{pascal}JsiAnn"))
                    .replace("_JsiV", &format!("_{pascal}JsiV"));
                out.push_str(&helper);
                out.push_str("\n\n");
            }
        }

        out.push_str(&body);
        (out, needs)
    }
}

/// Rewrite top-level `private` declarations to `internal` so the shared
/// helpers file (fixed `jst.helpers` package) is visible from generated
/// schema files compiled in the same module. Members inside classes are
/// indented and left untouched.
fn internalize(src: &str) -> String {
    let mut out: String = src
        .lines()
        .map(|l| {
            if let Some(rest) = l.strip_prefix("private ") {
                format!("internal {rest}\n")
            } else {
                format!("{l}\n")
            }
        })
        .collect();
    if !src.ends_with('\n') {
        out.pop();
    }
    out
}

/// Interface implemented by generated data/wrapper classes. `validate()`
/// re-runs the schema checks by round-tripping the value through its own
/// serializer (deserialize is where all generated validation lives).
///
/// Kept public on purpose: generated classes are public and Kotlin forbids a
/// public class from exposing an internal/private supertype. The leading
/// underscore matches the JSI helper convention so inline mode can mangle it
/// per file (`_JstValidatable` → `_{Pascal}JstValidatable`).
const VALIDATABLE_KT: &str = concat!(
    "/** Implemented by generated types. validate() re-runs schema validation by\n",
    " *  round-tripping this value through its serializer; it must be called\n",
    " *  explicitly (construction and copy() never validate). */\n",
    "interface _JstValidatable {\n",
    "    fun validate()\n",
    "    fun toValidatedJson(): String\n",
    "}\n",
);

/// Zod-style validation error carrier. Wrapper serializers collect EVERY
/// failed constraint into `issues` (path = RFC 6901 JSON Pointer, "" = root)
/// and throw one exception at the end instead of failing on the first check.
///
/// Both classes are deliberately public: user code catches the exception type
/// and inspects `issues`. Extending SerializationException keeps existing
/// catch sites (and the conformance harness) working unchanged. Inline mode
/// mangles the class names per file (`JstIssue` → `_{Pascal}JstIssue`); the
/// `private` pointer-escape helper is file-scoped and needs no mangling.
const ERROR_KT: &str = concat!(
    "/** A single validation failure: a JSON Pointer (RFC 6901) to the offending\n",
    " *  location (\"\" = the whole value) and a human-readable message. */\n",
    "data class JstIssue(val path: String, val message: String)\n",
    "\n",
    "/** Validation error carrying every failed constraint, not just the first.\n",
    " *  The message renders all issues, \"; \"-separated, each as `path: message`\n",
    " *  (root issues message-only). */\n",
    "class JstValidationException(val issues: List<JstIssue>) :\n",
    "    kotlinx.serialization.SerializationException(\n",
    "        issues.joinToString(\"; \") { if (it.path.isEmpty()) it.message else it.path + \": \" + it.message }\n",
    "    )\n",
    "\n",
    "/** Escape a key for use as a JSON Pointer token (RFC 6901: `~` → `~0`, `/` → `~1`). */\n",
    "private fun _jstPtr(segment: String): String = segment.replace(\"~\", \"~0\").replace(\"/\", \"~1\")\n",
);

/// Per-file generation options threaded through the definition emitters.
struct GenOptions<'a> {
    /// Name of the validation interface as visible from this file.
    iface: &'a str,
    /// Name of the issue data class as visible from this file.
    issue: &'a str,
    /// Name of the validation exception class as visible from this file.
    exc: &'a str,
    /// Emit `var` instead of `val` for stored properties.
    mutable: bool,
}

impl GenOptions<'_> {
    fn val_kw(&self) -> &'static str {
        if self.mutable { "var" } else { "val" }
    }
}

/// The `validate()`/`toValidatedJson()` members every generated class gets.
/// CRITICAL: deserialize constructs instances via the plain constructor, so
/// constructors/init blocks must never call validate() — the round-trip
/// would recurse infinitely. validate() is explicit-call only.
fn validate_members(name: &str) -> String {
    format!(
        concat!(
            "    override fun validate() {{ kotlinx.serialization.json.Json.decodeFromString<{name}>(kotlinx.serialization.json.Json.encodeToString(this)) }}\n",
            "    override fun toValidatedJson(): String {{ validate(); return kotlinx.serialization.json.Json.encodeToString(this) }}\n",
        ),
        name = name
    )
}

/// Canonical JSON string for uniqueItems comparison (object keys sorted).
const CANONICALIZE_KT: &str = concat!(
    "private fun _canonicalize(el: JsonElement): String = when (el) {\n",
    "    is JsonObject -> \"{\" + el.entries.sortedBy { it.key }.joinToString(\",\") { \"\\\"${it.key}\\\":${_canonicalize(it.value)}\" } + \"}\"\n",
    "    is JsonArray -> \"[\" + el.joinToString(\",\") { _canonicalize(it) } + \"]\"\n",
    "    else -> el.toString()\n",
    "}\n",
);

/// Lenient Json instance used when delegating validation to a referenced
/// type's serializer.
const LENIENT_JSON_KT: &str =
    "private val _lenientJson = kotlinx.serialization.json.Json { ignoreUnknownKeys = true }\n";

/// JSON-value equality per JSON Schema: numbers compare mathematically
/// (1 == 1.0) but true != 1 and "1" != 1. Exact content comparison is tried
/// first so big integers beyond double precision still compare correctly.
const EQ_HELPER_KT: &str = include_str!("jsi_eq.kt");

/// Self-contained draft 2020-12 validator with annotation tracking, used for
/// schemas routed to SchemaIr::Interpreted (unevaluatedProperties/Items,
/// $dynamicRef/$dynamicAnchor, $anchor, nested $id scopes, remote $refs).
/// Kotlin port of the JSI_HELPER reference implementation in zod.rs.
const JSI_HELPER_KT: &str = include_str!("jsi_validator.kt");

// ── Kotlin string escaping ───────────────────────────────────────────────────

fn escape_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => vec!['\\', '"'],
            '\\' => vec!['\\', '\\'],
            '\n' => vec!['\\', 'n'],
            '\r' => vec!['\\', 'r'],
            '\t' => vec!['\\', 't'],
            '$' => vec!['\\', '$'],
            c if c.is_control() => {
                format!("\\u{:04X}", c as u32).chars().collect()
            }
            other => vec![other],
        })
        .collect()
}

/// Translate ECMAScript-style Unicode property escapes (e.g. `\\p{Letter}`)
/// into the short general-category forms java.util.regex understands (`\\p{L}`).
fn translate_pattern(p: &str) -> String {
    const MAP: &[(&str, &str)] = &[
        ("Letter", "L"), ("Lowercase_Letter", "Ll"), ("Uppercase_Letter", "Lu"),
        ("Titlecase_Letter", "Lt"), ("Modifier_Letter", "Lm"), ("Other_Letter", "Lo"),
        ("Mark", "M"), ("Nonspacing_Mark", "Mn"), ("Spacing_Mark", "Mc"), ("Enclosing_Mark", "Me"),
        ("Number", "N"), ("Decimal_Number", "Nd"), ("digit", "Nd"), ("Letter_Number", "Nl"),
        ("Other_Number", "No"), ("Punctuation", "P"), ("Connector_Punctuation", "Pc"),
        ("Dash_Punctuation", "Pd"), ("Open_Punctuation", "Ps"), ("Close_Punctuation", "Pe"),
        ("Initial_Punctuation", "Pi"), ("Final_Punctuation", "Pf"), ("Other_Punctuation", "Po"),
        ("Symbol", "S"), ("Math_Symbol", "Sm"), ("Currency_Symbol", "Sc"),
        ("Modifier_Symbol", "Sk"), ("Other_Symbol", "So"),
        ("Separator", "Z"), ("Space_Separator", "Zs"), ("Line_Separator", "Zl"),
        ("Paragraph_Separator", "Zp"), ("Other", "C"), ("Control", "Cc"), ("Format", "Cf"),
        ("Surrogate", "Cs"), ("Private_Use", "Co"), ("Unassigned", "Cn"),
    ];
    if !p.contains("\\p{") && !p.contains("\\P{") {
        return p.to_string();
    }
    let chars: Vec<char> = p.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    while i < chars.len() {
        if i + 3 < chars.len()
            && chars[i] == '\\'
            && (chars[i + 1] == 'p' || chars[i + 1] == 'P')
            && chars[i + 2] == '{'
        {
            if let Some(close_rel) = chars[i + 3..].iter().position(|&c| c == '}') {
                let close = i + 3 + close_rel;
                let name: String = chars[i + 3..close].iter().collect();
                if let Some((_, short)) = MAP.iter().find(|(long, _)| *long == name) {
                    out.push(chars[i]);
                    out.push(chars[i + 1]);
                    out.push('{');
                    out.push_str(short);
                    out.push('}');
                    i = close + 1;
                    continue;
                }
            }
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

// ── Name sanitization ───────────────────────────────────────────────────────

const KOTLIN_RESERVED_TYPES: &[&str] = &[
    "Int", "Long", "Short", "Byte", "Double", "Float", "Boolean", "Char",
    "String", "Unit", "Nothing", "Any", "Number",
    "Array", "List", "Map", "Set", "Pair", "Triple",
    "Comparable", "Enum", "Error", "Exception",
    "Result", "Sequence",
];

/// Sanitize a `$defs` type name and prefix it with the root type's pascal
/// name so definitions from different generated files never collide when
/// compiled together as one module. Names that sanitize to nothing (e.g. a
/// `$defs` key of "") become `{prefix}AnonymousDef`.
fn sanitize_kotlin_name(name: &str, prefix: &str) -> String {
    let mut cleaned: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if cleaned.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        cleaned.insert(0, 'N');
    }
    if cleaned.is_empty() {
        cleaned = "AnonymousDef".to_string();
    } else if KOTLIN_RESERVED_TYPES.contains(&cleaned.as_str()) {
        cleaned.push_str("Schema");
    }
    format!("{prefix}{cleaned}")
}

// ── Definition dispatch ─────────────────────────────────────────────────────

fn emit_definition(name: &str, ir: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize, gopts: &GenOptions) -> String {
    match ir {
        SchemaIr::Object(obj) => {
            let needs_custom = matches!(obj.additional_properties, AdditionalProperties::Forbidden | AdditionalProperties::Schema(_))
                || !obj.pattern_properties.is_empty()
                || obj.property_names.is_some()
                || obj.min_properties.is_some()
                || obj.max_properties.is_some()
                || !obj.dependent_schemas.is_empty()
                || !obj.dependent_required.is_empty()
                || obj.fields.values().any(|f| !field_fully_typed(&f.schema))
                || obj.fields.iter().any(|(_, f)| !f.required);
            if needs_custom {
                emit_wrapper(name, ir, defs, prefix, counter, gopts)
            } else {
                emit_data_class(name, obj, defs, prefix, gopts)
            }
        }
        // Enum classes are inherently valid (every constructible value is a
        // member of the schema's enum), so they skip the JstValidatable
        // interface entirely.
        SchemaIr::Enum(cases) if !cases.is_empty() => emit_enum_class(name, cases),
        SchemaIr::Enum(_) => emit_never_class(name, counter, gopts), // empty enum
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => {
            emit_definition(name, inner, defs, prefix, counter, gopts)
        }
        SchemaIr::Nullable(inner) => {
            // For nullable, emit the inner as a separate type and alias
            if matches!(inner.as_ref(), SchemaIr::Object(_)) {
                emit_definition(name, inner, defs, prefix, counter, gopts)
            } else {
                emit_wrapper(name, ir, defs, prefix, counter, gopts)
            }
        }
        SchemaIr::Ref(ref_name) => {
            let safe = sanitize_kotlin_name(ref_name, prefix);
            format!("typealias {name} = {safe}")
        }
        _ => emit_wrapper(name, ir, defs, prefix, counter, gopts),
    }
}

/// True when the Kotlin type produced by `kotlin_type` fully enforces this
/// schema on its own (so a plain `@Serializable data class` field suffices).
/// Anything with value constraints, inline enums/literals, nested inline
/// objects, tuples, unions etc. needs the wrapper-serializer path instead.
fn field_fully_typed(ir: &SchemaIr) -> bool {
    match ir {
        SchemaIr::Any | SchemaIr::Unknown | SchemaIr::Boolean => true,
        SchemaIr::String(c) => {
            c.min_length.is_none() && c.max_length.is_none() && c.pattern.is_none()
        }
        SchemaIr::Ref(_) | SchemaIr::Lazy(_) => true,
        SchemaIr::Array(arr) => {
            arr.min_items.is_none()
                && arr.max_items.is_none()
                && !arr.unique_items
                && arr.contains.is_none()
                && field_fully_typed(&arr.items)
        }
        SchemaIr::Optional(inner)
        | SchemaIr::Nullable(inner)
        | SchemaIr::Describe(inner, _)
        | SchemaIr::Default(inner, _) => field_fully_typed(inner),
        // Int/Double fields reject 1.0-style integers or big values oddly, and
        // constrained numbers lose their bounds — keep only if unconstrained.
        SchemaIr::Integer(c) | SchemaIr::Number(c) => {
            c.minimum.is_none()
                && c.maximum.is_none()
                && c.exclusive_minimum.is_none()
                && c.exclusive_maximum.is_none()
                && c.multiple_of.is_none()
        }
        _ => false,
    }
}

// ── Object data class ───────────────────────────────────────────────────────

fn emit_data_class(name: &str, obj: &ObjectSchema, defs: &[DefEntry], prefix: &str, gopts: &GenOptions) -> String {
    let mut lines = vec!["@Serializable".to_string()];
    let vkw = gopts.val_kw();

    if obj.fields.is_empty() {
        lines.push(format!("data class {name}("));
        lines.push(format!("    {vkw} placeholder: Unit = Unit"));
    } else {
        lines.push(format!("data class {name}("));

        let fields: Vec<String> = obj
            .fields
            .iter()
            .map(|(k, f)| {
                let kt_name = to_camel_case(k);
                let kt_type = kotlin_type(&f.schema, defs, prefix);

                let type_str = if f.required {
                    kt_type
                } else {
                    format!("{kt_type}?")
                };

                let serial_name = if kt_name != *k {
                    format!("    @SerialName(\"{}\")\n", escape_string(k))
                } else {
                    String::new()
                };

                let default = if !f.required { " = null" } else { "" };

                format!("{serial_name}    {vkw} {kt_name}: {type_str}{default}")
            })
            .collect();

        lines.push(fields.join(",\n"));
    }

    lines.push(format!(") : {} {{", gopts.iface));
    lines.push(validate_members(name).trim_end().to_string());
    lines.push("}".to_string());

    lines.join("\n")
}

// ── Enum class ──────────────────────────────────────────────────────────────

fn emit_enum_class(name: &str, cases: &[String]) -> String {
    let mut lines = vec!["@Serializable".to_string()];
    lines.push(format!("enum class {name} {{"));
    let mut seen: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let entries: Vec<String> = cases
        .iter()
        .map(|c| {
            let mut kt_name: String = c.chars()
                .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_' || *ch == '-')
                .collect::<String>()
                .to_uppercase()
                .replace('-', "_");
            if kt_name.is_empty() {
                kt_name = "VALUE".to_string();
            }
            // Deduplicate
            let count = seen.entry(kt_name.clone()).or_insert(0);
            *count += 1;
            if *count > 1 {
                kt_name = format!("{kt_name}_{count}");
            }
            // Always use @SerialName for the raw JSON value
            format!(
                "    @SerialName(\"{}\") {}",
                escape_string(c),
                kt_name
            )
        })
        .collect();
    lines.push(entries.join(",\n"));
    lines.push("}".to_string());
    lines.join("\n")
}

// ── Wrapper class with custom serializer ────────────────────────────────────

fn emit_wrapper(name: &str, ir: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize, gopts: &GenOptions) -> String {
    let inner = unwrap_modifiers(ir);
    let is_nullable = matches!(ir, SchemaIr::Nullable(_));

    *counter += 1;
    let ser_name = format!("{name}Ser");

    let ctx = Ctx { prefix, issue: gopts.issue, exc: gopts.exc };
    let validation = emit_validation(inner, &ctx);

    let mut out = String::new();

    out.push_str(&format!(
        "private object {ser_name} : KSerializer<{name}> {{\n"
    ));
    out.push_str(&format!(
        "    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor\n"
    ));
    out.push_str(&format!(
        "    override fun deserialize(decoder: Decoder): {name} {{\n"
    ));
    out.push_str(
        "        val el = decoder.decodeSerializableValue(JsonElement.serializer())\n",
    );
    if is_nullable {
        out.push_str(&format!("        if (el is JsonNull) return {name}(el)\n"));
    }
    if !validation.is_empty() {
        // Zod-style: run every check, collecting issues, then throw once.
        out.push_str(&format!(
            "        val issues = mutableListOf<{}>()\n        val path = \"\"\n",
            gopts.issue
        ));
        out.push_str(&validation);
        out.push_str(&format!(
            "        if (issues.isNotEmpty()) throw {}(issues)\n",
            gopts.exc
        ));
    }
    out.push_str(&format!("        return {name}(el)\n"));
    out.push_str("    }\n");
    out.push_str(&format!(
        "    override fun serialize(encoder: Encoder, value: {name}) {{\n"
    ));
    out.push_str(
        "        encoder.encodeSerializableValue(JsonElement.serializer(), value.element)\n",
    );
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "@Serializable(with = {ser_name}::class)\n"
    ));
    out.push_str(&format!(
        "class {name}({vkw} element: JsonElement) : {iface} {{\n",
        vkw = gopts.val_kw(),
        iface = gopts.iface
    ));
    out.push_str(&validate_members(name));
    if let SchemaIr::Object(obj) = inner {
        if !obj.fields.is_empty() {
            out.push_str(&emit_companion_invoke(name, obj, defs, prefix));
        }
    }
    out.push('}');

    out
}

/// Typed construction for object-shaped wrapper classes: a companion
/// `operator fun invoke` mirroring the schema's declared properties, so
/// callers can write `OrderItem(id = "a", quantity = 1)` instead of building
/// a JsonElement by hand. Construction never validates (call validate()).
///
/// A companion invoke — rather than a secondary constructor — avoids JVM
/// platform-declaration clashes with the primary `(JsonElement)` constructor
/// (e.g. a lone field typed JsonElement?), and Kotlin resolves `Name(args)`
/// against constructors first, so the serializer's `Name(el)` call is safe.
fn emit_companion_invoke(name: &str, obj: &ObjectSchema, defs: &[DefEntry], prefix: &str) -> String {
    let mut seen: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let mut params: Vec<String> = Vec::new();
    let mut puts: Vec<String> = Vec::new();

    for (k, f) in &obj.fields {
        // Distinct JSON keys can camelCase to the same parameter name
        // (e.g. "foo\nbar" and "foo\"bar") — deduplicate like enum entries.
        let mut p = to_camel_case(k);
        let count = seen.entry(p.clone()).or_insert(0);
        *count += 1;
        if *count > 1 {
            let n = *count;
            p = if p.starts_with('`') {
                format!("`{}{}`", p.trim_matches('`'), n)
            } else {
                format!("{p}{n}")
            };
        }
        let t = kotlin_type(&f.schema, defs, prefix);
        let key = escape_string(k);

        if f.required {
            params.push(format!("            {p}: {t}"));
            if t.starts_with("Nothing") {
                // Literal-null / never fields: no runtime serializer needed.
                puts.push(format!(
                    "            put(\"{key}\", kotlinx.serialization.json.JsonNull)"
                ));
            } else {
                puts.push(format!(
                    "            put(\"{key}\", kotlinx.serialization.json.Json.encodeToJsonElement({p}))"
                ));
            }
        } else {
            let opt_t = if t.ends_with('?') { t.clone() } else { format!("{t}?") };
            params.push(format!("            {p}: {opt_t} = null"));
            if !t.starts_with("Nothing") {
                puts.push(format!(
                    "            if ({p} != null) put(\"{key}\", kotlinx.serialization.json.Json.encodeToJsonElement({p}))"
                ));
            }
        }
    }

    // A single required parameter typed JsonElement gives the invoke the same
    // JVM signature as the primary `(JsonElement)` constructor; overload
    // resolution always picks the constructor, so the companion would be
    // unreachable dead code — skip it (callers construct via the raw element).
    if obj.fields.len() == 1 {
        if let Some((_, f)) = obj.fields.iter().next() {
            if f.required && kotlin_type(&f.schema, defs, prefix) == "JsonElement" {
                return String::new();
            }
        }
    }

    format!(
        "    companion object {{\n        operator fun invoke(\n{params},\n        ): {name} = {name}(kotlinx.serialization.json.buildJsonObject {{\n{puts}\n        }})\n    }}\n",
        params = params.join(",\n"),
        puts = puts.join("\n"),
    )
}

fn unwrap_modifiers(ir: &SchemaIr) -> &SchemaIr {
    match ir {
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Nullable(inner) => {
            unwrap_modifiers(inner)
        }
        _ => ir,
    }
}

// ── Validation code generation ──────────────────────────────────────────────
//
// `emit_validation` returns Kotlin *statements* over three in-scope bindings —
// `el: JsonElement`, a JSON-Pointer `path: String` ("" = root), and
// `issues: MutableList<JstIssue>` — that push EVERY failed constraint
// (Zod-style), not just the first. Type mismatches short-circuit only their
// own subtree (a `return@run` inside the arm's own `run {}` scope; checking
// minLength of a non-string is meaningless), everything else accumulates.
// Verdicts stay equivalent to the previous throwing code (issues non-empty
// <=> the old `require(...)` chain threw), so accept/reject decisions across
// the conformance suite are unchanged. Composition members (anyOf/oneOf) use
// bool verdicts and report a single issue — only match/no-match is meaningful
// there — and the embedded JSI interpreter stays verdict-only likewise.
//
// Boundary rule: plain `@Serializable data class` shapes with no custom
// serializer keep native kotlinx errors — there is nothing to collect there.
// `validate()`/`toValidatedJson()` surface JstValidationException through the
// serializer round-trip automatically.

/// Generation context threaded through the validation emitters.
struct Ctx<'a> {
    prefix: &'a str,
    /// Issue class name as visible from this file (mangled in inline mode).
    issue: &'a str,
    /// Exception class name as visible from this file.
    exc: &'a str,
}

impl Ctx<'_> {
    /// `issues.add(JstIssue(<path expr>, "<msg>"))` statement.
    fn push(&self, path_expr: &str, msg: &str) -> String {
        format!(
            "issues.add({}({}, \"{}\"))",
            self.issue,
            path_expr,
            escape_string(msg)
        )
    }
}

/// Emit-side JSON Pointer token escaping for statically known keys
/// (RFC 6901: `~` → `~0`, `/` → `~1`).
fn ptr_seg(key: &str) -> String {
    key.replace('~', "~0").replace('/', "~1")
}

/// Kotlin expression for the child path of a statically known object key.
fn child_path(key: &str) -> String {
    format!("path + \"/{}\"", escape_string(&ptr_seg(key)))
}

/// Kotlin expression for the child path of a dynamic key `k` (runtime-escaped).
const DYN_KEY_PATH: &str = "path + \"/\" + _jstPtr(k)";

fn emit_validation(ir: &SchemaIr, ctx: &Ctx) -> String {
    match ir {
        SchemaIr::Interpreted { schema, remotes } => {
            let schema_json =
                serde_json::to_string(schema).unwrap_or_else(|_| "true".to_string());
            let remotes_json = {
                let map: serde_json::Map<String, serde_json::Value> = remotes
                    .iter()
                    .map(|(k, v)| (k.clone(), v.clone()))
                    .collect();
                serde_json::to_string(&serde_json::Value::Object(map))
                    .unwrap_or_else(|_| "{}".to_string())
            };
            format!(
                "        run {{\n            val _s = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\")\n            val _r = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\") as JsonObject\n            if (!_jsiValidate(_s, _r, el)) {}\n        }}\n",
                escape_string(&schema_json),
                escape_string(&remotes_json),
                ctx.push(
                    "path",
                    "does not match the schema (checked by the embedded draft 2020-12 validator)"
                )
            )
        }
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Optional(inner) => {
            emit_validation(inner, ctx)
        }
        SchemaIr::Nullable(inner) => {
            let v = emit_validation(inner, ctx);
            if v.is_empty() {
                String::new()
            } else {
                format!(
                    "        if (el !is JsonNull) {{\n    {}\n        }}\n",
                    v.trim_end().replace('\n', "\n    ")
                )
            }
        }
        SchemaIr::Enum(cases) => {
            let allowed: Vec<String> = cases
                .iter()
                .map(|c| format!("\"{}\"", escape_string(c)))
                .collect();
            format!(
                "        if (!(el is JsonPrimitive && el.isString && el.content in setOf<String>({}))) {}\n",
                allowed.join(", "),
                ctx.push("path", "must be one of the allowed values")
            )
        }
        SchemaIr::Integer(c) => {
            let mut out = String::new();
            out.push_str("        run {\n");
            out.push_str(&format!(
                "            if (!(el is JsonPrimitive && !el.isString && el.booleanOrNull == null)) {{ {}; return@run }}\n",
                ctx.push("path", "must be an integer")
            ));
            out.push_str("            val v = (el as JsonPrimitive).longOrNull ?: (el as JsonPrimitive).doubleOrNull?.let { if (it == it.toLong().toDouble()) it.toLong() else null }\n");
            out.push_str(&format!(
                "            if (v == null) {{ {}; return@run }}\n",
                ctx.push("path", "must be an integer")
            ));
            emit_number_pushes(&mut out, c, "v", ctx);
            out.push_str("        }\n");
            out
        }
        SchemaIr::Number(c) => {
            let mut out = String::new();
            out.push_str("        run {\n");
            out.push_str(&format!(
                "            if (!(el is JsonPrimitive && !el.isString && el.booleanOrNull == null)) {{ {}; return@run }}\n",
                ctx.push("path", "must be a number")
            ));
            out.push_str("            val v = (el as JsonPrimitive).doubleOrNull\n");
            out.push_str(&format!(
                "            if (v == null) {{ {}; return@run }}\n",
                ctx.push("path", "must be a number")
            ));
            emit_number_pushes(&mut out, c, "v", ctx);
            out.push_str("        }\n");
            out
        }
        SchemaIr::Boolean => format!(
            "        if (!(el is JsonPrimitive && !el.isString && el.booleanOrNull != null)) {}\n",
            ctx.push("path", "must be a boolean")
        ),
        SchemaIr::String(c) => {
            if c.min_length.is_none() && c.max_length.is_none() && c.pattern.is_none() {
                return format!(
                    "        if (!(el is JsonPrimitive && el.isString)) {}\n",
                    ctx.push("path", "must be a string")
                );
            }
            let mut out = String::new();
            out.push_str("        run {\n");
            out.push_str(&format!(
                "            if (!(el is JsonPrimitive && el.isString)) {{ {}; return@run }}\n",
                ctx.push("path", "must be a string")
            ));
            out.push_str("            val v = (el as JsonPrimitive).content\n");
            if let Some(min) = c.min_length {
                out.push_str(&format!(
                    "            if (!(v.codePointCount(0, v.length) >= {min})) {}\n",
                    ctx.push("path", &format!("must be at least {min} characters"))
                ));
            }
            if let Some(max) = c.max_length {
                out.push_str(&format!(
                    "            if (!(v.codePointCount(0, v.length) <= {max})) {}\n",
                    ctx.push("path", &format!("must be at most {max} characters"))
                ));
            }
            if let Some(ref pat) = c.pattern {
                out.push_str(&format!(
                    "            if (!Regex(\"{}\").containsMatchIn(v)) {}\n",
                    escape_string(&translate_pattern(pat)),
                    ctx.push("path", &format!("must match pattern {pat}"))
                ));
            }
            out.push_str("        }\n");
            out
        }
        SchemaIr::Null => format!(
            "        if (el !is JsonNull) {}\n",
            ctx.push("path", "must be null")
        ),
        SchemaIr::Any | SchemaIr::Unknown => String::new(), // accept anything
        SchemaIr::Never => format!("        {}\n", ctx.push("path", "schema rejects all values")),
        SchemaIr::Literal(lit) => {
            let msg = match lit {
                LiteralValue::Bool(b) => format!("must equal {b}"),
                LiteralValue::Integer(i) => format!("must equal {i}"),
                LiteralValue::Number(n) => format!("must equal {}", format_msg_number(*n)),
                LiteralValue::String(s) => format!("must equal \"{s}\""),
                LiteralValue::Null => "must be null".to_string(),
            };
            format!(
                "        if (!{}) {}\n",
                emit_literal_match(lit),
                ctx.push("path", &msg)
            )
        }
        SchemaIr::ConstEqual(val) => {
            let json_str = serde_json::to_string(val).unwrap_or_else(|_| "null".to_string());
            format!(
                "        run {{\n            val expected = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\")\n            if (!_jsiEq(el, expected)) {}\n        }}\n",
                escape_string(&json_str),
                ctx.push("path", "must equal the const value")
            )
        }
        SchemaIr::MixedEnum(lits) => {
            let checks: Vec<String> = lits.iter().map(|l| emit_literal_match(l)).collect();
            format!(
                "        if (!({})) {}\n",
                checks.join(" || "),
                ctx.push("path", "must be one of the allowed values")
            )
        }
        SchemaIr::ComplexEnum(vals) => {
            let json_str = serde_json::to_string(vals).unwrap_or_else(|_| "[]".to_string());
            format!(
                "        run {{\n            val allowed = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\") as JsonArray\n            if (!allowed.any {{ _jsiEq(el, it) }}) {}\n        }}\n",
                escape_string(&json_str),
                ctx.push("path", "must be one of the allowed values")
            )
        }
        SchemaIr::Array(arr) => emit_array_validation(arr, ctx),
        SchemaIr::Tuple(tuple) => emit_tuple_validation(tuple, ctx),
        SchemaIr::TypeGuarded(guards) => emit_type_guarded_validation(guards, ctx),
        SchemaIr::Not { base: _, not_schema } => emit_not_check(not_schema, ctx),
        SchemaIr::Conditional { base: _, if_schema, then_schema, else_schema } => {
            emit_conditional_check(if_schema, then_schema.as_deref(), else_schema.as_deref(), ctx)
        }
        SchemaIr::Union(members) if members.len() > 1 => emit_union_check(members, ctx, false),
        SchemaIr::ExclusiveUnion(members) if members.len() > 1 => {
            emit_union_check(members, ctx, true)
        }
        SchemaIr::Intersection(members) if members.len() == 1 => {
            emit_validation(&members[0], ctx)
        }
        SchemaIr::Intersection(members) if members.len() > 1 => {
            // Wrap each member in `run { }` so local vals (v, obj, arr, known…)
            // declared by one member's checks don't conflict with the next.
            // allOf accumulates every member's issues; type-mismatch
            // `return@run` guards bind to each arm's own inner scope.
            let mut checks = String::new();
            for member in members {
                let v = emit_validation(member, ctx);
                if v.is_empty() {
                    continue;
                }
                checks.push_str(&format!(
                    "        run {{\n    {}\n        }}\n",
                    v.trim_end().replace('\n', "\n    ")
                ));
            }
            checks
        }
        SchemaIr::Record(rec) => {
            let val_check = if matches!(rec.value.as_ref(), SchemaIr::Any | SchemaIr::Unknown) {
                String::new()
            } else {
                emit_inline_check(&rec.value, "v", DYN_KEY_PATH, ctx)
            };
            if val_check.is_empty() {
                format!(
                    "        if (el !is JsonObject) {}\n",
                    ctx.push("path", "must be an object")
                )
            } else {
                format!(
                    "        run {{\n            if (el !is JsonObject) {{ {}; return@run }}\n            for ((k, v) in el.jsonObject) {{ {} }}\n        }}\n",
                    ctx.push("path", "must be an object"),
                    val_check
                )
            }
        }
        SchemaIr::Object(obj) => {
            let body = emit_object_checks(obj, ctx, "            ");
            if body.is_empty() {
                format!(
                    "        if (el !is JsonObject) {}\n",
                    ctx.push("path", "must be an object")
                )
            } else {
                format!(
                    "        run {{\n            if (el !is JsonObject) {{ {}; return@run }}\n            val obj = el.jsonObject\n{}\n        }}\n",
                    ctx.push("path", "must be an object"),
                    body.join("\n")
                )
            }
        }
        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => {
            // Delegate to the referenced type's serializer, which performs the
            // full validation for that definition (data class, enum or
            // wrapper). Its collected issues are re-pathed under this
            // location; non-JST serialization failures (plain data classes,
            // enums) become a single issue here.
            let safe = sanitize_kotlin_name(name, ctx.prefix);
            format!(
                "        try {{\n            _lenientJson.decodeFromJsonElement<{safe}>(el)\n        }} catch (e: {exc}) {{\n            for (iss in e.issues) issues.add({issue}(path + iss.path, iss.message))\n        }} catch (e: Exception) {{\n            issues.add({issue}(path, e.message ?: \"does not match the referenced schema\"))\n        }}\n",
                exc = ctx.exc,
                issue = ctx.issue
            )
        }
        _ => String::new(),
    }
}

/// Bound/multipleOf pushes over an in-scope numeric `v` (12-space indent).
fn emit_number_pushes(out: &mut String, c: &NumberConstraints, var_name: &str, ctx: &Ctx) {
    if let Some(min) = c.minimum {
        out.push_str(&format!(
            "            if (!({var_name} >= {})) {}\n",
            format_kt_number(min),
            ctx.push("path", &format!("must be >= {}", format_msg_number(min)))
        ));
    }
    if let Some(max) = c.maximum {
        out.push_str(&format!(
            "            if (!({var_name} <= {})) {}\n",
            format_kt_number(max),
            ctx.push("path", &format!("must be <= {}", format_msg_number(max)))
        ));
    }
    if let Some(emin) = c.exclusive_minimum {
        out.push_str(&format!(
            "            if (!({var_name} > {})) {}\n",
            format_kt_number(emin),
            ctx.push("path", &format!("must be > {}", format_msg_number(emin)))
        ));
    }
    if let Some(emax) = c.exclusive_maximum {
        out.push_str(&format!(
            "            if (!({var_name} < {})) {}\n",
            format_kt_number(emax),
            ctx.push("path", &format!("must be < {}", format_msg_number(emax)))
        ));
    }
    if let Some(mul) = c.multiple_of {
        let b = format_kt_number(mul);
        out.push_str(&format!(
            "            if (!(({var_name}.toDouble() / {b}).let {{ it.isFinite() && it == kotlin.math.floor(it) }})) {}\n",
            ctx.push("path", &format!("must be a multiple of {}", format_msg_number(mul)))
        ));
    }
}

fn emit_literal_match(lit: &LiteralValue) -> String {
    match lit {
        LiteralValue::Bool(b) => format!("(el is JsonPrimitive && !el.isString && el.booleanOrNull == {b})"),
        LiteralValue::Integer(i) => format!(
            "(el is JsonPrimitive && !el.isString && el.booleanOrNull == null && (el.longOrNull == {i}L || el.doubleOrNull == {i}.0))"
        ),
        LiteralValue::Number(n) => {
            let b = format_kt_number(*n);
            format!("(el is JsonPrimitive && !el.isString && el.booleanOrNull == null && el.doubleOrNull == {b})")
        }
        LiteralValue::String(s) => {
            let escaped = escape_string(s);
            format!("(el is JsonPrimitive && el.isString && el.content == \"{escaped}\")")
        }
        LiteralValue::Null => "(el is JsonNull)".to_string(),
    }
}

/// Single-statement check for a value expression `var_name` at `path_expr`.
/// Simple types push directly; complex schemas rebind `el`/`path` in a `run`
/// scope (Kotlin resolves the initializers against the outer bindings) and
/// reuse the full statement generator, so nested failures accumulate into the
/// same `issues` list with composed paths.
fn emit_inline_check(ir: &SchemaIr, var_name: &str, path_expr: &str, ctx: &Ctx) -> String {
    match ir {
        SchemaIr::Integer(c) if c.minimum.is_none() && c.maximum.is_none() && c.exclusive_minimum.is_none() && c.exclusive_maximum.is_none() && c.multiple_of.is_none() => {
            format!(
                "if (!({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull == null && ({var_name}.jsonPrimitive.longOrNull != null || {var_name}.jsonPrimitive.doubleOrNull?.let {{ it == it.toLong().toDouble() }} == true))) {}",
                ctx.push(path_expr, "must be an integer")
            )
        }
        SchemaIr::Number(c) if c.minimum.is_none() && c.maximum.is_none() && c.exclusive_minimum.is_none() && c.exclusive_maximum.is_none() && c.multiple_of.is_none() => {
            format!(
                "if (!({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull == null && {var_name}.jsonPrimitive.doubleOrNull != null)) {}",
                ctx.push(path_expr, "must be a number")
            )
        }
        SchemaIr::Boolean => format!(
            "if (!({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull != null)) {}",
            ctx.push(path_expr, "must be a boolean")
        ),
        SchemaIr::String(c) if c.min_length.is_none() && c.max_length.is_none() && c.pattern.is_none() => {
            format!(
                "if (!({var_name} is JsonPrimitive && {var_name}.jsonPrimitive.isString)) {}",
                ctx.push(path_expr, "must be a string")
            )
        }
        SchemaIr::Null => format!(
            "if ({var_name} !is JsonNull) {}",
            ctx.push(path_expr, "must be null")
        ),
        SchemaIr::Any | SchemaIr::Unknown => String::new(),
        SchemaIr::Never => ctx.push(path_expr, "schema rejects all values"),
        _ => {
            // For complex schemas, use full validation via el/path rebinding.
            let validation = emit_validation(ir, ctx);
            if validation.is_empty() {
                return String::new();
            }
            format!(
                "run {{ val el = {var_name}; val path = {path_expr}; {} }}",
                validation.trim()
            )
        }
    }
}

/// Kotlin Boolean expression: does `var_name` match `ir`? Runs the collector
/// against a throwaway issues list in a private scope and reports emptiness —
/// used where composition needs only a match verdict (anyOf/oneOf branches,
/// if/then/else, not, contains counting, propertyNames).
fn emit_verdict_expr(ir: &SchemaIr, var_name: &str, ctx: &Ctx) -> String {
    let validation = emit_validation(ir, ctx);
    if validation.is_empty() {
        return "true".to_string();
    }
    format!(
        "try {{ run {{ val el = {var_name}; val path = \"\"; val issues = mutableListOf<{}>()\n{}\n        issues.isEmpty() }} }} catch (_: Exception) {{ false }}",
        ctx.issue,
        validation.trim_end()
    )
}

fn emit_array_validation(arr: &ArraySchema, ctx: &Ctx) -> String {
    let mut body: Vec<String> = Vec::new();

    if let Some(min) = arr.min_items {
        body.push(format!(
            "            if (arr.size < {min}) {}",
            ctx.push("path", &format!("must have at least {min} items"))
        ));
    }
    if let Some(max) = arr.max_items {
        body.push(format!(
            "            if (arr.size > {max}) {}",
            ctx.push("path", &format!("must have at most {max} items"))
        ));
    }

    // Item type validation, each index reported independently.
    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
        let item_check = emit_inline_check(&arr.items, "item", "path + \"/\" + i", ctx);
        if !item_check.is_empty() {
            body.push(format!(
                "            for ((i, item) in arr.withIndex()) {{ {item_check} }}"
            ));
        }
    }

    if arr.unique_items {
        // Every duplicate index gets its own issue.
        body.push("            val _seen = mutableSetOf<String>()".to_string());
        body.push(format!(
            "            for ((i, item) in arr.withIndex()) {{ if (!_seen.add(_canonicalize(item))) {} }}",
            ctx.push("path + \"/\" + i", "duplicate item")
        ));
    }

    if let Some(contains) = &arr.contains {
        push_contains_checks(&mut body, contains, ctx);
    }

    if body.is_empty() {
        return format!(
            "        if (el !is JsonArray) {}\n",
            ctx.push("path", "must be an array")
        );
    }
    format!(
        "        run {{\n            if (el !is JsonArray) {{ {}; return@run }}\n            val arr = el.jsonArray\n{}\n        }}\n",
        ctx.push("path", "must be an array"),
        body.join("\n")
    )
}

/// `contains`/`minContains`/`maxContains` checks over an in-scope `arr`
/// (verdict-only per item: only match/no-match is meaningful for counting).
fn push_contains_checks(body: &mut Vec<String>, contains: &ContainsSchema, ctx: &Ctx) {
    let verdict = emit_verdict_expr(&contains.schema, "it", ctx);
    let min = contains.min_contains.unwrap_or(1);
    if verdict == "true" {
        // contains schema is Any — every item matches
        body.push("            val matchCount = arr.size".to_string());
    } else {
        body.push(format!("            val matchCount = arr.count {{ {verdict} }}"));
    }
    body.push(format!(
        "            if (matchCount < {min}) {}",
        ctx.push("path", &format!("must contain at least {min} matching items (contains)"))
    ));
    if let Some(max) = contains.max_contains {
        body.push(format!(
            "            if (matchCount > {max}) {}",
            ctx.push("path", &format!("must contain at most {max} matching items (contains)"))
        ));
    }
}

fn emit_tuple_validation(tuple: &TupleSchema, ctx: &Ctx) -> String {
    let mut body: Vec<String> = Vec::new();

    // Prefix item type checks
    for (i, item) in tuple.items.iter().enumerate() {
        if matches!(item, SchemaIr::Any) {
            continue;
        }
        let item_check =
            emit_inline_check(item, &format!("arr[{i}]"), &format!("path + \"/{i}\""), ctx);
        if !item_check.is_empty() {
            body.push(format!("            if (arr.size > {i}) {{ {item_check} }}"));
        }
    }

    let prefix_count = tuple.items.len();
    if let Some(rest) = &tuple.rest {
        if !matches!(rest.as_ref(), SchemaIr::Any) {
            let rest_check = emit_inline_check(rest, "arr[i]", "path + \"/\" + i", ctx);
            if !rest_check.is_empty() {
                body.push(format!(
                    "            for (i in {prefix_count} until arr.size) {{ {rest_check} }}"
                ));
            }
        }
    } else {
        body.push(format!(
            "            if (arr.size > {prefix_count}) {}",
            ctx.push("path", &format!("must have at most {prefix_count} items"))
        ));
    }

    if let Some(min) = tuple.min_items {
        body.push(format!(
            "            if (arr.size < {min}) {}",
            ctx.push("path", &format!("must have at least {min} items"))
        ));
    }
    if let Some(max) = tuple.max_items {
        body.push(format!(
            "            if (arr.size > {max}) {}",
            ctx.push("path", &format!("must have at most {max} items"))
        ));
    }

    if tuple.unique_items {
        body.push("            val _seen = mutableSetOf<String>()".to_string());
        body.push(format!(
            "            for ((i, item) in arr.withIndex()) {{ if (!_seen.add(_canonicalize(item))) {} }}",
            ctx.push("path + \"/\" + i", "duplicate item")
        ));
    }

    if body.is_empty() {
        return format!(
            "        if (el !is JsonArray) {}\n",
            ctx.push("path", "must be an array")
        );
    }
    format!(
        "        run {{\n            if (el !is JsonArray) {{ {}; return@run }}\n            val arr = el.jsonArray\n{}\n        }}\n",
        ctx.push("path", "must be an array"),
        body.join("\n")
    )
}

fn emit_type_guarded_validation(guards: &[(TypeGuard, Box<SchemaIr>)], ctx: &Ctx) -> String {
    let mut checks: Vec<String> = Vec::new();

    for (guard, schema) in guards {
        match guard {
            TypeGuard::String => {
                if let SchemaIr::String(c) = schema.as_ref() {
                    checks.push("        if (el is JsonPrimitive && el.isString) {".to_string());
                    checks.push("            val v = el.content".to_string());
                    if let Some(min) = c.min_length {
                        checks.push(format!(
                            "            if (!(v.codePointCount(0, v.length) >= {min})) {}",
                            ctx.push("path", &format!("must be at least {min} characters"))
                        ));
                    }
                    if let Some(max) = c.max_length {
                        checks.push(format!(
                            "            if (!(v.codePointCount(0, v.length) <= {max})) {}",
                            ctx.push("path", &format!("must be at most {max} characters"))
                        ));
                    }
                    if let Some(ref pat) = c.pattern {
                        checks.push(format!(
                            "            if (!Regex(\"{}\").containsMatchIn(v)) {}",
                            escape_string(&translate_pattern(pat)),
                            ctx.push("path", &format!("must match pattern {pat}"))
                        ));
                    }
                    checks.push("        }".to_string());
                }
            }
            TypeGuard::Number => {
                let c = match schema.as_ref() {
                    SchemaIr::Number(c) | SchemaIr::Integer(c) => c,
                    _ => continue,
                };
                checks.push("        if (el is JsonPrimitive && !el.isString && el.booleanOrNull == null && el.doubleOrNull != null) {".to_string());
                checks.push("            val v = el.doubleOrNull!!".to_string());
                let mut pushes = String::new();
                emit_number_pushes(&mut pushes, c, "v", ctx);
                for l in pushes.trim_end().lines() {
                    checks.push(l.to_string());
                }
                checks.push("        }".to_string());
            }
            TypeGuard::Object => {
                if let SchemaIr::Object(obj) = schema.as_ref() {
                    checks.push("        if (el is JsonObject) {".to_string());
                    checks.push("            val obj = el.jsonObject".to_string());
                    checks.extend(emit_object_checks(obj, ctx, "            "));
                    checks.push("        }".to_string());
                }
                // Record in TypeGuard::Object
                if let SchemaIr::Record(rec) = schema.as_ref() {
                    let val_check = emit_inline_check(&rec.value, "v", DYN_KEY_PATH, ctx);
                    if !val_check.is_empty() {
                        checks.push("        if (el is JsonObject) {".to_string());
                        checks.push(format!(
                            "            for ((k, v) in el.jsonObject) {{ {val_check} }}"
                        ));
                        checks.push("        }".to_string());
                    }
                }
            }
            TypeGuard::Array => {
                if let SchemaIr::Array(arr) = schema.as_ref() {
                    checks.push("        if (el is JsonArray) {".to_string());
                    checks.push("            val arr = el.jsonArray".to_string());
                    if let Some(min) = arr.min_items {
                        checks.push(format!(
                            "            if (arr.size < {min}) {}",
                            ctx.push("path", &format!("must have at least {min} items"))
                        ));
                    }
                    if let Some(max) = arr.max_items {
                        checks.push(format!(
                            "            if (arr.size > {max}) {}",
                            ctx.push("path", &format!("must have at most {max} items"))
                        ));
                    }
                    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
                        let item_check =
                            emit_inline_check(&arr.items, "item", "path + \"/\" + i", ctx);
                        if !item_check.is_empty() {
                            checks.push(format!(
                                "            for ((i, item) in arr.withIndex()) {{ {item_check} }}"
                            ));
                        }
                    }
                    if arr.unique_items {
                        checks.push("            val _seen = mutableSetOf<String>()".to_string());
                        checks.push(format!(
                            "            for ((i, item) in arr.withIndex()) {{ if (!_seen.add(_canonicalize(item))) {} }}",
                            ctx.push("path + \"/\" + i", "duplicate item")
                        ));
                    }
                    // contains in TypeGuard::Array
                    if let Some(contains) = &arr.contains {
                        let mut contains_body: Vec<String> = Vec::new();
                        push_contains_checks(&mut contains_body, contains, ctx);
                        checks.extend(contains_body);
                    }
                    checks.push("        }".to_string());
                }
                // Also handle Tuple in Array TypeGuard
                if let SchemaIr::Tuple(tuple) = schema.as_ref() {
                    checks.push("        if (el is JsonArray) {".to_string());
                    checks.push("            val arr = el.jsonArray".to_string());
                    for (i, item) in tuple.items.iter().enumerate() {
                        if matches!(item, SchemaIr::Any) {
                            continue;
                        }
                        let item_check = emit_inline_check(
                            item,
                            &format!("arr[{i}]"),
                            &format!("path + \"/{i}\""),
                            ctx,
                        );
                        if !item_check.is_empty() {
                            checks.push(format!(
                                "            if (arr.size > {i}) {{ {item_check} }}"
                            ));
                        }
                    }
                    let prefix_count = tuple.items.len();
                    if let Some(rest) = &tuple.rest {
                        if !matches!(rest.as_ref(), SchemaIr::Any) {
                            let rest_check =
                                emit_inline_check(rest, "arr[i]", "path + \"/\" + i", ctx);
                            if !rest_check.is_empty() {
                                checks.push(format!(
                                    "            for (i in {prefix_count} until arr.size) {{ {rest_check} }}"
                                ));
                            }
                        }
                    } else {
                        checks.push(format!(
                            "            if (arr.size > {prefix_count}) {}",
                            ctx.push("path", &format!("must have at most {prefix_count} items"))
                        ));
                    }
                    if let Some(min) = tuple.min_items {
                        checks.push(format!(
                            "            if (arr.size < {min}) {}",
                            ctx.push("path", &format!("must have at least {min} items"))
                        ));
                    }
                    if let Some(max) = tuple.max_items {
                        checks.push(format!(
                            "            if (arr.size > {max}) {}",
                            ctx.push("path", &format!("must have at most {max} items"))
                        ));
                    }
                    if tuple.unique_items {
                        checks.push("            val _seen = mutableSetOf<String>()".to_string());
                        checks.push(format!(
                            "            for ((i, item) in arr.withIndex()) {{ if (!_seen.add(_canonicalize(item))) {} }}",
                            ctx.push("path + \"/\" + i", "duplicate item")
                        ));
                    }
                    checks.push("        }".to_string());
                }
            }
        }
    }

    if checks.is_empty() {
        String::new()
    } else {
        checks.join("\n") + "\n"
    }
}

/// Object constraint checks over in-scope `obj` (a JsonObject map), `el`,
/// `path` and `issues`. `ind` is the statement indent; used both by the
/// Object arm (inside its `run {}` guard) and TypeGuard::Object (inside its
/// `if (el is JsonObject)` block).
fn emit_object_checks(obj: &ObjectSchema, ctx: &Ctx, ind: &str) -> Vec<String> {
    let mut checks: Vec<String> = Vec::new();

    for (k, f) in &obj.fields {
        let ek = escape_string(k);
        if f.required {
            // Every missing required key reports its own issue.
            checks.push(format!(
                "{ind}if (\"{ek}\" !in obj) {}",
                ctx.push(&child_path(k), "required property is missing")
            ));
        }
        if !matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) {
            let field_check =
                emit_inline_check(&f.schema, &format!("obj[\"{ek}\"]!!"), &child_path(k), ctx);
            if !field_check.is_empty() {
                checks.push(format!("{ind}if (\"{ek}\" in obj) {{ {field_check} }}"));
            }
        }
    }
    if let Some(min) = obj.min_properties {
        checks.push(format!(
            "{ind}if (obj.size < {min}) {}",
            ctx.push("path", &format!("must have at least {min} properties"))
        ));
    }
    if let Some(max) = obj.max_properties {
        checks.push(format!(
            "{ind}if (obj.size > {max}) {}",
            ctx.push("path", &format!("must have at most {max} properties"))
        ));
    }
    // patternProperties + additionalProperties interaction:
    // additionalProperties applies only to keys not matched by a named
    // property or any patternProperties regex.
    let known: Vec<String> = obj
        .fields
        .keys()
        .map(|k| format!("\"{}\"", escape_string(k)))
        .collect();
    if !obj.pattern_properties.is_empty() {
        checks.push(format!("{ind}for ((k, v) in obj) {{"));
        checks.push(format!(
            "{ind}    var matched = setOf<String>({}).contains(k)",
            known.join(", ")
        ));
        for (pattern, pp_schema) in &obj.pattern_properties {
            let pp_check = emit_inline_check(pp_schema, "v", DYN_KEY_PATH, ctx);
            if !pp_check.is_empty() {
                checks.push(format!(
                    "{ind}    if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true; {} }}",
                    escape_string(&translate_pattern(pattern)),
                    pp_check
                ));
            } else {
                checks.push(format!(
                    "{ind}    if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true }}",
                    escape_string(&translate_pattern(pattern))
                ));
            }
        }
        if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
            checks.push(format!(
                "{ind}    if (!matched) {}",
                ctx.push(DYN_KEY_PATH, "unexpected property")
            ));
        } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
            let ap_check = emit_inline_check(ap, "v", DYN_KEY_PATH, ctx);
            if !ap_check.is_empty() {
                checks.push(format!("{ind}    if (!matched) {{ {ap_check} }}"));
            }
        }
        checks.push(format!("{ind}}}"));
    } else if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
        checks.push(format!(
            "{ind}val known = setOf<String>({})",
            known.join(", ")
        ));
        checks.push(format!(
            "{ind}for (k in obj.keys) {{ if (k !in known) {} }}",
            ctx.push(DYN_KEY_PATH, "unexpected property")
        ));
    } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
        let ap_check = emit_inline_check(ap, "v", DYN_KEY_PATH, ctx);
        if !ap_check.is_empty() {
            checks.push(format!(
                "{ind}val _known = setOf<String>({})",
                known.join(", ")
            ));
            checks.push(format!(
                "{ind}for ((k, v) in obj) {{ if (k !in _known) {{ {ap_check} }} }}"
            ));
        }
    }
    // propertyNames (verdict-only per key: the key either matches or not)
    if let Some(pn) = &obj.property_names {
        let m = emit_verdict_expr(pn, "JsonPrimitive(k)", ctx);
        if m != "true" {
            checks.push(format!(
                "{ind}for (k in obj.keys) {{ if (!({m})) {} }}",
                ctx.push(DYN_KEY_PATH, "invalid property name")
            ));
        }
    }
    // dependentRequired
    for (prop, required) in &obj.dependent_required {
        for r in required {
            checks.push(format!(
                "{ind}if (\"{}\" in obj && \"{}\" !in obj) {}",
                escape_string(prop),
                escape_string(r),
                ctx.push(&child_path(r), &format!("required when \"{prop}\" is present"))
            ));
        }
    }
    // dependentSchemas — collected against the whole object, so nested
    // failures keep their own paths.
    for (prop, dep_schema) in &obj.dependent_schemas {
        let dep = emit_validation(dep_schema, ctx);
        if !dep.is_empty() {
            checks.push(format!("{ind}if (\"{}\" in obj) {{", escape_string(prop)));
            // Fragments are generated at 8-space depth; shift to sit inside
            // this block.
            let extra = " ".repeat(ind.len().saturating_sub(8) + 4);
            for l in dep.trim_end().lines() {
                checks.push(format!("{extra}{l}"));
            }
            checks.push(format!("{ind}}}"));
        }
    }
    checks
}

fn emit_not_check(not_schema: &SchemaIr, ctx: &Ctx) -> String {
    let verdict = emit_verdict_expr(not_schema, "el", ctx);
    if verdict == "true" {
        // not_schema accepts everything → nothing can pass
        return format!(
            "        {}\n",
            ctx.push("path", "must not match the excluded schema")
        );
    }
    format!(
        "        if ({verdict}) {}\n",
        ctx.push("path", "must not match the excluded schema")
    )
}

fn emit_conditional_check(
    if_schema: &SchemaIr,
    then_schema: Option<&SchemaIr>,
    else_schema: Option<&SchemaIr>,
    ctx: &Ctx,
) -> String {
    let then_c = then_schema
        .map(|t| emit_validation(t, ctx))
        .unwrap_or_default();
    let else_c = else_schema
        .map(|e| emit_validation(e, ctx))
        .unwrap_or_default();
    if then_c.is_empty() && else_c.is_empty() {
        return String::new();
    }
    let if_v = emit_verdict_expr(if_schema, "el", ctx);
    let mut out = String::new();
    out.push_str("        run {\n");
    out.push_str(&format!("            val ifMatched = {if_v}\n"));
    if !then_c.is_empty() {
        out.push_str("            if (ifMatched) {\n");
        for l in then_c.trim_end().lines() {
            out.push_str(&format!("        {l}\n"));
        }
        out.push_str("            }\n");
    }
    if !else_c.is_empty() {
        out.push_str("            if (!ifMatched) {\n");
        for l in else_c.trim_end().lines() {
            out.push_str(&format!("        {l}\n"));
        }
        out.push_str("            }\n");
    }
    out.push_str("        }\n");
    out
}

fn emit_union_check(members: &[SchemaIr], ctx: &Ctx, exclusive: bool) -> String {
    // anyOf/oneOf verdicts stay single issues: per-branch failure details are
    // not meaningful when only one branch needs to match.
    let branch_checks: Vec<String> = members
        .iter()
        .map(|m| emit_verdict_expr(m, "el", ctx))
        .collect();

    let mut out = String::new();
    out.push_str("        run {\n");
    out.push_str("            val branchResults = listOf(\n");
    for (i, check) in branch_checks.iter().enumerate() {
        let comma = if i < branch_checks.len() - 1 { "," } else { "" };
        out.push_str(&format!("                {check}{comma}\n"));
    }
    out.push_str("            )\n");
    out.push_str("            val matchCount = branchResults.count { it }\n");
    if exclusive {
        out.push_str(&format!(
            "            if (matchCount != 1) {}\n",
            ctx.push("path", "must match exactly one of the expected schemas (oneOf)")
        ));
    } else {
        out.push_str(&format!(
            "            if (matchCount < 1) {}\n",
            ctx.push("path", "must match at least one of the expected schemas (anyOf)")
        ));
    }
    out.push_str("        }\n");
    out
}

fn emit_never_class(name: &str, counter: &mut usize, gopts: &GenOptions) -> String {
    *counter += 1;
    let ser_name = format!("{name}Ser");
    format!(
        "private object {ser_name} : KSerializer<{name}> {{\n    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor\n    override fun deserialize(decoder: Decoder): {name} {{ decoder.decodeSerializableValue(JsonElement.serializer()); throw {exc}(listOf({issue}(\"\", \"schema rejects all values\"))) }}\n    override fun serialize(encoder: Encoder, value: {name}) {{ encoder.encodeSerializableValue(JsonElement.serializer(), value.element) }}\n}}\n\n@Serializable(with = {ser_name}::class)\nclass {name}({vkw} element: JsonElement) : {iface} {{\n{members}}}",
        vkw = gopts.val_kw(),
        iface = gopts.iface,
        exc = gopts.exc,
        issue = gopts.issue,
        members = validate_members(name)
    )
}

// ── Type mapping ────────────────────────────────────────────────────────────

fn kotlin_type(ir: &SchemaIr, defs: &[DefEntry], prefix: &str) -> String {
    match ir {
        SchemaIr::String(_) => "String".to_string(),
        SchemaIr::Number(_) => "Double".to_string(),
        SchemaIr::Integer(_) => "Int".to_string(),
        SchemaIr::Boolean => "Boolean".to_string(),
        SchemaIr::Null => "Nothing?".to_string(),
        // TODO(kotlin-interpreter): validate via embedded spec interpreter
        SchemaIr::Any | SchemaIr::Unknown | SchemaIr::Interpreted { .. } => "JsonElement".to_string(),
        SchemaIr::Never => "Nothing".to_string(),

        SchemaIr::Literal(lit) => match lit {
            LiteralValue::String(_) => "String".to_string(),
            LiteralValue::Number(_) => "Double".to_string(),
            LiteralValue::Integer(_) => "Int".to_string(),
            LiteralValue::Bool(_) => "Boolean".to_string(),
            LiteralValue::Null => "Nothing?".to_string(),
        },

        SchemaIr::ConstEqual(_) | SchemaIr::ComplexEnum(_) => "JsonElement".to_string(),
        SchemaIr::Enum(_) => "String".to_string(),
        SchemaIr::MixedEnum(_) => "JsonElement".to_string(),

        SchemaIr::Array(arr) => format!("List<{}>", kotlin_type(&arr.items, defs, prefix)),
        SchemaIr::Tuple(_) => "List<JsonElement>".to_string(),
        SchemaIr::Object(_) => "JsonObject".to_string(),
        SchemaIr::Record(rec) => format!("Map<String, {}>", kotlin_type(&rec.value, defs, prefix)),

        SchemaIr::Union(members) | SchemaIr::ExclusiveUnion(members) => {
            if members.len() == 2 {
                let non_null: Vec<_> = members
                    .iter()
                    .filter(|m| !matches!(m, SchemaIr::Null))
                    .collect();
                if non_null.len() == 1 {
                    return format!("{}?", kotlin_type(non_null[0], defs, prefix));
                }
            }
            "JsonElement".to_string()
        }

        SchemaIr::Intersection(_) => "JsonElement".to_string(),
        SchemaIr::Nullable(inner) => format!("{}?", kotlin_type(inner, defs, prefix)),
        SchemaIr::Optional(inner) => format!("{}?", kotlin_type(inner, defs, prefix)),
        SchemaIr::Default(inner, _) => kotlin_type(inner, defs, prefix),
        SchemaIr::Describe(inner, _) => kotlin_type(inner, defs, prefix),
        SchemaIr::Not { base, .. } => kotlin_type(base, defs, prefix),
        SchemaIr::Conditional { base, .. } => kotlin_type(base, defs, prefix),
        SchemaIr::TypeGuarded(_) => "JsonElement".to_string(),
        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => sanitize_kotlin_name(name, prefix),
    }
}

fn format_kt_number(n: f64) -> String {
    if n == n.trunc() && n.abs() < 1e15 {
        format!("{}.0", n as i64)
    } else {
        format!("{n}")
    }
}

/// Human-friendly number rendering for diagnostic messages: integral values
/// print without the trailing ".0" (check expressions still use
/// `format_kt_number`, which must produce a valid Kotlin Double literal).
fn format_msg_number(n: f64) -> String {
    if n.fract() == 0.0 && n.abs() < 9.007199254740992e15 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

/// Convert to lowerCamelCase (Kotlin convention).
fn to_camel_case(s: &str) -> String {
    if !s.contains(|c: char| !c.is_ascii_alphanumeric())
        && s.chars().next().is_some_and(|c| c.is_ascii_lowercase())
    {
        let result = s.to_string();
        return if is_kotlin_keyword(&result) {
            format!("`{result}`")
        } else {
            result
        };
    }

    let parts: Vec<&str> = s
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
        .collect();

    if parts.is_empty() {
        return s.to_string();
    }

    let mut result = parts[0].to_lowercase();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }

    if is_kotlin_keyword(&result) {
        format!("`{result}`")
    } else {
        result
    }
}

fn is_kotlin_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "class" | "continue" | "do" | "else" | "false" | "for" | "fun"
            | "if" | "in" | "interface" | "is" | "null" | "object" | "package" | "return"
            | "super" | "this" | "throw" | "true" | "try" | "typealias" | "typeof" | "val"
            | "var" | "when" | "while"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::emit::SharedHelpers;
    use crate::Converter;
    use serde_json::json;

    fn order_item_schema() -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "quantity": {"type": "integer", "minimum": 1}
            },
            "required": ["id", "quantity"],
            "additionalProperties": false
        })
    }

    fn emit_opts(schema: &serde_json::Value, options: &EmitOptions) -> String {
        let converted = Converter::convert(schema).unwrap();
        KotlinEmitter.emit_with_options(&converted, "sample", options)
    }

    #[test]
    fn default_emit_conforms_to_mangled_validatable() {
        let out = emit_opts(&order_item_schema(), &EmitOptions::default());
        // Inline mode: interface declared per file under a mangled name.
        assert!(out.contains("interface _SampleJstValidatable"), "{out}");
        assert!(out.contains("class Sample(val element: JsonElement) : _SampleJstValidatable {"), "{out}");
        assert!(out.contains("override fun validate()"), "{out}");
        assert!(out.contains("override fun toValidatedJson(): String"), "{out}");
        // Typed construction via companion invoke, unvalidated by design.
        assert!(out.contains("operator fun invoke("), "{out}");
        assert!(out.contains("quantity: Int"), "{out}");
        // Immutable by default.
        assert!(!out.contains("var element"), "{out}");
    }

    #[test]
    fn mutable_emit_uses_var_properties() {
        let opts = EmitOptions { mutable: true, ..EmitOptions::default() };
        let wrapper = emit_opts(&order_item_schema(), &opts);
        assert!(wrapper.contains("class Sample(var element: JsonElement)"), "{wrapper}");

        // Fully-typed all-required object → data class path.
        let plain = json!({
            "type": "object",
            "properties": {"id": {"type": "string"}},
            "required": ["id"]
        });
        let dc = emit_opts(&plain, &opts);
        assert!(dc.contains("var id: String"), "{dc}");
        let dc_default = emit_opts(&plain, &EmitOptions::default());
        assert!(dc_default.contains("val id: String"), "{dc_default}");
        assert!(dc_default.contains(") : _SampleJstValidatable {"), "{dc_default}");
    }

    #[test]
    fn shared_mode_imports_canonical_interface_and_reports_need() {
        let converted = Converter::convert(&order_item_schema()).unwrap();
        let options = EmitOptions {
            helpers: Some(SharedHelpers::new("JstHelpers.kt")),
            mutable: false,
        };
        let (out, needs) = KotlinEmitter.emit_collecting(&converted, "sample", &options);
        assert!(needs.contains("validatable"), "{needs:?}");
        assert!(out.contains("import jst.helpers._JstValidatable"), "{out}");
        assert!(out.contains(": _JstValidatable {"), "{out}");
        assert!(!out.contains("interface _JstValidatable"), "{out}");

        let helpers = KotlinEmitter.helpers_content_for(&needs).unwrap();
        assert!(helpers.contains("interface _JstValidatable"), "{helpers}");
        // Public on purpose: generated public classes implement it.
        assert!(!helpers.contains("internal interface _JstValidatable"), "{helpers}");
    }

    #[test]
    fn enums_and_typealiases_skip_validatable() {
        let out = emit_opts(&json!({"enum": ["a", "b"]}), &EmitOptions::default());
        assert!(out.contains("enum class Sample"), "{out}");
        assert!(!out.contains("JstValidatable"), "{out}");
        assert!(!out.contains("import kotlinx.serialization.encodeToString"), "{out}");
        // No wrapper serializer → no error classes either.
        assert!(!out.contains("JstIssue"), "{out}");
    }

    #[test]
    fn wrapper_collects_all_issues_with_mangled_inline_names() {
        let out = emit_opts(&order_item_schema(), &EmitOptions::default());
        // Inline mode: issue/exception classes are declared per file under
        // mangled names and the serializer collects instead of throwing.
        assert!(out.contains("data class _SampleJstIssue(val path: String, val message: String)"), "{out}");
        assert!(out.contains("class _SampleJstValidationException(val issues: List<_SampleJstIssue>)"), "{out}");
        assert!(out.contains("val issues = mutableListOf<_SampleJstIssue>()"), "{out}");
        assert!(out.contains("if (issues.isNotEmpty()) throw _SampleJstValidationException(issues)"), "{out}");
        // Multiple independent constraint pushes, each with a pointer path.
        assert!(out.contains("issues.add(_SampleJstIssue(path + \"/id\", \"required property is missing\"))"), "{out}");
        assert!(out.contains("issues.add(_SampleJstIssue(path + \"/quantity\", \"required property is missing\"))"), "{out}");
        assert!(out.contains("\"must be >= 1\""), "{out}");
        assert!(out.contains("issues.add(_SampleJstIssue(path + \"/\" + _jstPtr(k), \"unexpected property\"))"), "{out}");
        // No first-failure aborts left in the wrapper serializer.
        assert!(!out.contains("require("), "{out}");
    }

    #[test]
    fn shared_mode_uses_canonical_error_names_and_tailors_helper() {
        let converted = Converter::convert(&order_item_schema()).unwrap();
        let options = EmitOptions {
            helpers: Some(SharedHelpers::new("JstHelpers.kt")),
            mutable: false,
        };
        let (out, needs) = KotlinEmitter.emit_collecting(&converted, "sample", &options);
        assert!(needs.contains("error"), "{needs:?}");
        assert!(out.contains("import jst.helpers.JstIssue"), "{out}");
        assert!(out.contains("import jst.helpers.JstValidationException"), "{out}");
        assert!(out.contains("import jst.helpers._jstPtr"), "{out}");
        assert!(out.contains("val issues = mutableListOf<JstIssue>()"), "{out}");
        assert!(!out.contains("_SampleJstIssue"), "{out}");

        let helpers = KotlinEmitter.helpers_content_for(&needs).unwrap();
        // Classes stay public (user code catches the exception type);
        // only the pointer-escape helper is internalized.
        assert!(helpers.contains("data class JstIssue"), "{helpers}");
        assert!(helpers.contains("class JstValidationException"), "{helpers}");
        assert!(helpers.contains("kotlinx.serialization.SerializationException"), "{helpers}");
        assert!(helpers.contains("internal fun _jstPtr"), "{helpers}");
        assert!(!helpers.contains("internal data class JstIssue"), "{helpers}");
    }

    #[test]
    fn unique_items_reports_every_duplicate_index() {
        let out = emit_opts(
            &json!({"type": "array", "items": {"type": "string"}, "uniqueItems": true}),
            &EmitOptions::default(),
        );
        assert!(out.contains("for ((i, item) in arr.withIndex()) { if (!_seen.add(_canonicalize(item)))"), "{out}");
        assert!(out.contains("issues.add(_SampleJstIssue(path + \"/\" + i, \"duplicate item\"))"), "{out}");
    }

    #[test]
    fn union_verdicts_stay_single_issue() {
        let out = emit_opts(
            &json!({"oneOf": [{"type": "string"}, {"type": "integer"}]}),
            &EmitOptions::default(),
        );
        assert!(out.contains("val branchResults = listOf("), "{out}");
        assert!(out.contains("must match exactly one of the expected schemas (oneOf)"), "{out}");
        // Branch verdicts run the collector privately and only report a bool.
        assert!(out.contains("issues.isEmpty() } } catch (_: Exception) { false }"), "{out}");
    }
}
