use crate::ir::*;
use crate::util::to_pascal_case;
use super::{EmitOptions, Emitter, HelperSet};

pub struct KotlinEmitter;

impl Emitter for KotlinEmitter {
    fn extension(&self) -> &str {
        "kt"
    }

    fn emit_with_options(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> String {
        self.emit_module(converted, name, options).0
    }

    fn emit_collecting(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> (String, HelperSet) {
        self.emit_module(converted, name, options)
    }

    fn helpers_content_for(&self, needs: &HelperSet) -> Option<String> {
        if needs.is_empty() {
            return None;
        }
        let mut s = String::from(concat!(
            "// Generated by json-schema-transformer — shared runtime helpers\n",
            "// DO NOT EDIT — changes will be overwritten on regeneration\n\n",
            "package jst.helpers\n\n",
            "import kotlinx.serialization.json.*\n\n",
        ));
        if needs.contains("validatable") {
            // Deliberately public: generated (public) classes implement it,
            // and a public class may not expose an internal supertype.
            s.push_str(VALIDATABLE_KT);
            s.push('\n');
        }
        if needs.contains("canonicalize") {
            s.push_str(&internalize(CANONICALIZE_KT));
            s.push('\n');
        }
        if needs.contains("lenient_json") {
            s.push_str(&internalize(LENIENT_JSON_KT));
            s.push('\n');
        }
        // The interpreter calls _jsiEq internally, so it drags the equality
        // helper into the shared file even when no module imports it directly.
        if needs.contains("jsi_eq") || needs.contains("jsi") {
            s.push_str(&internalize(EQ_HELPER_KT));
            s.push_str("\n\n");
        }
        if needs.contains("jsi") {
            s.push_str(&internalize(JSI_HELPER_KT));
            s.push('\n');
        }
        Some(s)
    }

    fn helpers_content(&self) -> Option<String> {
        let mut all = HelperSet::default();
        for n in ["validatable", "canonicalize", "lenient_json", "jsi_eq", "jsi"] {
            all.insert(n);
        }
        self.helpers_content_for(&all)
    }

    fn default_helpers_file(&self) -> Option<&'static str> {
        Some("JstHelpers.kt")
    }
}

impl KotlinEmitter {
    fn emit_module(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> (String, HelperSet) {
        let pascal = to_pascal_case(name);
        let mut out = String::new();

        out.push_str(&format!(
            "// Generated by json-schema-transformer\n// {name}\n// DO NOT EDIT — changes will be overwritten on regeneration\n\n"
        ));

        // Collection mode: utilities live in the fixed `jst.helpers`
        // package (see helpers_content_for) instead of being inlined per file.
        let shared = options.helpers.is_some();

        // The validation interface generated classes conform to. Shared mode
        // uses the canonical name from `jst.helpers`; inline mode mangles it
        // with the file's root type name (like the JSI classes) because
        // top-level declarations are package-scoped on the JVM and many
        // generated files may be compiled as one module.
        let iface = if shared {
            "_JstValidatable".to_string()
        } else {
            format!("_{pascal}JstValidatable")
        };
        let gopts = GenOptions {
            iface: &iface,
            mutable: options.mutable,
        };

        // Emit body first so we can scan for needed imports.
        // All $defs type names are prefixed with the root pascal name so that
        // hundreds of generated files can be compiled into a single Kotlin
        // module without top-level name collisions (e.g. `Foo` in many files).
        let mut counter = 0usize;
        let mut body = String::new();
        for def in &converted.defs {
            let safe_name = sanitize_kotlin_name(&def.name, &pascal);
            body.push_str(&emit_definition(&safe_name, &def.schema, &converted.defs, &pascal, &mut counter, &gopts));
            body.push_str("\n\n");
        }
        body.push_str(&emit_definition(
            &pascal,
            &converted.root,
            &converted.defs,
            &pascal,
            &mut counter,
            &gopts,
        ));
        body.push('\n');

        // Determine which imports are actually needed
        let needs_interpreter = body.contains("_jsiValidate(");
        let needs_eq = body.contains("_jsiEq(") || needs_interpreter;
        let needs_lenient = body.contains("_lenientJson");
        let needs_canonicalize = body.contains("_canonicalize(");
        // Helpers inlined into this file (never in shared mode) pull in
        // kotlinx.serialization.json types beyond what the body itself uses.
        let inline_eq = needs_eq && !shared;
        let inline_canonicalize = needs_canonicalize && !shared;
        let needs_serial_name = body.contains("@SerialName(");
        let needs_json_element = body.contains("JsonElement") || inline_eq;
        let needs_json_object = body.contains("JsonObject") || inline_canonicalize || inline_eq;
        let needs_json_primitive = body.contains("JsonPrimitive")
            || body.contains("jsonPrimitive")
            || body.contains("JsonNull")
            || inline_eq;
        let needs_json_array = body.contains("JsonArray") || body.contains("jsonArray") || inline_eq;
        let needs_kserializer = body.contains("KSerializer");
        let needs_json_content = body.contains("JsonContentPolymorphicSerializer")
            || body.contains("jsonObject");
        let needs_decode_from_element = body.contains("decodeFromJsonElement<");
        // validate()/toValidatedJson() round-trip through the type's own
        // serializer via the reified StringFormat extensions.
        let needs_validatable = body.contains("JstValidatable");
        let needs_encode_to_element = body.contains(".encodeToJsonElement(");

        if needs_serial_name {
            out.push_str("import kotlinx.serialization.SerialName\n");
        }
        out.push_str("import kotlinx.serialization.Serializable\n");
        if needs_validatable {
            out.push_str("import kotlinx.serialization.decodeFromString\n");
            out.push_str("import kotlinx.serialization.encodeToString\n");
        }
        if needs_kserializer {
            out.push_str("import kotlinx.serialization.KSerializer\n");
            out.push_str("import kotlinx.serialization.descriptors.SerialDescriptor\n");
            out.push_str("import kotlinx.serialization.encoding.Decoder\n");
            out.push_str("import kotlinx.serialization.encoding.Encoder\n");
        }
        if needs_json_element {
            out.push_str("import kotlinx.serialization.json.JsonElement\n");
        }
        if needs_json_object || needs_json_content {
            out.push_str("import kotlinx.serialization.json.JsonObject\n");
            out.push_str("import kotlinx.serialization.json.jsonObject\n");
        }
        if needs_json_primitive {
            out.push_str("import kotlinx.serialization.json.JsonPrimitive\n");
            out.push_str("import kotlinx.serialization.json.JsonNull\n");
            out.push_str("import kotlinx.serialization.json.jsonPrimitive\n");
            out.push_str("import kotlinx.serialization.json.intOrNull\n");
            out.push_str("import kotlinx.serialization.json.longOrNull\n");
            out.push_str("import kotlinx.serialization.json.doubleOrNull\n");
            out.push_str("import kotlinx.serialization.json.booleanOrNull\n");
            out.push_str("import kotlinx.serialization.json.contentOrNull\n");
        }
        if needs_json_array {
            out.push_str("import kotlinx.serialization.json.JsonArray\n");
            out.push_str("import kotlinx.serialization.json.jsonArray\n");
        }
        if needs_decode_from_element {
            out.push_str("import kotlinx.serialization.json.decodeFromJsonElement\n");
        }
        if needs_encode_to_element {
            out.push_str("import kotlinx.serialization.json.encodeToJsonElement\n");
        }
        let mut needs = HelperSet::default();
        if shared {
            if needs_validatable {
                needs.insert("validatable");
                out.push_str("import jst.helpers._JstValidatable\n");
            }
            // Reference helpers declared once in the companion file's fixed
            // `jst.helpers` package (canonical names — no per-file mangling).
            if needs_canonicalize {
                needs.insert("canonicalize");
                out.push_str("import jst.helpers._canonicalize\n");
            }
            if body.contains("_jsiEq(") {
                needs.insert("jsi_eq");
                out.push_str("import jst.helpers._jsiEq\n");
            }
            if needs_interpreter {
                needs.insert("jsi");
                out.push_str("import jst.helpers._jsiValidate\n");
            }
            if needs_lenient {
                needs.insert("lenient_json");
                out.push_str("import jst.helpers._lenientJson\n");
            }
        }
        out.push('\n');

        // Emit helper functions (inline mode only)
        if !shared {
            if needs_validatable {
                out.push_str(&VALIDATABLE_KT.replace("_JstValidatable", &iface));
                out.push('\n');
            }
            if needs_canonicalize {
                out.push_str(CANONICALIZE_KT);
                out.push('\n');
            }
            if needs_lenient {
                out.push_str(LENIENT_JSON_KT);
                out.push('\n');
            }
            if needs_eq {
                out.push_str(EQ_HELPER_KT);
                out.push_str("\n\n");
            }
            if needs_interpreter {
                // Top-level classes are package-scoped on the JVM even when
                // `private`, so mangle the helper class names with the file's
                // root type name to keep the single-module batch compile happy.
                let helper = JSI_HELPER_KT
                    .replace("_JsiAnn", &format!("_{pascal}JsiAnn"))
                    .replace("_JsiV", &format!("_{pascal}JsiV"));
                out.push_str(&helper);
                out.push_str("\n\n");
            }
        }

        out.push_str(&body);
        (out, needs)
    }
}

/// Rewrite top-level `private` declarations to `internal` so the shared
/// helpers file (fixed `jst.helpers` package) is visible from generated
/// schema files compiled in the same module. Members inside classes are
/// indented and left untouched.
fn internalize(src: &str) -> String {
    let mut out: String = src
        .lines()
        .map(|l| {
            if let Some(rest) = l.strip_prefix("private ") {
                format!("internal {rest}\n")
            } else {
                format!("{l}\n")
            }
        })
        .collect();
    if !src.ends_with('\n') {
        out.pop();
    }
    out
}

/// Interface implemented by generated data/wrapper classes. `validate()`
/// re-runs the schema checks by round-tripping the value through its own
/// serializer (deserialize is where all generated validation lives).
///
/// Kept public on purpose: generated classes are public and Kotlin forbids a
/// public class from exposing an internal/private supertype. The leading
/// underscore matches the JSI helper convention so inline mode can mangle it
/// per file (`_JstValidatable` → `_{Pascal}JstValidatable`).
const VALIDATABLE_KT: &str = concat!(
    "/** Implemented by generated types. validate() re-runs schema validation by\n",
    " *  round-tripping this value through its serializer; it must be called\n",
    " *  explicitly (construction and copy() never validate). */\n",
    "interface _JstValidatable {\n",
    "    fun validate()\n",
    "    fun toValidatedJson(): String\n",
    "}\n",
);

/// Per-file generation options threaded through the definition emitters.
struct GenOptions<'a> {
    /// Name of the validation interface as visible from this file.
    iface: &'a str,
    /// Emit `var` instead of `val` for stored properties.
    mutable: bool,
}

impl GenOptions<'_> {
    fn val_kw(&self) -> &'static str {
        if self.mutable { "var" } else { "val" }
    }
}

/// The `validate()`/`toValidatedJson()` members every generated class gets.
/// CRITICAL: deserialize constructs instances via the plain constructor, so
/// constructors/init blocks must never call validate() — the round-trip
/// would recurse infinitely. validate() is explicit-call only.
fn validate_members(name: &str) -> String {
    format!(
        concat!(
            "    override fun validate() {{ kotlinx.serialization.json.Json.decodeFromString<{name}>(kotlinx.serialization.json.Json.encodeToString(this)) }}\n",
            "    override fun toValidatedJson(): String {{ validate(); return kotlinx.serialization.json.Json.encodeToString(this) }}\n",
        ),
        name = name
    )
}

/// Canonical JSON string for uniqueItems comparison (object keys sorted).
const CANONICALIZE_KT: &str = concat!(
    "private fun _canonicalize(el: JsonElement): String = when (el) {\n",
    "    is JsonObject -> \"{\" + el.entries.sortedBy { it.key }.joinToString(\",\") { \"\\\"${it.key}\\\":${_canonicalize(it.value)}\" } + \"}\"\n",
    "    is JsonArray -> \"[\" + el.joinToString(\",\") { _canonicalize(it) } + \"]\"\n",
    "    else -> el.toString()\n",
    "}\n",
);

/// Lenient Json instance used when delegating validation to a referenced
/// type's serializer.
const LENIENT_JSON_KT: &str =
    "private val _lenientJson = kotlinx.serialization.json.Json { ignoreUnknownKeys = true }\n";

/// JSON-value equality per JSON Schema: numbers compare mathematically
/// (1 == 1.0) but true != 1 and "1" != 1. Exact content comparison is tried
/// first so big integers beyond double precision still compare correctly.
const EQ_HELPER_KT: &str = include_str!("jsi_eq.kt");

/// Self-contained draft 2020-12 validator with annotation tracking, used for
/// schemas routed to SchemaIr::Interpreted (unevaluatedProperties/Items,
/// $dynamicRef/$dynamicAnchor, $anchor, nested $id scopes, remote $refs).
/// Kotlin port of the JSI_HELPER reference implementation in zod.rs.
const JSI_HELPER_KT: &str = include_str!("jsi_validator.kt");

// ── Kotlin string escaping ───────────────────────────────────────────────────

fn escape_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => vec!['\\', '"'],
            '\\' => vec!['\\', '\\'],
            '\n' => vec!['\\', 'n'],
            '\r' => vec!['\\', 'r'],
            '\t' => vec!['\\', 't'],
            '$' => vec!['\\', '$'],
            c if c.is_control() => {
                format!("\\u{:04X}", c as u32).chars().collect()
            }
            other => vec![other],
        })
        .collect()
}

/// Translate ECMAScript-style Unicode property escapes (e.g. `\\p{Letter}`)
/// into the short general-category forms java.util.regex understands (`\\p{L}`).
fn translate_pattern(p: &str) -> String {
    const MAP: &[(&str, &str)] = &[
        ("Letter", "L"), ("Lowercase_Letter", "Ll"), ("Uppercase_Letter", "Lu"),
        ("Titlecase_Letter", "Lt"), ("Modifier_Letter", "Lm"), ("Other_Letter", "Lo"),
        ("Mark", "M"), ("Nonspacing_Mark", "Mn"), ("Spacing_Mark", "Mc"), ("Enclosing_Mark", "Me"),
        ("Number", "N"), ("Decimal_Number", "Nd"), ("digit", "Nd"), ("Letter_Number", "Nl"),
        ("Other_Number", "No"), ("Punctuation", "P"), ("Connector_Punctuation", "Pc"),
        ("Dash_Punctuation", "Pd"), ("Open_Punctuation", "Ps"), ("Close_Punctuation", "Pe"),
        ("Initial_Punctuation", "Pi"), ("Final_Punctuation", "Pf"), ("Other_Punctuation", "Po"),
        ("Symbol", "S"), ("Math_Symbol", "Sm"), ("Currency_Symbol", "Sc"),
        ("Modifier_Symbol", "Sk"), ("Other_Symbol", "So"),
        ("Separator", "Z"), ("Space_Separator", "Zs"), ("Line_Separator", "Zl"),
        ("Paragraph_Separator", "Zp"), ("Other", "C"), ("Control", "Cc"), ("Format", "Cf"),
        ("Surrogate", "Cs"), ("Private_Use", "Co"), ("Unassigned", "Cn"),
    ];
    if !p.contains("\\p{") && !p.contains("\\P{") {
        return p.to_string();
    }
    let chars: Vec<char> = p.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    while i < chars.len() {
        if i + 3 < chars.len()
            && chars[i] == '\\'
            && (chars[i + 1] == 'p' || chars[i + 1] == 'P')
            && chars[i + 2] == '{'
        {
            if let Some(close_rel) = chars[i + 3..].iter().position(|&c| c == '}') {
                let close = i + 3 + close_rel;
                let name: String = chars[i + 3..close].iter().collect();
                if let Some((_, short)) = MAP.iter().find(|(long, _)| *long == name) {
                    out.push(chars[i]);
                    out.push(chars[i + 1]);
                    out.push('{');
                    out.push_str(short);
                    out.push('}');
                    i = close + 1;
                    continue;
                }
            }
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

// ── Name sanitization ───────────────────────────────────────────────────────

const KOTLIN_RESERVED_TYPES: &[&str] = &[
    "Int", "Long", "Short", "Byte", "Double", "Float", "Boolean", "Char",
    "String", "Unit", "Nothing", "Any", "Number",
    "Array", "List", "Map", "Set", "Pair", "Triple",
    "Comparable", "Enum", "Error", "Exception",
    "Result", "Sequence",
];

/// Sanitize a `$defs` type name and prefix it with the root type's pascal
/// name so definitions from different generated files never collide when
/// compiled together as one module. Names that sanitize to nothing (e.g. a
/// `$defs` key of "") become `{prefix}AnonymousDef`.
fn sanitize_kotlin_name(name: &str, prefix: &str) -> String {
    let mut cleaned: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if cleaned.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        cleaned.insert(0, 'N');
    }
    if cleaned.is_empty() {
        cleaned = "AnonymousDef".to_string();
    } else if KOTLIN_RESERVED_TYPES.contains(&cleaned.as_str()) {
        cleaned.push_str("Schema");
    }
    format!("{prefix}{cleaned}")
}

// ── Definition dispatch ─────────────────────────────────────────────────────

fn emit_definition(name: &str, ir: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize, gopts: &GenOptions) -> String {
    match ir {
        SchemaIr::Object(obj) => {
            let needs_custom = matches!(obj.additional_properties, AdditionalProperties::Forbidden | AdditionalProperties::Schema(_))
                || !obj.pattern_properties.is_empty()
                || obj.property_names.is_some()
                || obj.min_properties.is_some()
                || obj.max_properties.is_some()
                || !obj.dependent_schemas.is_empty()
                || !obj.dependent_required.is_empty()
                || obj.fields.values().any(|f| !field_fully_typed(&f.schema))
                || obj.fields.iter().any(|(_, f)| !f.required);
            if needs_custom {
                emit_wrapper(name, ir, defs, prefix, counter, gopts)
            } else {
                emit_data_class(name, obj, defs, prefix, gopts)
            }
        }
        // Enum classes are inherently valid (every constructible value is a
        // member of the schema's enum), so they skip the JstValidatable
        // interface entirely.
        SchemaIr::Enum(cases) if !cases.is_empty() => emit_enum_class(name, cases),
        SchemaIr::Enum(_) => emit_never_class(name, counter, gopts), // empty enum
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => {
            emit_definition(name, inner, defs, prefix, counter, gopts)
        }
        SchemaIr::Nullable(inner) => {
            // For nullable, emit the inner as a separate type and alias
            if matches!(inner.as_ref(), SchemaIr::Object(_)) {
                emit_definition(name, inner, defs, prefix, counter, gopts)
            } else {
                emit_wrapper(name, ir, defs, prefix, counter, gopts)
            }
        }
        SchemaIr::Ref(ref_name) => {
            let safe = sanitize_kotlin_name(ref_name, prefix);
            format!("typealias {name} = {safe}")
        }
        _ => emit_wrapper(name, ir, defs, prefix, counter, gopts),
    }
}

/// True when the Kotlin type produced by `kotlin_type` fully enforces this
/// schema on its own (so a plain `@Serializable data class` field suffices).
/// Anything with value constraints, inline enums/literals, nested inline
/// objects, tuples, unions etc. needs the wrapper-serializer path instead.
fn field_fully_typed(ir: &SchemaIr) -> bool {
    match ir {
        SchemaIr::Any | SchemaIr::Unknown | SchemaIr::Boolean => true,
        SchemaIr::String(c) => {
            c.min_length.is_none() && c.max_length.is_none() && c.pattern.is_none()
        }
        SchemaIr::Ref(_) | SchemaIr::Lazy(_) => true,
        SchemaIr::Array(arr) => {
            arr.min_items.is_none()
                && arr.max_items.is_none()
                && !arr.unique_items
                && arr.contains.is_none()
                && field_fully_typed(&arr.items)
        }
        SchemaIr::Optional(inner)
        | SchemaIr::Nullable(inner)
        | SchemaIr::Describe(inner, _)
        | SchemaIr::Default(inner, _) => field_fully_typed(inner),
        // Int/Double fields reject 1.0-style integers or big values oddly, and
        // constrained numbers lose their bounds — keep only if unconstrained.
        SchemaIr::Integer(c) | SchemaIr::Number(c) => {
            c.minimum.is_none()
                && c.maximum.is_none()
                && c.exclusive_minimum.is_none()
                && c.exclusive_maximum.is_none()
                && c.multiple_of.is_none()
        }
        _ => false,
    }
}

// ── Object data class ───────────────────────────────────────────────────────

fn emit_data_class(name: &str, obj: &ObjectSchema, defs: &[DefEntry], prefix: &str, gopts: &GenOptions) -> String {
    let mut lines = vec!["@Serializable".to_string()];
    let vkw = gopts.val_kw();

    if obj.fields.is_empty() {
        lines.push(format!("data class {name}("));
        lines.push(format!("    {vkw} placeholder: Unit = Unit"));
    } else {
        lines.push(format!("data class {name}("));

        let fields: Vec<String> = obj
            .fields
            .iter()
            .map(|(k, f)| {
                let kt_name = to_camel_case(k);
                let kt_type = kotlin_type(&f.schema, defs, prefix);

                let type_str = if f.required {
                    kt_type
                } else {
                    format!("{kt_type}?")
                };

                let serial_name = if kt_name != *k {
                    format!("    @SerialName(\"{}\")\n", escape_string(k))
                } else {
                    String::new()
                };

                let default = if !f.required { " = null" } else { "" };

                format!("{serial_name}    {vkw} {kt_name}: {type_str}{default}")
            })
            .collect();

        lines.push(fields.join(",\n"));
    }

    lines.push(format!(") : {} {{", gopts.iface));
    lines.push(validate_members(name).trim_end().to_string());
    lines.push("}".to_string());

    lines.join("\n")
}

// ── Enum class ──────────────────────────────────────────────────────────────

fn emit_enum_class(name: &str, cases: &[String]) -> String {
    let mut lines = vec!["@Serializable".to_string()];
    lines.push(format!("enum class {name} {{"));
    let mut seen: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let entries: Vec<String> = cases
        .iter()
        .map(|c| {
            let mut kt_name: String = c.chars()
                .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_' || *ch == '-')
                .collect::<String>()
                .to_uppercase()
                .replace('-', "_");
            if kt_name.is_empty() {
                kt_name = "VALUE".to_string();
            }
            // Deduplicate
            let count = seen.entry(kt_name.clone()).or_insert(0);
            *count += 1;
            if *count > 1 {
                kt_name = format!("{kt_name}_{count}");
            }
            // Always use @SerialName for the raw JSON value
            format!(
                "    @SerialName(\"{}\") {}",
                escape_string(c),
                kt_name
            )
        })
        .collect();
    lines.push(entries.join(",\n"));
    lines.push("}".to_string());
    lines.join("\n")
}

// ── Wrapper class with custom serializer ────────────────────────────────────

fn emit_wrapper(name: &str, ir: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize, gopts: &GenOptions) -> String {
    let inner = unwrap_modifiers(ir);
    let is_nullable = matches!(ir, SchemaIr::Nullable(_));

    *counter += 1;
    let ser_name = format!("{name}Ser");

    let validation = emit_validation(inner, defs, prefix, counter);

    let mut out = String::new();

    out.push_str(&format!(
        "private object {ser_name} : KSerializer<{name}> {{\n"
    ));
    out.push_str(&format!(
        "    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor\n"
    ));
    out.push_str(&format!(
        "    override fun deserialize(decoder: Decoder): {name} {{\n"
    ));
    out.push_str(
        "        val el = decoder.decodeSerializableValue(JsonElement.serializer())\n",
    );
    if is_nullable {
        out.push_str(&format!("        if (el is JsonNull) return {name}(el)\n"));
    }
    out.push_str(&validation);
    out.push_str(&format!("        return {name}(el)\n"));
    out.push_str("    }\n");
    out.push_str(&format!(
        "    override fun serialize(encoder: Encoder, value: {name}) {{\n"
    ));
    out.push_str(
        "        encoder.encodeSerializableValue(JsonElement.serializer(), value.element)\n",
    );
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "@Serializable(with = {ser_name}::class)\n"
    ));
    out.push_str(&format!(
        "class {name}({vkw} element: JsonElement) : {iface} {{\n",
        vkw = gopts.val_kw(),
        iface = gopts.iface
    ));
    out.push_str(&validate_members(name));
    if let SchemaIr::Object(obj) = inner {
        if !obj.fields.is_empty() {
            out.push_str(&emit_companion_invoke(name, obj, defs, prefix));
        }
    }
    out.push('}');

    out
}

/// Typed construction for object-shaped wrapper classes: a companion
/// `operator fun invoke` mirroring the schema's declared properties, so
/// callers can write `OrderItem(id = "a", quantity = 1)` instead of building
/// a JsonElement by hand. Construction never validates (call validate()).
///
/// A companion invoke — rather than a secondary constructor — avoids JVM
/// platform-declaration clashes with the primary `(JsonElement)` constructor
/// (e.g. a lone field typed JsonElement?), and Kotlin resolves `Name(args)`
/// against constructors first, so the serializer's `Name(el)` call is safe.
fn emit_companion_invoke(name: &str, obj: &ObjectSchema, defs: &[DefEntry], prefix: &str) -> String {
    let mut seen: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let mut params: Vec<String> = Vec::new();
    let mut puts: Vec<String> = Vec::new();

    for (k, f) in &obj.fields {
        // Distinct JSON keys can camelCase to the same parameter name
        // (e.g. "foo\nbar" and "foo\"bar") — deduplicate like enum entries.
        let mut p = to_camel_case(k);
        let count = seen.entry(p.clone()).or_insert(0);
        *count += 1;
        if *count > 1 {
            let n = *count;
            p = if p.starts_with('`') {
                format!("`{}{}`", p.trim_matches('`'), n)
            } else {
                format!("{p}{n}")
            };
        }
        let t = kotlin_type(&f.schema, defs, prefix);
        let key = escape_string(k);

        if f.required {
            params.push(format!("            {p}: {t}"));
            if t.starts_with("Nothing") {
                // Literal-null / never fields: no runtime serializer needed.
                puts.push(format!(
                    "            put(\"{key}\", kotlinx.serialization.json.JsonNull)"
                ));
            } else {
                puts.push(format!(
                    "            put(\"{key}\", kotlinx.serialization.json.Json.encodeToJsonElement({p}))"
                ));
            }
        } else {
            let opt_t = if t.ends_with('?') { t.clone() } else { format!("{t}?") };
            params.push(format!("            {p}: {opt_t} = null"));
            if !t.starts_with("Nothing") {
                puts.push(format!(
                    "            if ({p} != null) put(\"{key}\", kotlinx.serialization.json.Json.encodeToJsonElement({p}))"
                ));
            }
        }
    }

    format!(
        "    companion object {{\n        operator fun invoke(\n{params},\n        ): {name} = {name}(kotlinx.serialization.json.buildJsonObject {{\n{puts}\n        }})\n    }}\n",
        params = params.join(",\n"),
        puts = puts.join("\n"),
    )
}

fn unwrap_modifiers(ir: &SchemaIr) -> &SchemaIr {
    match ir {
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Nullable(inner) => {
            unwrap_modifiers(inner)
        }
        _ => ir,
    }
}

// ── Validation code generation ──────────────────────────────────────────────

fn emit_validation(ir: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize) -> String {
    match ir {
        SchemaIr::Interpreted { schema, remotes } => {
            let schema_json =
                serde_json::to_string(schema).unwrap_or_else(|_| "true".to_string());
            let remotes_json = {
                let map: serde_json::Map<String, serde_json::Value> = remotes
                    .iter()
                    .map(|(k, v)| (k.clone(), v.clone()))
                    .collect();
                serde_json::to_string(&serde_json::Value::Object(map))
                    .unwrap_or_else(|_| "{}".to_string())
            };
            format!(
                "        val _s = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\")\n        val _r = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\") as JsonObject\n        require(_jsiValidate(_s, _r, el)) {{ \"does not match schema\" }}\n",
                escape_string(&schema_json),
                escape_string(&remotes_json)
            )
        }
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Optional(inner) => {
            emit_validation(inner, defs, prefix, counter)
        }
        SchemaIr::Nullable(inner) => {
            let v = emit_validation(inner, defs, prefix, counter);
            if v.is_empty() {
                String::new()
            } else {
                format!(
                    "        if (el !is JsonNull) {{\n    {}\n        }}\n",
                    v.trim_end().replace('\n', "\n    ")
                )
            }
        }
        SchemaIr::Enum(cases) => {
            let allowed: Vec<String> = cases
                .iter()
                .map(|c| format!("\"{}\"", escape_string(c)))
                .collect();
            format!(
                "        require(el is JsonPrimitive && el.isString && el.content in setOf<String>({})) {{ \"must be one of the allowed values\" }}\n",
                allowed.join(", ")
            )
        }
        SchemaIr::Integer(c) => {
            let mut checks = Vec::new();
            checks.push(
                "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == null) { \"must be an integer, not string or boolean\" }"
                    .to_string(),
            );
            checks.push(
                "        val v = (el as JsonPrimitive).longOrNull ?: (el as JsonPrimitive).doubleOrNull?.let { if (it == it.toLong().toDouble()) it.toLong() else null } ?: error(\"must be an integer\")"
                    .to_string(),
            );
            emit_number_checks(&mut checks, c, "v", true);
            checks.join("\n") + "\n"
        }
        SchemaIr::Number(c) => {
            let mut checks = Vec::new();
            checks.push(
                "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == null) { \"must be a number, not string or boolean\" }"
                    .to_string(),
            );
            checks.push(
                "        val v = (el as JsonPrimitive).doubleOrNull ?: error(\"must be a number\")"
                    .to_string(),
            );
            emit_number_checks(&mut checks, c, "v", false);
            checks.join("\n") + "\n"
        }
        SchemaIr::Boolean => {
            "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull != null) { \"must be a boolean\" }\n"
                .to_string()
        }
        SchemaIr::String(c) => {
            let mut checks = Vec::new();
            checks.push(
                "        require(el is JsonPrimitive && el.isString) { \"must be a string\" }"
                    .to_string(),
            );
            checks.push("        val v = el.content".to_string());
            if let Some(min) = c.min_length {
                checks.push(format!("        require(v.codePointCount(0, v.length) >= {min}) {{ \"minLength\" }}"));
            }
            if let Some(max) = c.max_length {
                checks.push(format!("        require(v.codePointCount(0, v.length) <= {max}) {{ \"maxLength\" }}"));
            }
            if let Some(ref pat) = c.pattern {
                checks.push(format!(
                    "        require(Regex(\"{}\").containsMatchIn(v)) {{ \"pattern\" }}",
                    escape_string(&translate_pattern(pat))
                ));
            }
            checks.join("\n") + "\n"
        }
        SchemaIr::Null => {
            "        require(el is JsonNull) { \"must be null\" }\n".to_string()
        }
        SchemaIr::Any | SchemaIr::Unknown => String::new(), // accept anything
        SchemaIr::Never => {
            "        error(\"schema rejects all values\")\n".to_string()
        }
        SchemaIr::Literal(lit) => emit_literal_check(lit),
        SchemaIr::ConstEqual(val) => {
            let json_str = serde_json::to_string(val).unwrap_or_else(|_| "null".to_string());
            let escaped = escape_string(&json_str);
            format!(
                "        val expected = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\")\n        require(_jsiEq(el, expected)) {{ \"must equal const value\" }}\n",
                escaped
            )
        }
        SchemaIr::MixedEnum(lits) => {
            let checks: Vec<String> = lits.iter().map(|l| emit_literal_match(l)).collect();
            let condition = checks.join(" || ");
            format!(
                "        require({condition}) {{ \"must be one of the allowed values\" }}\n"
            )
        }
        SchemaIr::ComplexEnum(vals) => {
            let json_str = serde_json::to_string(vals).unwrap_or_else(|_| "[]".to_string());
            let escaped = escape_string(&json_str);
            format!(
                "        val allowed = kotlinx.serialization.json.Json.parseToJsonElement(\"{escaped}\") as JsonArray\n        require(allowed.any {{ _jsiEq(el, it) }}) {{ \"must be one of the allowed values\" }}\n"
            )
        }
        SchemaIr::Array(arr) => emit_array_validation(arr, defs, prefix, counter),
        SchemaIr::Tuple(tuple) => emit_tuple_validation(tuple, defs, prefix, counter),
        SchemaIr::TypeGuarded(guards) => emit_type_guarded_validation(guards, defs, prefix, counter),
        SchemaIr::Not { base: _, not_schema } => {
            let not_check = emit_not_check(not_schema, defs, prefix, counter);
            format!("{not_check}")
        }
        SchemaIr::Conditional { base: _, if_schema, then_schema, else_schema } => {
            emit_conditional_check(if_schema, then_schema.as_deref(), else_schema.as_deref(), defs, prefix, counter)
        }
        SchemaIr::Union(members) if members.len() > 1 => {
            emit_union_check(members, defs, prefix, counter, false)
        }
        SchemaIr::ExclusiveUnion(members) if members.len() > 1 => {
            emit_union_check(members, defs, prefix, counter, true)
        }
        SchemaIr::Intersection(members) if members.len() == 1 => {
            emit_validation(&members[0], defs, prefix, counter)
        }
        SchemaIr::Intersection(members) if members.len() > 1 => {
            // Wrap each member in `run { }` so local vals (v, obj, arr, known…)
            // declared by one member's checks don't conflict with the next.
            let mut checks = String::new();
            for member in members {
                let v = emit_validation(member, defs, prefix, counter);
                if v.is_empty() {
                    continue;
                }
                checks.push_str(&format!("        run {{\n    {}\n        }}\n", v.trim_end().replace('\n', "\n    ")));
            }
            checks
        }
        SchemaIr::Record(rec) => {
            let mut checks = String::new();
            checks.push_str("        require(el is JsonObject) { \"must be an object\" }\n");
            if !matches!(rec.value.as_ref(), SchemaIr::Any | SchemaIr::Unknown) {
                // Validate each value
                let val_check = emit_inline_check(&rec.value, "v", defs, prefix);
                if !val_check.is_empty() {
                    checks.push_str(&format!(
                        "        for ((_, v) in el.jsonObject) {{ {} }}\n",
                        val_check
                    ));
                }
            }
            checks
        }
        SchemaIr::Object(obj) => {
            let mut checks = Vec::new();
            checks.push("        require(el is JsonObject) { \"must be an object\" }".to_string());
            checks.push("        val obj = el.jsonObject".to_string());
            for (k, f) in &obj.fields {
                if f.required {
                    checks.push(format!(
                        "        require(\"{}\" in obj) {{ \"required: {}\" }}",
                        escape_string(k), escape_string(k)
                    ));
                }
                let field_check = emit_inline_check(&f.schema, &format!("obj[\"{}\"]!!", escape_string(k)), defs, prefix);
                if !field_check.is_empty() && !matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) {
                    checks.push(format!(
                        "        if (\"{}\" in obj) {{ {} }}",
                        escape_string(k), field_check
                    ));
                }
            }
            if let Some(min) = obj.min_properties {
                checks.push(format!("        require(obj.size >= {min}) {{ \"minProperties\" }}"));
            }
            if let Some(max) = obj.max_properties {
                checks.push(format!("        require(obj.size <= {max}) {{ \"maxProperties\" }}"));
            }
            // patternProperties + additionalProperties interaction
            if !obj.pattern_properties.is_empty() {
                let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                checks.push("        for ((k, v) in obj) {".to_string());
                checks.push(format!("            var matched = setOf<String>({}).contains(k)", known.join(", ")));
                for (pattern, pp_schema) in &obj.pattern_properties {
                    let pp_check = emit_inline_check(pp_schema, "v", defs, prefix);
                    if !pp_check.is_empty() {
                        checks.push(format!(
                            "            if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true; {} }}",
                            escape_string(&translate_pattern(pattern)), pp_check
                        ));
                    } else {
                        checks.push(format!(
                            "            if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true }}",
                            escape_string(&translate_pattern(pattern))
                        ));
                    }
                }
                if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                    checks.push("            require(matched) { \"unexpected property: $k\" }".to_string());
                } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                    let ap_check = emit_inline_check(ap, "v", defs, prefix);
                    if !ap_check.is_empty() {
                        checks.push(format!("            if (!matched) {{ {} }}", ap_check));
                    }
                }
                checks.push("        }".to_string());
            } else if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                checks.push(format!(
                    "        val known = setOf<String>({})",
                    known.join(", ")
                ));
                checks.push("        for (k in obj.keys) { require(k in known) { \"unexpected property: $k\" } }".to_string());
            } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                let ap_check = emit_inline_check(ap, "v", defs, prefix);
                if !ap_check.is_empty() {
                    checks.push(format!(
                        "        val _known = setOf<String>({})\n        for ((k, v) in obj) {{ if (k !in _known) {{ {} }} }}",
                        known.join(", "), ap_check
                    ));
                }
            }
            // propertyNames
            if let Some(pn) = &obj.property_names {
                emit_property_names_checks(pn, &mut checks, "        ", defs, prefix);
            }
            // dependentRequired
            for (prop, required) in &obj.dependent_required {
                for r in required {
                    checks.push(format!(
                        "        if (\"{}\" in obj) require(\"{}\" in obj) {{ \"dependentRequired\" }}",
                        escape_string(prop), escape_string(r)
                    ));
                }
            }
            // dependentSchemas
            for (prop, dep_schema) in &obj.dependent_schemas {
                let dep_check = emit_match_expression(dep_schema, "el", defs, prefix);
                if dep_check != "true" {
                    checks.push(format!(
                        "        if (\"{}\" in obj) {{ require({}) {{ \"dependentSchemas\" }} }}",
                        escape_string(prop), dep_check
                    ));
                }
            }
            // NOTE: additionalProperties-with-schema is fully handled in the
            // pattern-properties/else-if chain above; emitting it again here
            // used to produce a conflicting duplicate `val _known`.
            if checks.len() <= 2 {
                // Only the require(el is JsonObject) + val obj — no real validation
                "        require(el is JsonObject) { \"must be an object\" }\n".to_string()
            } else {
                checks.join("\n") + "\n"
            }
        }
        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => {
            // Delegate to the referenced type's serializer, which performs the
            // full validation for that definition (data class, enum or wrapper).
            let safe = sanitize_kotlin_name(name, prefix);
            format!("        _lenientJson.decodeFromJsonElement<{safe}>(el)\n")
        }
        _ => String::new(),
    }
}

fn emit_number_checks(checks: &mut Vec<String>, c: &NumberConstraints, var_name: &str, _is_int: bool) {
    if let Some(min) = c.minimum {
        let b = format_kt_number(min);
        checks.push(format!("        require({var_name} >= {b}) {{ \"minimum\" }}"));
    }
    if let Some(max) = c.maximum {
        let b = format_kt_number(max);
        checks.push(format!("        require({var_name} <= {b}) {{ \"maximum\" }}"));
    }
    if let Some(emin) = c.exclusive_minimum {
        let b = format_kt_number(emin);
        checks.push(format!("        require({var_name} > {b}) {{ \"exclusiveMinimum\" }}"));
    }
    if let Some(emax) = c.exclusive_maximum {
        let b = format_kt_number(emax);
        checks.push(format!("        require({var_name} < {b}) {{ \"exclusiveMaximum\" }}"));
    }
    if let Some(mul) = c.multiple_of {
        let b = format_kt_number(mul);
        checks.push(format!(
            "        require(({var_name}.toDouble() / {b}).let {{ it.isFinite() && it == kotlin.math.floor(it) }}) {{ \"multipleOf\" }}"
        ));
    }
}

fn emit_literal_check(lit: &LiteralValue) -> String {
    match lit {
        LiteralValue::Bool(b) => format!(
            "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == {}) {{ \"must be {}\" }}\n",
            b, b
        ),
        LiteralValue::Integer(i) => format!(
            "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == null && (el.longOrNull == {i}L || el.doubleOrNull == {i}.0)) {{ \"must be {i}\" }}\n"
        ),
        LiteralValue::Number(n) => {
            let b = format_kt_number(*n);
            format!(
                "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == null && el.doubleOrNull == {b}) {{ \"must be {b}\" }}\n"
            )
        }
        LiteralValue::String(s) => {
            let escaped = escape_string(s);
            format!(
                "        require(el is JsonPrimitive && el.isString && el.content == \"{escaped}\") {{ \"must be \\\"{escaped}\\\"\" }}\n"
            )
        }
        LiteralValue::Null => {
            "        require(el is JsonNull) { \"must be null\" }\n".to_string()
        }
    }
}

fn emit_literal_match(lit: &LiteralValue) -> String {
    match lit {
        LiteralValue::Bool(b) => format!("(el is JsonPrimitive && !el.isString && el.booleanOrNull == {b})"),
        LiteralValue::Integer(i) => format!(
            "(el is JsonPrimitive && !el.isString && el.booleanOrNull == null && (el.longOrNull == {i}L || el.doubleOrNull == {i}.0))"
        ),
        LiteralValue::Number(n) => {
            let b = format_kt_number(*n);
            format!("(el is JsonPrimitive && !el.isString && el.booleanOrNull == null && el.doubleOrNull == {b})")
        }
        LiteralValue::String(s) => {
            let escaped = escape_string(s);
            format!("(el is JsonPrimitive && el.isString && el.content == \"{escaped}\")")
        }
        LiteralValue::Null => "(el is JsonNull)".to_string(),
    }
}

fn emit_inline_check(ir: &SchemaIr, var_name: &str, defs: &[DefEntry], prefix: &str) -> String {
    match ir {
        SchemaIr::Integer(c) if c.minimum.is_none() && c.maximum.is_none() && c.exclusive_minimum.is_none() && c.exclusive_maximum.is_none() && c.multiple_of.is_none() => {
            format!("require({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull == null && ({var_name}.jsonPrimitive.longOrNull != null || {var_name}.jsonPrimitive.doubleOrNull?.let {{ it == it.toLong().toDouble() }} == true))")
        }
        SchemaIr::Number(c) if c.minimum.is_none() && c.maximum.is_none() && c.exclusive_minimum.is_none() && c.exclusive_maximum.is_none() && c.multiple_of.is_none() => {
            format!("require({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull == null && {var_name}.jsonPrimitive.doubleOrNull != null)")
        }
        SchemaIr::Boolean => format!("require({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull != null)"),
        SchemaIr::String(c) if c.min_length.is_none() && c.max_length.is_none() && c.pattern.is_none() => {
            format!("require({var_name} is JsonPrimitive && {var_name}.jsonPrimitive.isString)")
        }
        SchemaIr::Null => format!("require({var_name} is JsonNull)"),
        SchemaIr::Any | SchemaIr::Unknown => String::new(),
        SchemaIr::Never => format!("error(\"schema rejects all values\")"),
        _ => {
            // For complex schemas, use full validation via el rebinding
            let mut counter = 0usize;
            let validation = emit_validation(ir, defs, prefix, &mut counter);
            if validation.is_empty() {
                return String::new();
            }
            format!("run {{ val el = {var_name}; {} }}", validation.trim())
        }
    }
}

/// Generate a try/catch expression that returns true if `var_name` matches `ir`.
fn emit_match_expression(ir: &SchemaIr, var_name: &str, defs: &[DefEntry], prefix: &str) -> String {
    let mut counter = 0usize;
    let validation = emit_validation(ir, defs, prefix, &mut counter);
    if validation.is_empty() {
        return "true".to_string();
    }
    format!(
        "try {{ val el = {var_name}; {}; true }} catch (_: Exception) {{ false }}",
        validation.trim()
    )
}

fn emit_array_validation(arr: &ArraySchema, defs: &[DefEntry], prefix: &str, _counter: &mut usize) -> String {
    let mut checks = Vec::new();
    checks.push("        require(el is JsonArray) { \"must be an array\" }".to_string());
    checks.push("        val arr = el.jsonArray".to_string());

    if let Some(min) = arr.min_items {
        checks.push(format!("        require(arr.size >= {min}) {{ \"minItems\" }}"));
    }
    if let Some(max) = arr.max_items {
        checks.push(format!("        require(arr.size <= {max}) {{ \"maxItems\" }}"));
    }

    // Item type validation
    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
        let item_check = emit_inline_check(&arr.items, "item", defs, prefix);
        if !item_check.is_empty() {
            checks.push(format!("        for (item in arr) {{ {item_check} }}"));
        }
    }

    if arr.unique_items {
        checks.push(
            "        require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                .to_string(),
        );
    }

    if let Some(contains) = &arr.contains {
        let contains_check = emit_inline_check(&contains.schema, "it", defs, prefix);
        let min = contains.min_contains.unwrap_or(1);
        if !contains_check.is_empty() {
            checks.push(format!(
                "        val matchCount = arr.count {{ try {{ {contains_check}; true }} catch (_: Exception) {{ false }} }}"
            ));
        } else {
            // contains schema is Any — every item matches
            checks.push("        val matchCount = arr.size".to_string());
        }
        checks.push(format!(
            "        require(matchCount >= {min}) {{ \"must contain at least {min} matching items\" }}"
        ));
        if let Some(max) = contains.max_contains {
            checks.push(format!(
                "        require(matchCount <= {max}) {{ \"must contain at most {max} matching items\" }}"
            ));
        }
    }

    checks.join("\n") + "\n"
}

fn emit_tuple_validation(tuple: &TupleSchema, defs: &[DefEntry], prefix: &str, _counter: &mut usize) -> String {
    let mut checks = Vec::new();
    checks.push("        require(el is JsonArray) { \"must be an array\" }".to_string());
    checks.push("        val arr = el.jsonArray".to_string());

    // Prefix item type checks
    for (i, item) in tuple.items.iter().enumerate() {
        if matches!(item, SchemaIr::Any) {
            continue;
        }
        let item_check = emit_inline_check(item, &format!("arr[{i}]"), defs, prefix);
        if !item_check.is_empty() {
            checks.push(format!("        if (arr.size > {i}) {{ {item_check} }}"));
        }
    }

    let prefix_count = tuple.items.len();
    if let Some(rest) = &tuple.rest {
        if !matches!(rest.as_ref(), SchemaIr::Any) {
            let rest_check = emit_inline_check(rest, "arr[i]", defs, prefix);
            if !rest_check.is_empty() {
                checks.push(format!("        for (i in {prefix_count} until arr.size) {{ {rest_check} }}"));
            }
        }
    } else {
        checks.push(format!(
            "        require(arr.size <= {prefix_count}) {{ \"too many items\" }}"
        ));
    }

    if let Some(min) = tuple.min_items {
        checks.push(format!("        require(arr.size >= {min}) {{ \"minItems\" }}"));
    }
    if let Some(max) = tuple.max_items {
        checks.push(format!("        require(arr.size <= {max}) {{ \"maxItems\" }}"));
    }

    if tuple.unique_items {
        checks.push(
            "        require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                .to_string(),
        );
    }

    checks.join("\n") + "\n"
}

fn emit_type_guarded_validation(
    guards: &[(TypeGuard, Box<SchemaIr>)],
    defs: &[DefEntry],
    prefix: &str,
    _counter: &mut usize,
) -> String {
    let mut checks = Vec::new();

    for (guard, schema) in guards {
        match guard {
            TypeGuard::String => {
                if let SchemaIr::String(c) = schema.as_ref() {
                    checks.push("        if (el is JsonPrimitive && el.isString) {".to_string());
                    checks.push("            val v = el.content".to_string());
                    if let Some(min) = c.min_length {
                        checks.push(format!("            require(v.codePointCount(0, v.length) >= {min}) {{ \"minLength\" }}"));
                    }
                    if let Some(max) = c.max_length {
                        checks.push(format!("            require(v.codePointCount(0, v.length) <= {max}) {{ \"maxLength\" }}"));
                    }
                    if let Some(ref pat) = c.pattern {
                        checks.push(format!(
                            "            require(Regex(\"{}\").containsMatchIn(v)) {{ \"pattern\" }}",
                            escape_string(&translate_pattern(pat))
                        ));
                    }
                    checks.push("        }".to_string());
                }
            }
            TypeGuard::Number => {
                let c = match schema.as_ref() {
                    SchemaIr::Number(c) | SchemaIr::Integer(c) => c,
                    _ => continue,
                };
                checks.push("        if (el is JsonPrimitive && !el.isString && el.booleanOrNull == null && el.doubleOrNull != null) {".to_string());
                checks.push("            val v = el.doubleOrNull!!".to_string());
                if let Some(min) = c.minimum {
                    let b = format_kt_number(min);
                    checks.push(format!("            require(v >= {b}) {{ \"minimum\" }}"));
                }
                if let Some(max) = c.maximum {
                    let b = format_kt_number(max);
                    checks.push(format!("            require(v <= {b}) {{ \"maximum\" }}"));
                }
                if let Some(emin) = c.exclusive_minimum {
                    let b = format_kt_number(emin);
                    checks.push(format!("            require(v > {b}) {{ \"exclusiveMinimum\" }}"));
                }
                if let Some(emax) = c.exclusive_maximum {
                    let b = format_kt_number(emax);
                    checks.push(format!("            require(v < {b}) {{ \"exclusiveMaximum\" }}"));
                }
                if let Some(mul) = c.multiple_of {
                    let b = format_kt_number(mul);
                    checks.push(format!(
                        "            require((v / {b}).let {{ it.isFinite() && it == kotlin.math.floor(it) }}) {{ \"multipleOf\" }}"
                    ));
                }
                checks.push("        }".to_string());
            }
            TypeGuard::Object => {
                if let SchemaIr::Object(obj) = schema.as_ref() {
                    checks.push("        if (el is JsonObject) {".to_string());
                    checks.push("            val obj = el.jsonObject".to_string());
                    for (k, f) in &obj.fields {
                        if f.required {
                            checks.push(format!(
                                "            require(\"{}\" in obj) {{ \"required: {}\" }}",
                                escape_string(k), escape_string(k)
                            ));
                        }
                        // Field type validation
                        let field_check = emit_inline_check(&f.schema, &format!("obj[\"{}\"]!!", escape_string(k)), defs, prefix);
                        if !field_check.is_empty() && !matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) {
                            checks.push(format!(
                                "            if (\"{}\" in obj) {{ {} }}",
                                escape_string(k), field_check
                            ));
                        }
                    }
                    if let Some(min) = obj.min_properties {
                        checks.push(format!("            require(obj.size >= {min}) {{ \"minProperties\" }}"));
                    }
                    if let Some(max) = obj.max_properties {
                        checks.push(format!("            require(obj.size <= {max}) {{ \"maxProperties\" }}"));
                    }
                    // patternProperties + additionalProperties interaction:
                    // additionalProperties applies only to keys not matched by
                    // a named property or any patternProperties regex.
                    if !obj.pattern_properties.is_empty() {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                        checks.push("            for ((k, v) in obj) {".to_string());
                        checks.push(format!("                var matched = setOf<String>({}).contains(k)", known.join(", ")));
                        for (pattern, pp_schema) in &obj.pattern_properties {
                            let pp_check = emit_inline_check(pp_schema, "v", defs, prefix);
                            if !pp_check.is_empty() {
                                checks.push(format!(
                                    "                if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true; {} }}",
                                    escape_string(&translate_pattern(pattern)), pp_check
                                ));
                            } else {
                                checks.push(format!(
                                    "                if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true }}",
                                    escape_string(&translate_pattern(pattern))
                                ));
                            }
                        }
                        if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                            checks.push("                require(matched) { \"unexpected property: $k\" }".to_string());
                        } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                            let ap_check = emit_inline_check(ap, "v", defs, prefix);
                            if !ap_check.is_empty() {
                                checks.push(format!("                if (!matched) {{ {} }}", ap_check));
                            }
                        }
                        checks.push("            }".to_string());
                    } else if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                        checks.push(format!(
                            "            val known = setOf<String>({})",
                            known.join(", ")
                        ));
                        checks.push("            for (k in obj.keys) { require(k in known) { \"unexpected property: $k\" } }".to_string());
                    } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                        let ap_check = emit_inline_check(ap, "v", defs, prefix);
                        if !ap_check.is_empty() {
                            checks.push(format!(
                                "            val _known = setOf<String>({})\n            for ((k, v) in obj) {{ if (k !in _known) {{ {} }} }}",
                                known.join(", "), ap_check
                            ));
                        }
                    }
                    // propertyNames
                    if let Some(pn) = &obj.property_names {
                        emit_property_names_checks(pn, &mut checks, "            ", defs, prefix);
                    }
                    // dependentRequired
                    for (prop, required) in &obj.dependent_required {
                        for r in required {
                            checks.push(format!(
                                "            if (\"{}\" in obj) require(\"{}\" in obj) {{ \"dependentRequired\" }}",
                                escape_string(prop), escape_string(r)
                            ));
                        }
                    }
                    // dependentSchemas
                    for (prop, dep_schema) in &obj.dependent_schemas {
                        let dep_check = emit_match_expression(dep_schema, "el", defs, prefix);
                        if dep_check != "true" {
                            checks.push(format!(
                                "            if (\"{}\" in obj) {{ require({}) {{ \"dependentSchemas\" }} }}",
                                escape_string(prop), dep_check
                            ));
                        }
                    }
                    checks.push("        }".to_string());
                }
                // Record in TypeGuard::Object
                if let SchemaIr::Record(rec) = schema.as_ref() {
                    let val_check = emit_inline_check(&rec.value, "v", defs, prefix);
                    if !val_check.is_empty() {
                        checks.push("        if (el is JsonObject) {".to_string());
                        checks.push(format!("            for ((_, v) in el.jsonObject) {{ {} }}", val_check));
                        checks.push("        }".to_string());
                    }
                }
            }
            TypeGuard::Array => {
                if let SchemaIr::Array(arr) = schema.as_ref() {
                    checks.push("        if (el is JsonArray) {".to_string());
                    checks.push("            val arr = el.jsonArray".to_string());
                    if let Some(min) = arr.min_items {
                        checks.push(format!("            require(arr.size >= {min}) {{ \"minItems\" }}"));
                    }
                    if let Some(max) = arr.max_items {
                        checks.push(format!("            require(arr.size <= {max}) {{ \"maxItems\" }}"));
                    }
                    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
                        let item_check = emit_inline_check(&arr.items, "item", defs, prefix);
                        if !item_check.is_empty() {
                            checks.push(format!("            for (item in arr) {{ {item_check} }}"));
                        }
                    }
                    if arr.unique_items {
                        checks.push(
                            "            require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                                .to_string(),
                        );
                    }
                    // contains in TypeGuard::Array
                    if let Some(contains) = &arr.contains {
                        let match_expr = emit_match_expression(&contains.schema, "it", defs, prefix);
                        let min = contains.min_contains.unwrap_or(1);
                        checks.push(format!(
                            "            val matchCount = arr.count {{ {match_expr} }}"
                        ));
                        checks.push(format!(
                            "            require(matchCount >= {min}) {{ \"must contain at least {min} matching items\" }}"
                        ));
                        if let Some(max) = contains.max_contains {
                            checks.push(format!(
                                "            require(matchCount <= {max}) {{ \"must contain at most {max} matching items\" }}"
                            ));
                        }
                    }
                    checks.push("        }".to_string());
                }
                // Also handle Tuple in Array TypeGuard
                if let SchemaIr::Tuple(tuple) = schema.as_ref() {
                    checks.push("        if (el is JsonArray) {".to_string());
                    checks.push("            val arr = el.jsonArray".to_string());
                    for (i, item) in tuple.items.iter().enumerate() {
                        if matches!(item, SchemaIr::Any) { continue; }
                        let item_check = emit_inline_check(item, &format!("arr[{i}]"), defs, prefix);
                        if !item_check.is_empty() {
                            checks.push(format!("            if (arr.size > {i}) {{ {item_check} }}"));
                        }
                    }
                    let prefix_count = tuple.items.len();
                    if let Some(rest) = &tuple.rest {
                        if !matches!(rest.as_ref(), SchemaIr::Any) {
                            let rest_check = emit_inline_check(rest, "arr[i]", defs, prefix);
                            if !rest_check.is_empty() {
                                checks.push(format!("            for (i in {prefix_count} until arr.size) {{ {rest_check} }}"));
                            }
                        }
                    } else {
                        checks.push(format!(
                            "            require(arr.size <= {prefix_count}) {{ \"too many items\" }}"
                        ));
                    }
                    if let Some(min) = tuple.min_items {
                        checks.push(format!("            require(arr.size >= {min}) {{ \"minItems\" }}"));
                    }
                    if let Some(max) = tuple.max_items {
                        checks.push(format!("            require(arr.size <= {max}) {{ \"maxItems\" }}"));
                    }
                    if tuple.unique_items {
                        checks.push(
                            "            require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                                .to_string(),
                        );
                    }
                    checks.push("        }".to_string());
                }
            }
        }
    }

    if checks.is_empty() {
        String::new()
    } else {
        checks.join("\n") + "\n"
    }
}

fn emit_property_names_checks(pn: &SchemaIr, checks: &mut Vec<String>, indent: &str, defs: &[DefEntry], prefix: &str) {
    let m = emit_match_expression(pn, "JsonPrimitive(k)", defs, prefix);
    if m == "true" {
        return;
    }
    checks.push(format!(
        "{indent}for (k in obj.keys) {{ require({m}) {{ \"propertyNames\" }} }}"
    ));
}

fn emit_not_check(not_schema: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize) -> String {
    let inner_validation = emit_validation(not_schema, defs, prefix, counter);
    if inner_validation.is_empty() {
        // not_schema accepts everything → nothing can pass
        return "        error(\"must not match excluded schema\")\n".to_string();
    }
    format!(
        "        val notMatched = try {{ {}; true }} catch (_: Exception) {{ false }}\n        require(!notMatched) {{ \"must not match excluded schema\" }}\n",
        inner_validation.trim()
    )
}

fn emit_conditional_check(
    if_schema: &SchemaIr,
    then_schema: Option<&SchemaIr>,
    else_schema: Option<&SchemaIr>,
    defs: &[DefEntry],
    prefix: &str,
    counter: &mut usize,
) -> String {
    let if_validation = emit_validation(if_schema, defs, prefix, counter);
    let mut out = String::new();

    out.push_str(&format!(
        "        val ifMatched = try {{ {}; true }} catch (_: Exception) {{ false }}\n",
        if_validation.trim()
    ));

    if let Some(then_s) = then_schema {
        let then_validation = emit_validation(then_s, defs, prefix, counter);
        if !then_validation.is_empty() {
            out.push_str(&format!(
                "        if (ifMatched) {{ {} }}\n",
                then_validation.trim()
            ));
        }
    }
    if let Some(else_s) = else_schema {
        let else_validation = emit_validation(else_s, defs, prefix, counter);
        if !else_validation.is_empty() {
            out.push_str(&format!(
                "        if (!ifMatched) {{ {} }}\n",
                else_validation.trim()
            ));
        }
    }

    out
}

fn emit_union_check(members: &[SchemaIr], defs: &[DefEntry], prefix: &str, counter: &mut usize, exclusive: bool) -> String {
    let mut branch_checks = Vec::new();
    for member in members {
        let validation = emit_validation(member, defs, prefix, counter);
        if validation.is_empty() {
            branch_checks.push("true".to_string());
        } else {
            branch_checks.push(format!(
                "try {{ {}; true }} catch (_: Exception) {{ false }}",
                validation.trim()
            ));
        }
    }

    let mut out = String::new();
    out.push_str("        val branchResults = listOf(\n");
    for (i, check) in branch_checks.iter().enumerate() {
        let comma = if i < branch_checks.len() - 1 { "," } else { "" };
        out.push_str(&format!("            {check}{comma}\n"));
    }
    out.push_str("        )\n");
    out.push_str("        val matchCount = branchResults.count { it }\n");
    if exclusive {
        out.push_str(
            "        require(matchCount == 1) { \"must match exactly one schema, matched $matchCount\" }\n",
        );
    } else {
        out.push_str(
            "        require(matchCount >= 1) { \"must match at least one schema\" }\n",
        );
    }
    out
}

fn emit_never_class(name: &str, counter: &mut usize, gopts: &GenOptions) -> String {
    *counter += 1;
    let ser_name = format!("{name}Ser");
    format!(
        "private object {ser_name} : KSerializer<{name}> {{\n    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor\n    override fun deserialize(decoder: Decoder): {name} {{ decoder.decodeSerializableValue(JsonElement.serializer()); error(\"schema rejects all values\") }}\n    override fun serialize(encoder: Encoder, value: {name}) {{ encoder.encodeSerializableValue(JsonElement.serializer(), value.element) }}\n}}\n\n@Serializable(with = {ser_name}::class)\nclass {name}({vkw} element: JsonElement) : {iface} {{\n{members}}}",
        vkw = gopts.val_kw(),
        iface = gopts.iface,
        members = validate_members(name)
    )
}

// ── Type mapping ────────────────────────────────────────────────────────────

fn kotlin_type(ir: &SchemaIr, defs: &[DefEntry], prefix: &str) -> String {
    match ir {
        SchemaIr::String(_) => "String".to_string(),
        SchemaIr::Number(_) => "Double".to_string(),
        SchemaIr::Integer(_) => "Int".to_string(),
        SchemaIr::Boolean => "Boolean".to_string(),
        SchemaIr::Null => "Nothing?".to_string(),
        // TODO(kotlin-interpreter): validate via embedded spec interpreter
        SchemaIr::Any | SchemaIr::Unknown | SchemaIr::Interpreted { .. } => "JsonElement".to_string(),
        SchemaIr::Never => "Nothing".to_string(),

        SchemaIr::Literal(lit) => match lit {
            LiteralValue::String(_) => "String".to_string(),
            LiteralValue::Number(_) => "Double".to_string(),
            LiteralValue::Integer(_) => "Int".to_string(),
            LiteralValue::Bool(_) => "Boolean".to_string(),
            LiteralValue::Null => "Nothing?".to_string(),
        },

        SchemaIr::ConstEqual(_) | SchemaIr::ComplexEnum(_) => "JsonElement".to_string(),
        SchemaIr::Enum(_) => "String".to_string(),
        SchemaIr::MixedEnum(_) => "JsonElement".to_string(),

        SchemaIr::Array(arr) => format!("List<{}>", kotlin_type(&arr.items, defs, prefix)),
        SchemaIr::Tuple(_) => "List<JsonElement>".to_string(),
        SchemaIr::Object(_) => "JsonObject".to_string(),
        SchemaIr::Record(rec) => format!("Map<String, {}>", kotlin_type(&rec.value, defs, prefix)),

        SchemaIr::Union(members) | SchemaIr::ExclusiveUnion(members) => {
            if members.len() == 2 {
                let non_null: Vec<_> = members
                    .iter()
                    .filter(|m| !matches!(m, SchemaIr::Null))
                    .collect();
                if non_null.len() == 1 {
                    return format!("{}?", kotlin_type(non_null[0], defs, prefix));
                }
            }
            "JsonElement".to_string()
        }

        SchemaIr::Intersection(_) => "JsonElement".to_string(),
        SchemaIr::Nullable(inner) => format!("{}?", kotlin_type(inner, defs, prefix)),
        SchemaIr::Optional(inner) => format!("{}?", kotlin_type(inner, defs, prefix)),
        SchemaIr::Default(inner, _) => kotlin_type(inner, defs, prefix),
        SchemaIr::Describe(inner, _) => kotlin_type(inner, defs, prefix),
        SchemaIr::Not { base, .. } => kotlin_type(base, defs, prefix),
        SchemaIr::Conditional { base, .. } => kotlin_type(base, defs, prefix),
        SchemaIr::TypeGuarded(_) => "JsonElement".to_string(),
        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => sanitize_kotlin_name(name, prefix),
    }
}

fn format_kt_number(n: f64) -> String {
    if n == n.trunc() && n.abs() < 1e15 {
        format!("{}.0", n as i64)
    } else {
        format!("{n}")
    }
}

/// Convert to lowerCamelCase (Kotlin convention).
fn to_camel_case(s: &str) -> String {
    if !s.contains(|c: char| !c.is_ascii_alphanumeric())
        && s.chars().next().is_some_and(|c| c.is_ascii_lowercase())
    {
        let result = s.to_string();
        return if is_kotlin_keyword(&result) {
            format!("`{result}`")
        } else {
            result
        };
    }

    let parts: Vec<&str> = s
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
        .collect();

    if parts.is_empty() {
        return s.to_string();
    }

    let mut result = parts[0].to_lowercase();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }

    if is_kotlin_keyword(&result) {
        format!("`{result}`")
    } else {
        result
    }
}

fn is_kotlin_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "class" | "continue" | "do" | "else" | "false" | "for" | "fun"
            | "if" | "in" | "interface" | "is" | "null" | "object" | "package" | "return"
            | "super" | "this" | "throw" | "true" | "try" | "typealias" | "typeof" | "val"
            | "var" | "when" | "while"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::emit::SharedHelpers;
    use crate::Converter;
    use serde_json::json;

    fn order_item_schema() -> serde_json::Value {
        json!({
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "quantity": {"type": "integer", "minimum": 1}
            },
            "required": ["id", "quantity"],
            "additionalProperties": false
        })
    }

    fn emit_opts(schema: &serde_json::Value, options: &EmitOptions) -> String {
        let converted = Converter::convert(schema).unwrap();
        KotlinEmitter.emit_with_options(&converted, "sample", options)
    }

    #[test]
    fn default_emit_conforms_to_mangled_validatable() {
        let out = emit_opts(&order_item_schema(), &EmitOptions::default());
        // Inline mode: interface declared per file under a mangled name.
        assert!(out.contains("interface _SampleJstValidatable"), "{out}");
        assert!(out.contains("class Sample(val element: JsonElement) : _SampleJstValidatable {"), "{out}");
        assert!(out.contains("override fun validate()"), "{out}");
        assert!(out.contains("override fun toValidatedJson(): String"), "{out}");
        // Typed construction via companion invoke, unvalidated by design.
        assert!(out.contains("operator fun invoke("), "{out}");
        assert!(out.contains("quantity: Int"), "{out}");
        // Immutable by default.
        assert!(!out.contains("var element"), "{out}");
    }

    #[test]
    fn mutable_emit_uses_var_properties() {
        let opts = EmitOptions { mutable: true, ..EmitOptions::default() };
        let wrapper = emit_opts(&order_item_schema(), &opts);
        assert!(wrapper.contains("class Sample(var element: JsonElement)"), "{wrapper}");

        // Fully-typed all-required object → data class path.
        let plain = json!({
            "type": "object",
            "properties": {"id": {"type": "string"}},
            "required": ["id"]
        });
        let dc = emit_opts(&plain, &opts);
        assert!(dc.contains("var id: String"), "{dc}");
        let dc_default = emit_opts(&plain, &EmitOptions::default());
        assert!(dc_default.contains("val id: String"), "{dc_default}");
        assert!(dc_default.contains(") : _SampleJstValidatable {"), "{dc_default}");
    }

    #[test]
    fn shared_mode_imports_canonical_interface_and_reports_need() {
        let converted = Converter::convert(&order_item_schema()).unwrap();
        let options = EmitOptions {
            helpers: Some(SharedHelpers::new("JstHelpers.kt")),
            mutable: false,
        };
        let (out, needs) = KotlinEmitter.emit_collecting(&converted, "sample", &options);
        assert!(needs.contains("validatable"), "{needs:?}");
        assert!(out.contains("import jst.helpers._JstValidatable"), "{out}");
        assert!(out.contains(": _JstValidatable {"), "{out}");
        assert!(!out.contains("interface _JstValidatable"), "{out}");

        let helpers = KotlinEmitter.helpers_content_for(&needs).unwrap();
        assert!(helpers.contains("interface _JstValidatable"), "{helpers}");
        // Public on purpose: generated public classes implement it.
        assert!(!helpers.contains("internal interface _JstValidatable"), "{helpers}");
    }

    #[test]
    fn enums_and_typealiases_skip_validatable() {
        let out = emit_opts(&json!({"enum": ["a", "b"]}), &EmitOptions::default());
        assert!(out.contains("enum class Sample"), "{out}");
        assert!(!out.contains("JstValidatable"), "{out}");
        assert!(!out.contains("import kotlinx.serialization.encodeToString"), "{out}");
    }
}
