use std::collections::HashSet;

use super::{module_header, sanitize_comment_text, EmitOptions, Emitter, HelperSet};
use crate::ir::*;
use crate::util::{to_pascal_case, to_snake_case};

pub struct RustEmitter;

/// JSON-value equality (`_jst_eq`) and canonical stringify (`_jst_canonical`).
const EQ_HELPER_RS: &str = include_str!("eq.rs");
/// Numeric predicates: `_jst_is_integer`, `_jst_multiple_of`.
const NUM_HELPER_RS: &str = include_str!("num.rs");
/// String-format predicates (`_jst_is_email`, `_jst_is_uuid`, ...).
const FORMATS_HELPER_RS: &str = include_str!("formats.rs");
/// Self-contained draft 2020-12 mini-validator (`_jst_jsi_validate`) used for
/// schemas routed to SchemaIr::Interpreted.
const JSI_HELPER_RS: &str = include_str!("jsi_validator.rs");

impl Emitter for RustEmitter {
    fn extension(&self) -> &str {
        "rs"
    }

    fn emit_with_options(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> String {
        self.emit_module(converted, name, options).0
    }

    fn emit_collecting(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> (String, HelperSet) {
        self.emit_module(converted, name, options)
    }

    fn helpers_content_for(&self, needs: &HelperSet) -> Option<String> {
        if needs.is_empty() {
            return None;
        }
        let mut s = String::from(concat!(
            "// Generated by json-schema-transformer — shared runtime helpers\n",
            "// DO NOT EDIT — changes will be overwritten on regeneration\n\n",
        ));
        // The interpreter calls _jst_eq internally, so it drags the equality
        // helper into the shared file even when no module needs it directly.
        if needs.contains("eq") || needs.contains("jsi") {
            s.push_str(EQ_HELPER_RS);
            s.push('\n');
        }
        if needs.contains("num") {
            s.push_str(NUM_HELPER_RS);
            s.push('\n');
        }
        if needs.contains("formats") {
            s.push_str(FORMATS_HELPER_RS);
            s.push('\n');
        }
        if needs.contains("jsi") {
            s.push_str(JSI_HELPER_RS);
            s.push('\n');
        }
        Some(s)
    }

    fn helpers_content(&self) -> Option<String> {
        let mut all = HelperSet::default();
        for n in ["eq", "num", "formats", "jsi"] {
            all.insert(n);
        }
        self.helpers_content_for(&all)
    }

    fn default_helpers_file(&self) -> Option<&'static str> {
        Some("jst_helpers.rs")
    }
}

impl RustEmitter {
    fn emit_module(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> (String, HelperSet) {
        let pascal = root_type_name(name);

        // `options.mutable` is a documented no-op for Rust: generated struct
        // fields are already `pub`, so instances are mutable by construction.
        let _ = options.mutable;

        // All $defs type names are prefixed with the root pascal name so that
        // many generated files can be compiled into one crate as sibling
        // modules without top-level name collisions being confusing, and so
        // that Rust keywords / prelude names can never be produced.
        let mut ctx = Ctx {
            defs: &converted.defs,
            prefix: pascal.clone(),
            extra: Vec::new(),
            used_names: HashSet::new(),
        };
        ctx.used_names.insert(pascal.clone());
        for def in &converted.defs {
            let n = sanitize_rust_name(&def.name, &pascal);
            ctx.used_names.insert(n);
        }

        let mut body = String::new();
        for def in &converted.defs {
            let n = sanitize_rust_name(&def.name, &pascal);
            let code = emit_definition(&n, &def.schema, &mut ctx);
            for extra in std::mem::take(&mut ctx.extra) {
                body.push_str(&extra);
                body.push_str("\n\n");
            }
            body.push_str(&code);
            body.push_str("\n\n");
        }
        let root_code = emit_definition(&pascal, &converted.root, &mut ctx);
        for extra in std::mem::take(&mut ctx.extra) {
            body.push_str(&extra);
            body.push_str("\n\n");
        }
        body.push_str(&root_code);
        body.push('\n');

        let needs_all = detect_needs(&body);
        let shared = options.helpers.is_some();

        let mut out = module_header(name);
        out.push('\n');

        let mut needs = HelperSet::default();
        if let Some(sh) = &options.helpers {
            if !needs_all.is_empty() {
                needs = needs_all.clone();
                // Root-level file → `use super::jst_helpers::*;`; one extra
                // `super::` per directory nesting level.
                let module = sh.file_name.trim_end_matches(".rs");
                out.push_str(&format!(
                    "#[allow(unused_imports)]\nuse {}{}::*;\n\n",
                    "super::".repeat(sh.depth() + 1),
                    module
                ));
            }
        }

        out.push_str(&body);

        // Inline mode: append the needed helper snippets so the module is
        // fully self-contained (symbols are _jst_-prefixed; each generated
        // file is its own module so there is no cross-file collision risk).
        if !shared && !needs_all.is_empty() {
            out.push('\n');
            if needs_all.contains("eq") || needs_all.contains("jsi") {
                out.push_str(EQ_HELPER_RS);
                out.push('\n');
            }
            if needs_all.contains("num") {
                out.push_str(NUM_HELPER_RS);
                out.push('\n');
            }
            if needs_all.contains("formats") {
                out.push_str(FORMATS_HELPER_RS);
                out.push('\n');
            }
            if needs_all.contains("jsi") {
                out.push_str(JSI_HELPER_RS);
                out.push('\n');
            }
        }

        (out, needs)
    }
}

/// Strip double-quoted string literals and doc-comment lines so helper
/// detection cannot false-positive on schema-derived text (a const string or
/// description containing "_jst_jsi_validate(" would otherwise pull the
/// interpreter in as dead code). Generated code never uses raw strings —
/// `esc()` escapes quotes and backslashes — so a simple scanner suffices.
fn strip_schema_text(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    for line in body.lines() {
        if line.trim_start().starts_with("///") {
            continue;
        }
        let mut in_str = false;
        let mut escaped = false;
        for c in line.chars() {
            if in_str {
                if escaped {
                    escaped = false;
                } else if c == '\\' {
                    escaped = true;
                } else if c == '"' {
                    in_str = false;
                    out.push('"');
                }
            } else {
                out.push(c);
                if c == '"' {
                    in_str = true;
                }
            }
        }
        out.push('\n');
    }
    out
}

fn detect_needs(body: &str) -> HelperSet {
    let body = strip_schema_text(body);
    let body = body.as_str();
    let mut needs = HelperSet::default();
    if body.contains("_jst_eq(") || body.contains("_jst_canonical(") {
        needs.insert("eq");
    }
    if body.contains("_jst_is_integer(") || body.contains("_jst_multiple_of(") {
        needs.insert("num");
    }
    const FORMAT_FNS: [&str; 12] = [
        "_jst_is_email(",
        "_jst_is_uri(",
        "_jst_is_uuid(",
        "_jst_is_date_time(",
        "_jst_is_date(",
        "_jst_is_time(",
        "_jst_is_duration(",
        "_jst_is_ip(",
        "_jst_is_ipv4(",
        "_jst_is_ipv6(",
        "_jst_is_hostname(",
        "_jst_is_base64(",
    ];
    if FORMAT_FNS.iter().any(|f| body.contains(f)) {
        needs.insert("formats");
    }
    if body.contains("_jst_jsi_validate(") {
        needs.insert("jsi");
    }
    needs
}

// ── Names & escaping ────────────────────────────────────────────────────────

fn root_type_name(name: &str) -> String {
    let p = to_pascal_case(name);
    if p.is_empty() {
        "Root".to_string()
    } else if p == "Self" {
        // `Self` is the only PascalCase Rust keyword.
        "SelfSchema".to_string()
    } else {
        p
    }
}

/// Sanitize a `$defs` type name and prefix it with the root type's pascal
/// name (mirrors the Kotlin emitter's approach). The non-empty prefix also
/// guarantees the result is never a Rust keyword or prelude type.
fn sanitize_rust_name(name: &str, prefix: &str) -> String {
    let mut cleaned: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if cleaned.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        cleaned.insert(0, 'N');
    }
    if cleaned.is_empty() {
        cleaned = "AnonymousDef".to_string();
    }
    format!("{prefix}{cleaned}")
}

/// Escape a string for use inside a normal Rust string literal.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c == '\u{7f}' => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

/// Format an f64 as a Rust f64 literal (`{:?}` always keeps `.0` / exponent).
fn fmt_f64(n: f64) -> String {
    format!("{n:?}")
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
    "where", "while", "async", "await", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
];

/// Snake-case field identifier for a JSON key, deduplicated within a struct.
/// Keywords become raw identifiers (`r#type`) except the few that cannot be
/// raw (`crate`/`self`/`super`), which get a trailing underscore.
fn field_ident(key: &str, used: &mut HashSet<String>) -> String {
    let mut base = to_snake_case(key);
    if base.is_empty() || base.chars().all(|c| c == '_') {
        base = "field".to_string();
    }
    if base.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        base.insert(0, 'n');
    }
    // Apply the keyword transform BEFORE deduplicating, and dedupe on the
    // FINAL ident: mapping `crate` → `crate_` after the dedupe set was
    // updated would collide with a sibling property literally named
    // `crate_` (two `pub crate_` fields → E0124).
    let base = match base.as_str() {
        "crate" | "self" | "super" => format!("{base}_"),
        b if RUST_KEYWORDS.contains(&b) => format!("r#{base}"),
        _ => base,
    };
    let mut candidate = base.clone();
    let mut i = 1;
    while used.contains(&candidate) {
        i += 1;
        candidate = format!("{base}_{i}");
    }
    used.insert(candidate.clone());
    candidate
}

fn doc_comment(text: &str) -> String {
    // Descriptions are arbitrary schema strings: strip bare CRs (hard rustc
    // error in doc comments) and bidi controls (deny-by-default lint) while
    // keeping newlines for the multi-line handling below.
    sanitize_comment_text(text)
        .lines()
        .map(|l| format!("/// {}\n", l.trim_end()))
        .collect()
}

// ── Module context ──────────────────────────────────────────────────────────

struct Ctx<'a> {
    defs: &'a [DefEntry],
    prefix: String,
    /// Nested struct definitions generated while typing object fields.
    extra: Vec<String>,
    used_names: HashSet<String>,
}

impl Ctx<'_> {
    fn unique_type_name(&mut self, base: &str) -> String {
        let mut candidate = base.to_string();
        let mut i = 1;
        while self.used_names.contains(&candidate) {
            i += 1;
            candidate = format!("{base}{i}");
        }
        self.used_names.insert(candidate.clone());
        candidate
    }
}

// ── Definition dispatch ─────────────────────────────────────────────────────

/// Typed structs only keep declared properties, so re-serialization drops any
/// unknown keys the schema permits. That lossiness is fine for every object
/// constraint except `minProperties`: dropping keys can only make
/// maxProperties/patternProperties/propertyNames/dependent* EASIER to satisfy,
/// but it can turn a `minProperties`-satisfying instance into a failing one —
/// a freshly decoded value would then fail `validate()`. When (a) the object
/// can retain unknown keys (additionalProperties allowed or schema-checked,
/// or any patternProperties) AND (b) `minProperties` is set, fall back to the
/// newtype-over-Value shape, which keeps full raw fidelity.
fn object_can_lose_min_properties(obj: &ObjectSchema) -> bool {
    let retains_unknown_keys = matches!(
        obj.additional_properties,
        AdditionalProperties::Allowed | AdditionalProperties::Schema(_)
    ) || !obj.pattern_properties.is_empty();
    retains_unknown_keys && obj.min_properties.is_some()
}

fn emit_definition(name: &str, ir: &SchemaIr, ctx: &mut Ctx) -> String {
    // Default/Describe are transparent wrappers; Describe adds a doc comment.
    let mut doc = String::new();
    let mut inner = ir;
    loop {
        match inner {
            SchemaIr::Describe(i, text) => {
                doc.push_str(&doc_comment(text));
                inner = i;
            }
            SchemaIr::Default(i, _) => inner = i,
            _ => break,
        }
    }

    let code = match inner {
        SchemaIr::Object(obj)
            if !obj.fields.is_empty() && !object_can_lose_min_properties(obj) =>
        {
            emit_struct(name, obj, ctx)
        }
        SchemaIr::Enum(cases) if !cases.is_empty() => emit_enum(name, cases),
        SchemaIr::Ref(target) => {
            let safe = sanitize_rust_name(target, &ctx.prefix);
            format!("#[allow(dead_code)]\npub type {name} = {safe};")
        }
        _ => emit_newtype(name, inner, ctx),
    };
    format!("{doc}{code}")
}

fn deserialize_impl(name: &str) -> String {
    format!(
        "impl<'de> serde::Deserialize<'de> for {name} {{\n    \
         fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {{\n        \
         let v = serde_json::Value::deserialize(d)?;\n        \
         Self::_jst_from_value(&v).map_err(serde::de::Error::custom)\n    \
         }}\n}}"
    )
}

/// The generated `_jst_check` associated fn: all schema checks against a raw
/// JSON value, built from an `emit_check` bool expression over `v`.
fn check_fn(check: &str, reject_msg: &str) -> String {
    let body = if check == "false" {
        "        let _ = v;\n        Err(\"schema rejects all values\".to_string())".to_string()
    } else if check == "true" {
        "        let _ = v;\n        Ok(())".to_string()
    } else {
        format!(
            "        if !{check} {{\n            return Err(\"{reject_msg}\".to_string());\n        }}\n        Ok(())"
        )
    };
    format!(
        "    /// All schema checks against a raw JSON value.\n    #[allow(dead_code)]\n    pub fn _jst_check(v: &serde_json::Value) -> Result<(), String> {{\n{body}\n    }}\n"
    )
}

/// The generated `validate` / `to_validated_json` methods, shared verbatim by
/// every type shape (struct, enum, newtype). They round-trip through serde
/// serialization so `_jst_check` sees exactly what `to_string` would emit.
fn validate_methods() -> &'static str {
    concat!(
        "    /// Re-validate this value (e.g. after field mutation) by round-tripping\n",
        "    /// through the schema checks.\n",
        "    #[allow(dead_code)]\n",
        "    pub fn validate(&self) -> Result<(), String> {\n",
        "        Self::_jst_check(&serde_json::to_value(self).map_err(|e| e.to_string())?)\n",
        "    }\n",
        "    /// Validate, then serialize. Plain serde serialization does NOT validate.\n",
        "    #[allow(dead_code)]\n",
        "    pub fn to_validated_json(&self) -> Result<String, String> {\n",
        "        self.validate()?;\n",
        "        serde_json::to_string(self).map_err(|e| e.to_string())\n",
        "    }\n",
    )
}

// ── Newtype (validated serde_json::Value) ───────────────────────────────────

fn emit_newtype(name: &str, ir: &SchemaIr, ctx: &mut Ctx) -> String {
    let check = emit_check(ir, "v", ctx.defs, &ctx.prefix);
    format!(
        "#[derive(Debug, Clone, serde::Serialize)]\n#[allow(dead_code)]\npub struct {name}(pub serde_json::Value);\n\n{}\n\nimpl {name} {{\n{}    #[allow(dead_code)]\n    pub fn _jst_from_value(v: &serde_json::Value) -> Result<Self, String> {{\n        Self::_jst_check(v)?;\n        Ok(Self(v.clone()))\n    }}\n{}}}",
        deserialize_impl(name),
        check_fn(&check, "does not match schema"),
        validate_methods()
    )
}

// ── String enum ─────────────────────────────────────────────────────────────

fn emit_enum(name: &str, cases: &[String]) -> String {
    let mut used: HashSet<String> = HashSet::new();
    let mut seen_raw: HashSet<&str> = HashSet::new();
    let mut variants = Vec::new(); // (variant_name, raw_value)
    for c in cases {
        // Duplicate enum values are legal JSON Schema but would emit an
        // unreachable match arm and a duplicate #[serde(rename)].
        if !seen_raw.insert(c.as_str()) {
            continue;
        }
        let mut vname = to_pascal_case(c);
        if vname.is_empty() {
            vname = "Value".to_string();
        }
        if vname == "Self" {
            vname = "SelfValue".to_string();
        }
        let base = vname.clone();
        let mut i = 1;
        while used.contains(&vname) {
            i += 1;
            vname = format!("{base}{i}");
        }
        used.insert(vname.clone());
        variants.push((vname, c.clone()));
    }

    let decl: String = variants
        .iter()
        .map(|(v, raw)| format!("    #[serde(rename = \"{}\")]\n    {v},\n", esc(raw)))
        .collect();
    let arms: String = variants
        .iter()
        .map(|(v, raw)| format!("            Some(\"{}\") => Ok(Self::{v}),\n", esc(raw)))
        .collect();
    let pats: Vec<String> = variants
        .iter()
        .map(|(_, raw)| format!("Some(\"{}\")", esc(raw)))
        .collect();
    let check = format!("matches!(v.as_str(), {})", pats.join(" | "));

    format!(
        "#[derive(Debug, Clone, serde::Serialize)]\n#[allow(dead_code)]\npub enum {name} {{\n{decl}}}\n\n{}\n\nimpl {name} {{\n{}    #[allow(dead_code)]\n    pub fn _jst_from_value(v: &serde_json::Value) -> Result<Self, String> {{\n        Self::_jst_check(v)?;\n        match v.as_str() {{\n{arms}            _ => Err(\"must be one of the allowed values\".to_string()),\n        }}\n    }}\n{}}}",
        deserialize_impl(name),
        check_fn(&check, "must be one of the allowed values"),
        validate_methods()
    )
}

// ── Typed object struct ─────────────────────────────────────────────────────

fn emit_struct(name: &str, obj: &ObjectSchema, ctx: &mut Ctx) -> String {
    let mut used_idents: HashSet<String> = HashSet::new();
    let mut decls = String::new();
    let mut inits = String::new();

    for (key, f) in &obj.fields {
        // Unwrap modifier layers, tracking key-optionality and nullability.
        let mut core = &f.schema;
        let mut optional = !f.required;
        let mut nullable = false;
        loop {
            match core {
                SchemaIr::Optional(i) => {
                    optional = true;
                    core = i;
                }
                SchemaIr::Nullable(i) => {
                    nullable = true;
                    core = i;
                }
                SchemaIr::Describe(i, _) | SchemaIr::Default(i, _) => core = i,
                _ => break,
            }
        }

        let ident = field_ident(key, &mut used_idents);
        let hint = {
            let h = to_pascal_case(key);
            if h.is_empty() { "Field".to_string() } else { h }
        };
        let (ty, extract) = extraction(core, "x", 0, ctx, name, &hint);

        let is_opt = optional || nullable;
        let decl_ty = if is_opt { format!("Option<{ty}>") } else { ty };
        let skip = if optional {
            ", skip_serializing_if = \"Option::is_none\""
        } else {
            ""
        };
        decls.push_str(&format!(
            "    #[serde(rename = \"{}\"{skip})]\n    pub {ident}: {decl_ty},\n",
            esc(key)
        ));

        let init = if is_opt {
            format!(
                "match o.get(\"{k}\") {{\n                None => None,\n                Some(x) if x.is_null() => None,\n                Some(x) => Some({extract}),\n            }}",
                k = esc(key)
            )
        } else {
            format!(
                "{{\n                let x = o.get(\"{k}\").ok_or_else(|| \"missing property: {k}\".to_string())?;\n                {extract}\n            }}",
                k = esc(key)
            )
        };
        inits.push_str(&format!("            {ident}: {init},\n"));
    }

    // Full raw-value validation (every constraint, mirroring the Kotlin
    // wrapper path) lives in `_jst_check`; extraction is then mechanical.
    let check = emit_check(&SchemaIr::Object(obj.clone()), "v", ctx.defs, &ctx.prefix);

    format!(
        "#[derive(Debug, Clone, serde::Serialize)]\n#[allow(dead_code)]\npub struct {name} {{\n{decls}}}\n\n{}\n\nimpl {name} {{\n{}    #[allow(dead_code)]\n    pub fn _jst_from_value(v: &serde_json::Value) -> Result<Self, String> {{\n        Self::_jst_check(v)?;\n        let o = match v.as_object() {{\n            Some(o) => o,\n            None => return Err(\"must be an object\".to_string()),\n        }};\n        Ok(Self {{\n{inits}        }})\n    }}\n{}}}",
        deserialize_impl(name),
        check_fn(&check, "does not match schema"),
        validate_methods()
    )
}

// ── Typed field extraction ──────────────────────────────────────────────────

/// Map a field schema to a Rust type plus an extraction expression over the
/// variable `x` (`&serde_json::Value`). The expression may use `?` (the
/// enclosing fn returns `Result<_, String>`). Falls back to
/// `serde_json::Value` + `.clone()` for shapes without a clean typed mapping;
/// validation completeness is unaffected (the raw value is fully validated
/// before extraction).
fn extraction(
    ir: &SchemaIr,
    x: &str,
    depth: usize,
    ctx: &mut Ctx,
    owner: &str,
    hint: &str,
) -> (String, String) {
    match ir {
        SchemaIr::Describe(i, _) | SchemaIr::Default(i, _) | SchemaIr::Optional(i) => {
            extraction(i, x, depth, ctx, owner, hint)
        }
        SchemaIr::Nullable(i) => {
            let (t, e) = extraction(i, x, depth, ctx, owner, hint);
            (
                format!("Option<{t}>"),
                format!("if {x}.is_null() {{ None }} else {{ Some({e}) }}"),
            )
        }
        SchemaIr::String(_) | SchemaIr::Enum(_) | SchemaIr::Literal(LiteralValue::String(_)) => (
            "String".to_string(),
            format!("{x}.as_str().ok_or_else(|| \"expected string\".to_string())?.to_string()"),
        ),
        SchemaIr::Number(_) | SchemaIr::Literal(LiteralValue::Number(_)) => (
            "f64".to_string(),
            format!("{x}.as_f64().ok_or_else(|| \"expected number\".to_string())?"),
        ),
        // Integers store as serde_json::Number: never rejects a valid instance
        // (arbitrary magnitude, integral floats) and round-trips exactly.
        SchemaIr::Integer(_) | SchemaIr::Literal(LiteralValue::Integer(_)) => (
            "serde_json::Number".to_string(),
            format!(
                "match {x} {{ serde_json::Value::Number(n) => n.clone(), _ => return Err(\"expected number\".to_string()) }}"
            ),
        ),
        SchemaIr::Boolean | SchemaIr::Literal(LiteralValue::Bool(_)) => (
            "bool".to_string(),
            format!("{x}.as_bool().ok_or_else(|| \"expected boolean\".to_string())?"),
        ),
        SchemaIr::Array(arr) => {
            let (t, e) = extraction(
                &arr.items,
                &format!("e{depth}"),
                depth + 1,
                ctx,
                owner,
                &format!("{hint}Item"),
            );
            (
                format!("Vec<{t}>"),
                format!(
                    "{{ let a{depth} = {x}.as_array().ok_or_else(|| \"expected array\".to_string())?; let mut out{depth} = Vec::with_capacity(a{depth}.len()); for e{depth} in a{depth} {{ out{depth}.push({e}); }} out{depth} }}"
                ),
            )
        }
        SchemaIr::Record(rec) => {
            let (t, e) = extraction(
                &rec.value,
                &format!("mv{depth}"),
                depth + 1,
                ctx,
                owner,
                &format!("{hint}Value"),
            );
            (
                format!("std::collections::BTreeMap<String, {t}>"),
                format!(
                    "{{ let m{depth} = {x}.as_object().ok_or_else(|| \"expected object\".to_string())?; let mut out{depth} = std::collections::BTreeMap::new(); for (mk{depth}, mv{depth}) in m{depth} {{ out{depth}.insert(mk{depth}.clone(), {e}); }} out{depth} }}"
                ),
            )
        }
        SchemaIr::Tuple(_) => (
            "Vec<serde_json::Value>".to_string(),
            format!("{x}.as_array().cloned().ok_or_else(|| \"expected array\".to_string())?"),
        ),
        SchemaIr::Ref(n) | SchemaIr::Lazy(n) => {
            let t = sanitize_rust_name(n, &ctx.prefix);
            let recursive = ctx
                .defs
                .iter()
                .find(|d| d.name == *n)
                .is_some_and(|d| d.is_recursive);
            if recursive {
                // Box the field so recursive types have finite size (the Swift
                // emitter switches to class for the same reason).
                (
                    format!("Box<{t}>"),
                    format!("Box::new({t}::_jst_from_value({x})?)"),
                )
            } else {
                (t.clone(), format!("{t}::_jst_from_value({x})?"))
            }
        }
        // Same lossiness guard as emit_definition: a nested typed struct would
        // drop unknown keys on the parent's re-serialization and could break
        // `validate()` under minProperties; hold the raw value instead.
        SchemaIr::Object(o) if !o.fields.is_empty() && !object_can_lose_min_properties(o) => {
            let nested = ctx.unique_type_name(&format!("{owner}{hint}"));
            let code = emit_struct(&nested, o, ctx);
            ctx.extra.push(code);
            (
                nested.clone(),
                format!("{nested}::_jst_from_value({x})?"),
            )
        }
        // Null, Any, Unknown, unions, intersections, const/enum-of-values,
        // TypeGuarded, Not, Conditional, Interpreted, Never, bare objects:
        // hold the (already fully validated) raw value.
        _ => ("serde_json::Value".to_string(), format!("{x}.clone()")),
    }
}

// ── Validation check generation ─────────────────────────────────────────────
//
// `emit_check` returns a Rust *bool expression* over `var` (an expression of
// type `&serde_json::Value`). Every returned expression is syntactically
// atomic (a literal, method call, `matches!`, helper call, or an immediately
// invoked closure) so callers can combine them with `!`, `&&`, `||` or use
// them as `if` conditions without extra parentheses.

fn emit_check(ir: &SchemaIr, var: &str, defs: &[DefEntry], prefix: &str) -> String {
    match ir {
        SchemaIr::Any | SchemaIr::Unknown => "true".to_string(),
        SchemaIr::Never => "false".to_string(),
        SchemaIr::Boolean => format!("{var}.is_boolean()"),
        SchemaIr::Null => format!("{var}.is_null()"),
        SchemaIr::Describe(i, _) | SchemaIr::Default(i, _) | SchemaIr::Optional(i) => {
            emit_check(i, var, defs, prefix)
        }
        SchemaIr::Nullable(i) => {
            let inner = emit_check(i, var, defs, prefix);
            if inner == "true" {
                "true".to_string()
            } else {
                bool_closure(
                    &format!("if v.is_null() {{ return true; }}\n{inner}"),
                    var,
                )
            }
        }
        SchemaIr::String(c) => string_check(c, var),
        SchemaIr::Number(c) => number_check(c, var, false),
        SchemaIr::Integer(c) => number_check(c, var, true),
        SchemaIr::Literal(lit) => literal_check(lit, var),
        SchemaIr::Enum(cases) => {
            if cases.is_empty() {
                return "false".to_string();
            }
            let pats: Vec<String> = cases.iter().map(|c| format!("Some(\"{}\")", esc(c))).collect();
            format!("matches!({var}.as_str(), {})", pats.join(" | "))
        }
        SchemaIr::MixedEnum(lits) => {
            let checks: Vec<String> = lits.iter().map(|l| literal_check(l, "v")).collect();
            bool_closure(&checks.join(" || ").to_string(), var)
        }
        SchemaIr::ConstEqual(val) => {
            let json = esc(&serde_json::to_string(val).unwrap_or_else(|_| "null".to_string()));
            bool_closure(
                &format!(
                    "static C: std::sync::OnceLock<serde_json::Value> = std::sync::OnceLock::new();\n_jst_eq(v, C.get_or_init(|| serde_json::from_str(\"{json}\").unwrap_or(serde_json::Value::Null)))"
                ),
                var,
            )
        }
        SchemaIr::ComplexEnum(vals) => {
            let json = esc(&serde_json::to_string(vals).unwrap_or_else(|_| "[]".to_string()));
            bool_closure(
                &format!(
                    "static C: std::sync::OnceLock<serde_json::Value> = std::sync::OnceLock::new();\nlet allowed = C.get_or_init(|| serde_json::from_str(\"{json}\").unwrap_or(serde_json::Value::Null));\nallowed.as_array().map(|a| a.iter().any(|c| _jst_eq(v, c))).unwrap_or(false)"
                ),
                var,
            )
        }
        SchemaIr::Array(arr) => array_check(arr, var, defs, prefix),
        SchemaIr::Tuple(t) => tuple_check(t, var, defs, prefix),
        SchemaIr::Object(obj) => object_check(obj, var, defs, prefix),
        SchemaIr::Record(rec) => record_check(rec, var, defs, prefix),
        SchemaIr::Union(members) => {
            if members.is_empty() {
                return "true".to_string();
            }
            let checks: Vec<String> = members
                .iter()
                .map(|m| emit_check(m, "v", defs, prefix))
                .collect();
            if checks.iter().any(|c| c == "true") {
                return "true".to_string();
            }
            if checks.len() == 1 {
                return emit_check(&members[0], var, defs, prefix);
            }
            bool_closure(&checks.join(" || ").to_string(), var)
        }
        SchemaIr::ExclusiveUnion(members) => {
            if members.is_empty() {
                return "false".to_string();
            }
            if members.len() == 1 {
                return emit_check(&members[0], var, defs, prefix);
            }
            let checks: Vec<String> = members
                .iter()
                .map(|m| emit_check(m, "v", defs, prefix))
                .collect();
            bool_closure(
                &format!(
                    "let branches = [{}];\nbranches.iter().filter(|&&b| b).count() == 1",
                    checks.join(", ")
                ),
                var,
            )
        }
        SchemaIr::Intersection(members) => {
            let checks: Vec<String> = members
                .iter()
                .map(|m| emit_check(m, "v", defs, prefix))
                .filter(|c| c != "true")
                .collect();
            if checks.is_empty() {
                return "true".to_string();
            }
            if checks.len() == 1 && members.len() == 1 {
                return emit_check(&members[0], var, defs, prefix);
            }
            bool_closure(&checks.join(" && ").to_string(), var)
        }
        SchemaIr::Not { base, not_schema } => {
            let base_check = emit_check(base, "v", defs, prefix);
            let not_check = emit_check(not_schema, "v", defs, prefix);
            let mut body = String::new();
            if base_check != "true" {
                body.push_str(&format!("if !{base_check} {{ return false; }}\n"));
            }
            body.push_str(&format!("!{not_check}"));
            bool_closure(&body, var)
        }
        SchemaIr::Conditional {
            base,
            if_schema,
            then_schema,
            else_schema,
        } => {
            let base_check = emit_check(base, "v", defs, prefix);
            let if_check = emit_check(if_schema, "v", defs, prefix);
            let then_check = then_schema
                .as_deref()
                .map(|s| emit_check(s, "v", defs, prefix))
                .unwrap_or_else(|| "true".to_string());
            let else_check = else_schema
                .as_deref()
                .map(|s| emit_check(s, "v", defs, prefix))
                .unwrap_or_else(|| "true".to_string());
            let mut body = String::new();
            if base_check != "true" {
                body.push_str(&format!("if !{base_check} {{ return false; }}\n"));
            }
            body.push_str(&format!(
                "if {if_check} {{ {then_check} }} else {{ {else_check} }}"
            ));
            bool_closure(&body, var)
        }
        SchemaIr::TypeGuarded(guards) => {
            let mut body = String::new();
            for (guard, schema) in guards {
                let (test, check) = match guard {
                    TypeGuard::String => {
                        ("v.is_string()", emit_check(schema, "v", defs, prefix))
                    }
                    TypeGuard::Number => {
                        // Typeless numeric constraints apply to any number;
                        // do not force integrality (mirrors the Kotlin path).
                        let check = match schema.as_ref() {
                            SchemaIr::Integer(c) => number_check(c, "v", false),
                            other => emit_check(other, "v", defs, prefix),
                        };
                        ("v.is_number()", check)
                    }
                    TypeGuard::Object => ("v.is_object()", emit_check(schema, "v", defs, prefix)),
                    TypeGuard::Array => ("v.is_array()", emit_check(schema, "v", defs, prefix)),
                };
                if check != "true" {
                    body.push_str(&format!("if {test} {{ if !{check} {{ return false; }} }}\n"));
                }
            }
            if body.is_empty() {
                "true".to_string()
            } else {
                bool_closure(&format!("{body}true"), var)
            }
        }
        SchemaIr::Ref(n) | SchemaIr::Lazy(n) => {
            // Recurse into the referenced type's raw-value checks; this keeps
            // `_jst_check` comprehensive (validate() catches everything decode
            // would) without constructing intermediate typed values.
            let t = sanitize_rust_name(n, prefix);
            format!("{t}::_jst_check({var}).is_ok()")
        }
        SchemaIr::Interpreted { schema, remotes } => {
            let schema_json =
                esc(&serde_json::to_string(schema).unwrap_or_else(|_| "true".to_string()));
            let remotes_map: serde_json::Map<String, serde_json::Value> = remotes
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();
            let remotes_json = esc(
                &serde_json::to_string(&serde_json::Value::Object(remotes_map))
                    .unwrap_or_else(|_| "{}".to_string()),
            );
            bool_closure(
                &format!(
                    "static S: std::sync::OnceLock<serde_json::Value> = std::sync::OnceLock::new();\n\
                     static R: std::sync::OnceLock<Vec<(String, serde_json::Value)>> = std::sync::OnceLock::new();\n\
                     let s = S.get_or_init(|| serde_json::from_str(\"{schema_json}\").unwrap_or(serde_json::Value::Bool(true)));\n\
                     let r = R.get_or_init(|| serde_json::from_str::<serde_json::Value>(\"{remotes_json}\").ok().and_then(|m| m.as_object().map(|o| o.iter().map(|(k, val)| (k.clone(), val.clone())).collect::<Vec<_>>())).unwrap_or_default());\n\
                     _jst_jsi_validate(s, r, v)"
                ),
                var,
            )
        }
    }
}

/// Wrap statements + tail expression into an immediately invoked closure so
/// the resulting expression is atomic. Ensures the closure parameter is used
/// to avoid unused-variable warnings when the body folded to constants.
fn bool_closure(body: &str, var: &str) -> String {
    let mut body = body.to_string();
    if !uses_ident(&body, 'v') {
        body = format!("let _ = v;\n{body}");
    }
    let indented: String = body
        .lines()
        .map(|l| format!("            {l}\n"))
        .collect();
    format!("(|v: &serde_json::Value| -> bool {{\n{indented}        }})({var})")
}

/// Crude ident-boundary scan: is `c` present as a standalone identifier?
fn uses_ident(body: &str, c: char) -> bool {
    let bytes: Vec<char> = body.chars().collect();
    for (i, &ch) in bytes.iter().enumerate() {
        if ch != c {
            continue;
        }
        let prev_ok = i == 0 || {
            let p = bytes[i - 1];
            !p.is_ascii_alphanumeric() && p != '_'
        };
        let next_ok = i + 1 >= bytes.len() || {
            let n = bytes[i + 1];
            !n.is_ascii_alphanumeric() && n != '_'
        };
        if prev_ok && next_ok {
            return true;
        }
    }
    false
}

/// Statement form: `let re_ok = { static RE ... };` — compiled once, cached.
/// `on_fail` is the result when the pattern fails to compile in the `regex`
/// crate (ECMA-only syntax): value checks pass permissively, key matching
/// reports no match.
fn regex_stmt(bind: &str, pattern: &str, subject: &str, on_fail: bool) -> String {
    format!(
        "let {bind} = {{ static RE: std::sync::OnceLock<Option<regex::Regex>> = std::sync::OnceLock::new(); RE.get_or_init(|| regex::Regex::new(\"{}\").ok()).as_ref().map(|r| r.is_match({subject})).unwrap_or({on_fail}) }};",
        esc(pattern)
    )
}

fn string_check(c: &StringConstraints, var: &str) -> String {
    let plain = c.min_length.is_none()
        && c.max_length.is_none()
        && c.pattern.is_none()
        && c.format.is_none();
    if plain {
        return format!("{var}.is_string()");
    }
    let mut body = String::new();
    body.push_str("let s = match v.as_str() { Some(s) => s, None => return false };\n");
    // JSON Schema counts Unicode code points; chars() yields scalar values.
    if let Some(min) = c.min_length {
        body.push_str(&format!("if s.chars().count() < {min} {{ return false; }}\n"));
    }
    if let Some(max) = c.max_length {
        body.push_str(&format!("if s.chars().count() > {max} {{ return false; }}\n"));
    }
    if let Some(pat) = &c.pattern {
        body.push_str(&regex_stmt("re_ok", pat, "s", true));
        body.push_str("\nif !re_ok { return false; }\n");
    }
    if let Some(f) = &c.format {
        body.push_str(&format!("if !{}(s) {{ return false; }}\n", format_fn(f)));
    }
    body.push_str("true");
    bool_closure(&body, var)
}

fn format_fn(f: &StringFormat) -> &'static str {
    match f {
        StringFormat::Email => "_jst_is_email",
        StringFormat::Uri => "_jst_is_uri",
        StringFormat::Uuid => "_jst_is_uuid",
        StringFormat::DateTime => "_jst_is_date_time",
        StringFormat::Date => "_jst_is_date",
        StringFormat::Time => "_jst_is_time",
        StringFormat::Duration => "_jst_is_duration",
        StringFormat::Ip => "_jst_is_ip",
        StringFormat::Ipv4 => "_jst_is_ipv4",
        StringFormat::Ipv6 => "_jst_is_ipv6",
        StringFormat::Hostname => "_jst_is_hostname",
        StringFormat::Base64 => "_jst_is_base64",
    }
}

fn number_check(c: &NumberConstraints, var: &str, integer: bool) -> String {
    let plain = c.minimum.is_none()
        && c.maximum.is_none()
        && c.exclusive_minimum.is_none()
        && c.exclusive_maximum.is_none()
        && c.multiple_of.is_none();
    if plain {
        return if integer {
            format!("_jst_is_integer({var})")
        } else {
            format!("{var}.is_number()")
        };
    }
    let mut body = String::new();
    if integer {
        body.push_str("if !_jst_is_integer(v) { return false; }\n");
    } else {
        body.push_str("if !v.is_number() { return false; }\n");
    }
    let has_bounds = c.minimum.is_some()
        || c.maximum.is_some()
        || c.exclusive_minimum.is_some()
        || c.exclusive_maximum.is_some();
    if has_bounds {
        body.push_str("let n = match v.as_f64() { Some(n) => n, None => return false };\n");
        if let Some(min) = c.minimum {
            body.push_str(&format!("if !(n >= {}) {{ return false; }}\n", fmt_f64(min)));
        }
        if let Some(max) = c.maximum {
            body.push_str(&format!("if !(n <= {}) {{ return false; }}\n", fmt_f64(max)));
        }
        if let Some(emin) = c.exclusive_minimum {
            body.push_str(&format!("if !(n > {}) {{ return false; }}\n", fmt_f64(emin)));
        }
        if let Some(emax) = c.exclusive_maximum {
            body.push_str(&format!("if !(n < {}) {{ return false; }}\n", fmt_f64(emax)));
        }
    }
    if let Some(m) = c.multiple_of {
        body.push_str(&format!(
            "let mo = match v {{ serde_json::Value::Number(num) => _jst_multiple_of(num, {}), _ => false }};\nif !mo {{ return false; }}\n",
            fmt_f64(m)
        ));
    }
    body.push_str("true");
    bool_closure(&body, var)
}

fn literal_check(lit: &LiteralValue, var: &str) -> String {
    match lit {
        LiteralValue::String(s) => format!("matches!({var}.as_str(), Some(\"{}\"))", esc(s)),
        LiteralValue::Bool(b) => format!("matches!({var}.as_bool(), Some({b}))"),
        LiteralValue::Null => format!("{var}.is_null()"),
        // Integer literals match both 5 and 5.0 (numbers compare
        // mathematically, mirroring _jst_eq): integer-typed instances
        // (i64/u64) compare EXACTLY — the f64 fallback would wrongly accept
        // neighbors that round to the same double (e.g. 2^53 vs 2^53+1, or
        // i64::MAX vs the u64 above it). Only float-typed instances use the
        // f64 comparison, so 5.0 still matches const 5.
        LiteralValue::Integer(i) => {
            // A float instance can only mathematically equal the literal when
            // the literal is exactly representable as f64 — decided here at
            // generation time so the emitted check stays branch-simple.
            let float_arm = if (*i as f64) as i64 == *i {
                format!("n.as_f64() == Some({i}f64)")
            } else {
                "false".to_string()
            };
            bool_closure(
                &format!(
                    "match v {{\n    serde_json::Value::Number(n) => {{\n        if let Some(x) = n.as_i64() {{ x == {i}i64 }}\n        else if n.as_u64().is_some() {{ false }}\n        else {{ {float_arm} }}\n    }}\n    _ => false,\n}}"
                ),
                var,
            )
        }
        LiteralValue::Number(n) => {
            // Mirror the Integer arm: integer-typed instances compare via
            // round-trip exactness so e.g. const 9007199254740992.0 does not
            // accept the integer 2^53+1 (whose f64 rounding coincides).
            let nf = fmt_f64(*n);
            bool_closure(
                &format!(
                    "match v {{\n    serde_json::Value::Number(n) => {{\n        if let Some(x) = n.as_i64() {{ (x as f64) == {nf} && ({nf} as i64) == x }}\n        else if let Some(x) = n.as_u64() {{ (x as f64) == {nf} && ({nf} as u64) == x }}\n        else {{ n.as_f64() == Some({nf}) }}\n    }}\n    _ => false,\n}}"
                ),
                var,
            )
        }
    }
}

fn array_check(arr: &ArraySchema, var: &str, defs: &[DefEntry], prefix: &str) -> String {
    let item_check = emit_check(&arr.items, "item", defs, prefix);
    let no_constraints = arr.min_items.is_none()
        && arr.max_items.is_none()
        && !arr.unique_items
        && arr.contains.is_none()
        && item_check == "true";
    if no_constraints {
        return format!("{var}.is_array()");
    }
    let mut body = String::new();
    body.push_str("let a = match v.as_array() { Some(a) => a, None => return false };\n");
    if let Some(min) = arr.min_items {
        body.push_str(&format!("if a.len() < {min} {{ return false; }}\n"));
    }
    if let Some(max) = arr.max_items {
        body.push_str(&format!("if a.len() > {max} {{ return false; }}\n"));
    }
    if item_check != "true" {
        body.push_str(&format!(
            "if !a.iter().all(|item| {item_check}) {{ return false; }}\n"
        ));
    }
    if arr.unique_items {
        body.push_str(
            "let mut seen = std::collections::BTreeSet::new();\nfor item in a { if !seen.insert(_jst_canonical(item)) { return false; } }\n",
        );
    }
    if let Some(contains) = &arr.contains {
        push_contains(&mut body, contains, defs, prefix);
    }
    body.push_str("true");
    bool_closure(&body, var)
}

fn push_contains(body: &mut String, contains: &ContainsSchema, defs: &[DefEntry], prefix: &str) {
    let check = emit_check(&contains.schema, "item", defs, prefix);
    let min = contains.min_contains.unwrap_or(1);
    if check == "true" {
        body.push_str("let match_count = a.len();\n");
    } else {
        body.push_str(&format!(
            "let match_count = a.iter().map(|item| {check}).filter(|&b| b).count();\n"
        ));
    }
    body.push_str(&format!("if match_count < {min} {{ return false; }}\n"));
    if let Some(max) = contains.max_contains {
        body.push_str(&format!("if match_count > {max} {{ return false; }}\n"));
    }
}

fn tuple_check(t: &TupleSchema, var: &str, defs: &[DefEntry], prefix: &str) -> String {
    let mut body = String::new();
    body.push_str("let a = match v.as_array() { Some(a) => a, None => return false };\n");
    for (i, item) in t.items.iter().enumerate() {
        let check = emit_check(item, "x", defs, prefix);
        if check != "true" {
            body.push_str(&format!(
                "if let Some(x) = a.get({i}) {{ if !{check} {{ return false; }} }}\n"
            ));
        }
    }
    let prefix_count = t.items.len();
    if let Some(rest) = &t.rest {
        let check = emit_check(rest, "item", defs, prefix);
        if check != "true" {
            body.push_str(&format!(
                "if !a.iter().skip({prefix_count}).all(|item| {check}) {{ return false; }}\n"
            ));
        }
    } else {
        body.push_str(&format!(
            "if a.len() > {prefix_count} {{ return false; }}\n"
        ));
    }
    if let Some(min) = t.min_items {
        body.push_str(&format!("if a.len() < {min} {{ return false; }}\n"));
    }
    if let Some(max) = t.max_items {
        body.push_str(&format!("if a.len() > {max} {{ return false; }}\n"));
    }
    if t.unique_items {
        body.push_str(
            "let mut seen = std::collections::BTreeSet::new();\nfor item in a { if !seen.insert(_jst_canonical(item)) { return false; } }\n",
        );
    }
    if let Some(contains) = &t.contains {
        push_contains(&mut body, contains, defs, prefix);
    }
    body.push_str("true");
    bool_closure(&body, var)
}

fn record_check(rec: &RecordSchema, var: &str, defs: &[DefEntry], prefix: &str) -> String {
    let key_check = emit_check(&rec.key, "kvr", defs, prefix);
    // A bare string key schema is a tautology — every JSON key is a string.
    let key_trivial = key_check == "true" || key_check == "kvr.is_string()";
    let value_check = emit_check(&rec.value, "x", defs, prefix);
    if key_trivial && value_check == "true" {
        return format!("{var}.is_object()");
    }
    let mut body = String::new();
    body.push_str("let o = match v.as_object() { Some(o) => o, None => return false };\n");
    if !key_trivial {
        body.push_str(&format!(
            "for k in o.keys() {{ let kv = serde_json::Value::String(k.clone()); let kvr = &kv; if !{key_check} {{ return false; }} }}\n"
        ));
    }
    if value_check != "true" {
        body.push_str(&format!(
            "for x in o.values() {{ if !{value_check} {{ return false; }} }}\n"
        ));
    }
    body.push_str("true");
    bool_closure(&body, var)
}

fn object_check(obj: &ObjectSchema, var: &str, defs: &[DefEntry], prefix: &str) -> String {
    let mut body = String::new();

    // Required properties
    for (k, f) in &obj.fields {
        if f.required {
            body.push_str(&format!(
                "if !o.contains_key(\"{}\") {{ return false; }}\n",
                esc(k)
            ));
        }
    }
    // Per-property checks
    for (k, f) in &obj.fields {
        let check = emit_check(&f.schema, "x", defs, prefix);
        if check != "true" {
            body.push_str(&format!(
                "if let Some(x) = o.get(\"{}\") {{ if !{check} {{ return false; }} }}\n",
                esc(k)
            ));
        }
    }
    if let Some(min) = obj.min_properties {
        body.push_str(&format!("if o.len() < {min} {{ return false; }}\n"));
    }
    if let Some(max) = obj.max_properties {
        body.push_str(&format!("if o.len() > {max} {{ return false; }}\n"));
    }

    // patternProperties + additionalProperties interaction:
    // additionalProperties applies only to keys not matched by a named
    // property or any patternProperties regex.
    let known_pats: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", esc(k))).collect();
    let known_match = if known_pats.is_empty() {
        "false".to_string()
    } else {
        format!("matches!(k.as_str(), {})", known_pats.join(" | "))
    };
    if !obj.pattern_properties.is_empty() {
        let needs_matched = !matches!(obj.additional_properties, AdditionalProperties::Allowed);
        let mut loop_body = String::new();
        if needs_matched {
            loop_body.push_str(&format!("    let mut matched = {known_match};\n"));
        }
        let mut uses_value = false;
        for (pattern, pp_schema) in &obj.pattern_properties {
            let pp_check = emit_check(pp_schema, "x", defs, prefix);
            loop_body.push_str(&format!("    {}\n", regex_stmt("re_ok", pattern, "k", false)));
            let mark = if needs_matched { "matched = true; " } else { "" };
            if pp_check == "true" {
                if needs_matched {
                    loop_body.push_str("    if re_ok { matched = true; }\n");
                } else {
                    loop_body.push_str("    let _ = re_ok;\n");
                }
            } else {
                uses_value = true;
                loop_body.push_str(&format!(
                    "    if re_ok {{ {mark}if !{pp_check} {{ return false; }} }}\n"
                ));
            }
        }
        match &obj.additional_properties {
            AdditionalProperties::Forbidden => {
                loop_body.push_str("    if !matched { return false; }\n");
            }
            AdditionalProperties::Schema(ap) => {
                let ap_check = emit_check(ap, "x", defs, prefix);
                if ap_check == "true" {
                    loop_body.push_str("    let _ = matched;\n");
                } else {
                    uses_value = true;
                    loop_body.push_str(&format!(
                        "    if !matched {{ if !{ap_check} {{ return false; }} }}\n"
                    ));
                }
            }
            AdditionalProperties::Allowed => {}
        }
        let binding = if uses_value { "x" } else { "_x" };
        body.push_str(&format!("for (k, {binding}) in o {{\n{loop_body}}}\n"));
    } else {
        match &obj.additional_properties {
            AdditionalProperties::Forbidden => {
                if known_pats.is_empty() {
                    body.push_str("if !o.is_empty() { return false; }\n");
                } else {
                    body.push_str(&format!(
                        "if !o.keys().all(|k| {known_match}) {{ return false; }}\n"
                    ));
                }
            }
            AdditionalProperties::Schema(ap) => {
                let ap_check = emit_check(ap, "x", defs, prefix);
                if ap_check != "true" {
                    if known_pats.is_empty() {
                        body.push_str(&format!(
                            "for x in o.values() {{ if !{ap_check} {{ return false; }} }}\n"
                        ));
                    } else {
                        body.push_str(&format!(
                            "for (k, x) in o {{ if !{known_match} {{ if !{ap_check} {{ return false; }} }} }}\n"
                        ));
                    }
                }
            }
            AdditionalProperties::Allowed => {}
        }
    }

    // propertyNames
    if let Some(pn) = &obj.property_names {
        let pn_check = emit_check(pn, "kvr", defs, prefix);
        if pn_check != "true" && pn_check != "kvr.is_string()" {
            body.push_str(&format!(
                "for k in o.keys() {{ let kv = serde_json::Value::String(k.clone()); let kvr = &kv; if !{pn_check} {{ return false; }} }}\n"
            ));
        }
    }
    // dependentRequired
    for (prop, required) in &obj.dependent_required {
        for r in required {
            body.push_str(&format!(
                "if o.contains_key(\"{}\") && !o.contains_key(\"{}\") {{ return false; }}\n",
                esc(prop),
                esc(r)
            ));
        }
    }
    // dependentSchemas — validated against the whole object value.
    for (prop, dep_schema) in &obj.dependent_schemas {
        let dep_check = emit_check(dep_schema, "v", defs, prefix);
        if dep_check != "true" {
            body.push_str(&format!(
                "if o.contains_key(\"{}\") {{ if !{dep_check} {{ return false; }} }}\n",
                esc(prop)
            ));
        }
    }

    if body.is_empty() {
        return format!("{var}.is_object()");
    }
    let full = format!(
        "let o = match v.as_object() {{ Some(o) => o, None => return false }};\n{body}true"
    );
    bool_closure(&full, var)
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Converter;
    use serde_json::json;

    fn emit(schema: serde_json::Value) -> String {
        let converted = Converter::convert(&schema).unwrap();
        RustEmitter.emit_with_options(&converted, "sample", &EmitOptions::default())
    }

    fn emit_shared(schema: serde_json::Value) -> (String, HelperSet) {
        let converted = Converter::convert(&schema).unwrap();
        let options = EmitOptions {
            helpers: Some(super::super::SharedHelpers::new("jst_helpers.rs")),
            ..EmitOptions::default()
        };
        RustEmitter.emit_collecting(&converted, "sample", &options)
    }

    #[test]
    fn object_typed_struct() {
        let out = emit(json!({
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "qty": {"type": "integer"},
                "tags": {"type": "array", "items": {"type": "string"}}
            },
            "required": ["id", "qty"]
        }));
        assert!(out.contains("pub struct Sample {"), "{out}");
        assert!(out.contains("pub id: String"), "{out}");
        assert!(out.contains("pub qty: serde_json::Number"), "{out}");
        assert!(out.contains("pub tags: Option<Vec<String>>"), "{out}");
        assert!(out.contains("_jst_from_value"), "{out}");
    }

    #[test]
    fn integer_multiple_of_uses_num_helper() {
        let out = emit(json!({"type": "integer", "multipleOf": 0.5}));
        assert!(out.contains("_jst_multiple_of("), "{out}");
        assert!(out.contains("_jst_is_integer("), "{out}");
        // Inline mode appends the num helper snippet.
        assert!(out.contains("pub fn _jst_multiple_of"), "{out}");
    }

    #[test]
    fn unique_items_uses_canonical() {
        let out = emit(json!({"type": "array", "items": {"type": "number"}, "uniqueItems": true}));
        assert!(out.contains("_jst_canonical("), "{out}");
        assert!(out.contains("pub fn _jst_canonical"), "{out}");
    }

    #[test]
    fn const_object_uses_eq() {
        let out = emit(json!({"const": {"a": 1}}));
        assert!(out.contains("_jst_eq("), "{out}");
    }

    #[test]
    fn one_of_exactly_one() {
        let out = emit(json!({"oneOf": [
            {"type": "integer", "multipleOf": 5},
            {"type": "integer", "multipleOf": 3}
        ]}));
        assert!(out.contains("count() == 1"), "{out}");
        assert!(out.contains("pub struct Sample(pub serde_json::Value)"), "{out}");
    }

    #[test]
    fn string_enum_emits_rust_enum() {
        let out = emit(json!({"enum": ["red", "green-blue"]}));
        assert!(out.contains("pub enum Sample"), "{out}");
        assert!(out.contains("#[serde(rename = \"green-blue\")]"), "{out}");
    }

    #[test]
    fn recursive_ref_boxed() {
        let out = emit(json!({
            "$defs": {
                "node": {
                    "type": "object",
                    "properties": {
                        "value": {"type": "string"},
                        "next": {"$ref": "#/$defs/node"}
                    },
                    "required": ["value"]
                }
            },
            "$ref": "#/$defs/node"
        }));
        assert!(out.contains("Box<SampleNode>"), "{out}");
        assert!(out.contains("pub type Sample = SampleNode;"), "{out}");
    }

    #[test]
    fn keyword_field_renamed() {
        let out = emit(json!({
            "type": "object",
            "properties": {"type": {"type": "string"}},
            "required": ["type"]
        }));
        assert!(out.contains("pub r#type: String"), "{out}");
        assert!(out.contains("#[serde(rename = \"type\")]"), "{out}");
    }

    #[test]
    fn collection_mode_uses_shared_helpers() {
        let (out, needs) = emit_shared(json!({"const": {"a": 1}}));
        assert!(out.contains("use super::jst_helpers::*;"), "{out}");
        assert!(!out.contains("pub fn _jst_eq"), "{out}");
        assert!(needs.contains("eq"));
    }

    #[test]
    fn helpers_content_jsi_implies_eq() {
        let mut needs = HelperSet::default();
        needs.insert("jsi");
        let content = RustEmitter.helpers_content_for(&needs).unwrap();
        assert!(content.contains("pub fn _jst_eq"), "{content}");
        assert!(content.contains("pub fn _jst_jsi_validate"), "{content}");
    }

    #[test]
    fn format_maps_to_predicate() {
        let out = emit(json!({"type": "string", "format": "email"}));
        assert!(out.contains("_jst_is_email(s)"), "{out}");
        assert!(out.contains("pub fn _jst_is_email"), "{out}");
    }

    #[test]
    fn split_check_and_validate_methods() {
        let out = emit(json!({
            "type": "object",
            "properties": {"id": {"type": "string"}},
            "required": ["id"]
        }));
        assert!(out.contains("pub fn _jst_check"), "{out}");
        assert!(out.contains("pub fn validate"), "{out}");
        assert!(out.contains("pub fn to_validated_json"), "{out}");
        // _jst_from_value routes through _jst_check.
        assert!(out.contains("Self::_jst_check(v)?;"), "{out}");
    }

    #[test]
    fn enum_and_newtype_get_validate() {
        let e = emit(json!({"enum": ["red", "blue"]}));
        assert!(e.contains("pub fn _jst_check"), "{e}");
        assert!(e.contains("pub fn validate"), "{e}");
        assert!(e.contains("Self::_jst_check(v)?;"), "{e}");
        let n = emit(json!({"type": "string", "minLength": 1}));
        assert!(n.contains("pub fn _jst_check"), "{n}");
        assert!(n.contains("pub fn to_validated_json"), "{n}");
    }

    #[test]
    fn ref_check_recurses_into_jst_check() {
        let out = emit(json!({
            "$defs": {"node": {"type": "object", "properties": {"v": {"type": "string"}}, "required": ["v"]}},
            "type": "object",
            "properties": {"n": {"$ref": "#/$defs/node"}},
            "required": ["n"]
        }));
        assert!(out.contains("SampleNode::_jst_check("), "{out}");
    }

    #[test]
    fn mutable_flag_is_noop() {
        let schema = json!({
            "type": "object",
            "properties": {"id": {"type": "string"}},
            "required": ["id"]
        });
        let converted = Converter::convert(&schema).unwrap();
        let plain = RustEmitter.emit_with_options(&converted, "sample", &EmitOptions::default());
        let mutable = RustEmitter.emit_with_options(
            &converted,
            "sample",
            &EmitOptions {
                mutable: true,
                ..EmitOptions::default()
            },
        );
        assert_eq!(plain, mutable);
    }

    #[test]
    fn interpreted_embeds_schema() {
        let out = emit(json!({
            "type": "object",
            "properties": {"a": {"type": "string"}},
            "unevaluatedProperties": false
        }));
        assert!(out.contains("_jst_jsi_validate("), "{out}");
    }
}
