#!/usr/bin/env bun
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';

/**
 * Rust conformance harness: assemble a scratch cargo project from the
 * generated fixtures + jst_helpers, generate src/main.rs from the manifest,
 * compile everything in one cargo invocation, run the whole suite in one
 * process, write conformance/results/rust.json.
 *
 *   bun conformance/rust/run.ts
 *
 * Files that fail to compile are excluded iteratively (their groups are
 * marked all-tests-failed with the compiler error as the reason).
 */
import { $ } from 'bun';

const HERE = import.meta.dir;
const ROOT = resolve(HERE, '../..');
const GEN_DIR = join(ROOT, 'conformance/generated/rust');
const MANIFEST = join(ROOT, 'conformance/generated/manifest.json');
const BUILD = join(HERE, 'build');
const PROJECT = join(BUILD, 'runner');
const SRC = join(PROJECT, 'src');
const RESULTS_DIR = join(ROOT, 'conformance/results');
const RESULTS = join(RESULTS_DIR, 'rust.json');
const EXCLUSIONS = join(BUILD, 'exclusions.json');
const MAX_ATTEMPTS = 6;

const CARGO_TOML = `# AUTO-GENERATED by conformance/rust/run.ts — DO NOT EDIT
[package]
name = "jst-conformance-runner"
version = "0.0.0"
edition = "2021"
publish = false

# Detach from the repository workspace
[workspace]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"

[profile.dev]
debug = false
`;

interface Exclusions {
  files: Record<string, string>;
}

/** Parse cargo/rustc errors and add offending generated files to the exclusions. */
function addExclusions(log: string, exclusions: Exclusions): number {
  let added = 0;
  // rustc error locations look like: `  --> src/ref_g35.rs:12:5`; associate
  // each with the nearest preceding `error[...]:` / `error:` message line.
  // Warning locations must NOT be attributed: reset on `warning:` lines and
  // only exclude while inside an error diagnostic.
  const lines = log.split('\n');
  let lastError = '';
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^error(\[[^\]]+\])?:/.test(trimmed)) {
      lastError = trimmed;
      continue;
    }
    if (/^warning(\[[^\]]+\])?:/.test(trimmed)) {
      lastError = '';
      continue;
    }
    if (lastError === '') continue;
    const m = line.match(/-->\s+src\/([a-z0-9_]+\.rs):\d+:\d+/);
    if (!m) continue;
    const base = m[1]!;
    if (base === 'main.rs' || base === 'jst_helpers.rs') continue;
    if (exclusions.files[base] === undefined) {
      const reason = `compile error: ${lastError.slice(0, 200)}`;
      exclusions.files[base] = reason;
      console.log(`  excluding ${base} (${reason})`);
      added++;
    }
  }
  return added;
}

function errorSummary(log: string): string[] {
  const counts = new Map<string, number>();
  for (const line of log.split('\n')) {
    if (!/^error(\[[^\]]+\])?:/.test(line.trim())) continue;
    const msg = line.trim();
    counts.set(msg, (counts.get(msg) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([msg, n]) => `  ${n}× ${msg}`);
}

if (!existsSync(GEN_DIR)) {
  console.error(`generated fixtures not found: ${GEN_DIR} — run \`bun run generate\` first`);
  process.exit(1);
}

rmSync(SRC, { recursive: true, force: true });
mkdirSync(SRC, { recursive: true });
mkdirSync(RESULTS_DIR, { recursive: true });
writeFileSync(join(PROJECT, 'Cargo.toml'), CARGO_TOML);
const LOCK_TEMPLATE = join(HERE, 'Cargo.lock.template');
if (existsSync(LOCK_TEMPLATE) && !existsSync(join(PROJECT, 'Cargo.lock'))) {
  copyFileSync(LOCK_TEMPLATE, join(PROJECT, 'Cargo.lock'));
}

// Copy all generated fixtures + helpers into the scratch project. Excluded
// files keep their sources around; only their `mod` declarations go away.
const fixtures = readdirSync(GEN_DIR).filter((f) => f.endsWith('.rs'));
for (const f of fixtures) {
  copyFileSync(join(GEN_DIR, f), join(SRC, f));
}

const exclusions: Exclusions = { files: {} };
const compileStart = Date.now();
let compiled = false;
let lastLog = '';

for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
  // 1. (Re)generate src/main.rs honouring current exclusions
  writeFileSync(EXCLUSIONS, JSON.stringify(exclusions, null, 2) + '\n');
  const gen =
    await $`bun ${join(HERE, 'gen-runner.ts')} ${MANIFEST} ${EXCLUSIONS} ${join(SRC, 'main.rs')}`.nothrow();
  if (gen.exitCode !== 0) process.exit(gen.exitCode);

  const excludedCount = Object.keys(exclusions.files).length;
  console.log(
    `[attempt ${attempt}] compiling ${fixtures.length - excludedCount} fixtures + runner...`
  );
  const result = await $`cargo build --manifest-path ${join(PROJECT, 'Cargo.toml')}`
    .quiet()
    .nothrow();
  lastLog = result.stdout.toString() + result.stderr.toString();
  writeFileSync(join(BUILD, 'cargo.log'), lastLog);

  if (result.exitCode === 0) {
    compiled = true;
    break;
  }

  // 2. Parse errors, exclude offending generated files
  console.log(`[attempt ${attempt}] compile failed; error summary:`);
  for (const line of errorSummary(lastLog)) console.log(line);

  if (addExclusions(lastLog, exclusions) === 0) {
    console.error(
      'compile errors are not attributable to generated fixtures (main.rs, jst_helpers.rs, or toolchain problem):'
    );
    console.error(lastLog.split('\n').slice(0, 40).join('\n'));
    process.exit(1);
  }
}

if (!compiled) {
  console.error(`compilation still failing after ${MAX_ATTEMPTS} attempts`);
  process.exit(1);
}

const compileTime = ((Date.now() - compileStart) / 1000).toFixed(0);
console.log(
  `compile OK in ${compileTime}s (excluded files: ${Object.keys(exclusions.files).length})`
);

// 3. Run the whole suite in one process
const runStart = Date.now();
const binary = join(PROJECT, 'target/debug/jst-conformance-runner');
const run = await $`${binary} ${MANIFEST} ${RESULTS}`.nothrow();
console.log(
  `compile time: ${compileTime}s, run time: ${((Date.now() - runStart) / 1000).toFixed(0)}s`
);
console.log(`results written to ${RESULTS}`);
process.exit(run.exitCode);
