use crate::ir::*;
use crate::util::to_pascal_case;
use super::Emitter;

pub struct KotlinEmitter;

impl Emitter for KotlinEmitter {
    fn extension(&self) -> &str {
        "kt"
    }

    fn emit(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        namespace: &str,
        version: u32,
    ) -> String {
        let pascal = to_pascal_case(name);
        let mut out = String::new();

        out.push_str(&format!(
            "// Generated by event-registry\n// {namespace}/{name}@{version}\n// DO NOT EDIT — changes will be overwritten on next pull\n\n"
        ));

        let package = namespace.replace('-', "_").replace('.', "_");
        out.push_str(&format!("package {package}.events\n\n"));

        // Emit body first so we can scan for needed imports.
        // All $defs type names are prefixed with the root pascal name so that
        // hundreds of generated files can be compiled into a single Kotlin
        // module without top-level name collisions (e.g. `Foo` in many files).
        let mut counter = 0usize;
        let mut body = String::new();
        for def in &converted.defs {
            let safe_name = sanitize_kotlin_name(&def.name, &pascal);
            body.push_str(&emit_definition(&safe_name, &def.schema, &converted.defs, &pascal, &mut counter));
            body.push_str("\n\n");
        }
        body.push_str(&emit_definition(
            &format!("{pascal}V{version}Data"),
            &converted.root,
            &converted.defs,
            &pascal,
            &mut counter,
        ));
        body.push('\n');

        // Determine which imports are actually needed
        let needs_serial_name = body.contains("@SerialName(");
        let needs_json_element = body.contains("JsonElement");
        let needs_canonicalize = body.contains("_canonicalize(");
        let needs_json_object = body.contains("JsonObject") || needs_canonicalize;
        let needs_json_primitive = body.contains("JsonPrimitive")
            || body.contains("jsonPrimitive")
            || body.contains("JsonNull");
        let needs_json_array = body.contains("JsonArray") || body.contains("jsonArray");
        let needs_kserializer = body.contains("KSerializer");
        let needs_json_content = body.contains("JsonContentPolymorphicSerializer")
            || body.contains("jsonObject");

        if needs_serial_name {
            out.push_str("import kotlinx.serialization.SerialName\n");
        }
        out.push_str("import kotlinx.serialization.Serializable\n");
        if needs_kserializer {
            out.push_str("import kotlinx.serialization.KSerializer\n");
            out.push_str("import kotlinx.serialization.descriptors.SerialDescriptor\n");
            out.push_str("import kotlinx.serialization.encoding.Decoder\n");
            out.push_str("import kotlinx.serialization.encoding.Encoder\n");
        }
        if needs_json_element {
            out.push_str("import kotlinx.serialization.json.JsonElement\n");
        }
        if needs_json_object || needs_json_content {
            out.push_str("import kotlinx.serialization.json.JsonObject\n");
            out.push_str("import kotlinx.serialization.json.jsonObject\n");
        }
        if needs_json_primitive {
            out.push_str("import kotlinx.serialization.json.JsonPrimitive\n");
            out.push_str("import kotlinx.serialization.json.JsonNull\n");
            out.push_str("import kotlinx.serialization.json.jsonPrimitive\n");
            out.push_str("import kotlinx.serialization.json.intOrNull\n");
            out.push_str("import kotlinx.serialization.json.longOrNull\n");
            out.push_str("import kotlinx.serialization.json.doubleOrNull\n");
            out.push_str("import kotlinx.serialization.json.booleanOrNull\n");
            out.push_str("import kotlinx.serialization.json.contentOrNull\n");
        }
        if needs_json_array {
            out.push_str("import kotlinx.serialization.json.JsonArray\n");
            out.push_str("import kotlinx.serialization.json.jsonArray\n");
        }
        out.push('\n');

        // Emit helper functions
        if body.contains("_canonicalize(") {
            out.push_str(concat!(
                "private fun _canonicalize(el: JsonElement): String = when (el) {\n",
                "    is JsonObject -> \"{\" + el.entries.sortedBy { it.key }.joinToString(\",\") { \"\\\"${it.key}\\\":${_canonicalize(it.value)}\" } + \"}\"\n",
                "    is JsonArray -> \"[\" + el.joinToString(\",\") { _canonicalize(it) } + \"]\"\n",
                "    else -> el.toString()\n",
                "}\n\n",
            ));
        }

        out.push_str(&body);
        out
    }
}

// ── Kotlin string escaping ───────────────────────────────────────────────────

fn escape_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => vec!['\\', '"'],
            '\\' => vec!['\\', '\\'],
            '\n' => vec!['\\', 'n'],
            '\r' => vec!['\\', 'r'],
            '\t' => vec!['\\', 't'],
            '$' => vec!['\\', '$'],
            c if c.is_control() => {
                format!("\\u{:04X}", c as u32).chars().collect()
            }
            other => vec![other],
        })
        .collect()
}

// ── Name sanitization ───────────────────────────────────────────────────────

const KOTLIN_RESERVED_TYPES: &[&str] = &[
    "Int", "Long", "Short", "Byte", "Double", "Float", "Boolean", "Char",
    "String", "Unit", "Nothing", "Any", "Number",
    "Array", "List", "Map", "Set", "Pair", "Triple",
    "Comparable", "Enum", "Error", "Exception",
    "Result", "Sequence",
];

/// Sanitize a `$defs` type name and prefix it with the root type's pascal
/// name so definitions from different generated files never collide when
/// compiled together as one module. Names that sanitize to nothing (e.g. a
/// `$defs` key of "") become `{prefix}AnonymousDef`.
fn sanitize_kotlin_name(name: &str, prefix: &str) -> String {
    let mut cleaned: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if cleaned.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        cleaned.insert(0, 'N');
    }
    if cleaned.is_empty() {
        cleaned = "AnonymousDef".to_string();
    } else if KOTLIN_RESERVED_TYPES.contains(&cleaned.as_str()) {
        cleaned.push_str("Schema");
    }
    format!("{prefix}{cleaned}")
}

// ── Definition dispatch ─────────────────────────────────────────────────────

fn emit_definition(name: &str, ir: &SchemaIr, defs: &[DefEntry], prefix: &str, counter: &mut usize) -> String {
    match ir {
        SchemaIr::Object(obj) => {
            let needs_custom = matches!(obj.additional_properties, AdditionalProperties::Forbidden | AdditionalProperties::Schema(_))
                || !obj.pattern_properties.is_empty()
                || obj.property_names.is_some()
                || obj.min_properties.is_some()
                || obj.max_properties.is_some()
                || !obj.dependent_schemas.is_empty();
            if needs_custom {
                emit_wrapper(name, ir, defs, counter)
            } else {
                emit_data_class(name, obj, defs, prefix)
            }
        }
        SchemaIr::Enum(cases) if !cases.is_empty() => emit_enum_class(name, cases),
        SchemaIr::Enum(_) => emit_never_class(name, counter), // empty enum
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => {
            emit_definition(name, inner, defs, prefix, counter)
        }
        SchemaIr::Nullable(inner) => {
            // For nullable, emit the inner as a separate type and alias
            if matches!(inner.as_ref(), SchemaIr::Object(_)) {
                emit_definition(name, inner, defs, prefix, counter)
            } else {
                emit_wrapper(name, ir, defs, counter)
            }
        }
        SchemaIr::Ref(ref_name) => {
            let safe = sanitize_kotlin_name(ref_name, prefix);
            format!("typealias {name} = {safe}")
        }
        _ => emit_wrapper(name, ir, defs, counter),
    }
}

// ── Object data class ───────────────────────────────────────────────────────

fn emit_data_class(name: &str, obj: &ObjectSchema, defs: &[DefEntry], prefix: &str) -> String {
    let mut lines = vec!["@Serializable".to_string()];

    if obj.fields.is_empty() {
        lines.push(format!("data class {name}("));
        lines.push("    val placeholder: Unit = Unit".to_string());
        lines.push(")".to_string());
    } else {
        lines.push(format!("data class {name}("));

        let fields: Vec<String> = obj
            .fields
            .iter()
            .map(|(k, f)| {
                let kt_name = to_camel_case(k);
                let kt_type = kotlin_type(&f.schema, defs, prefix);

                let type_str = if f.required {
                    kt_type
                } else {
                    format!("{kt_type}?")
                };

                let serial_name = if kt_name != *k {
                    format!("    @SerialName(\"{}\")\n", escape_string(k))
                } else {
                    String::new()
                };

                let default = if !f.required { " = null" } else { "" };

                format!("{serial_name}    val {kt_name}: {type_str}{default}")
            })
            .collect();

        lines.push(fields.join(",\n"));
        lines.push(")".to_string());
    }

    lines.join("\n")
}

// ── Enum class ──────────────────────────────────────────────────────────────

fn emit_enum_class(name: &str, cases: &[String]) -> String {
    let mut lines = vec!["@Serializable".to_string()];
    lines.push(format!("enum class {name} {{"));
    let mut seen: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let entries: Vec<String> = cases
        .iter()
        .map(|c| {
            let mut kt_name: String = c.chars()
                .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_' || *ch == '-')
                .collect::<String>()
                .to_uppercase()
                .replace('-', "_");
            if kt_name.is_empty() {
                kt_name = "VALUE".to_string();
            }
            // Deduplicate
            let count = seen.entry(kt_name.clone()).or_insert(0);
            *count += 1;
            if *count > 1 {
                kt_name = format!("{kt_name}_{count}");
            }
            // Always use @SerialName for the raw JSON value
            format!(
                "    @SerialName(\"{}\") {}",
                escape_string(c),
                kt_name
            )
        })
        .collect();
    lines.push(entries.join(",\n"));
    lines.push("}".to_string());
    lines.join("\n")
}

// ── Wrapper class with custom serializer ────────────────────────────────────

fn emit_wrapper(name: &str, ir: &SchemaIr, defs: &[DefEntry], counter: &mut usize) -> String {
    let inner = unwrap_modifiers(ir);
    let is_nullable = matches!(ir, SchemaIr::Nullable(_));

    *counter += 1;
    let ser_name = format!("{name}Ser");

    let validation = emit_validation(inner, defs, counter);

    let mut out = String::new();

    out.push_str(&format!(
        "private object {ser_name} : KSerializer<{name}> {{\n"
    ));
    out.push_str(&format!(
        "    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor\n"
    ));
    out.push_str(&format!(
        "    override fun deserialize(decoder: Decoder): {name} {{\n"
    ));
    out.push_str(
        "        val el = decoder.decodeSerializableValue(JsonElement.serializer())\n",
    );
    if is_nullable {
        out.push_str(&format!("        if (el is JsonNull) return {name}(el)\n"));
    }
    out.push_str(&validation);
    out.push_str(&format!("        return {name}(el)\n"));
    out.push_str("    }\n");
    out.push_str(&format!(
        "    override fun serialize(encoder: Encoder, value: {name}) {{\n"
    ));
    out.push_str(
        "        encoder.encodeSerializableValue(JsonElement.serializer(), value.element)\n",
    );
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "@Serializable(with = {ser_name}::class)\n"
    ));
    out.push_str(&format!("class {name}(val element: JsonElement)"));

    out
}

fn unwrap_modifiers(ir: &SchemaIr) -> &SchemaIr {
    match ir {
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Nullable(inner) => {
            unwrap_modifiers(inner)
        }
        _ => ir,
    }
}

// ── Validation code generation ──────────────────────────────────────────────

fn emit_validation(ir: &SchemaIr, defs: &[DefEntry], counter: &mut usize) -> String {
    match ir {
        SchemaIr::Integer(c) => {
            let mut checks = Vec::new();
            checks.push(
                "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == null) { \"must be an integer, not string or boolean\" }"
                    .to_string(),
            );
            checks.push(
                "        val v = (el as JsonPrimitive).longOrNull ?: (el as JsonPrimitive).doubleOrNull?.let { if (it == it.toLong().toDouble()) it.toLong() else null } ?: error(\"must be an integer\")"
                    .to_string(),
            );
            emit_number_checks(&mut checks, c, "v", true);
            checks.join("\n") + "\n"
        }
        SchemaIr::Number(c) => {
            let mut checks = Vec::new();
            checks.push(
                "        require(el is JsonPrimitive && !el.isString && el.booleanOrNull == null) { \"must be a number, not string or boolean\" }"
                    .to_string(),
            );
            checks.push(
                "        val v = (el as JsonPrimitive).doubleOrNull ?: error(\"must be a number\")"
                    .to_string(),
            );
            emit_number_checks(&mut checks, c, "v", false);
            checks.join("\n") + "\n"
        }
        SchemaIr::Boolean => {
            "        require(el is JsonPrimitive && el.booleanOrNull != null) { \"must be a boolean\" }\n"
                .to_string()
        }
        SchemaIr::String(c) => {
            let mut checks = Vec::new();
            checks.push(
                "        require(el is JsonPrimitive && el.isString) { \"must be a string\" }"
                    .to_string(),
            );
            checks.push("        val v = el.content".to_string());
            if let Some(min) = c.min_length {
                checks.push(format!("        require(v.length >= {min}) {{ \"minLength\" }}"));
            }
            if let Some(max) = c.max_length {
                checks.push(format!("        require(v.length <= {max}) {{ \"maxLength\" }}"));
            }
            if let Some(ref pat) = c.pattern {
                checks.push(format!(
                    "        require(Regex(\"{}\").containsMatchIn(v)) {{ \"pattern\" }}",
                    escape_string(pat)
                ));
            }
            checks.join("\n") + "\n"
        }
        SchemaIr::Null => {
            "        require(el is JsonNull) { \"must be null\" }\n".to_string()
        }
        SchemaIr::Any | SchemaIr::Unknown => String::new(), // accept anything
        SchemaIr::Never => {
            "        error(\"schema rejects all values\")\n".to_string()
        }
        SchemaIr::Literal(lit) => emit_literal_check(lit),
        SchemaIr::ConstEqual(val) => {
            let json_str = serde_json::to_string(val).unwrap_or_else(|_| "null".to_string());
            let escaped = escape_string(&json_str);
            format!(
                "        val expected = kotlinx.serialization.json.Json.parseToJsonElement(\"{}\")\n        require(el == expected) {{ \"must equal const value\" }}\n",
                escaped
            )
        }
        SchemaIr::MixedEnum(lits) => {
            let checks: Vec<String> = lits.iter().map(|l| emit_literal_match(l)).collect();
            let condition = checks.join(" || ");
            format!(
                "        require({condition}) {{ \"must be one of the allowed values\" }}\n"
            )
        }
        SchemaIr::ComplexEnum(vals) => {
            let json_str = serde_json::to_string(vals).unwrap_or_else(|_| "[]".to_string());
            let escaped = escape_string(&json_str);
            format!(
                "        val allowed = kotlinx.serialization.json.Json.parseToJsonElement(\"{escaped}\") as JsonArray\n        require(el in allowed) {{ \"must be one of the allowed values\" }}\n"
            )
        }
        SchemaIr::Array(arr) => emit_array_validation(arr, defs, counter),
        SchemaIr::Tuple(tuple) => emit_tuple_validation(tuple, defs, counter),
        SchemaIr::TypeGuarded(guards) => emit_type_guarded_validation(guards, defs, counter),
        SchemaIr::Not { base: _, not_schema } => {
            let not_check = emit_not_check(not_schema, defs, counter);
            format!("{not_check}")
        }
        SchemaIr::Conditional { base: _, if_schema, then_schema, else_schema } => {
            emit_conditional_check(if_schema, then_schema.as_deref(), else_schema.as_deref(), defs, counter)
        }
        SchemaIr::Union(members) if members.len() > 1 => {
            emit_union_check(members, defs, counter, false)
        }
        SchemaIr::ExclusiveUnion(members) if members.len() > 1 => {
            emit_union_check(members, defs, counter, true)
        }
        SchemaIr::Intersection(members) if members.len() == 1 => {
            emit_validation(&members[0], defs, counter)
        }
        SchemaIr::Intersection(members) if members.len() > 1 => {
            // Wrap each member in `run { }` so local vals (v, obj, arr, known…)
            // declared by one member's checks don't conflict with the next.
            let mut checks = String::new();
            for member in members {
                let v = emit_validation(member, defs, counter);
                if v.is_empty() {
                    continue;
                }
                checks.push_str(&format!("        run {{\n    {}\n        }}\n", v.trim_end().replace('\n', "\n    ")));
            }
            checks
        }
        SchemaIr::Record(rec) => {
            let mut checks = String::new();
            checks.push_str("        require(el is JsonObject) { \"must be an object\" }\n");
            if !matches!(rec.value.as_ref(), SchemaIr::Any | SchemaIr::Unknown) {
                // Validate each value
                let val_check = emit_inline_check(&rec.value, "v", defs);
                if !val_check.is_empty() {
                    checks.push_str(&format!(
                        "        for ((_, v) in el.jsonObject) {{ {} }}\n",
                        val_check
                    ));
                }
            }
            checks
        }
        SchemaIr::Object(obj) => {
            let mut checks = Vec::new();
            checks.push("        require(el is JsonObject) { \"must be an object\" }".to_string());
            checks.push("        val obj = el.jsonObject".to_string());
            for (k, f) in &obj.fields {
                if f.required {
                    checks.push(format!(
                        "        require(\"{}\" in obj) {{ \"required: {}\" }}",
                        escape_string(k), escape_string(k)
                    ));
                }
                let field_check = emit_inline_check(&f.schema, &format!("obj[\"{}\"]!!", escape_string(k)), defs);
                if !field_check.is_empty() && !matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) {
                    checks.push(format!(
                        "        if (\"{}\" in obj) {{ {} }}",
                        escape_string(k), field_check
                    ));
                }
            }
            if let Some(min) = obj.min_properties {
                checks.push(format!("        require(obj.size >= {min}) {{ \"minProperties\" }}"));
            }
            if let Some(max) = obj.max_properties {
                checks.push(format!("        require(obj.size <= {max}) {{ \"maxProperties\" }}"));
            }
            // patternProperties + additionalProperties interaction
            if !obj.pattern_properties.is_empty() {
                let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                checks.push("        for ((k, v) in obj) {".to_string());
                checks.push(format!("            var matched = setOf<String>({}).contains(k)", known.join(", ")));
                for (pattern, pp_schema) in &obj.pattern_properties {
                    let pp_check = emit_inline_check(pp_schema, "v", defs);
                    if !pp_check.is_empty() {
                        checks.push(format!(
                            "            if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true; {} }}",
                            escape_string(pattern), pp_check
                        ));
                    } else {
                        checks.push(format!(
                            "            if (Regex(\"{}\").containsMatchIn(k)) {{ matched = true }}",
                            escape_string(pattern)
                        ));
                    }
                }
                if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                    checks.push("            require(matched) { \"unexpected property: $k\" }".to_string());
                } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                    let ap_check = emit_inline_check(ap, "v", defs);
                    if !ap_check.is_empty() {
                        checks.push(format!("            if (!matched) {{ {} }}", ap_check));
                    }
                }
                checks.push("        }".to_string());
            } else if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                checks.push(format!(
                    "        val known = setOf<String>({})",
                    known.join(", ")
                ));
                checks.push("        for (k in obj.keys) { require(k in known) { \"unexpected property: $k\" } }".to_string());
            } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                let ap_check = emit_inline_check(ap, "v", defs);
                if !ap_check.is_empty() {
                    checks.push(format!(
                        "        val _known = setOf<String>({})\n        for ((k, v) in obj) {{ if (k !in _known) {{ {} }} }}",
                        known.join(", "), ap_check
                    ));
                }
            }
            // propertyNames
            if let Some(pn) = &obj.property_names {
                emit_property_names_checks(pn, &mut checks, "        ");
            }
            // dependentRequired
            for (prop, required) in &obj.dependent_required {
                for r in required {
                    checks.push(format!(
                        "        if (\"{}\" in obj) require(\"{}\" in obj) {{ \"dependentRequired\" }}",
                        escape_string(prop), escape_string(r)
                    ));
                }
            }
            // dependentSchemas
            for (prop, dep_schema) in &obj.dependent_schemas {
                let dep_check = emit_match_expression(dep_schema, "el", defs);
                if dep_check != "true" {
                    checks.push(format!(
                        "        if (\"{}\" in obj) {{ require({}) {{ \"dependentSchemas\" }} }}",
                        escape_string(prop), dep_check
                    ));
                }
            }
            // NOTE: additionalProperties-with-schema is fully handled in the
            // pattern-properties/else-if chain above; emitting it again here
            // used to produce a conflicting duplicate `val _known`.
            if checks.len() <= 2 {
                // Only the require(el is JsonObject) + val obj — no real validation
                "        require(el is JsonObject) { \"must be an object\" }\n".to_string()
            } else {
                checks.join("\n") + "\n"
            }
        }
        SchemaIr::Ref(_) | SchemaIr::Lazy(_) => String::new(), // handled by typealias
        _ => String::new(),
    }
}

fn emit_number_checks(checks: &mut Vec<String>, c: &NumberConstraints, var_name: &str, _is_int: bool) {
    if let Some(min) = c.minimum {
        let b = format_kt_number(min);
        checks.push(format!("        require({var_name} >= {b}) {{ \"minimum\" }}"));
    }
    if let Some(max) = c.maximum {
        let b = format_kt_number(max);
        checks.push(format!("        require({var_name} <= {b}) {{ \"maximum\" }}"));
    }
    if let Some(emin) = c.exclusive_minimum {
        let b = format_kt_number(emin);
        checks.push(format!("        require({var_name} > {b}) {{ \"exclusiveMinimum\" }}"));
    }
    if let Some(emax) = c.exclusive_maximum {
        let b = format_kt_number(emax);
        checks.push(format!("        require({var_name} < {b}) {{ \"exclusiveMaximum\" }}"));
    }
    if let Some(mul) = c.multiple_of {
        let b = format_kt_number(mul);
        checks.push(format!(
            "        require({var_name}.toDouble().rem({b}).let {{ kotlin.math.abs(it) < 1e-9 || kotlin.math.abs(kotlin.math.abs(it) - {b}) < 1e-9 }}) {{ \"multipleOf\" }}"
        ));
    }
}

fn emit_literal_check(lit: &LiteralValue) -> String {
    match lit {
        LiteralValue::Bool(b) => format!(
            "        require(el is JsonPrimitive && el.booleanOrNull == {}) {{ \"must be {}\" }}\n",
            b, b
        ),
        LiteralValue::Integer(i) => format!(
            "        require(el is JsonPrimitive && el.booleanOrNull == null && (el.longOrNull == {i}L || el.doubleOrNull == {i}.0)) {{ \"must be {i}\" }}\n"
        ),
        LiteralValue::Number(n) => {
            let b = format_kt_number(*n);
            format!(
                "        require(el is JsonPrimitive && el.booleanOrNull == null && el.doubleOrNull == {b}) {{ \"must be {b}\" }}\n"
            )
        }
        LiteralValue::String(s) => {
            let escaped = escape_string(s);
            format!(
                "        require(el is JsonPrimitive && el.isString && el.content == \"{escaped}\") {{ \"must be \\\"{escaped}\\\"\" }}\n"
            )
        }
        LiteralValue::Null => {
            "        require(el is JsonNull) { \"must be null\" }\n".to_string()
        }
    }
}

fn emit_literal_match(lit: &LiteralValue) -> String {
    match lit {
        LiteralValue::Bool(b) => format!("(el is JsonPrimitive && el.booleanOrNull == {b})"),
        LiteralValue::Integer(i) => format!(
            "(el is JsonPrimitive && el.booleanOrNull == null && (el.longOrNull == {i}L || el.doubleOrNull == {i}.0))"
        ),
        LiteralValue::Number(n) => {
            let b = format_kt_number(*n);
            format!("(el is JsonPrimitive && el.booleanOrNull == null && el.doubleOrNull == {b})")
        }
        LiteralValue::String(s) => {
            let escaped = escape_string(s);
            format!("(el is JsonPrimitive && el.isString && el.content == \"{escaped}\")")
        }
        LiteralValue::Null => "(el is JsonNull)".to_string(),
    }
}

fn emit_inline_check(ir: &SchemaIr, var_name: &str, defs: &[DefEntry]) -> String {
    match ir {
        SchemaIr::Integer(c) if c.minimum.is_none() && c.maximum.is_none() && c.exclusive_minimum.is_none() && c.exclusive_maximum.is_none() && c.multiple_of.is_none() => {
            format!("require({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull == null && ({var_name}.jsonPrimitive.longOrNull != null || {var_name}.jsonPrimitive.doubleOrNull?.let {{ it == it.toLong().toDouble() }} == true))")
        }
        SchemaIr::Number(c) if c.minimum.is_none() && c.maximum.is_none() && c.exclusive_minimum.is_none() && c.exclusive_maximum.is_none() && c.multiple_of.is_none() => {
            format!("require({var_name} is JsonPrimitive && !{var_name}.jsonPrimitive.isString && {var_name}.jsonPrimitive.booleanOrNull == null && {var_name}.jsonPrimitive.doubleOrNull != null)")
        }
        SchemaIr::Boolean => format!("require({var_name} is JsonPrimitive && {var_name}.jsonPrimitive.booleanOrNull != null)"),
        SchemaIr::String(c) if c.min_length.is_none() && c.max_length.is_none() && c.pattern.is_none() => {
            format!("require({var_name} is JsonPrimitive && {var_name}.jsonPrimitive.isString)")
        }
        SchemaIr::Null => format!("require({var_name} is JsonNull)"),
        SchemaIr::Any | SchemaIr::Unknown => String::new(),
        SchemaIr::Never => format!("error(\"schema rejects all values\")"),
        _ => {
            // For complex schemas, use full validation via el rebinding
            let mut counter = 0usize;
            let validation = emit_validation(ir, defs, &mut counter);
            if validation.is_empty() {
                return String::new();
            }
            format!("run {{ val el = {var_name}; {} }}", validation.trim())
        }
    }
}

/// Generate a try/catch expression that returns true if `var_name` matches `ir`.
fn emit_match_expression(ir: &SchemaIr, var_name: &str, defs: &[DefEntry]) -> String {
    let mut counter = 0usize;
    let validation = emit_validation(ir, defs, &mut counter);
    if validation.is_empty() {
        return "true".to_string();
    }
    format!(
        "try {{ val el = {var_name}; {}; true }} catch (_: Exception) {{ false }}",
        validation.trim()
    )
}

fn emit_array_validation(arr: &ArraySchema, defs: &[DefEntry], _counter: &mut usize) -> String {
    let mut checks = Vec::new();
    checks.push("        require(el is JsonArray) { \"must be an array\" }".to_string());
    checks.push("        val arr = el.jsonArray".to_string());

    if let Some(min) = arr.min_items {
        checks.push(format!("        require(arr.size >= {min}) {{ \"minItems\" }}"));
    }
    if let Some(max) = arr.max_items {
        checks.push(format!("        require(arr.size <= {max}) {{ \"maxItems\" }}"));
    }

    // Item type validation
    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
        let item_check = emit_inline_check(&arr.items, "item", defs);
        if !item_check.is_empty() {
            checks.push(format!("        for (item in arr) {{ {item_check} }}"));
        }
    }

    if arr.unique_items {
        checks.push(
            "        require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                .to_string(),
        );
    }

    if let Some(contains) = &arr.contains {
        let contains_check = emit_inline_check(&contains.schema, "it", defs);
        let min = contains.min_contains.unwrap_or(1);
        if !contains_check.is_empty() {
            checks.push(format!(
                "        val matchCount = arr.count {{ try {{ {contains_check}; true }} catch (_: Exception) {{ false }} }}"
            ));
        } else {
            // contains schema is Any — every item matches
            checks.push("        val matchCount = arr.size".to_string());
        }
        checks.push(format!(
            "        require(matchCount >= {min}) {{ \"must contain at least {min} matching items\" }}"
        ));
        if let Some(max) = contains.max_contains {
            checks.push(format!(
                "        require(matchCount <= {max}) {{ \"must contain at most {max} matching items\" }}"
            ));
        }
    }

    checks.join("\n") + "\n"
}

fn emit_tuple_validation(tuple: &TupleSchema, defs: &[DefEntry], _counter: &mut usize) -> String {
    let mut checks = Vec::new();
    checks.push("        require(el is JsonArray) { \"must be an array\" }".to_string());
    checks.push("        val arr = el.jsonArray".to_string());

    // Prefix item type checks
    for (i, item) in tuple.items.iter().enumerate() {
        if matches!(item, SchemaIr::Any) {
            continue;
        }
        let item_check = emit_inline_check(item, &format!("arr[{i}]"), defs);
        if !item_check.is_empty() {
            checks.push(format!("        if (arr.size > {i}) {{ {item_check} }}"));
        }
    }

    let prefix_count = tuple.items.len();
    if let Some(rest) = &tuple.rest {
        if !matches!(rest.as_ref(), SchemaIr::Any) {
            let rest_check = emit_inline_check(rest, "arr[i]", defs);
            if !rest_check.is_empty() {
                checks.push(format!("        for (i in {prefix_count} until arr.size) {{ {rest_check} }}"));
            }
        }
    } else {
        checks.push(format!(
            "        require(arr.size <= {prefix_count}) {{ \"too many items\" }}"
        ));
    }

    if let Some(min) = tuple.min_items {
        checks.push(format!("        require(arr.size >= {min}) {{ \"minItems\" }}"));
    }
    if let Some(max) = tuple.max_items {
        checks.push(format!("        require(arr.size <= {max}) {{ \"maxItems\" }}"));
    }

    if tuple.unique_items {
        checks.push(
            "        require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                .to_string(),
        );
    }

    checks.join("\n") + "\n"
}

fn emit_type_guarded_validation(
    guards: &[(TypeGuard, Box<SchemaIr>)],
    defs: &[DefEntry],
    _counter: &mut usize,
) -> String {
    let mut checks = Vec::new();

    for (guard, schema) in guards {
        match guard {
            TypeGuard::String => {
                if let SchemaIr::String(c) = schema.as_ref() {
                    checks.push("        if (el is JsonPrimitive && el.isString) {".to_string());
                    checks.push("            val v = el.content".to_string());
                    if let Some(min) = c.min_length {
                        checks.push(format!("            require(v.length >= {min}) {{ \"minLength\" }}"));
                    }
                    if let Some(max) = c.max_length {
                        checks.push(format!("            require(v.length <= {max}) {{ \"maxLength\" }}"));
                    }
                    if let Some(ref pat) = c.pattern {
                        checks.push(format!(
                            "            require(Regex(\"{}\").containsMatchIn(v)) {{ \"pattern\" }}",
                            escape_string(pat)
                        ));
                    }
                    checks.push("        }".to_string());
                }
            }
            TypeGuard::Number => {
                let c = match schema.as_ref() {
                    SchemaIr::Number(c) | SchemaIr::Integer(c) => c,
                    _ => continue,
                };
                checks.push("        if (el is JsonPrimitive && !el.isString && el.booleanOrNull == null && el.doubleOrNull != null) {".to_string());
                checks.push("            val v = el.doubleOrNull!!".to_string());
                if let Some(min) = c.minimum {
                    let b = format_kt_number(min);
                    checks.push(format!("            require(v >= {b}) {{ \"minimum\" }}"));
                }
                if let Some(max) = c.maximum {
                    let b = format_kt_number(max);
                    checks.push(format!("            require(v <= {b}) {{ \"maximum\" }}"));
                }
                if let Some(emin) = c.exclusive_minimum {
                    let b = format_kt_number(emin);
                    checks.push(format!("            require(v > {b}) {{ \"exclusiveMinimum\" }}"));
                }
                if let Some(emax) = c.exclusive_maximum {
                    let b = format_kt_number(emax);
                    checks.push(format!("            require(v < {b}) {{ \"exclusiveMaximum\" }}"));
                }
                if let Some(mul) = c.multiple_of {
                    let b = format_kt_number(mul);
                    checks.push(format!(
                        "            require(v.rem({b}).let {{ kotlin.math.abs(it) < 1e-9 || kotlin.math.abs(kotlin.math.abs(it) - {b}) < 1e-9 }}) {{ \"multipleOf\" }}"
                    ));
                }
                checks.push("        }".to_string());
            }
            TypeGuard::Object => {
                if let SchemaIr::Object(obj) = schema.as_ref() {
                    checks.push("        if (el is JsonObject) {".to_string());
                    checks.push("            val obj = el.jsonObject".to_string());
                    for (k, f) in &obj.fields {
                        if f.required {
                            checks.push(format!(
                                "            require(\"{}\" in obj) {{ \"required: {}\" }}",
                                escape_string(k), escape_string(k)
                            ));
                        }
                        // Field type validation
                        let field_check = emit_inline_check(&f.schema, &format!("obj[\"{}\"]!!", escape_string(k)), defs);
                        if !field_check.is_empty() && !matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) {
                            checks.push(format!(
                                "            if (\"{}\" in obj) {{ {} }}",
                                escape_string(k), field_check
                            ));
                        }
                    }
                    if let Some(min) = obj.min_properties {
                        checks.push(format!("            require(obj.size >= {min}) {{ \"minProperties\" }}"));
                    }
                    if let Some(max) = obj.max_properties {
                        checks.push(format!("            require(obj.size <= {max}) {{ \"maxProperties\" }}"));
                    }
                    if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                        checks.push(format!(
                            "            val known = setOf<String>({})",
                            known.join(", ")
                        ));
                        checks.push("            for (k in obj.keys) { require(k in known) { \"unexpected property: $k\" } }".to_string());
                    }
                    // propertyNames
                    if let Some(pn) = &obj.property_names {
                        emit_property_names_checks(pn, &mut checks, "            ");
                    }
                    // dependentRequired
                    for (prop, required) in &obj.dependent_required {
                        for r in required {
                            checks.push(format!(
                                "            if (\"{}\" in obj) require(\"{}\" in obj) {{ \"dependentRequired\" }}",
                                escape_string(prop), escape_string(r)
                            ));
                        }
                    }
                    // dependentSchemas
                    for (prop, dep_schema) in &obj.dependent_schemas {
                        let dep_check = emit_match_expression(dep_schema, "el", defs);
                        if dep_check != "true" {
                            checks.push(format!(
                                "            if (\"{}\" in obj) {{ require({}) {{ \"dependentSchemas\" }} }}",
                                escape_string(prop), dep_check
                            ));
                        }
                    }
                    // additionalProperties with schema
                    if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", escape_string(k))).collect();
                        let ap_check = emit_inline_check(ap, "v", defs);
                        if !ap_check.is_empty() {
                            checks.push(format!(
                                "            val _known = setOf<String>({})\n            for ((k, v) in obj) {{ if (k !in _known) {{ {} }} }}",
                                known.join(", "), ap_check
                            ));
                        }
                    }
                    // patternProperties in TypeGuard::Object
                    for (pattern, pp_schema) in &obj.pattern_properties {
                        let pp_check = emit_inline_check(pp_schema, "v", defs);
                        if !pp_check.is_empty() {
                            checks.push(format!(
                                "            for ((k, v) in obj) {{ if (Regex(\"{}\").containsMatchIn(k)) {{ {} }} }}",
                                escape_string(pattern), pp_check
                            ));
                        }
                    }
                    checks.push("        }".to_string());
                }
                // Record in TypeGuard::Object
                if let SchemaIr::Record(rec) = schema.as_ref() {
                    let val_check = emit_inline_check(&rec.value, "v", defs);
                    if !val_check.is_empty() {
                        checks.push("        if (el is JsonObject) {".to_string());
                        checks.push(format!("            for ((_, v) in el.jsonObject) {{ {} }}", val_check));
                        checks.push("        }".to_string());
                    }
                }
            }
            TypeGuard::Array => {
                if let SchemaIr::Array(arr) = schema.as_ref() {
                    checks.push("        if (el is JsonArray) {".to_string());
                    checks.push("            val arr = el.jsonArray".to_string());
                    if let Some(min) = arr.min_items {
                        checks.push(format!("            require(arr.size >= {min}) {{ \"minItems\" }}"));
                    }
                    if let Some(max) = arr.max_items {
                        checks.push(format!("            require(arr.size <= {max}) {{ \"maxItems\" }}"));
                    }
                    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
                        let item_check = emit_inline_check(&arr.items, "item", defs);
                        if !item_check.is_empty() {
                            checks.push(format!("            for (item in arr) {{ {item_check} }}"));
                        }
                    }
                    if arr.unique_items {
                        checks.push(
                            "            require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                                .to_string(),
                        );
                    }
                    // contains in TypeGuard::Array
                    if let Some(contains) = &arr.contains {
                        let match_expr = emit_match_expression(&contains.schema, "it", defs);
                        let min = contains.min_contains.unwrap_or(1);
                        checks.push(format!(
                            "            val matchCount = arr.count {{ {match_expr} }}"
                        ));
                        checks.push(format!(
                            "            require(matchCount >= {min}) {{ \"must contain at least {min} matching items\" }}"
                        ));
                        if let Some(max) = contains.max_contains {
                            checks.push(format!(
                                "            require(matchCount <= {max}) {{ \"must contain at most {max} matching items\" }}"
                            ));
                        }
                    }
                    checks.push("        }".to_string());
                }
                // Also handle Tuple in Array TypeGuard
                if let SchemaIr::Tuple(tuple) = schema.as_ref() {
                    checks.push("        if (el is JsonArray) {".to_string());
                    checks.push("            val arr = el.jsonArray".to_string());
                    for (i, item) in tuple.items.iter().enumerate() {
                        if matches!(item, SchemaIr::Any) { continue; }
                        let item_check = emit_inline_check(item, &format!("arr[{i}]"), defs);
                        if !item_check.is_empty() {
                            checks.push(format!("            if (arr.size > {i}) {{ {item_check} }}"));
                        }
                    }
                    let prefix_count = tuple.items.len();
                    if let Some(rest) = &tuple.rest {
                        if !matches!(rest.as_ref(), SchemaIr::Any) {
                            let rest_check = emit_inline_check(rest, "arr[i]", defs);
                            if !rest_check.is_empty() {
                                checks.push(format!("            for (i in {prefix_count} until arr.size) {{ {rest_check} }}"));
                            }
                        }
                    } else {
                        checks.push(format!(
                            "            require(arr.size <= {prefix_count}) {{ \"too many items\" }}"
                        ));
                    }
                    if let Some(min) = tuple.min_items {
                        checks.push(format!("            require(arr.size >= {min}) {{ \"minItems\" }}"));
                    }
                    if let Some(max) = tuple.max_items {
                        checks.push(format!("            require(arr.size <= {max}) {{ \"maxItems\" }}"));
                    }
                    if tuple.unique_items {
                        checks.push(
                            "            require(arr.map { _canonicalize(it) }.toSet().size == arr.size) { \"uniqueItems\" }"
                                .to_string(),
                        );
                    }
                    checks.push("        }".to_string());
                }
            }
        }
    }

    if checks.is_empty() {
        String::new()
    } else {
        checks.join("\n") + "\n"
    }
}

fn emit_property_names_checks(pn: &SchemaIr, checks: &mut Vec<String>, indent: &str) {
    match pn {
        SchemaIr::Never => {
            checks.push(format!("{indent}require(obj.isEmpty()) {{ \"propertyNames: no properties allowed\" }}"));
        }
        SchemaIr::String(c) => {
            if let Some(max) = c.max_length {
                checks.push(format!("{indent}for (k in obj.keys) {{ require(k.length <= {max}) {{ \"propertyNames\" }} }}"));
            }
            if let Some(min) = c.min_length {
                checks.push(format!("{indent}for (k in obj.keys) {{ require(k.length >= {min}) {{ \"propertyNames\" }} }}"));
            }
            if let Some(ref pat) = c.pattern {
                checks.push(format!(
                    "{indent}for (k in obj.keys) {{ require(Regex(\"{}\").containsMatchIn(k)) {{ \"propertyNames\" }} }}",
                    escape_string(pat)
                ));
            }
        }
        SchemaIr::Literal(LiteralValue::String(s)) => {
            let escaped = escape_string(s);
            checks.push(format!("{indent}for (k in obj.keys) {{ require(k == \"{escaped}\") {{ \"propertyNames\" }} }}"));
        }
        SchemaIr::Enum(cases) => {
            let allowed: Vec<String> = cases.iter().map(|c| format!("\"{}\"", escape_string(c))).collect();
            checks.push(format!("{indent}val _pnAllowed = setOf<String>({})", allowed.join(", ")));
            checks.push(format!("{indent}for (k in obj.keys) {{ require(k in _pnAllowed) {{ \"propertyNames\" }} }}"));
        }
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Nullable(inner) => {
            emit_property_names_checks(inner, checks, indent);
        }
        _ => {}
    }
}

fn emit_not_check(not_schema: &SchemaIr, defs: &[DefEntry], counter: &mut usize) -> String {
    let inner_validation = emit_validation(not_schema, defs, counter);
    if inner_validation.is_empty() {
        // not_schema accepts everything → nothing can pass
        return "        error(\"must not match excluded schema\")\n".to_string();
    }
    format!(
        "        val notMatched = try {{ {}; true }} catch (_: Exception) {{ false }}\n        require(!notMatched) {{ \"must not match excluded schema\" }}\n",
        inner_validation.trim()
    )
}

fn emit_conditional_check(
    if_schema: &SchemaIr,
    then_schema: Option<&SchemaIr>,
    else_schema: Option<&SchemaIr>,
    defs: &[DefEntry],
    counter: &mut usize,
) -> String {
    let if_validation = emit_validation(if_schema, defs, counter);
    let mut out = String::new();

    out.push_str(&format!(
        "        val ifMatched = try {{ {}; true }} catch (_: Exception) {{ false }}\n",
        if_validation.trim()
    ));

    if let Some(then_s) = then_schema {
        let then_validation = emit_validation(then_s, defs, counter);
        if !then_validation.is_empty() {
            out.push_str(&format!(
                "        if (ifMatched) {{ {} }}\n",
                then_validation.trim()
            ));
        }
    }
    if let Some(else_s) = else_schema {
        let else_validation = emit_validation(else_s, defs, counter);
        if !else_validation.is_empty() {
            out.push_str(&format!(
                "        if (!ifMatched) {{ {} }}\n",
                else_validation.trim()
            ));
        }
    }

    out
}

fn emit_union_check(members: &[SchemaIr], defs: &[DefEntry], counter: &mut usize, exclusive: bool) -> String {
    let mut branch_checks = Vec::new();
    for member in members {
        let validation = emit_validation(member, defs, counter);
        if validation.is_empty() {
            branch_checks.push("true".to_string());
        } else {
            branch_checks.push(format!(
                "try {{ {}; true }} catch (_: Exception) {{ false }}",
                validation.trim()
            ));
        }
    }

    let mut out = String::new();
    out.push_str("        val branchResults = listOf(\n");
    for (i, check) in branch_checks.iter().enumerate() {
        let comma = if i < branch_checks.len() - 1 { "," } else { "" };
        out.push_str(&format!("            {check}{comma}\n"));
    }
    out.push_str("        )\n");
    out.push_str("        val matchCount = branchResults.count { it }\n");
    if exclusive {
        out.push_str(
            "        require(matchCount == 1) { \"must match exactly one schema, matched $matchCount\" }\n",
        );
    } else {
        out.push_str(
            "        require(matchCount >= 1) { \"must match at least one schema\" }\n",
        );
    }
    out
}

fn emit_never_class(name: &str, counter: &mut usize) -> String {
    *counter += 1;
    let ser_name = format!("{name}Ser");
    format!(
        "private object {ser_name} : KSerializer<{name}> {{\n    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor\n    override fun deserialize(decoder: Decoder): {name} {{ decoder.decodeSerializableValue(JsonElement.serializer()); error(\"schema rejects all values\") }}\n    override fun serialize(encoder: Encoder, value: {name}) {{ encoder.encodeSerializableValue(JsonElement.serializer(), value.element) }}\n}}\n\n@Serializable(with = {ser_name}::class)\nclass {name}(val element: JsonElement)"
    )
}

// ── Type mapping ────────────────────────────────────────────────────────────

fn kotlin_type(ir: &SchemaIr, defs: &[DefEntry], prefix: &str) -> String {
    match ir {
        SchemaIr::String(_) => "String".to_string(),
        SchemaIr::Number(_) => "Double".to_string(),
        SchemaIr::Integer(_) => "Int".to_string(),
        SchemaIr::Boolean => "Boolean".to_string(),
        SchemaIr::Null => "Nothing?".to_string(),
        SchemaIr::Any | SchemaIr::Unknown => "JsonElement".to_string(),
        SchemaIr::Never => "Nothing".to_string(),

        SchemaIr::Literal(lit) => match lit {
            LiteralValue::String(_) => "String".to_string(),
            LiteralValue::Number(_) => "Double".to_string(),
            LiteralValue::Integer(_) => "Int".to_string(),
            LiteralValue::Bool(_) => "Boolean".to_string(),
            LiteralValue::Null => "Nothing?".to_string(),
        },

        SchemaIr::ConstEqual(_) | SchemaIr::ComplexEnum(_) => "JsonElement".to_string(),
        SchemaIr::Enum(_) => "String".to_string(),
        SchemaIr::MixedEnum(_) => "JsonElement".to_string(),

        SchemaIr::Array(arr) => format!("List<{}>", kotlin_type(&arr.items, defs, prefix)),
        SchemaIr::Tuple(_) => "List<JsonElement>".to_string(),
        SchemaIr::Object(_) => "JsonObject".to_string(),
        SchemaIr::Record(rec) => format!("Map<String, {}>", kotlin_type(&rec.value, defs, prefix)),

        SchemaIr::Union(members) | SchemaIr::ExclusiveUnion(members) => {
            if members.len() == 2 {
                let non_null: Vec<_> = members
                    .iter()
                    .filter(|m| !matches!(m, SchemaIr::Null))
                    .collect();
                if non_null.len() == 1 {
                    return format!("{}?", kotlin_type(non_null[0], defs, prefix));
                }
            }
            "JsonElement".to_string()
        }

        SchemaIr::Intersection(_) => "JsonElement".to_string(),
        SchemaIr::Nullable(inner) => format!("{}?", kotlin_type(inner, defs, prefix)),
        SchemaIr::Optional(inner) => format!("{}?", kotlin_type(inner, defs, prefix)),
        SchemaIr::Default(inner, _) => kotlin_type(inner, defs, prefix),
        SchemaIr::Describe(inner, _) => kotlin_type(inner, defs, prefix),
        SchemaIr::Not { base, .. } => kotlin_type(base, defs, prefix),
        SchemaIr::Conditional { base, .. } => kotlin_type(base, defs, prefix),
        SchemaIr::TypeGuarded(_) => "JsonElement".to_string(),
        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => sanitize_kotlin_name(name, prefix),
    }
}

fn format_kt_number(n: f64) -> String {
    if n == n.trunc() && n.abs() < 1e15 {
        format!("{}.0", n as i64)
    } else {
        format!("{n}")
    }
}

/// Convert to lowerCamelCase (Kotlin convention).
fn to_camel_case(s: &str) -> String {
    if !s.contains(|c: char| !c.is_ascii_alphanumeric())
        && s.chars().next().is_some_and(|c| c.is_ascii_lowercase())
    {
        let result = s.to_string();
        return if is_kotlin_keyword(&result) {
            format!("`{result}`")
        } else {
            result
        };
    }

    let parts: Vec<&str> = s
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
        .collect();

    if parts.is_empty() {
        return s.to_string();
    }

    let mut result = parts[0].to_lowercase();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }

    if is_kotlin_keyword(&result) {
        format!("`{result}`")
    } else {
        result
    }
}

fn is_kotlin_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "class" | "continue" | "do" | "else" | "false" | "for" | "fun"
            | "if" | "in" | "interface" | "is" | "null" | "object" | "package" | "return"
            | "super" | "this" | "throw" | "true" | "try" | "typealias" | "typeof" | "val"
            | "var" | "when" | "while"
    )
}
