#[cfg(feature = "kotlin")]
pub mod kotlin;
#[cfg(feature = "pydantic")]
pub mod pydantic;
#[cfg(feature = "swift")]
pub mod swift;
#[cfg(feature = "typescript")]
pub mod typescript;
#[cfg(feature = "zod")]
pub mod zod;

use crate::ir::ConvertedSchema;

/// Trait for emitting generated code from a converted JSON Schema.
pub trait Emitter {
    /// File extension for the generated output (e.g., "zod.ts", "d.ts", "py").
    fn extension(&self) -> &str;

    /// Generate the output module/file as a string.
    fn emit(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        namespace: &str,
        version: u32,
    ) -> String;
}

// Re-export emitter types
#[cfg(feature = "kotlin")]
pub use kotlin::KotlinEmitter;
#[cfg(feature = "pydantic")]
pub use pydantic::PydanticEmitter;
#[cfg(feature = "swift")]
pub use swift::SwiftEmitter;
#[cfg(feature = "typescript")]
pub use typescript::TypeScriptEmitter;
#[cfg(feature = "zod")]
pub use zod::ZodEmitter;

// Re-export zod_for for backward compatibility with tests
#[cfg(feature = "zod")]
pub use zod::zod_for;

/// Shared helper: check if a JS/TS identifier needs quoting.
pub fn needs_quoting(key: &str) -> bool {
    if key.is_empty() || key == "__proto__" {
        return true;
    }
    let mut chars = key.chars();
    let first = chars.next().unwrap();
    if !first.is_ascii_alphabetic() && first != '_' && first != '$' {
        return true;
    }
    chars.any(|c| !c.is_ascii_alphanumeric() && c != '_' && c != '$')
}

/// Shared helper: check if a Python identifier needs special handling.
pub fn needs_python_quoting(key: &str) -> bool {
    const PYTHON_KEYWORDS: &[&str] = &[
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
        "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
        "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise",
        "return", "try", "while", "with", "yield",
    ];
    if key.is_empty() {
        return true;
    }
    if PYTHON_KEYWORDS.contains(&key) {
        return true;
    }
    let mut chars = key.chars();
    let first = chars.next().unwrap();
    if !first.is_ascii_alphabetic() && first != '_' {
        return true;
    }
    chars.any(|c| !c.is_ascii_alphanumeric() && c != '_')
}

/// Generate a module header comment.
pub fn module_header(namespace: &str, name: &str, version: u32) -> String {
    format!(
        "// Generated by json-schema-transformer\n// {namespace}/{name}@{version}\n// DO NOT EDIT — changes will be overwritten on regeneration\n"
    )
}
