#[cfg(feature = "kotlin")]
pub mod kotlin;
#[cfg(feature = "pydantic")]
pub mod pydantic;
#[cfg(feature = "swift")]
pub mod swift;
#[cfg(feature = "typescript")]
pub mod typescript;
#[cfg(feature = "zod")]
pub mod zod;

use crate::ir::ConvertedSchema;

/// Options controlling module emission.
#[derive(Debug, Clone, Default)]
pub struct EmitOptions {
    /// When set, utility helpers (deep-equality, canonical stringify, the
    /// spec-interpreter, format wrapper types, ...) are NOT emitted inline into
    /// the module. The module instead references them from this companion file:
    /// an import in TypeScript/Python, same-module internal declarations in
    /// Swift/Kotlin. Generate the companion file once via
    /// [`Emitter::helpers_content`]. The value is the helper file's name,
    /// e.g. "jst-helpers.ts" (used to derive import paths where relevant).
    pub helpers_file: Option<String>,
}

/// Trait for emitting generated code from a converted JSON Schema.
pub trait Emitter {
    /// File extension for the generated output (e.g., "zod.ts", "d.ts", "py").
    fn extension(&self) -> &str;

    /// Generate a self-contained output module (helpers inlined). The name is
    /// PascalCased into the root type name.
    fn emit(&self, converted: &ConvertedSchema, name: &str) -> String {
        self.emit_with_options(converted, name, &EmitOptions::default())
    }

    /// Generate the output module honoring [`EmitOptions`].
    fn emit_with_options(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        options: &EmitOptions,
    ) -> String;

    /// Full content of this language's shared helpers file (static — identical
    /// for every schema). None when the language emits no runtime helpers.
    fn helpers_content(&self) -> Option<String> {
        None
    }

    /// Conventional file name for the shared helpers file.
    fn default_helpers_file(&self) -> Option<&'static str> {
        None
    }
}

// Re-export emitter types
#[cfg(feature = "kotlin")]
pub use kotlin::KotlinEmitter;
#[cfg(feature = "pydantic")]
pub use pydantic::PydanticEmitter;
#[cfg(feature = "swift")]
pub use swift::SwiftEmitter;
#[cfg(feature = "typescript")]
pub use typescript::TypeScriptEmitter;
#[cfg(feature = "zod")]
pub use zod::ZodEmitter;

// Re-export zod_for for backward compatibility with tests
#[cfg(feature = "zod")]
pub use zod::zod_for;

/// Shared helper: check if a JS/TS identifier needs quoting.
pub fn needs_quoting(key: &str) -> bool {
    if key.is_empty() || key == "__proto__" {
        return true;
    }
    let mut chars = key.chars();
    let first = chars.next().unwrap();
    if !first.is_ascii_alphabetic() && first != '_' && first != '$' {
        return true;
    }
    chars.any(|c| !c.is_ascii_alphanumeric() && c != '_' && c != '$')
}

/// Shared helper: check if a Python identifier needs special handling.
pub fn needs_python_quoting(key: &str) -> bool {
    const PYTHON_KEYWORDS: &[&str] = &[
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
        "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
        "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise",
        "return", "try", "while", "with", "yield",
    ];
    if key.is_empty() {
        return true;
    }
    if PYTHON_KEYWORDS.contains(&key) {
        return true;
    }
    let mut chars = key.chars();
    let first = chars.next().unwrap();
    if !first.is_ascii_alphabetic() && first != '_' {
        return true;
    }
    chars.any(|c| !c.is_ascii_alphanumeric() && c != '_')
}

/// Generate a module header comment.
pub fn module_header(name: &str) -> String {
    format!(
        "// Generated by json-schema-transformer\n// {name}\n// DO NOT EDIT — changes will be overwritten on regeneration\n"
    )
}
