use std::cell::RefCell;
use std::sync::atomic::{AtomicUsize, Ordering};
use crate::ir::*;
use crate::util::to_pascal_case;
use super::Emitter;

static SUB_SCHEMA_COUNTER: AtomicUsize = AtomicUsize::new(0);

thread_local! {
    /// Per-file type prefix applied to $defs type names so that many generated
    /// files can be compiled into a single Swift module without collisions.
    static TYPE_PREFIX: RefCell<String> = const { RefCell::new(String::new()) };
}

/// Shared helper type names that appear in type signatures (so they cannot be
/// `private`) and must instead be prefixed per-file to avoid duplicate symbols
/// when compiling many generated files into one module.
const SIGNATURE_HELPER_TYPES: &[&str] = &[
    "EmailAddress",
    "HostnameString",
    "IPv4Address",
    "IPv6Address",
    "IPAddress",
    "TimeString",
    "DurationString",
    "Base64String",
];

pub struct SwiftEmitter;

impl Emitter for SwiftEmitter {
    fn extension(&self) -> &str {
        "swift"
    }

    fn emit(
        &self,
        converted: &ConvertedSchema,
        name: &str,
        namespace: &str,
        version: u32,
    ) -> String {
        // Reset global sub-schema counter for each emit
        SUB_SCHEMA_COUNTER.store(0, Ordering::Relaxed);
        let pascal = to_pascal_case(name);
        // Prefix $defs type names per file so many files can share one module.
        TYPE_PREFIX.with(|p| *p.borrow_mut() = format!("{pascal}V{version}"));
        let mut out = String::new();

        out.push_str(&format!(
            "// Generated by event-registry\n// {namespace}/{name}@{version}\n// DO NOT EDIT — changes will be overwritten on next pull\n\n"
        ));
        out.push_str("import Foundation\n\n");

        // Emit body first to detect which helpers are needed
        let mut body = String::new();
        for def in &converted.defs {
            let safe_name = sanitize_swift_name(&def.name);
            let code = emit_struct(&safe_name, &def.schema, &converted.defs);
            // For recursive types, Swift structs can't form cycles — use class
            let code = if def.is_recursive {
                code.replacen(&format!("struct {safe_name}:"), &format!("final class {safe_name}:"), 1)
            } else {
                code
            };
            body.push_str(&code);
            body.push_str("\n\n");
        }
        body.push_str(&emit_struct(
            &format!("{pascal}V{version}Data"),
            &converted.root,
            &converted.defs,
        ));
        body.push('\n');

        // Emit validation error enum if any validating types are used
        let mut helpers = SwiftHelpers::default();
        helpers.detect(&body);

        if helpers.needs_any() {
            out.push_str(&helpers.emit_validation_error());
            out.push('\n');
        }
        if helpers.needs_email {
            out.push_str(EMAIL_ADDRESS_HELPER);
            out.push('\n');
        }
        if helpers.needs_hostname {
            out.push_str(HOSTNAME_HELPER);
            out.push('\n');
        }
        if helpers.needs_ipv4 {
            out.push_str(IPV4_ADDRESS_HELPER);
            out.push('\n');
        }
        if helpers.needs_ipv6 {
            out.push_str(IPV6_ADDRESS_HELPER);
            out.push('\n');
        }
        if helpers.needs_ip {
            // IPAddress depends on IPv4Address and IPv6Address
            if !helpers.needs_ipv4 {
                out.push_str(IPV4_ADDRESS_HELPER);
                out.push('\n');
            }
            if !helpers.needs_ipv6 {
                out.push_str(IPV6_ADDRESS_HELPER);
                out.push('\n');
            }
            out.push_str(IP_ADDRESS_HELPER);
            out.push('\n');
        }
        if helpers.needs_time {
            out.push_str(TIME_STRING_HELPER);
            out.push('\n');
        }
        if helpers.needs_duration {
            out.push_str(DURATION_STRING_HELPER);
            out.push('\n');
        }
        if helpers.needs_base64 {
            out.push_str(BASE64_STRING_HELPER);
            out.push('\n');
        }
        if helpers.needs_serialize_any {
            out.push_str(SERIALIZE_ANY_HELPER);
            out.push('\n');
        }

        out.push_str(&body);

        // Prefix signature-visible helper types (EmailAddress, TimeString, …)
        // per file: they appear in stored-property/typealias signatures of the
        // internal root type, so they cannot be `private` — renaming them keeps
        // every generated file safe to compile into one shared module.
        let prefix = format!("{pascal}V{version}");
        for helper in SIGNATURE_HELPER_TYPES {
            if out.contains(helper) {
                out = out.replace(helper, &format!("{prefix}{helper}"));
            }
        }
        out
    }
}

// ── Helper detection ─────────────────────────────────────────────────────────

#[derive(Default)]
struct SwiftHelpers {
    needs_email: bool,
    needs_hostname: bool,
    needs_ipv4: bool,
    needs_ipv6: bool,
    needs_ip: bool,
    needs_time: bool,
    needs_duration: bool,
    needs_base64: bool,
    needs_numeric_validation: bool,
    needs_serialize_any: bool,
}

impl SwiftHelpers {
    fn detect(&mut self, body: &str) {
        self.needs_email = body.contains("EmailAddress");
        self.needs_hostname = body.contains("HostnameString");
        self.needs_ipv4 = body.contains("IPv4Address");
        self.needs_ipv6 = body.contains("IPv6Address");
        self.needs_ip = body.contains("IPAddress");
        self.needs_time = body.contains("TimeString");
        self.needs_duration = body.contains("DurationString");
        self.needs_base64 = body.contains("Base64String");
        self.needs_numeric_validation = body.contains("// @validate");
        self.needs_serialize_any = body.contains("_serializeAny");
    }

    fn needs_any(&self) -> bool {
        self.needs_email
            || self.needs_hostname
            || self.needs_ipv4
            || self.needs_ipv6
            || self.needs_ip
            || self.needs_time
            || self.needs_duration
            || self.needs_base64
            || self.needs_numeric_validation
    }

    fn emit_validation_error(&self) -> String {
        let mut cases = Vec::new();
        let mut descriptions = Vec::new();

        if self.needs_email {
            cases.push("    case invalidEmail(String)");
            descriptions.push(r#"        case .invalidEmail(let v): "Invalid email address: \(v)""#);
        }
        if self.needs_hostname {
            cases.push("    case invalidHostname(String)");
            descriptions.push(r#"        case .invalidHostname(let v): "Invalid hostname: \(v)""#);
        }
        if self.needs_ipv4 || self.needs_ip {
            cases.push("    case invalidIPv4(String)");
            descriptions.push(r#"        case .invalidIPv4(let v): "Invalid IPv4 address: \(v)""#);
        }
        if self.needs_ipv6 || self.needs_ip {
            cases.push("    case invalidIPv6(String)");
            descriptions.push(r#"        case .invalidIPv6(let v): "Invalid IPv6 address: \(v)""#);
        }
        if self.needs_ip {
            cases.push("    case invalidIP(String)");
            descriptions.push(r#"        case .invalidIP(let v): "Invalid IP address: \(v)""#);
        }
        if self.needs_time {
            cases.push("    case invalidTime(String)");
            descriptions.push(r#"        case .invalidTime(let v): "Invalid time: \(v)""#);
        }
        if self.needs_duration {
            cases.push("    case invalidDuration(String)");
            descriptions.push(r#"        case .invalidDuration(let v): "Invalid duration: \(v)""#);
        }
        if self.needs_base64 {
            cases.push("    case invalidBase64(String)");
            descriptions.push(r#"        case .invalidBase64(let v): "Invalid base64: \(v)""#);
        }
        if self.needs_numeric_validation {
            cases.push("    case outOfRange(String, String)");
            descriptions.push(r#"        case .outOfRange(let field, let detail): "\(field): \(detail)""#);
        }

        format!(
            "private enum ValidationError: LocalizedError {{\n{}\n\n    var errorDescription: String? {{\n        switch self {{\n{}\n        }}\n    }}\n}}\n",
            cases.join("\n"),
            descriptions.join("\n"),
        )
    }
}

// ── Validating type helpers ──────────────────────────────────────────────────


const EMAIL_ADDRESS_HELPER: &str = r##"struct EmailAddress: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        let pattern = try! Regex(#"[^@\s]+@[^@\s]+\.[^@\s]+"#)
        guard value.wholeMatch(of: pattern) != nil else {
            throw ValidationError.invalidEmail(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"##;

const HOSTNAME_HELPER: &str = r#"struct HostnameString: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        guard value.count <= 253,
              !value.isEmpty,
              value.split(separator: ".").allSatisfy({
                  !$0.isEmpty && $0.count <= 63 &&
                  $0.allSatisfy({ $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-") }) &&
                  !$0.hasPrefix("-") && !$0.hasSuffix("-")
              }) else {
            throw ValidationError.invalidHostname(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"#;

const IPV4_ADDRESS_HELPER: &str = r#"struct IPv4Address: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        let parts = value.split(separator: ".")
        guard parts.count == 4,
              parts.allSatisfy({ part in
                  guard let n = Int(part), (0...255).contains(n) else { return false }
                  return String(n) == part // reject leading zeros
              }) else {
            throw ValidationError.invalidIPv4(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"#;

const IPV6_ADDRESS_HELPER: &str = r#"struct IPv6Address: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        // Basic IPv6 validation: 1-8 groups of hex digits separated by ":"
        // Allows :: shorthand for consecutive zero groups
        let stripped = value.lowercased()
        let groups: [Substring]
        if stripped.contains("::") {
            let halves = stripped.split(separator: "::", maxSplits: 1, omittingEmptySubsequences: false)
            guard halves.count == 2 else { throw ValidationError.invalidIPv6(value) }
            let left = halves[0].isEmpty ? [] : halves[0].split(separator: ":")
            let right = halves[1].isEmpty ? [] : halves[1].split(separator: ":")
            guard left.count + right.count <= 7 else { throw ValidationError.invalidIPv6(value) }
            groups = left + right
        } else {
            groups = stripped.split(separator: ":")
            guard groups.count == 8 else { throw ValidationError.invalidIPv6(value) }
        }
        guard groups.allSatisfy({ g in
            (1...4).contains(g.count) && g.allSatisfy({ $0.isHexDigit })
        }) else {
            throw ValidationError.invalidIPv6(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"#;

const IP_ADDRESS_HELPER: &str = r#"struct IPAddress: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        // Try IPv4 first, then IPv6
        if (try? IPv4Address(value)) != nil || (try? IPv6Address(value)) != nil {
            self.value = value
        } else {
            throw ValidationError.invalidIP(value)
        }
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"#;

const TIME_STRING_HELPER: &str = r##"struct TimeString: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        // RFC 3339 time: HH:MM:SS[.fractional][Z|+HH:MM|-HH:MM]
        let pattern = try! Regex(#"(?i)\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?"#)
        guard value.wholeMatch(of: pattern) != nil else {
            throw ValidationError.invalidTime(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"##;

const DURATION_STRING_HELPER: &str = r##"struct DurationString: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        // ISO 8601 duration: P[nY][nM][nD][T[nH][nM][nS]]
        let pattern = try! Regex(#"P(\d+Y)?(\d+M)?(\d+D)?(T(\d+H)?(\d+M)?(\d+(\.\d+)?S)?)?"#)
        guard value.wholeMatch(of: pattern) != nil, value != "P" else {
            throw ValidationError.invalidDuration(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"##;

const BASE64_STRING_HELPER: &str = r#"struct Base64String: Codable, Hashable, CustomStringConvertible {
    let value: String

    var description: String { value }

    init(_ value: String) throws {
        guard Data(base64Encoded: value) != nil else {
            throw ValidationError.invalidBase64(value)
        }
        self.value = value
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}
"#;

const SERIALIZE_ANY_HELPER: &str = r#"private func _serializeAny(_ value: Any) -> Data {
    if JSONSerialization.isValidJSONObject(value) {
        return (try? JSONSerialization.data(withJSONObject: value, options: .sortedKeys)) ?? Data()
    }
    guard let wrapped = try? JSONSerialization.data(withJSONObject: [value], options: .sortedKeys),
          let str = String(data: wrapped, encoding: .utf8) else { return Data() }
    let inner = String(str.dropFirst().dropLast())
    return inner.data(using: .utf8) ?? Data()
}
"#;

// ── Swift string escaping ────────────────────────────────────────────────────

/// Escape a string for use in a Swift string literal.
/// Handles all control characters using Swift's \u{XX} syntax.
fn swift_escape(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => vec!['\\', '"'],
            '\\' => vec!['\\', '\\'],
            '\n' => vec!['\\', 'n'],
            '\r' => vec!['\\', 'r'],
            '\t' => vec!['\\', 't'],
            '\0' => vec!['\\', '0'],
            c if c.is_control() => {
                format!("\\u{{{:02X}}}", c as u32).chars().collect()
            }
            other => vec![other],
        })
        .collect()
}

// ── Name sanitization ───────────────────────────────────────────────────────

/// Swift reserved type names that must not be used as generated type names.
const SWIFT_RESERVED_TYPES: &[&str] = &[
    "Bool", "Int", "Int8", "Int16", "Int32", "Int64",
    "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
    "Float", "Double", "String", "Character",
    "Array", "Dictionary", "Set", "Optional",
    "Never", "Void", "Any", "AnyObject", "AnyHashable",
    "Error", "Result", "Data", "Date", "URL", "UUID",
    "Codable", "Decodable", "Encodable",
    "Equatable", "Hashable", "Comparable",
    "Type",
];

fn sanitize_swift_name(name: &str) -> String {
    let base = if SWIFT_RESERVED_TYPES.contains(&name) {
        format!("{name}Schema")
    } else {
        name.to_string()
    };
    // Prefix with the per-file root type prefix so $defs types with generic
    // names (Address, Node, …) never collide across files in one module.
    TYPE_PREFIX.with(|p| format!("{}{}", p.borrow(), base))
}

/// Mark a top-level generated declaration `private` (Swift top-level `private`
/// is file-scoped, so every generated file may safely re-declare the same
/// helper names when compiled into a single module).
fn privatize_decl(code: String, name: &str) -> String {
    code.replacen(&format!("struct {name}:"), &format!("private struct {name}:"), 1)
        .replacen(&format!("enum {name}:"), &format!("private enum {name}:"), 1)
        .replacen(&format!("final class {name}:"), &format!("private final class {name}:"), 1)
        .replacen(&format!("typealias {name} ="), &format!("private typealias {name} ="), 1)
}

// ── Struct emission ──────────────────────────────────────────────────────────

fn emit_struct(name: &str, ir: &SchemaIr, defs: &[DefEntry]) -> String {
    match ir {
        SchemaIr::Object(obj) => {
            let mut preamble = String::new();
            let mut lines = vec![format!("struct {name}: Codable {{")];

            let mut needs_coding_keys = false;
            let mut fields_info: Vec<(&str, String, String, bool, Vec<FieldGuard>)> = Vec::new();
            let mut has_field_constraints = false;
            let forbid_extra = matches!(obj.additional_properties, AdditionalProperties::Forbidden);
            let has_pattern_props = !obj.pattern_properties.is_empty();
            let has_property_names = obj.property_names.is_some();
            let has_min_props = obj.min_properties.is_some();
            let has_max_props = obj.max_properties.is_some();
            let has_dep_required = !obj.dependent_required.is_empty();
            let has_dep_schemas = !obj.dependent_schemas.is_empty();
            let has_ap_schema = matches!(obj.additional_properties, AdditionalProperties::Schema(_));
            let mut nested_enums: Vec<String> = Vec::new();
            let mut seen_names: std::collections::HashMap<String, usize> = std::collections::HashMap::new();

            for (k, f) in &obj.fields {
                let mut swift_name = to_camel_case(k);
                let count = seen_names.entry(swift_name.clone()).or_insert(0);
                *count += 1;
                if *count > 1 {
                    swift_name = format!("{swift_name}{count}");
                }
                let optional = !f.required;
                let guards = field_guards(&f.schema);

                // Generate nested enum for inline string enums
                let field_type = if let SchemaIr::Enum(cases) = &f.schema {
                    let enum_name = to_pascal_case(k);
                    nested_enums.push(emit_nested_enum(&enum_name, cases));
                    enum_name
                } else {
                    swift_type(&f.schema, defs)
                };

                if swift_name != *k {
                    needs_coding_keys = true;
                }
                if !guards.is_empty() {
                    has_field_constraints = true;
                }

                let type_str = if optional {
                    format!("{field_type}?")
                } else {
                    field_type.clone()
                };

                lines.push(format!("    let {swift_name}: {type_str}"));
                fields_info.push((k, swift_name, field_type, optional, guards));
            }

            // Emit nested enums
            if !nested_enums.is_empty() {
                lines.push(String::new());
                for e in &nested_enums {
                    lines.push(e.clone());
                }
            }

            let needs_custom_init = has_field_constraints || forbid_extra
                || has_pattern_props || has_property_names
                || has_min_props || has_max_props
                || has_dep_required || has_dep_schemas || has_ap_schema;
            // CodingKeys needed when names differ OR when we need a custom init(from:)
            let needs_coding_keys = needs_coding_keys || needs_custom_init;

            if needs_coding_keys && !fields_info.is_empty() {
                lines.push(String::new());
                lines.push("    enum CodingKeys: String, CodingKey {".to_string());
                for (json_key, swift_name, _, _, _) in &fields_info {
                    if *swift_name != *json_key {
                        lines.push(format!(
                            "        case {swift_name} = \"{}\"",
                            swift_escape(json_key)
                        ));
                    } else {
                        lines.push(format!("        case {swift_name}"));
                    }
                }
                lines.push("    }".to_string());
            }

            // Custom init(from:) for field validation and/or additionalProperties check
            if needs_custom_init {
                // Leave a comment so the helper detector knows we need ValidationError
                lines.push(String::new());
                lines.push("    // @validate".to_string());
                lines.push("    init(from decoder: Decoder) throws {".to_string());
                if !fields_info.is_empty() {
                    lines.push("        let container = try decoder.container(keyedBy: CodingKeys.self)".to_string());
                }

                // DynamicKey needed for key iteration (forbid_extra, patternProperties, AP schema, propertyNames, min/maxProperties, dependentRequired/Schemas)
                let needs_dynamic_keys = forbid_extra || has_pattern_props || has_ap_schema
                    || has_property_names || has_min_props || has_max_props
                    || has_dep_required || has_dep_schemas;
                if needs_dynamic_keys {
                    lines.push("        struct DynamicKey: CodingKey { var stringValue: String; init?(stringValue: String) { self.stringValue = stringValue }; var intValue: Int?; init?(intValue: Int) { return nil } }".to_string());
                    lines.push("        let allKeysContainer = try decoder.container(keyedBy: DynamicKey.self)".to_string());
                    let known_json_keys: Vec<String> = fields_info.iter().map(|(jk, _, _, _, _)| format!("\"{}\"", swift_escape(jk))).collect();
                    lines.push(format!(
                        "        let knownKeys: Set<String> = [{}]",
                        known_json_keys.join(", ")
                    ));
                }

                // forbid_extra: reject unexpected keys
                if forbid_extra && !has_pattern_props {
                    lines.push(
                        "        for key in allKeysContainer.allKeys where !knownKeys.contains(key.stringValue) { throw ValidationError.outOfRange(key.stringValue, \"unexpected property\") }".to_string()
                    );
                }

                // Decode fields
                for (_, swift_name, swift_type, optional, guards) in &fields_info {
                    if *optional {
                        lines.push(format!(
                            "        {swift_name} = try container.decodeIfPresent({swift_type}.self, forKey: .{swift_name})"
                        ));
                    } else {
                        lines.push(format!(
                            "        {swift_name} = try container.decode({swift_type}.self, forKey: .{swift_name})"
                        ));
                    }
                    emit_guard_lines(swift_name, *optional, guards, &mut lines);
                }

                // minProperties / maxProperties
                if has_min_props || has_max_props {
                    lines.push("        let propCount = allKeysContainer.allKeys.count".to_string());
                    if let Some(min) = obj.min_properties {
                        lines.push(format!("        if propCount < {min} {{ throw ValidationError.outOfRange(\"value\", \"minProperties\") }}"));
                    }
                    if let Some(max) = obj.max_properties {
                        lines.push(format!("        if propCount > {max} {{ throw ValidationError.outOfRange(\"value\", \"maxProperties\") }}"));
                    }
                }

                // patternProperties + additionalProperties interaction
                if has_pattern_props {
                    lines.push("        for key in allKeysContainer.allKeys {".to_string());
                    lines.push("            var matched = knownKeys.contains(key.stringValue)".to_string());
                    for (pattern, pp_schema) in &obj.pattern_properties {
                        let mut pp_c = 0usize;
                        let (pp_pre, pt) = emit_swift_sub_schema("PP", pp_schema, defs, &mut pp_c);
                        if !pp_pre.is_empty() { preamble.push_str(&pp_pre); }
                        lines.push(format!(
                            "            if key.stringValue.range(of: \"{}\", options: .regularExpression) != nil {{ matched = true; let pv = try allKeysContainer.decode(AnyCodable.self, forKey: key); let pd = _serializeAny(pv.value); let _ = try JSONDecoder().decode({pt}.self, from: pd) }}",
                            swift_escape(pattern)
                        ));
                    }
                    if forbid_extra {
                        lines.push("            if !matched { throw ValidationError.outOfRange(key.stringValue, \"unexpected property\") }".to_string());
                    }
                    lines.push("        }".to_string());
                } else if has_ap_schema {
                    // additionalProperties with schema validation
                    if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                        let mut ap_c = 0usize;
                        let (ap_pre, at) = emit_swift_sub_schema("AP", ap, defs, &mut ap_c);
                        if !ap_pre.is_empty() { preamble.push_str(&ap_pre); }
                        lines.push("        for key in allKeysContainer.allKeys where !knownKeys.contains(key.stringValue) {".to_string());
                        lines.push(format!("            let av = try allKeysContainer.decode(AnyCodable.self, forKey: key); let ad = _serializeAny(av.value); let _ = try JSONDecoder().decode({at}.self, from: ad)"));
                        lines.push("        }".to_string());
                    }
                }

                // propertyNames
                if let Some(pn) = &obj.property_names {
                    emit_property_names_check(pn, "allKeysContainer.allKeys", &mut lines, &mut preamble, defs);
                }

                // dependentRequired
                for (prop, required) in &obj.dependent_required {
                    let trigger_key = swift_escape(prop);
                    lines.push(format!("        if allKeysContainer.allKeys.contains(where: {{ $0.stringValue == \"{}\" }}) {{", trigger_key));
                    for r in required {
                        let rk = swift_escape(r);
                        lines.push(format!("            if !allKeysContainer.allKeys.contains(where: {{ $0.stringValue == \"{rk}\" }}) {{ throw ValidationError.outOfRange(\"{rk}\", \"dependentRequired\") }}"));
                    }
                    lines.push("        }".to_string());
                }

                // dependentSchemas — decode raw dict once, then validate
                if has_dep_schemas {
                    lines.push("        var rawDict: [String: AnyCodable] = [:]".to_string());
                    lines.push("        for key in allKeysContainer.allKeys { rawDict[key.stringValue] = try allKeysContainer.decode(AnyCodable.self, forKey: key) }".to_string());
                    lines.push("        let rawData = _serializeAny(rawDict.mapValues { $0.value })".to_string());
                    let mut ds_counter = 0usize;
                    for (prop, dep_schema) in &obj.dependent_schemas {
                        let (sub_pre, dt) = emit_swift_sub_schema("DS", dep_schema, defs, &mut ds_counter);
                        if !sub_pre.is_empty() {
                            preamble.push_str(&sub_pre);
                        }
                        let trigger_key = swift_escape(prop);
                        lines.push(format!("        if rawDict[\"{trigger_key}\"] != nil {{"));
                        lines.push(format!("            let _ = try JSONDecoder().decode({dt}.self, from: rawData)"));
                        lines.push("        }".to_string());
                    }
                }

                lines.push("    }".to_string());
            }

            lines.push("}".to_string());
            format!("{preamble}{}", lines.join("\n"))
        }

        SchemaIr::Enum(cases) if cases.is_empty() => {
            // Empty enum — reject all values
            format!(
                "struct {name}: Codable {{\n    // @validate\n    init(from decoder: Decoder) throws {{\n        throw ValidationError.outOfRange(\"value\", \"schema rejects all values\")\n    }}\n    func encode(to encoder: Encoder) throws {{}}\n}}"
            )
        }

        SchemaIr::Enum(cases) => {
            let mut lines = vec![format!("enum {name}: String, Codable {{")];
            let mut seen_cases: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
            for case in cases {
                let mut swift_case = to_camel_case(case);
                let count = seen_cases.entry(swift_case.clone()).or_insert(0);
                *count += 1;
                if *count > 1 {
                    swift_case = format!("{swift_case}{count}");
                }
                if swift_case != *case {
                    lines.push(format!(
                        "    case {swift_case} = \"{}\"",
                        swift_escape(case)
                    ));
                } else {
                    lines.push(format!("    case {swift_case}"));
                }
            }
            lines.push("}".to_string());
            lines.join("\n")
        }

        _ => {
            if should_emit_wrapper(ir) {
                emit_wrapper_struct(name, ir, defs)
            } else {
                format!("typealias {name} = {}", swift_type(ir, defs))
            }
        }
    }
}

/// Determine if a non-Object IR node needs a wrapper struct for validation.
fn should_emit_wrapper(ir: &SchemaIr) -> bool {
    match ir {
        SchemaIr::Integer(_) | SchemaIr::Number(_) | SchemaIr::Boolean => true,
        SchemaIr::String(c) => {
            c.min_length.is_some() || c.max_length.is_some() || c.pattern.is_some()
        }
        SchemaIr::Array(arr) => {
            arr.min_items.is_some()
                || arr.max_items.is_some()
                || arr.unique_items
                || arr.contains.is_some()
                || !matches!(arr.items.as_ref(), SchemaIr::Any)
        }
        SchemaIr::MixedEnum(_) | SchemaIr::Literal(_) | SchemaIr::ConstEqual(_)
        | SchemaIr::ComplexEnum(_) | SchemaIr::TypeGuarded(_) | SchemaIr::Never
        | SchemaIr::Null => true,
        SchemaIr::Not { .. } | SchemaIr::Conditional { .. } | SchemaIr::ExclusiveUnion(_) => true,
        SchemaIr::Union(members) if members.len() > 1 => true,
        SchemaIr::Enum(cases) if cases.is_empty() => true,
        SchemaIr::Intersection(members) if members.len() > 1 => true,
        SchemaIr::Intersection(members) if members.len() == 1 => should_emit_wrapper(&members[0]),
        SchemaIr::Nullable(inner) | SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => {
            should_emit_wrapper(inner)
        }
        _ => false,
    }
}

/// Emit a wrapper struct with single-value decoding and validation.
fn emit_wrapper_struct(name: &str, ir: &SchemaIr, defs: &[DefEntry]) -> String {
    // Track if outer IR was Nullable before unwrapping
    let is_nullable = matches!(ir, SchemaIr::Nullable(_));
    // Unwrap modifiers
    let inner = unwrap_modifiers(ir);

    match inner {
        SchemaIr::Integer(c) => emit_numeric_wrapper(name, "Int", c, true),
        SchemaIr::Number(c) => emit_numeric_wrapper(name, "Double", c, false),
        SchemaIr::Boolean => {
            format!(
                "struct {name}: Codable {{\n    let value: Bool\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        guard raw.value is Bool else {{\n            throw ValidationError.outOfRange(\"value\", \"expected boolean, got non-boolean\")\n        }}\n        value = raw.value as! Bool\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
            )
        }
        SchemaIr::String(c) => emit_string_wrapper(name, c),
        SchemaIr::Array(arr) => emit_array_wrapper(name, arr, defs),
        SchemaIr::TypeGuarded(guards) => emit_type_guarded_wrapper(name, guards, defs),
        SchemaIr::MixedEnum(lits) => emit_mixed_enum_wrapper(name, lits),
        SchemaIr::Literal(lit) => emit_literal_wrapper(name, lit),
        SchemaIr::ConstEqual(val) => emit_const_equal_wrapper(name, val),
        SchemaIr::ComplexEnum(vals) => emit_complex_enum_wrapper(name, vals),
        SchemaIr::Null => {
            format!(
                "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        guard raw.value is NSNull else {{ throw ValidationError.outOfRange(\"value\", \"expected null\") }}\n        value = raw\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
            )
        }
        SchemaIr::Never => {
            format!(
                "struct {name}: Codable {{\n    // @validate\n    init(from decoder: Decoder) throws {{\n        throw ValidationError.outOfRange(\"value\", \"schema rejects all values\")\n    }}\n    func encode(to encoder: Encoder) throws {{}}\n}}"
            )
        }
        SchemaIr::Not { base, not_schema } => emit_not_wrapper(name, base, not_schema, defs),
        SchemaIr::Conditional { base: _, if_schema, then_schema, else_schema } => {
            emit_conditional_wrapper(name, if_schema, then_schema.as_deref(), else_schema.as_deref(), defs)
        }
        SchemaIr::Union(members) if members.len() > 1 => {
            if is_nullable {
                let mut extended = members.to_vec();
                extended.push(SchemaIr::Null);
                emit_anyof_wrapper(name, &extended, defs)
            } else {
                emit_anyof_wrapper(name, members, defs)
            }
        }
        SchemaIr::ExclusiveUnion(members) => emit_oneof_wrapper(name, members, defs),
        SchemaIr::Intersection(members) => emit_intersection_wrapper(name, members, defs),
        SchemaIr::Object(_) | SchemaIr::Tuple(_) => emit_struct(name, inner, defs),
        SchemaIr::Enum(cases) if cases.is_empty() => {
            format!(
                "struct {name}: Codable {{\n    // @validate\n    init(from decoder: Decoder) throws {{\n        throw ValidationError.outOfRange(\"value\", \"schema rejects all values\")\n    }}\n    func encode(to encoder: Encoder) throws {{}}\n}}"
            )
        }
        SchemaIr::Enum(_) => emit_struct(name, inner, defs),
        _ => format!("typealias {name} = {}", swift_type(ir, defs)),
    }
}

fn unwrap_modifiers(ir: &SchemaIr) -> &SchemaIr {
    match ir {
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) | SchemaIr::Nullable(inner) => {
            unwrap_modifiers(inner)
        }
        _ => ir,
    }
}

fn emit_numeric_wrapper(name: &str, swift_ty: &str, c: &NumberConstraints, is_int: bool) -> String {
    let mut guards = Vec::new();
    if is_int {
        guards.push(format!(
            "        guard !(raw.value is Bool) else {{ throw ValidationError.outOfRange(\"value\", \"boolean is not {}\")}}", if is_int { "an integer" } else { "a number" }
        ));
        // Accept Int or Double (if whole number) for integer type
        guards.push(format!(
            "        if let i = raw.value as? Int {{ value = i }} else if let d = raw.value as? Double, d == d.rounded(.towardZero), d >= Double(Int.min), d <= Double(Int.max) {{ value = Int(d) }} else {{ throw ValidationError.outOfRange(\"value\", \"expected {swift_ty}\") }}"
        ));
    } else {
        guards.push(format!(
            "        guard !(raw.value is Bool) else {{ throw ValidationError.outOfRange(\"value\", \"boolean is not a number\")}}"
        ));
        guards.push(format!(
            "        if let d = raw.value as? Double {{ value = d }} else if let i = raw.value as? Int {{ value = Double(i) }} else {{ throw ValidationError.outOfRange(\"value\", \"expected {swift_ty}\") }}"
        ));
    }
    // Numeric constraint guards
    if let Some(v) = c.minimum {
        let b = format_number(v);
        guards.push(format!("        if !(value >= {b}) {{ throw ValidationError.outOfRange(\"value\", \">= {b}\") }}"));
    }
    if let Some(v) = c.maximum {
        let b = format_number(v);
        guards.push(format!("        if !(value <= {b}) {{ throw ValidationError.outOfRange(\"value\", \"<= {b}\") }}"));
    }
    if let Some(v) = c.exclusive_minimum {
        let b = format_number(v);
        guards.push(format!("        if !(value > {b}) {{ throw ValidationError.outOfRange(\"value\", \"> {b}\") }}"));
    }
    if let Some(v) = c.exclusive_maximum {
        let b = format_number(v);
        guards.push(format!("        if !(value < {b}) {{ throw ValidationError.outOfRange(\"value\", \"< {b}\") }}"));
    }
    if let Some(v) = c.multiple_of {
        let b = format_number(v);
        if is_int {
            guards.push(format!("        if (Double(value) / {b}).isInfinite {{ throw ValidationError.outOfRange(\"value\", \"must be a multiple of {b}\") }}"));
            guards.push(format!("        let _mof = Double(value).remainder(dividingBy: {b})"));
            guards.push(format!("        if _mof.isNaN || _mof.isInfinite || (abs(_mof) > 1e-9 && abs(abs(_mof) - {b}) > 1e-9) {{ throw ValidationError.outOfRange(\"value\", \"must be a multiple of {b}\") }}"));
        } else {
            guards.push(format!("        if (value / {b}).isInfinite {{ throw ValidationError.outOfRange(\"value\", \"must be a multiple of {b}\") }}"));
            guards.push(format!("        let _mof = value.remainder(dividingBy: {b})"));
            guards.push(format!("        if _mof.isNaN || _mof.isInfinite || (abs(_mof) > 1e-9 && abs(abs(_mof) - {b}) > 1e-9) {{ throw ValidationError.outOfRange(\"value\", \"must be a multiple of {b}\") }}"));
        }
    }

    format!(
        "struct {name}: Codable {{\n    let value: {swift_ty}\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n{}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        guards.join("\n")
    )
}

fn emit_string_wrapper(name: &str, c: &StringConstraints) -> String {
    let mut guards = Vec::new();
    if let Some(min) = c.min_length {
        guards.push(format!("        if value.count < {min} {{ throw ValidationError.outOfRange(\"value\", \"length must be >= {min}\") }}"));
    }
    if let Some(max) = c.max_length {
        guards.push(format!("        if value.count > {max} {{ throw ValidationError.outOfRange(\"value\", \"length must be <= {max}\") }}"));
    }
    if let Some(ref pat) = c.pattern {
        let escaped = swift_escape(pat);
        guards.push(format!("        if value.range(of: \"{escaped}\", options: .regularExpression) == nil {{ throw ValidationError.outOfRange(\"value\", \"must match pattern\") }}"));
    }

    format!(
        "struct {name}: Codable {{\n    let value: String\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        value = try container.decode(String.self)\n{}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        guards.join("\n")
    )
}

fn emit_array_wrapper(name: &str, arr: &ArraySchema, defs: &[DefEntry]) -> String {
    let mut guards = Vec::new();
    let mut preamble = String::new();

    if let Some(min) = arr.min_items {
        guards.push(format!("        if value.count < {min} {{ throw ValidationError.outOfRange(\"value\", \"must have at least {min} items\") }}"));
    }
    if let Some(max) = arr.max_items {
        guards.push(format!("        if value.count > {max} {{ throw ValidationError.outOfRange(\"value\", \"must have at most {max} items\") }}"));
    }

    // Item type validation (if items is not Any)
    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
        let mut item_counter = 0usize;
        let (item_pre, item_type) = emit_swift_sub_schema("Item", &arr.items, defs, &mut item_counter);
        if !item_pre.is_empty() { preamble.push_str(&item_pre); }
        guards.push(format!(
            "        for (i, item) in value.enumerated() {{ let data = _serializeAny(item.value); let _ = try JSONDecoder().decode({item_type}.self, from: data) }}"
        ));
    }

    // UniqueItems
    if arr.unique_items {
        guards.push(
            "        let serialized = try value.map { try String(data: _serializeAny($0.value), encoding: .utf8) ?? \"\" }\n        if Set(serialized).count != value.count { throw ValidationError.outOfRange(\"value\", \"items must be unique\") }"
                .to_string(),
        );
    }

    // Contains
    if let Some(contains) = &arr.contains {
        let mut con_counter = 0usize;
        let (con_pre, contains_type) = emit_swift_sub_schema("Con", &contains.schema, defs, &mut con_counter);
        if !con_pre.is_empty() { preamble.push_str(&con_pre); }
        let min = contains.min_contains.unwrap_or(1);
        guards.push(format!(
            "        let matchCount = value.filter {{ item in (try? JSONDecoder().decode({contains_type}.self, from: _serializeAny(item.value))) != nil }}.count"
        ));
        guards.push(format!(
            "        if matchCount < {min} {{ throw ValidationError.outOfRange(\"value\", \"must contain at least {min} matching items\") }}"
        ));
        if let Some(max) = contains.max_contains {
            guards.push(format!(
                "        if matchCount > {max} {{ throw ValidationError.outOfRange(\"value\", \"must contain at most {max} matching items\") }}"
            ));
        }
    }

    let body = format!(
        "struct {name}: Codable {{\n    let value: [AnyCodable]\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        value = try container.decode([AnyCodable].self)\n{}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        guards.join("\n")
    );
    format!("{preamble}{body}")
}

fn emit_type_guarded_wrapper(name: &str, guards: &[(TypeGuard, Box<SchemaIr>)], defs: &[DefEntry]) -> String {
    let mut checks = Vec::new();
    let mut preamble = String::new();

    for (guard, schema) in guards {
        match guard {
            TypeGuard::String => {
                if let SchemaIr::String(c) = schema.as_ref() {
                    checks.push("        if let s = raw.value as? String {".to_string());
                    if let Some(min) = c.min_length {
                        checks.push(format!("            if s.count < {min} {{ throw ValidationError.outOfRange(\"value\", \"minLength\") }}"));
                    }
                    if let Some(max) = c.max_length {
                        checks.push(format!("            if s.count > {max} {{ throw ValidationError.outOfRange(\"value\", \"maxLength\") }}"));
                    }
                    if let Some(ref pat) = c.pattern {
                        let escaped = swift_escape(pat);
                        checks.push(format!("            if s.range(of: \"{escaped}\", options: .regularExpression) == nil {{ throw ValidationError.outOfRange(\"value\", \"pattern\") }}"));
                    }
                    checks.push("        }".to_string());
                }
            }
            TypeGuard::Number => {
                let c = match schema.as_ref() {
                    SchemaIr::Number(c) | SchemaIr::Integer(c) => c,
                    _ => continue,
                };
                checks.push("        if let n = raw.value as? Double, !(raw.value is Bool) {".to_string());
                if let Some(v) = c.minimum {
                    let b = format_number(v);
                    checks.push(format!("            if n < {b} {{ throw ValidationError.outOfRange(\"value\", \"minimum\") }}"));
                }
                if let Some(v) = c.maximum {
                    let b = format_number(v);
                    checks.push(format!("            if n > {b} {{ throw ValidationError.outOfRange(\"value\", \"maximum\") }}"));
                }
                if let Some(v) = c.exclusive_minimum {
                    let b = format_number(v);
                    checks.push(format!("            if n <= {b} {{ throw ValidationError.outOfRange(\"value\", \"exclusiveMinimum\") }}"));
                }
                if let Some(v) = c.exclusive_maximum {
                    let b = format_number(v);
                    checks.push(format!("            if n >= {b} {{ throw ValidationError.outOfRange(\"value\", \"exclusiveMaximum\") }}"));
                }
                if let Some(v) = c.multiple_of {
                    let b = format_number(v);
                    checks.push(format!("            if (n / {b}).isInfinite {{ throw ValidationError.outOfRange(\"value\", \"multipleOf\") }}"));
                    checks.push(format!("            let _mof = n.remainder(dividingBy: {b})"));
                    checks.push(format!("            if _mof.isNaN || _mof.isInfinite || (abs(_mof) > 1e-9 && abs(abs(_mof) - {b}) > 1e-9) {{ throw ValidationError.outOfRange(\"value\", \"multipleOf\") }}"));
                }
                checks.push("        } else if let n = raw.value as? Int, !(raw.value is Bool) {".to_string());
                if let Some(v) = c.minimum {
                    let b = format_number(v);
                    checks.push(format!("            if Double(n) < {b} {{ throw ValidationError.outOfRange(\"value\", \"minimum\") }}"));
                }
                if let Some(v) = c.maximum {
                    let b = format_number(v);
                    checks.push(format!("            if Double(n) > {b} {{ throw ValidationError.outOfRange(\"value\", \"maximum\") }}"));
                }
                if let Some(v) = c.exclusive_minimum {
                    let b = format_number(v);
                    checks.push(format!("            if Double(n) <= {b} {{ throw ValidationError.outOfRange(\"value\", \"exclusiveMinimum\") }}"));
                }
                if let Some(v) = c.exclusive_maximum {
                    let b = format_number(v);
                    checks.push(format!("            if Double(n) >= {b} {{ throw ValidationError.outOfRange(\"value\", \"exclusiveMaximum\") }}"));
                }
                if let Some(v) = c.multiple_of {
                    let b = format_number(v);
                    checks.push(format!("            if (Double(n) / {b}).isInfinite {{ throw ValidationError.outOfRange(\"value\", \"multipleOf\") }}"));
                    checks.push(format!("            let _mofi = Double(n).remainder(dividingBy: {b})"));
                    checks.push(format!("            if _mofi.isNaN || _mofi.isInfinite || (abs(_mofi) > 1e-9 && abs(abs(_mofi) - {b}) > 1e-9) {{ throw ValidationError.outOfRange(\"value\", \"multipleOf\") }}"));
                }
                checks.push("        }".to_string());
            }
            TypeGuard::Object => {
                if let SchemaIr::Object(obj) = schema.as_ref() {
                    checks.push("        if let dict = raw.value as? [String: Any] {".to_string());
                    for (k, f) in &obj.fields {
                        if f.required {
                            checks.push(format!(
                                "            if dict[\"{}\"] == nil {{ throw ValidationError.outOfRange(\"value\", \"missing required: {}\") }}",
                                swift_escape(k), swift_escape(k)
                            ));
                        }
                    }
                    // Field type validation via JSON round-trip
                    for (k, f) in &obj.fields {
                        if matches!(&f.schema, SchemaIr::Any | SchemaIr::Unknown) { continue; }
                        let mut fc = 0usize;
                        let (fp, ft) = emit_swift_sub_schema("FV", &f.schema, defs, &mut fc);
                        if !fp.is_empty() { preamble.push_str(&fp); }
                        checks.push(format!(
                            "            if dict[\"{k}\"] != nil {{ let fd = _serializeAny(dict[\"{k}\"]!); let _ = try JSONDecoder().decode({ft}.self, from: fd) }}",
                            k = swift_escape(k)
                        ));
                    }
                    if let Some(min) = obj.min_properties {
                        checks.push(format!("            if dict.count < {min} {{ throw ValidationError.outOfRange(\"value\", \"minProperties\") }}"));
                    }
                    if let Some(max) = obj.max_properties {
                        checks.push(format!("            if dict.count > {max} {{ throw ValidationError.outOfRange(\"value\", \"maxProperties\") }}"));
                    }
                    // patternProperties + additionalProperties
                    if !obj.pattern_properties.is_empty() {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", swift_escape(k))).collect();
                        checks.push("            for (k, v) in dict {".to_string());
                        checks.push("                var matched = false".to_string());
                        for (pattern, pp_schema) in &obj.pattern_properties {
                            let mut pp_c = 0usize;
                            let (pp_pre, pt) = emit_swift_sub_schema("PP", pp_schema, defs, &mut pp_c);
                            if !pp_pre.is_empty() { preamble.push_str(&pp_pre); }
                            checks.push(format!(
                                "                if k.range(of: \"{}\", options: .regularExpression) != nil {{ matched = true; let pd = _serializeAny(v); let _ = try JSONDecoder().decode({pt}.self, from: pd) }}",
                                swift_escape(pattern)
                            ));
                        }
                        if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                            let ks = if known.is_empty() { "Set<String>()".to_string() } else { format!("Set([{}])", known.join(", ")) };
                            checks.push(format!("                if !matched && !{ks}.contains(k) {{ throw ValidationError.outOfRange(k, \"unexpected property\") }}"));
                        } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                            let mut ap_c = 0usize;
                            let (ap_pre, at) = emit_swift_sub_schema("AP", ap, defs, &mut ap_c);
                            if !ap_pre.is_empty() { preamble.push_str(&ap_pre); }
                            let ks = if known.is_empty() { "Set<String>()".to_string() } else { format!("Set([{}])", known.join(", ")) };
                            checks.push(format!("                if !matched && !{ks}.contains(k) {{ let ad = _serializeAny(v); let _ = try JSONDecoder().decode({at}.self, from: ad) }}"));
                        }
                        checks.push("            }".to_string());
                    } else if matches!(obj.additional_properties, AdditionalProperties::Forbidden) {
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", swift_escape(k))).collect();
                        let ks = if known.is_empty() { "Set<String>()".to_string() } else { format!("Set([{}])", known.join(", ")) };
                        checks.push(format!("            for k in dict.keys where !{ks}.contains(k) {{ throw ValidationError.outOfRange(k, \"unexpected property\") }}"));
                    } else if let AdditionalProperties::Schema(ap) = &obj.additional_properties {
                        let mut ap_c = 0usize;
                        let (ap_pre, at) = emit_swift_sub_schema("AP", ap, defs, &mut ap_c);
                        if !ap_pre.is_empty() { preamble.push_str(&ap_pre); }
                        let known: Vec<String> = obj.fields.keys().map(|k| format!("\"{}\"", swift_escape(k))).collect();
                        let ks = if known.is_empty() { "Set<String>()".to_string() } else { format!("Set([{}])", known.join(", ")) };
                        if at != "AnyCodable" {
                            checks.push(format!("            for (k, v) in dict where !{ks}.contains(k) {{ let ad = _serializeAny(v); let _ = try JSONDecoder().decode({at}.self, from: ad) }}"));
                        }
                    }
                    // propertyNames
                    if let Some(pn) = &obj.property_names {
                        emit_property_names_check_tg(pn, &mut checks, &mut preamble, defs);
                    }
                    // dependentRequired
                    for (prop, required) in &obj.dependent_required {
                        for r in required {
                            checks.push(format!(
                                "            if dict[\"{}\"] != nil && dict[\"{}\"] == nil {{ throw ValidationError.outOfRange(\"{}\", \"dependentRequired\") }}",
                                swift_escape(prop), swift_escape(r), swift_escape(r)
                            ));
                        }
                    }
                    // dependentSchemas
                    let mut ds_counter = 0usize;
                    for (prop, dep_schema) in &obj.dependent_schemas {
                        let (sub_pre, dt) = emit_swift_sub_schema("DS", dep_schema, defs, &mut ds_counter);
                        if !sub_pre.is_empty() {
                            preamble.push_str(&sub_pre);
                        }
                        checks.push(format!(
                            "            if dict[\"{}\"] != nil {{ let dd = _serializeAny(raw.value); let _ = try JSONDecoder().decode({dt}.self, from: dd) }}",
                            swift_escape(prop)
                        ));
                    }
                    checks.push("        }".to_string());
                }
                // Record in Object TypeGuard
                if let SchemaIr::Record(rec) = schema.as_ref() {
                    let vt = swift_type(&rec.value, defs);
                    if vt != "AnyCodable" {
                        checks.push("        if let dict = raw.value as? [String: Any] {".to_string());
                        checks.push(format!("            for (_, v) in dict {{ let rd = _serializeAny(v); let _ = try JSONDecoder().decode({vt}.self, from: rd) }}"));
                        checks.push("        }".to_string());
                    }
                }
            }
            TypeGuard::Array => {
                if let SchemaIr::Array(arr) = schema.as_ref() {
                    checks.push("        if let arr = raw.value as? [Any] {".to_string());
                    if let Some(min) = arr.min_items {
                        checks.push(format!("            if arr.count < {min} {{ throw ValidationError.outOfRange(\"value\", \"minItems\") }}"));
                    }
                    if let Some(max) = arr.max_items {
                        checks.push(format!("            if arr.count > {max} {{ throw ValidationError.outOfRange(\"value\", \"maxItems\") }}"));
                    }
                    if !matches!(arr.items.as_ref(), SchemaIr::Any) {
                        let mut item_counter = 0usize;
                        let (item_pre, it) = emit_swift_sub_schema("ArrItem", &arr.items, defs, &mut item_counter);
                        if !item_pre.is_empty() { preamble.push_str(&item_pre); }
                        checks.push(format!("            for item in arr {{ let id = _serializeAny(item); let _ = try JSONDecoder().decode({it}.self, from: id) }}"));
                    }
                    if arr.unique_items {
                        checks.push("            let ser = try arr.map { try String(data: _serializeAny($0), encoding: .utf8) ?? \"\" }".to_string());
                        checks.push("            if Set(ser).count != arr.count { throw ValidationError.outOfRange(\"value\", \"uniqueItems\") }".to_string());
                    }
                    if let Some(contains) = &arr.contains {
                        let mut ct_counter = 0usize;
                        let (ct_pre, ct) = emit_swift_sub_schema("Con", &contains.schema, defs, &mut ct_counter);
                        if !ct_pre.is_empty() { preamble.push_str(&ct_pre); }
                        let min = contains.min_contains.unwrap_or(1);
                        checks.push(format!("            let mc = arr.filter {{ i in (try? JSONDecoder().decode({ct}.self, from: _serializeAny(i))) != nil }}.count"));
                        checks.push(format!("            if mc < {min} {{ throw ValidationError.outOfRange(\"value\", \"must contain at least {min} matching items\") }}"));
                        if let Some(max) = contains.max_contains {
                            checks.push(format!("            if mc > {max} {{ throw ValidationError.outOfRange(\"value\", \"must contain at most {max} matching items\") }}"));
                        }
                    }
                    checks.push("        }".to_string());
                }
                // Tuple in Array TypeGuard
                if let SchemaIr::Tuple(tuple) = schema.as_ref() {
                    checks.push("        if let arr = raw.value as? [Any] {".to_string());
                    for (i, item) in tuple.items.iter().enumerate() {
                        if matches!(item, SchemaIr::Any) { continue; }
                        let mut ti_c = 0usize;
                        let (ti_pre, it) = emit_swift_sub_schema("TI", item, defs, &mut ti_c);
                        if !ti_pre.is_empty() { preamble.push_str(&ti_pre); }
                        checks.push(format!("            if arr.count > {i} {{ let td = _serializeAny(arr[{i}]); let _ = try JSONDecoder().decode({it}.self, from: td) }}"));
                    }
                    let pc = tuple.items.len();
                    if let Some(rest) = &tuple.rest {
                        if !matches!(rest.as_ref(), SchemaIr::Any) {
                            let mut rest_c = 0usize;
                            let (rest_pre, rt) = emit_swift_sub_schema("Rest", rest, defs, &mut rest_c);
                            if !rest_pre.is_empty() { preamble.push_str(&rest_pre); }
                            checks.push(format!("            for ri in {pc}..<arr.count {{ let rd = _serializeAny(arr[ri]); let _ = try JSONDecoder().decode({rt}.self, from: rd) }}"));
                        }
                    } else {
                        checks.push(format!("            if arr.count > {pc} {{ throw ValidationError.outOfRange(\"value\", \"too many items\") }}"));
                    }
                    if let Some(min) = tuple.min_items {
                        checks.push(format!("            if arr.count < {min} {{ throw ValidationError.outOfRange(\"value\", \"minItems\") }}"));
                    }
                    if let Some(max) = tuple.max_items {
                        checks.push(format!("            if arr.count > {max} {{ throw ValidationError.outOfRange(\"value\", \"maxItems\") }}"));
                    }
                    if tuple.unique_items {
                        checks.push("            let ser = try arr.map { try String(data: _serializeAny($0), encoding: .utf8) ?? \"\" }".to_string());
                        checks.push("            if Set(ser).count != arr.count { throw ValidationError.outOfRange(\"value\", \"uniqueItems\") }".to_string());
                    }
                    checks.push("        }".to_string());
                }
            }
        }
    }

    let body = format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n{}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        checks.join("\n")
    );
    format!("{preamble}{body}")
}

fn emit_literal_wrapper(name: &str, lit: &LiteralValue) -> String {
    let check = match lit {
        LiteralValue::Bool(b) => {
            let val = if *b { "true" } else { "false" };
            format!("        guard (raw.value as? Bool) == {val} else {{ throw ValidationError.outOfRange(\"value\", \"must be {val}\") }}")
        }
        LiteralValue::Integer(i) => {
            format!("        guard !(raw.value is Bool), let n = raw.value as? Int, n == {i} else {{ throw ValidationError.outOfRange(\"value\", \"must be {i}\") }}")
        }
        LiteralValue::Number(n) => {
            let b = format_number(*n);
            format!("        guard !(raw.value is Bool), let d = raw.value as? Double, d == {b} else {{ throw ValidationError.outOfRange(\"value\", \"must be {b}\") }}")
        }
        LiteralValue::String(s) => {
            let escaped = swift_escape(s);
            format!("        guard let s = raw.value as? String, s == \"{escaped}\" else {{ throw ValidationError.outOfRange(\"value\", \"must be \\\"{escaped}\\\"\") }}")
        }
        LiteralValue::Null => {
            "        guard raw.value is NSNull else { throw ValidationError.outOfRange(\"value\", \"must be null\") }".to_string()
        }
    };

    format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n{check}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
    )
}

fn emit_mixed_enum_wrapper(name: &str, lits: &[LiteralValue]) -> String {
    let mut checks = Vec::new();
    for lit in lits {
        let check = match lit {
            LiteralValue::Bool(b) => {
                let val = if *b { "true" } else { "false" };
                format!("(raw.value as? Bool) == {val}")
            }
            LiteralValue::Integer(i) => {
                format!("(!(raw.value is Bool) && ((raw.value as? Int) == {i} || (raw.value as? Double) == Double({i})))")
            }
            LiteralValue::Number(n) => {
                let b = format_number(*n);
                format!("(!(raw.value is Bool) && ((raw.value as? Double) == {b} || (raw.value as? Int).map(Double.init) == {b}))")
            }
            LiteralValue::String(s) => {
                format!("(raw.value as? String) == \"{}\"", swift_escape(s))
            }
            LiteralValue::Null => "raw.value is NSNull".to_string(),
        };
        checks.push(check);
    }

    let condition = checks.join(" || ");
    format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        guard {condition} else {{ throw ValidationError.outOfRange(\"value\", \"must be one of the allowed values\") }}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
    )
}

fn emit_const_equal_wrapper(name: &str, val: &serde_json::Value) -> String {
    let json_str = serde_json::to_string(val).unwrap_or_else(|_| "null".to_string());
    let escaped = swift_escape(&json_str);

    format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        let expectedData = \"{escaped}\".data(using: .utf8)!\n        let expected = try JSONDecoder().decode(AnyCodable.self, from: expectedData)\n        let rawData = _serializeAny(raw.value)\n        let expData = _serializeAny(expected.value)\n        guard rawData == expData else {{ throw ValidationError.outOfRange(\"value\", \"must equal const value\") }}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
    )
}

fn emit_complex_enum_wrapper(name: &str, vals: &[serde_json::Value]) -> String {
    let json_str = serde_json::to_string(vals).unwrap_or_else(|_| "[]".to_string());
    let escaped = swift_escape(&json_str);

    format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        let allowedData = \"{escaped}\".data(using: .utf8)!\n        let allowed = try JSONDecoder().decode([AnyCodable].self, from: allowedData)\n        let rawData = _serializeAny(raw.value)\n        let matched = allowed.contains {{ a in (try? _serializeAny(a.value)) == rawData }}\n        guard matched else {{ throw ValidationError.outOfRange(\"value\", \"must be one of the allowed values\") }}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
    )
}

/// Emit a sub-schema as a named struct if it's complex, returning (preamble, type_name).
/// Emit a sub-schema as a named struct if it's complex, returning (preamble, type_name).
fn emit_swift_sub_schema(prefix: &str, ir: &SchemaIr, defs: &[DefEntry], _counter: &mut usize) -> (String, String) {
    // Unwrap modifiers
    let inner = unwrap_modifiers(ir);

    // Any (boolean true) — accepts everything, no wrapper needed
    if matches!(inner, SchemaIr::Any | SchemaIr::Unknown) {
        return (String::new(), "AnyCodable".to_string());
    }

    // Never needs a wrapper (Swift's Never type can't be decoded)
    if matches!(inner, SchemaIr::Never) {
        let idx = SUB_SCHEMA_COUNTER.fetch_add(1, Ordering::Relaxed) + 1;
        let sub_name = format!("_{prefix}{idx}");
        let def = format!(
            "private struct {sub_name}: Codable {{\n    // @validate\n    init(from decoder: Decoder) throws {{\n        throw ValidationError.outOfRange(\"value\", \"schema rejects all values\")\n    }}\n    func encode(to encoder: Encoder) throws {{}}\n}}"
        );
        return (format!("{def}\n\n"), sub_name);
    }

    let st = swift_type(ir, defs);

    // If the IR needs validation that swift_type alone can't express, emit a wrapper
    // This catches Literal(exact value), ConstEqual, MixedEnum, ComplexEnum, Not, Conditional,
    // TypeGuarded, constrained Integer/Number/String, constrained Array, etc.
    let needs_wrapper = match inner {
        SchemaIr::Literal(_) | SchemaIr::ConstEqual(_) | SchemaIr::ComplexEnum(_)
        | SchemaIr::MixedEnum(_) | SchemaIr::TypeGuarded(_) | SchemaIr::Not { .. }
        | SchemaIr::Conditional { .. } | SchemaIr::ExclusiveUnion(_)
        | SchemaIr::Object(_) | SchemaIr::Tuple(_) => true,
        SchemaIr::Integer(c) => c.minimum.is_some() || c.maximum.is_some()
            || c.exclusive_minimum.is_some() || c.exclusive_maximum.is_some()
            || c.multiple_of.is_some(),
        SchemaIr::Number(c) => c.minimum.is_some() || c.maximum.is_some()
            || c.exclusive_minimum.is_some() || c.exclusive_maximum.is_some()
            || c.multiple_of.is_some(),
        SchemaIr::String(c) => c.min_length.is_some() || c.max_length.is_some() || c.pattern.is_some(),
        SchemaIr::Boolean => true, // needs wrapper to reject non-bool
        SchemaIr::Null => true, // needs wrapper for null-only
        SchemaIr::Array(arr) => arr.min_items.is_some() || arr.max_items.is_some()
            || arr.unique_items || arr.contains.is_some()
            || !matches!(arr.items.as_ref(), SchemaIr::Any),
        SchemaIr::Intersection(members) if members.len() > 1 => true,
        SchemaIr::Intersection(members) if members.len() == 1 => {
            // Delegate to single member — handled via recursive call below
            return emit_swift_sub_schema(prefix, &members[0], defs, _counter);
        }
        SchemaIr::Union(members) if members.len() > 1 => st == "AnyCodable",
        SchemaIr::Enum(cases) if cases.is_empty() => true,
        _ => st == "AnyCodable",
    };

    if needs_wrapper {
        let idx = SUB_SCHEMA_COUNTER.fetch_add(1, Ordering::Relaxed) + 1;
        let sub_name = format!("_{prefix}{idx}");
        let def = privatize_decl(emit_wrapper_struct(&sub_name, inner, defs), &sub_name);
        return (format!("{def}\n\n"), sub_name);
    }

    // If swift_type gives us a real named type, use it directly
    if st != "AnyCodable" {
        return (String::new(), st);
    }
    // Need to emit a named wrapper struct
    let idx = SUB_SCHEMA_COUNTER.fetch_add(1, Ordering::Relaxed) + 1;
    let sub_name = format!("_{prefix}{idx}");
    let def = privatize_decl(emit_wrapper_struct(&sub_name, ir, defs), &sub_name);
    (format!("{def}\n\n"), sub_name)
}

fn emit_not_wrapper(name: &str, _base: &SchemaIr, not_schema: &SchemaIr, defs: &[DefEntry]) -> String {
    let mut counter = 0usize;
    let (preamble, not_type) = emit_swift_sub_schema("Not", not_schema, defs, &mut counter);
    let body = format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        let data = _serializeAny(raw.value)\n        if (try? JSONDecoder().decode({not_type}.self, from: data)) != nil {{\n            throw ValidationError.outOfRange(\"value\", \"must not match excluded schema\")\n        }}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}"
    );
    format!("{preamble}{body}")
}

fn emit_oneof_wrapper(name: &str, members: &[SchemaIr], defs: &[DefEntry]) -> String {
    let mut counter = 0usize;
    let mut preamble = String::new();
    let mut type_checks = Vec::new();
    for member in members.iter() {
        let (p, member_type) = emit_swift_sub_schema("OneOf", member, defs, &mut counter);
        preamble.push_str(&p);
        type_checks.push(format!(
            "        if (try? JSONDecoder().decode({member_type}.self, from: data)) != nil {{ matches += 1 }}"
        ));
    }

    let body = format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        let data = _serializeAny(raw.value)\n        var matches = 0\n{}\n        guard matches == 1 else {{ throw ValidationError.outOfRange(\"value\", \"must match exactly one schema\") }}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        type_checks.join("\n")
    );
    format!("{preamble}{body}")
}

fn emit_intersection_wrapper(name: &str, members: &[SchemaIr], defs: &[DefEntry]) -> String {
    let mut counter = 0usize;
    let mut preamble = String::new();
    let mut validation_lines = Vec::new();
    for member in members {
        let (p, member_type) = emit_swift_sub_schema("Inter", member, defs, &mut counter);
        preamble.push_str(&p);
        validation_lines.push(format!(
            "        let _ = try JSONDecoder().decode({member_type}.self, from: data)"
        ));
    }

    let body = format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        let data = _serializeAny(raw.value)\n{}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        validation_lines.join("\n")
    );
    format!("{preamble}{body}")
}

fn emit_conditional_wrapper(
    name: &str,
    if_schema: &SchemaIr,
    then_schema: Option<&SchemaIr>,
    else_schema: Option<&SchemaIr>,
    defs: &[DefEntry],
) -> String {
    let mut counter = 0usize;
    let mut preamble = String::new();
    let (p, if_type) = emit_swift_sub_schema("If", if_schema, defs, &mut counter);
    preamble.push_str(&p);
    let mut body = Vec::new();
    body.push("        let data = _serializeAny(raw.value)".to_string());
    body.push(format!(
        "        let ifMatched = (try? JSONDecoder().decode({if_type}.self, from: data)) != nil"
    ));
    if let Some(then_s) = then_schema {
        let (p, then_type) = emit_swift_sub_schema("Then", then_s, defs, &mut counter);
        preamble.push_str(&p);
        body.push(format!(
            "        if ifMatched {{ let _ = try JSONDecoder().decode({then_type}.self, from: data) }}"
        ));
    }
    if let Some(else_s) = else_schema {
        let (p, else_type) = emit_swift_sub_schema("Else", else_s, defs, &mut counter);
        preamble.push_str(&p);
        body.push(format!(
            "        if !ifMatched {{ let _ = try JSONDecoder().decode({else_type}.self, from: data) }}"
        ));
    }

    let struct_body = format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n{}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        body.join("\n")
    );
    format!("{preamble}{struct_body}")
}

fn emit_anyof_wrapper(name: &str, members: &[SchemaIr], defs: &[DefEntry]) -> String {
    let mut counter = 0usize;
    let mut preamble = String::new();
    let mut type_checks = Vec::new();
    for member in members {
        let (p, member_type) = emit_swift_sub_schema("AnyOf", member, defs, &mut counter);
        preamble.push_str(&p);
        type_checks.push(format!(
            "        if (try? JSONDecoder().decode({member_type}.self, from: data)) != nil {{ matches += 1 }}"
        ));
    }

    let body = format!(
        "struct {name}: Codable {{\n    let value: AnyCodable\n\n    // @validate\n    init(from decoder: Decoder) throws {{\n        let container = try decoder.singleValueContainer()\n        let raw = try container.decode(AnyCodable.self)\n        value = raw\n        let data = _serializeAny(raw.value)\n        var matches = 0\n{}\n        guard matches >= 1 else {{ throw ValidationError.outOfRange(\"value\", \"must match at least one schema\") }}\n    }}\n\n    func encode(to encoder: Encoder) throws {{\n        var container = encoder.singleValueContainer()\n        try container.encode(value)\n    }}\n}}",
        type_checks.join("\n")
    );
    format!("{preamble}{body}")
}

fn emit_nested_enum(name: &str, cases: &[String]) -> String {
    let mut lines = vec![format!("    enum {name}: String, Codable {{")];
    for case in cases {
        let swift_case = to_camel_case(case);
        if swift_case != *case {
            lines.push(format!(
                "        case {swift_case} = \"{}\"",
                swift_escape(case)
            ));
        } else {
            lines.push(format!("        case {swift_case}"));
        }
    }
    lines.push("    }".to_string());
    lines.join("\n")
}

fn swift_type(ir: &SchemaIr, defs: &[DefEntry]) -> String {
    match ir {
        SchemaIr::String(c) => match &c.format {
            Some(StringFormat::Email) => "EmailAddress".to_string(),
            Some(StringFormat::DateTime) => "Date".to_string(),
            Some(StringFormat::Date) => "Date".to_string(),
            Some(StringFormat::Time) => "TimeString".to_string(),
            Some(StringFormat::Uri) => "URL".to_string(),
            Some(StringFormat::Uuid) => "UUID".to_string(),
            Some(StringFormat::Ip) => "IPAddress".to_string(),
            Some(StringFormat::Ipv4) => "IPv4Address".to_string(),
            Some(StringFormat::Ipv6) => "IPv6Address".to_string(),
            Some(StringFormat::Hostname) => "HostnameString".to_string(),
            Some(StringFormat::Duration) => "DurationString".to_string(),
            Some(StringFormat::Base64) => "Base64String".to_string(),
            None => "String".to_string(),
        },
        SchemaIr::Number(_) => "Double".to_string(),
        SchemaIr::Integer(_) => "Int".to_string(),
        SchemaIr::Boolean => "Bool".to_string(),
        SchemaIr::Null => "Never?".to_string(),
        SchemaIr::Any | SchemaIr::Unknown => "AnyCodable".to_string(),
        SchemaIr::Never => "Never".to_string(),

        SchemaIr::Literal(lit) => match lit {
            LiteralValue::String(_) => "String".to_string(),
            LiteralValue::Number(_) => "Double".to_string(),
            LiteralValue::Integer(_) => "Int".to_string(),
            LiteralValue::Bool(_) => "Bool".to_string(),
            LiteralValue::Null => "Never?".to_string(),
        },

        SchemaIr::ConstEqual(_) | SchemaIr::ComplexEnum(_) => "AnyCodable".to_string(),

        SchemaIr::Enum(_) => {
            // For inline enums referenced as a type, use String
            // (named enums get their own type via emit_struct)
            "String".to_string()
        }

        SchemaIr::MixedEnum(_) => "AnyCodable".to_string(),

        SchemaIr::Array(arr) => {
            format!("[{}]", swift_type(&arr.items, defs))
        }

        SchemaIr::Tuple(_) => "[AnyCodable]".to_string(),

        SchemaIr::Object(_) => "[String: AnyCodable]".to_string(),

        SchemaIr::Record(rec) => {
            format!("[String: {}]", swift_type(&rec.value, defs))
        }

        SchemaIr::Union(members) | SchemaIr::ExclusiveUnion(members) => {
            if members.len() == 2 {
                let non_null: Vec<_> = members
                    .iter()
                    .filter(|m| !matches!(m, SchemaIr::Null))
                    .collect();
                if non_null.len() == 1 {
                    return format!("{}?", swift_type(non_null[0], defs));
                }
            }
            "AnyCodable".to_string()
        }

        SchemaIr::Intersection(_) => "AnyCodable".to_string(),

        SchemaIr::Nullable(inner) => format!("{}?", swift_type(inner, defs)),
        SchemaIr::Optional(inner) => format!("{}?", swift_type(inner, defs)),
        SchemaIr::Default(inner, _) => swift_type(inner, defs),
        SchemaIr::Describe(inner, _) => swift_type(inner, defs),
        SchemaIr::Not { base, .. } => swift_type(base, defs),
        SchemaIr::Conditional { base, .. } => swift_type(base, defs),
        SchemaIr::TypeGuarded(_) => "AnyCodable".to_string(),

        SchemaIr::Ref(name) | SchemaIr::Lazy(name) => {
            // A ref to a def that was never converted would not compile —
            // degrade to accept-all rather than emitting a dangling type name.
            if defs.iter().any(|d| d.name == *name) {
                sanitize_swift_name(name)
            } else {
                "AnyCodable".to_string()
            }
        }
    }
}

/// Convert a string to lowerCamelCase (Swift convention for properties).
/// Preserves already-camelCase input like "tradeId".
fn to_camel_case(s: &str) -> String {
    // If input has no separators and starts lowercase, it's already camelCase
    if !s.contains(|c: char| !c.is_ascii_alphanumeric())
        && s.chars().next().is_some_and(|c| c.is_ascii_lowercase())
    {
        let result = s.to_string();
        return if is_swift_keyword(&result) {
            format!("`{result}`")
        } else {
            result
        };
    }

    let parts: Vec<&str> = s
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
        .collect();

    if parts.is_empty() {
        return s.to_string();
    }

    let mut result = parts[0].to_lowercase();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }

    if is_swift_keyword(&result) {
        format!("`{result}`")
    } else {
        result
    }
}

// ── Field constraint extraction ──────────────────────────────────────────────

enum FieldGuard {
    // Numeric
    Minimum(f64),
    Maximum(f64),
    ExclusiveMinimum(f64),
    ExclusiveMaximum(f64),
    MultipleOf(f64),
    // String
    MinLength(u64),
    MaxLength(u64),
    Pattern(String),
    // Array
    MinItems(u64),
    MaxItems(u64),
}

/// Extract validation guards from a schema IR node.
fn field_guards(ir: &SchemaIr) -> Vec<FieldGuard> {
    match ir {
        SchemaIr::Number(c) | SchemaIr::Integer(c) => {
            let mut guards = Vec::new();
            if let Some(v) = c.minimum { guards.push(FieldGuard::Minimum(v)); }
            if let Some(v) = c.maximum { guards.push(FieldGuard::Maximum(v)); }
            if let Some(v) = c.exclusive_minimum { guards.push(FieldGuard::ExclusiveMinimum(v)); }
            if let Some(v) = c.exclusive_maximum { guards.push(FieldGuard::ExclusiveMaximum(v)); }
            if let Some(v) = c.multiple_of { guards.push(FieldGuard::MultipleOf(v)); }
            guards
        }
        SchemaIr::String(c) => {
            // Skip string constraints if a format type handles validation already
            if c.format.is_some() {
                return Vec::new();
            }
            let mut guards = Vec::new();
            if let Some(v) = c.min_length { guards.push(FieldGuard::MinLength(v)); }
            if let Some(v) = c.max_length { guards.push(FieldGuard::MaxLength(v)); }
            if let Some(ref v) = c.pattern { guards.push(FieldGuard::Pattern(v.clone())); }
            guards
        }
        SchemaIr::Enum(_) => {
            // Handled via nested enum type, not a guard
            Vec::new()
        }
        SchemaIr::Array(arr) => {
            let mut guards = Vec::new();
            if let Some(v) = arr.min_items { guards.push(FieldGuard::MinItems(v)); }
            if let Some(v) = arr.max_items { guards.push(FieldGuard::MaxItems(v)); }
            guards
        }
        SchemaIr::Describe(inner, _) | SchemaIr::Default(inner, _) => field_guards(inner),
        _ => Vec::new(),
    }
}

/// Format a number for Swift source code — use integer form when possible.
fn format_number(n: f64) -> String {
    if n == n.trunc() && n.abs() < 1e15 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

/// Emit propertyNames validation for the Object struct path.
/// `keys_expr` is the Swift expression for the keys collection (e.g., "allKeysContainer.allKeys").
fn emit_property_names_check(
    pn: &SchemaIr,
    keys_expr: &str,
    lines: &mut Vec<String>,
    preamble: &mut String,
    defs: &[DefEntry],
) {
    let inner = unwrap_modifiers(pn);
    match inner {
        SchemaIr::Never => {
            lines.push(format!("        if !{keys_expr}.isEmpty {{ throw ValidationError.outOfRange(\"value\", \"propertyNames: no properties allowed\") }}"));
        }
        SchemaIr::String(c) => {
            lines.push(format!("        for key in {keys_expr} {{"));
            if let Some(max) = c.max_length {
                lines.push(format!("            if key.stringValue.count > {max} {{ throw ValidationError.outOfRange(key.stringValue, \"propertyNames\") }}"));
            }
            if let Some(min) = c.min_length {
                lines.push(format!("            if key.stringValue.count < {min} {{ throw ValidationError.outOfRange(key.stringValue, \"propertyNames\") }}"));
            }
            if let Some(ref pat) = c.pattern {
                lines.push(format!("            if key.stringValue.range(of: \"{}\", options: .regularExpression) == nil {{ throw ValidationError.outOfRange(key.stringValue, \"propertyNames\") }}", swift_escape(pat)));
            }
            lines.push("        }".to_string());
        }
        SchemaIr::Literal(LiteralValue::String(s)) => {
            let escaped = swift_escape(s);
            lines.push(format!("        for key in {keys_expr} {{ if key.stringValue != \"{escaped}\" {{ throw ValidationError.outOfRange(key.stringValue, \"propertyNames\") }} }}"));
        }
        SchemaIr::Enum(cases) => {
            let allowed: Vec<String> = cases.iter().map(|c| format!("\"{}\"", swift_escape(c))).collect();
            lines.push(format!("        let _pnAllowed: Set<String> = [{}]", allowed.join(", ")));
            lines.push(format!("        for key in {keys_expr} {{ if !_pnAllowed.contains(key.stringValue) {{ throw ValidationError.outOfRange(key.stringValue, \"propertyNames\") }} }}"));
        }
        _ => {
            // Generic: serialize each key as JSON string and validate against sub-schema
            let mut sub_counter = 0usize;
            let (sub_pre, pn_type) = emit_swift_sub_schema("PN", pn, defs, &mut sub_counter);
            if !sub_pre.is_empty() {
                preamble.push_str(&sub_pre);
            }
            if pn_type != "AnyCodable" {
                lines.push(format!("        for key in {keys_expr} {{ let kd = _serializeAny(key.stringValue); let _ = try JSONDecoder().decode({pn_type}.self, from: kd) }}"));
            }
        }
    }
}

/// Emit propertyNames validation for the TypeGuarded wrapper path.
/// Uses `dict.keys` iteration (different syntax from the keyed container approach).
fn emit_property_names_check_tg(
    pn: &SchemaIr,
    checks: &mut Vec<String>,
    preamble: &mut String,
    defs: &[DefEntry],
) {
    let inner = unwrap_modifiers(pn);
    match inner {
        SchemaIr::Never => {
            checks.push("            if !dict.isEmpty { throw ValidationError.outOfRange(\"value\", \"propertyNames: no properties allowed\") }".to_string());
        }
        SchemaIr::String(c) => {
            if let Some(max) = c.max_length {
                checks.push(format!("            for k in dict.keys {{ if k.count > {max} {{ throw ValidationError.outOfRange(k, \"propertyNames\") }} }}"));
            }
            if let Some(min) = c.min_length {
                checks.push(format!("            for k in dict.keys {{ if k.count < {min} {{ throw ValidationError.outOfRange(k, \"propertyNames\") }} }}"));
            }
            if let Some(ref pat) = c.pattern {
                checks.push(format!("            for k in dict.keys {{ if k.range(of: \"{}\", options: .regularExpression) == nil {{ throw ValidationError.outOfRange(k, \"propertyNames\") }} }}", swift_escape(pat)));
            }
        }
        SchemaIr::Literal(LiteralValue::String(s)) => {
            let escaped = swift_escape(s);
            checks.push(format!("            for k in dict.keys {{ if k != \"{escaped}\" {{ throw ValidationError.outOfRange(k, \"propertyNames\") }} }}"));
        }
        SchemaIr::Enum(cases) => {
            let allowed: Vec<String> = cases.iter().map(|c| format!("\"{}\"", swift_escape(c))).collect();
            checks.push(format!("            let _pnAllowed: Set<String> = [{}]", allowed.join(", ")));
            checks.push("            for k in dict.keys { if !_pnAllowed.contains(k) { throw ValidationError.outOfRange(k, \"propertyNames\") } }".to_string());
        }
        _ => {
            // Generic: serialize each key as JSON string and validate against sub-schema
            let mut sub_counter = 0usize;
            let (sub_pre, pn_type) = emit_swift_sub_schema("PN", pn, defs, &mut sub_counter);
            if !sub_pre.is_empty() {
                preamble.push_str(&sub_pre);
            }
            if pn_type != "AnyCodable" {
                checks.push(format!("            for k in dict.keys {{ let kd = _serializeAny(k); let _ = try JSONDecoder().decode({pn_type}.self, from: kd) }}"));
            }
        }
    }
}

/// Emit Swift guard statements for a single field's constraints.
fn emit_guard_lines(
    swift_name: &str,
    optional: bool,
    guards: &[FieldGuard],
    lines: &mut Vec<String>,
) {
    for guard in guards {
        let v = if optional { "v" } else { swift_name };

        match guard {
            FieldGuard::Minimum(n) => {
                let bound = format_number(*n);
                emit_comparison(swift_name, v, optional, ">=", &bound, &format!(">= {bound}"), lines);
            }
            FieldGuard::Maximum(n) => {
                let bound = format_number(*n);
                emit_comparison(swift_name, v, optional, "<=", &bound, &format!("<= {bound}"), lines);
            }
            FieldGuard::ExclusiveMinimum(n) => {
                let bound = format_number(*n);
                emit_comparison(swift_name, v, optional, ">", &bound, &format!("> {bound}"), lines);
            }
            FieldGuard::ExclusiveMaximum(n) => {
                let bound = format_number(*n);
                emit_comparison(swift_name, v, optional, "<", &bound, &format!("< {bound}"), lines);
            }
            FieldGuard::MultipleOf(n) => {
                let bound = format_number(*n);
                let msg = format!("must be a multiple of {bound}");
                if optional {
                    lines.push(format!(
                        "        if let v = {swift_name} {{ if (Double(v) / {bound}).isInfinite {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}; let _mof = Double(v).remainder(dividingBy: {bound}); if _mof.isNaN || _mof.isInfinite || (abs(_mof) > 1e-9 && abs(abs(_mof) - {bound}) > 1e-9) {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }} }}"
                    ));
                } else {
                    lines.push(format!(
                        "        if (Double({v}) / {bound}).isInfinite {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                    lines.push(format!(
                        "        let _mof = Double({v}).remainder(dividingBy: {bound})"
                    ));
                    lines.push(format!(
                        "        if _mof.isNaN || _mof.isInfinite || (abs(_mof) > 1e-9 && abs(abs(_mof) - {bound}) > 1e-9) {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                }
            }
            FieldGuard::MinLength(n) => {
                let msg = format!("length must be >= {n}");
                if optional {
                    lines.push(format!(
                        "        if let v = {swift_name}, v.count < {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                } else {
                    lines.push(format!(
                        "        if {v}.count < {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                }
            }
            FieldGuard::MaxLength(n) => {
                let msg = format!("length must be <= {n}");
                if optional {
                    lines.push(format!(
                        "        if let v = {swift_name}, v.count > {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                } else {
                    lines.push(format!(
                        "        if {v}.count > {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                }
            }
            FieldGuard::Pattern(pat) => {
                let escaped = swift_escape(pat);
                let msg = format!("must match pattern {escaped}");
                if optional {
                    lines.push(format!(
                        "        if let v = {swift_name}, v.range(of: \"{escaped}\", options: .regularExpression) == nil {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                } else {
                    lines.push(format!(
                        "        if {v}.range(of: \"{escaped}\", options: .regularExpression) == nil {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                }
            }
            FieldGuard::MinItems(n) => {
                let msg = format!("must have at least {n} items");
                if optional {
                    lines.push(format!(
                        "        if let v = {swift_name}, v.count < {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                } else {
                    lines.push(format!(
                        "        if {v}.count < {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                }
            }
            FieldGuard::MaxItems(n) => {
                let msg = format!("must have at most {n} items");
                if optional {
                    lines.push(format!(
                        "        if let v = {swift_name}, v.count > {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                } else {
                    lines.push(format!(
                        "        if {v}.count > {n} {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
                    ));
                }
            }
        }
    }
}

fn emit_comparison(
    swift_name: &str,
    v: &str,
    optional: bool,
    op: &str,
    bound: &str,
    msg: &str,
    lines: &mut Vec<String>,
) {
    if optional {
        lines.push(format!(
            "        if let v = {swift_name}, !(v {op} {bound}) {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
        ));
    } else {
        lines.push(format!(
            "        if !({v} {op} {bound}) {{ throw ValidationError.outOfRange(\"{swift_name}\", \"{msg}\") }}"
        ));
    }
}

fn is_swift_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "case" | "catch" | "class" | "continue" | "default" | "defer"
            | "do" | "else" | "enum" | "extension" | "fallthrough" | "false" | "for"
            | "func" | "guard" | "if" | "import" | "in" | "init" | "inout" | "internal"
            | "is" | "let" | "nil" | "operator" | "private" | "protocol" | "public"
            | "repeat" | "return" | "self" | "static" | "struct" | "subscript" | "super"
            | "switch" | "throw" | "throws" | "true" | "try" | "typealias" | "var"
            | "where" | "while" | "type" | "description"
    )
}
